---
title: Blog Content List
subtitle: Guide Map of Blog Contents 
description: |
  As the number of blog topics has increased, organizing the content has become more challenging. To enhance content accessibility and facilitate an understanding of the blog's relevance, we have provided links to a list of contents categorized by topic.
categories:
  - All List
author: Kwangmin Kim
date: 01/01/3000
format: 
  html:
    page-layout: full
    code-fold: true
---

:::{.callout-note}
* Scalars are denoted with a lower-case letter (ex a ) or a non-bolded lower-case Greek letter (ex $\alpha$ ).
* Vectors are denoted using a bold-faced lower-case letter (ex $\mathbf a$).
* Matrices are denoted using a bold-faced upper-case letter (ex $\mathbf A$, $\mathbf \phi$) or a bold-faced upper-case Greek letter (ex $\mathbf \Phi$).
* Tensors are denoted using a bold-faced upper-case letter with multiple subscripts or superscripts, indicating the number of indices and the dimensions of the tensor along each axis. 
  * A second-order tensor (also known as a matrix) $\mathbf A$ with dimensions $n \times m$ can be represented as: 
  $\mathbf A_{ij}$ where $i = 1,\dots,m$ and $j = 1,\dots,n$, which are the indices that run over the rows and columns of the matrix, respectively. 
  * A third-order tensor $T$ with dimensions $n \times m \times p$ can be represented as:
   $\mathbf A_{ijk}$ where $i = 1,\dots,m$, $j = 1,\dots,n$, which are $i$, and $k = 1,\dots,p$ $j$, and $k$, which are the indices that run over the three dimensions of the tensor.

:::

# Contents


* [Engineering](../posts/Engineering/guide_map/index.qmd)
* [Surveilance](../posts/Surveilance/guide_map/index.qmd)
* [Data Governance](../posts/Surveilance/guide_map/index.qmd)