<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ko" xml:lang="ko"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.543">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kwangmin Kim">
<meta name="description" content="Gelman BDA Ch.13의 마지막 세 절 § 13.10~13.12를 한 번에 다룬다. § 13.10은 likelihood의 정규화 상수 z(\theta) 자체가 모수 \theta 에 의존하여 계산 불가능한 doubly intractable 문제를 정의하고, Bridge/Path Sampling, Exchange algorithm, Pseudo-marginal MCMC, ABC 같은 해법 패밀리를 소개한다. § 13.11은 Ch.13 전체의 문헌을 Laplace/EM/VI/EP/정규화 상수 주제별로 분류하고, § 13.12는 EM 단조증가 증명·퇴화 mode·Probit VB·미지 정규화 상수 계산 등 핵심 연습문제를 풀이한다. 마지막으로 Ch.13 심화 4편 시리즈의 로직맵과 실전 체크리스트로 결산한다.">

<title>Kwangmin Kim - Ch.13 § 13.10~13.12 — Unknown Normalizing Factors·문헌·연습 심화</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../../../">
<script src="../../../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../../../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../../../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": true,
  "language": {
    "search-no-results-text": "일치 없음",
    "search-matching-documents-text": "일치된 문서",
    "search-copy-link-title": "검색 링크 복사",
    "search-hide-matches-text": "추가 검색 결과 숨기기",
    "search-more-match-text": "추가 검색결과",
    "search-more-matches-text": "추가 검색결과",
    "search-clear-button-title": "제거",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "취소",
    "search-submit-button-title": "검색",
    "search-label": "검색"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-6W0EKFMWBN"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-6W0EKFMWBN', { 'anonymize_ip': true});
</script>
<style>

      .quarto-title-block .quarto-title-banner h1,
      .quarto-title-block .quarto-title-banner h2,
      .quarto-title-block .quarto-title-banner h3,
      .quarto-title-block .quarto-title-banner h4,
      .quarto-title-block .quarto-title-banner h5,
      .quarto-title-block .quarto-title-banner h6
      {
        color: black;
      }

      .quarto-title-block .quarto-title-banner {
        color: black;
background: #EDF3F9;
      }
</style>
<style>
.custom-footer { 
  text-align: center; 
  font-size: 0.8em; 
  color: #666; 
  margin-top: 2rem; 
}
</style>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../../../styles.css">
<meta property="og:title" content="Kwangmin Kim - Ch.13 § 13.10~13.12 — Unknown Normalizing Factors·문헌·연습 심화">
<meta property="og:description" content="Gelman BDA Ch.13의 마지막 세 절 § 13.10~13.12를 한 번에 다룬다. § 13.10은 likelihood의 정규화 상수 \(z(\theta)\) 자체가 모수 \(\theta\) 에 의존하여 계산 불가능한 doubly intractable 문제를 정의하고, Bridge/Path Sampling, Exchange algorithm, Pseudo-marginal MCMC, ABC 같은 해법 패밀리를 소개한다. § 13.11은 Ch.13 전체의 문헌을 Laplace/EM/VI/EP/정규화 상수 주제별로 분류하고, § 13.12는 EM 단조증가 증명·퇴화 mode·Probit VB·미지 정규화 상수 계산 등 핵심 연습문제를 풀이한다. 마지막으로 Ch.13 심화 4편 시리즈의 로직맵과 실전 체크리스트로 결산한다.">
<meta property="og:site_name" content="Kwangmin Kim">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../../../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../../../.././images/logo.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../../../../index.html">
    <span class="navbar-title">Kwangmin Kim</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="검색"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="탐색 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../../docs/blog/index.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../../../about.html"> 
<span class="menu-text">Me</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/kmink3225"> <i class="bi bi-github" role="img" aria-label="Github">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/kwangmin-kim-a5241b200/"> <i class="bi bi-linkedin" role="img" aria-label="Linkedin">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../../../../docs/blog/index.xml"> <i class="bi bi-rss" role="img" aria-label="RSS">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="다크 모드 전환"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Ch.13 § 13.10~13.12 — Unknown Normalizing Factors·문헌·연습 심화</h1>
            <p class="subtitle lead">z(θ)가 미지일 때의 사후 추론, Ch.13 문헌 지도, 연습문제 풀이, Ch.13 심화 시리즈 결산</p>
                  <div>
        <div class="description">
          <p>Gelman BDA Ch.13의 마지막 세 절 § 13.10~13.12를 한 번에 다룬다. § 13.10은 likelihood의 정규화 상수 <span class="math inline">\(z(\theta)\)</span> 자체가 모수 <span class="math inline">\(\theta\)</span> 에 의존하여 계산 불가능한 doubly intractable 문제를 정의하고, Bridge/Path Sampling, Exchange algorithm, Pseudo-marginal MCMC, ABC 같은 해법 패밀리를 소개한다. § 13.11은 Ch.13 전체의 문헌을 Laplace/EM/VI/EP/정규화 상수 주제별로 분류하고, § 13.12는 EM 단조증가 증명·퇴화 mode·Probit VB·미지 정규화 상수 계산 등 핵심 연습문제를 풀이한다. 마지막으로 Ch.13 심화 4편 시리즈의 로직맵과 실전 체크리스트로 결산한다.</p>
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">Statistics</div>
                <div class="quarto-category">Bayesian</div>
                <div class="quarto-category">Modal-Approximations</div>
                <div class="quarto-category">Doubly-Intractable</div>
                <div class="quarto-category">Bridge-Sampling</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">저자</div>
      <div class="quarto-title-meta-contents">
               <p>Kwangmin Kim </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">공개</div>
      <div class="quarto-title-meta-contents">
        <p class="date">2026년 04월 23일</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">목차</h2>
   
  <ul>
  <li><a href="#개요" id="toc-개요" class="nav-link active" data-scroll-target="#개요"><span class="header-section-number">1</span> 개요</a></li>
  <li><a href="#unknown-normalizing-factors" id="toc-unknown-normalizing-factors" class="nav-link" data-scroll-target="#unknown-normalizing-factors"><span class="header-section-number">2</span> § 13.10 Unknown Normalizing Factors</a>
  <ul class="collapse">
  <li><a href="#문제-정의-ztheta-가-theta-에-의존하는-모형" id="toc-문제-정의-ztheta-가-theta-에-의존하는-모형" class="nav-link" data-scroll-target="#문제-정의-ztheta-가-theta-에-의존하는-모형"><span class="header-section-number">2.1</span> 문제 정의 — <span class="math inline">\(z(\theta)\)</span> 가 <span class="math inline">\(\theta\)</span> 에 의존하는 모형</a></li>
  <li><a href="#전형적-예시" id="toc-전형적-예시" class="nav-link" data-scroll-target="#전형적-예시"><span class="header-section-number">2.2</span> 전형적 예시</a></li>
  <li><a href="#계층-모형에서의-확장" id="toc-계층-모형에서의-확장" class="nav-link" data-scroll-target="#계층-모형에서의-확장"><span class="header-section-number">2.3</span> 계층 모형에서의 확장</a></li>
  <li><a href="#기본-계산-전략-gelman-13.10" id="toc-기본-계산-전략-gelman-13.10" class="nav-link" data-scroll-target="#기본-계산-전략-gelman-13.10"><span class="header-section-number">2.4</span> 기본 계산 전략 (Gelman 13.10)</a></li>
  <li><a href="#ztheta-의-수치-계산-importance-sampling" id="toc-ztheta-의-수치-계산-importance-sampling" class="nav-link" data-scroll-target="#ztheta-의-수치-계산-importance-sampling"><span class="header-section-number">2.5</span> <span class="math inline">\(z(\theta)\)</span> 의 수치 계산 — Importance Sampling</a></li>
  <li><a href="#bridge-sampling-두-극점-사이의-보간" id="toc-bridge-sampling-두-극점-사이의-보간" class="nav-link" data-scroll-target="#bridge-sampling-두-극점-사이의-보간"><span class="header-section-number">2.6</span> Bridge Sampling — 두 극점 사이의 보간</a></li>
  <li><a href="#path-sampling-연속-보간-thermodynamic-integration" id="toc-path-sampling-연속-보간-thermodynamic-integration" class="nav-link" data-scroll-target="#path-sampling-연속-보간-thermodynamic-integration"><span class="header-section-number">2.7</span> Path Sampling — 연속 보간 (Thermodynamic Integration)</a></li>
  <li><a href="#parallel-tempering과의-연결" id="toc-parallel-tempering과의-연결" class="nav-link" data-scroll-target="#parallel-tempering과의-연결"><span class="header-section-number">2.8</span> Parallel Tempering과의 연결</a></li>
  <li><a href="#최신-발전-2006현재-교재-미포함" id="toc-최신-발전-2006현재-교재-미포함" class="nav-link" data-scroll-target="#최신-발전-2006현재-교재-미포함"><span class="header-section-number">2.9</span> 최신 발전 (2006~현재) — 교재 미포함</a></li>
  <li><a href="#비교-전통-기법-vs-현대-기법" id="toc-비교-전통-기법-vs-현대-기법" class="nav-link" data-scroll-target="#비교-전통-기법-vs-현대-기법"><span class="header-section-number">2.10</span> 비교 — 전통 기법 vs 현대 기법</a></li>
  </ul></li>
  <li><a href="#bibliographic-note-ch.13-문헌-지도" id="toc-bibliographic-note-ch.13-문헌-지도" class="nav-link" data-scroll-target="#bibliographic-note-ch.13-문헌-지도"><span class="header-section-number">3</span> § 13.11 Bibliographic Note — Ch.13 문헌 지도</a>
  <ul class="collapse">
  <li><a href="#최적화-및-mode-finding" id="toc-최적화-및-mode-finding" class="nav-link" data-scroll-target="#최적화-및-mode-finding"><span class="header-section-number">3.1</span> 최적화 및 Mode Finding</a></li>
  <li><a href="#laplace-근사" id="toc-laplace-근사" class="nav-link" data-scroll-target="#laplace-근사"><span class="header-section-number">3.2</span> Laplace 근사</a></li>
  <li><a href="#em-algorithm-패밀리" id="toc-em-algorithm-패밀리" class="nav-link" data-scroll-target="#em-algorithm-패밀리"><span class="header-section-number">3.3</span> EM Algorithm 패밀리</a></li>
  <li><a href="#variational-inference" id="toc-variational-inference" class="nav-link" data-scroll-target="#variational-inference"><span class="header-section-number">3.4</span> Variational Inference</a></li>
  <li><a href="#expectation-propagation" id="toc-expectation-propagation" class="nav-link" data-scroll-target="#expectation-propagation"><span class="header-section-number">3.5</span> Expectation Propagation</a></li>
  <li><a href="#bridge-path-sampling-정규화-상수" id="toc-bridge-path-sampling-정규화-상수" class="nav-link" data-scroll-target="#bridge-path-sampling-정규화-상수"><span class="header-section-number">3.6</span> Bridge &amp; Path Sampling, 정규화 상수</a></li>
  <li><a href="#substitution-likelihood-copula" id="toc-substitution-likelihood-copula" class="nav-link" data-scroll-target="#substitution-likelihood-copula"><span class="header-section-number">3.7</span> Substitution Likelihood · Copula</a></li>
  </ul></li>
  <li><a href="#exercises-핵심-연습문제-풀이" id="toc-exercises-핵심-연습문제-풀이" class="nav-link" data-scroll-target="#exercises-핵심-연습문제-풀이"><span class="header-section-number">4</span> § 13.12 Exercises — 핵심 연습문제 풀이</a>
  <ul class="collapse">
  <li><a href="#exercise-13.6-em의-단조-증가-증명" id="toc-exercise-13.6-em의-단조-증가-증명" class="nav-link" data-scroll-target="#exercise-13.6-em의-단조-증가-증명"><span class="header-section-number">4.1</span> Exercise 13.6 — EM의 단조 증가 증명</a></li>
  <li><a href="#exercise-13.8-coagulation-예제의-퇴화-mode" id="toc-exercise-13.8-coagulation-예제의-퇴화-mode" class="nav-link" data-scroll-target="#exercise-13.8-coagulation-예제의-퇴화-mode"><span class="header-section-number">4.2</span> Exercise 13.8 — Coagulation 예제의 퇴화 Mode</a></li>
  <li><a href="#exercise-13.10-probit-회귀의-variational-bayes" id="toc-exercise-13.10-probit-회귀의-variational-bayes" class="nav-link" data-scroll-target="#exercise-13.10-probit-회귀의-variational-bayes"><span class="header-section-number">4.3</span> Exercise 13.10 — Probit 회귀의 Variational Bayes</a></li>
  <li><a href="#exercise-13.11-unknown-normalizing-factor-계산" id="toc-exercise-13.11-unknown-normalizing-factor-계산" class="nav-link" data-scroll-target="#exercise-13.11-unknown-normalizing-factor-계산"><span class="header-section-number">4.4</span> Exercise 13.11 — Unknown Normalizing Factor 계산</a></li>
  </ul></li>
  <li><a href="#ch.13-심화-시리즈-결산" id="toc-ch.13-심화-시리즈-결산" class="nav-link" data-scroll-target="#ch.13-심화-시리즈-결산"><span class="header-section-number">5</span> Ch.13 심화 시리즈 결산</a>
  <ul class="collapse">
  <li><a href="#편-논리-지도" id="toc-편-논리-지도" class="nav-link" data-scroll-target="#편-논리-지도"><span class="header-section-number">5.1</span> 4편 논리 지도</a></li>
  <li><a href="#ch.13-심화-전체-체크리스트" id="toc-ch.13-심화-전체-체크리스트" class="nav-link" data-scroll-target="#ch.13-심화-전체-체크리스트"><span class="header-section-number">5.2</span> Ch.13 심화 전체 체크리스트</a></li>
  <li><a href="#구현-환경-매핑" id="toc-구현-환경-매핑" class="nav-link" data-scroll-target="#구현-환경-매핑"><span class="header-section-number">5.3</span> 구현 환경 매핑</a></li>
  </ul></li>
  <li><a href="#관련-주제" id="toc-관련-주제" class="nav-link" data-scroll-target="#관련-주제"><span class="header-section-number">6</span> 관련 주제</a></li>
  <li><a href="#참고문헌" id="toc-참고문헌" class="nav-link" data-scroll-target="#참고문헌"><span class="header-section-number">7</span> 참고문헌</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="개요" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="개요"><span class="header-section-number">1</span> 개요</h2>
<p>Ch.13 심화 시리즈의 <strong>마지막 편</strong>이다. 앞선 세 편에서 다룬 내용을 정리하면 다음과 같다.</p>
<ul>
<li>§ 13.1~13.3 — Mode finding, Boundary-avoiding priors, Laplace 근사 (02-13-1)</li>
<li>§ 13.4~13.6 — EM, ECM/ECME, 조건부·주변 근사, 계층적 정규 모형 (02-13-2)</li>
<li>§ 13.7~13.8 — Variational Inference, Expectation Propagation (02-13-3)</li>
</ul>
<p>§ 13.9는 Gelman 3rd ed.에 존재하지 않는다 (§ 13.1~13.8 이후 바로 § 13.10으로 넘어간다). 따라서 이 편은 <strong>§ 13.10 (unknown normalizing factors) · § 13.11 (문헌) · § 13.12 (연습)</strong> 세 절을 한데 묶는다.</p>
<p>§ 13.10은 Ch.13 내에서 성격이 다소 이질적이다. 앞선 절들이 “사후 분포 <span class="math inline">\(p(\theta | y)\)</span> 를 어떻게 <strong>근사</strong>할 것인가”를 다루었다면, § 13.10은 “likelihood <span class="math inline">\(p(y|\theta) = q(y|\theta)/z(\theta)\)</span> 의 정규화 상수 <span class="math inline">\(z(\theta)\)</span> 자체를 모를 때 어떻게 <strong>계산</strong>할 것인가”를 다룬다. 이 문제는 <strong>doubly intractable posterior</strong> (Murray, Ghahramani, MacKay, 2006) 라는 이름으로 공간 통계, 이미지 분석, 생물학, 사회 네트워크 등에서 지속적으로 등장하며, Bridge/Path Sampling 같은 고전적 접근과 Exchange algorithm·Pseudo-marginal MCMC 같은 현대적 접근이 뒤엉켜 있다.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관: 왜 “doubly intractable”인가
</div>
</div>
<div class="callout-body-container callout-body">
<p>일반적인 베이지안 계산에서 intractable한 것은 <strong>marginal likelihood</strong> <span class="math inline">\(p(y) = \int p(\theta) p(y|\theta) \, d\theta\)</span> 하나다. Metropolis-Hastings 같은 MCMC가 이를 우회하는 이유는 ratio <span class="math inline">\(p(\theta_1|y) / p(\theta_0|y)\)</span> 를 취하면 <span class="math inline">\(p(y)\)</span> 가 약분되기 때문이다.</p>
<p>그런데 likelihood 자체가 <span class="math inline">\(p(y|\theta) = q(y|\theta)/z(\theta)\)</span> 형태로 <span class="math inline">\(z(\theta)\)</span> 에 의존하면, MH ratio를 계산할 때도</p>
<p><span class="math display">\[
\frac{p(\theta^*|y)}{p(\theta|y)} = \frac{p(\theta^*) q(y|\theta^*) / z(\theta^*)}{p(\theta) q(y|\theta) / z(\theta)}
\]</span></p>
<p>에서 <span class="math inline">\(z(\theta)\)</span> 가 <strong>약분되지 않고 남는다</strong>. 따라서 “모수별로 intractable한 적분을 추가로 또 계산해야” 하고, 이것이 “doubly intractable”이라는 이름의 유래이다.</p>
</div>
</div>
</section>
<section id="unknown-normalizing-factors" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="unknown-normalizing-factors"><span class="header-section-number">2</span> § 13.10 Unknown Normalizing Factors</h2>
<section id="문제-정의-ztheta-가-theta-에-의존하는-모형" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="문제-정의-ztheta-가-theta-에-의존하는-모형"><span class="header-section-number">2.1</span> 문제 정의 — <span class="math inline">\(z(\theta)\)</span> 가 <span class="math inline">\(\theta\)</span> 에 의존하는 모형</h3>
<p>Gelman의 일반 표기법:</p>
<p><span class="math display">\[
p(y|\theta) = \frac{1}{z(\theta)} q(y|\theta), \qquad z(\theta) = \int q(y|\theta) \, dy \quad \text{(13.31)}
\]</span></p>
<p>여기서 <span class="math inline">\(q(y|\theta)\)</span> 는 <strong>unnormalized density</strong>로 해석적으로 계산 가능하지만, 정규화 상수 <span class="math inline">\(z(\theta)\)</span> 는 닫힌 형태가 없거나 계산이 매우 비싸다. 사전분포 <span class="math inline">\(p(\theta)\)</span> 와 결합하면 사후분포는</p>
<p><span class="math display">\[
p(\theta|y) \propto p(\theta) \cdot \frac{q(y|\theta)}{z(\theta)}
\]</span></p>
<p>가 된다. <span class="math inline">\(z(\theta)\)</span> 가 <span class="math inline">\(\theta\)</span> 에 의존하므로 사후 추론 전체에서 이 함수의 모양을 추적해야 한다.</p>
<p><strong>사전분포의 미지 정규화 상수는 문제가 되지 않는다.</strong> <span class="math inline">\(p(\theta) \propto q_\theta(\theta)\)</span> 에서 <span class="math inline">\(q_\theta\)</span> 의 상수 배는 사후분포에서 곧바로 약분된다. 문제는 오직 <strong>likelihood의 <span class="math inline">\(z(\theta)\)</span></strong>다.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
정의: Doubly Intractable Posterior
</div>
</div>
<div class="callout-body-container callout-body">
<p>다음 조건을 만족하는 사후 분포를 doubly intractable이라 한다.</p>
<ol type="1">
<li>Marginal likelihood <span class="math inline">\(p(y) = \int p(\theta) p(y|\theta) \, d\theta\)</span> 가 해석적으로 불가능 (일반적 intractability).</li>
<li>Likelihood <span class="math inline">\(p(y|\theta)\)</span> 자체의 정규화 상수 <span class="math inline">\(z(\theta) = \int q(y|\theta) \, dy\)</span> 도 해석적으로 불가능하고 <span class="math inline">\(\theta\)</span> 에 의존.</li>
</ol>
<p>2번 조건으로 인해 MH acceptance ratio에서 <span class="math inline">\(z(\theta)\)</span> 가 약분되지 않는다.</p>
</div>
</div>
</section>
<section id="전형적-예시" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="전형적-예시"><span class="header-section-number">2.2</span> 전형적 예시</h3>
<table class="table">
<colgroup>
<col style="width: 24%">
<col style="width: 24%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>영역</th>
<th>모형</th>
<th>정규화 상수</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>공간 통계 (Besag, 1974)</td>
<td>Ising model, Markov random field</td>
<td>상태 <span class="math inline">\(2^n\)</span> 개 합산 — 격자 크기 <span class="math inline">\(n \sim 100 \times 100\)</span> 만 되어도 <span class="math inline">\(2^{10000}\)</span> 항</td>
</tr>
<tr class="even">
<td>이미지 분석</td>
<td>Potts model, Gibbs random field</td>
<td>조건부 독립 구조에서 유도, 전체 정규화 상수는 intractable</td>
</tr>
<tr class="odd">
<td>생물학</td>
<td>Exponential random graph model (ERGM)</td>
<td>그래프 공간 전체 합산 필요</td>
</tr>
<tr class="even">
<td>점과정 (Ripley, 1981)</td>
<td>Strauss process, Gibbs point process</td>
<td>점 구성 공간 적분</td>
</tr>
<tr class="odd">
<td>통계물리</td>
<td>Boltzmann machine, RBM</td>
<td>partition function <span class="math inline">\(Z\)</span> 가 지수적 복잡도</td>
</tr>
</tbody>
</table>
<p><strong>핵심 관찰</strong>: 이들 모형은 대부분 <strong>조건부로 정의</strong>된다 (조건부 확률은 닫힌 형태, 결합 확률은 intractable). Gelman이 <span class="math inline">\(q(y|\theta)\)</span> 를 “spatial statistics처럼 conditionally specified 모형에서 자주 나타난다”라고 쓴 이유다.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관: 조건부로 정의된 모형이 왜 intractable이 되는가
</div>
</div>
<div class="callout-body-container callout-body">
<p>Ising 격자에서 각 스핀 <span class="math inline">\(y_i \in \{-1, +1\}\)</span> 의 조건부 분포는 인접 스핀에만 의존한다.</p>
<p><span class="math display">\[
p(y_i | y_{-i}, \theta) = \frac{\exp(\theta \sum_{j \sim i} y_i y_j)}{\exp(\theta \sum_{j \sim i} y_j) + \exp(-\theta \sum_{j \sim i} y_j)}
\]</span></p>
<p>이 식은 완벽하게 닫혀 있다. 그러나 결합 분포는</p>
<p><span class="math display">\[
p(y|\theta) = \frac{1}{z(\theta)} \exp\left( \theta \sum_{(i,j) \in E} y_i y_j \right)
\]</span></p>
<p>이고, <span class="math inline">\(z(\theta) = \sum_{y \in \{-1,+1\}^n} \exp(\theta \sum y_i y_j)\)</span> 는 <span class="math inline">\(2^n\)</span> 개 상태를 모두 합산해야 한다. <strong>조건부의 단순함과 결합의 intractability는 동전의 양면</strong>이다 (Hammersley-Clifford 정리의 귀결).</p>
</div>
</div>
</section>
<section id="계층-모형에서의-확장" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="계층-모형에서의-확장"><span class="header-section-number">2.3</span> 계층 모형에서의 확장</h3>
<p>Gelman은 동일한 문제가 <strong>계층 모형의 모집단 분포</strong>에서도 나타남을 지적한다. 데이터 <span class="math inline">\(y\)</span>, 1차 모수 <span class="math inline">\(\gamma\)</span>, 초모수 <span class="math inline">\(\phi\)</span> 에 대해</p>
<p><span class="math display">\[
p(\gamma, \phi | y) \propto p(\phi) \cdot \frac{1}{z(\phi)} q(\gamma | \phi) \cdot p(y | \gamma)
\]</span></p>
<p>여기서 <span class="math inline">\(q(\gamma|\phi) = z(\phi) p(\gamma|\phi)\)</span> 이고 <span class="math inline">\(z(\phi)\)</span> 가 <span class="math inline">\(\phi\)</span> 에 의존한다. 이런 상황은 <strong>계층 모형의 모집단 분포가 Gaussian copula나 공간 구조를 포함</strong>할 때 발생한다.</p>
</section>
<section id="기본-계산-전략-gelman-13.10" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="기본-계산-전략-gelman-13.10"><span class="header-section-number">2.4</span> 기본 계산 전략 (Gelman 13.10)</h3>
<p>Gelman은 다음 3단계 전략을 권한다.</p>
<p><strong>Step 1</strong>. 대략적 추정 <span class="math inline">\(\hat{\theta}\)</span> 에서 Laplace의 방법으로 <span class="math inline">\(z(\theta)\)</span> 의 초기 근사를 얻는다.</p>
<p><strong>Step 2</strong>. Ch.13 앞 절의 기법 (Laplace·VI·EP)으로 사후분포에 대한 대략적 근사를 구성한다. 이 근사는 직접 적분 가능한 경우가 많으므로 빠른 초기 탐색에 유용하다.</p>
<p><strong>Step 3</strong>. 더 정밀한 계산이 필요하면, 사후분포 평가가 요구되는 각 <span class="math inline">\(\theta\)</span> 에서 <span class="math inline">\(z(\theta)\)</span> 를 수치적으로 계산한다. 이때 <span class="math inline">\(z(\theta)\)</span> 를 “계산이 비싼 known function”처럼 취급한다.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관: 왜 “근사 먼저, 정밀 나중”인가
</div>
</div>
<div class="callout-body-container callout-body">
<p>사후 확률이 본질적으로 0인 영역에서는 <span class="math inline">\(z(\theta)\)</span> 계산이 시간 낭비다. Step 1~2로 후보 영역을 좁혀놓고 (사후 mass의 지지 집합을 Laplace·VI로 선점), Step 3에서는 그 영역에서만 <span class="math inline">\(z(\theta)\)</span> 를 정밀하게 계산한다.</p>
<p>즉, Ch.13의 <strong>앞 절 전체가 § 13.10의 선행 단계</strong>로 자연스럽게 연결된다. Ch.13의 논리 구조가 한 바퀴 돌아서 § 13.10에서 닫힌다.</p>
</div>
</div>
</section>
<section id="ztheta-의-수치-계산-importance-sampling" class="level3" data-number="2.5">
<h3 data-number="2.5" class="anchored" data-anchor-id="ztheta-의-수치-계산-importance-sampling"><span class="header-section-number">2.5</span> <span class="math inline">\(z(\theta)\)</span> 의 수치 계산 — Importance Sampling</h3>
<p>식 (13.31)에 직접 적용할 수 있는 importance sampling identity는</p>
<p><span class="math display">\[
z(\theta) = \int q(y|\theta) \, dy = \int \frac{q(y|\theta)}{g(y)} g(y) \, dy = \mathbb{E}_g\left[ \frac{q(y|\theta)}{g(y)} \right]
\]</span></p>
<p>근사 분포 <span class="math inline">\(g(y)\)</span> 에서 <span class="math inline">\(y^1, \dots, y^S\)</span> 를 추출하면 추정량은</p>
<p><span class="math display">\[
\hat{z}(\theta) = \frac{1}{S} \sum_{s=1}^{S} \frac{q(y^s|\theta)}{g(y^s)}
\]</span></p>
<p><strong>핵심 트릭</strong>: 같은 simulations <span class="math inline">\(y^1, \dots, y^S\)</span> 를 여러 <span class="math inline">\(\theta\)</span> 값에 재사용할 수 있다. 다만 <span class="math inline">\(\theta\)</span> 가 크게 변하면 <span class="math inline">\(g(y)\)</span> 와 <span class="math inline">\(q(y|\theta)\)</span> 의 support가 어긋나 importance weight의 분산이 폭발하므로 <strong>국소적 <span class="math inline">\(\theta\)</span> 범위</strong>에서만 유효하다.</p>
<p>또한 <span class="math inline">\(z(\theta)\)</span> 는 <strong>비례 상수까지만</strong> 알면 되므로 <span class="math inline">\(g(y)\)</span> 도 정규화될 필요가 없다. 이 자유도가 Bridge/Path Sampling의 유연성으로 이어진다.</p>
</section>
<section id="bridge-sampling-두-극점-사이의-보간" class="level3" data-number="2.6">
<h3 data-number="2.6" class="anchored" data-anchor-id="bridge-sampling-두-극점-사이의-보간"><span class="header-section-number">2.6</span> Bridge Sampling — 두 극점 사이의 보간</h3>
<p><span class="math inline">\(\theta_*\)</span> 하나로는 전 범위를 커버 못 할 때, <strong>양 끝 두 점</strong> <span class="math inline">\(\theta_0, \theta_1\)</span> 에서 각각 simulation을 얻어 <strong>가중 평균</strong>으로 임의의 <span class="math inline">\(\theta\)</span> 에서 <span class="math inline">\(z(\theta)\)</span> 를 추정한다.</p>
<p>직관: “현수교 비유” — 분포 family를 양쪽 기둥 (<span class="math inline">\(\theta_0\)</span>, <span class="math inline">\(\theta_1\)</span>) 이 지탱하는 다리로 보고, 중간 지점 <span class="math inline">\(\theta\)</span> 의 값은 양쪽에서 끌어당기는 장력의 조합으로 결정된다.</p>
<p>Meng-Wong (1996) 의 Bridge identity:</p>
<p><span class="math display">\[
\frac{z(\theta_1)}{z(\theta_0)} = \frac{\mathbb{E}_{\theta_0}[\alpha(y) q(y|\theta_1)]}{\mathbb{E}_{\theta_1}[\alpha(y) q(y|\theta_0)]}
\]</span></p>
<p>여기서 <span class="math inline">\(\alpha(y)\)</span> 는 임의의 함수이며, <span class="math inline">\(\alpha(y) = 1/[s_0 q(y|\theta_0) + s_1 q(y|\theta_1)]\)</span> (<span class="math inline">\(s_i\)</span> 는 sample 크기 비율) 선택 시 분산 최소화 (optimal bridge).</p>
</section>
<section id="path-sampling-연속-보간-thermodynamic-integration" class="level3" data-number="2.7">
<h3 data-number="2.7" class="anchored" data-anchor-id="path-sampling-연속-보간-thermodynamic-integration"><span class="header-section-number">2.7</span> Path Sampling — 연속 보간 (Thermodynamic Integration)</h3>
<p>Bridge sampling의 <strong>미분 극한</strong> (Gelman-Meng, 1998): <span class="math inline">\(\theta\)</span> 가 <span class="math inline">\([0, 1]\)</span> 구간을 연속적으로 훑을 때,</p>
<p><span class="math display">\[
\frac{d}{d\phi} \log p(\phi|y) = \mathbb{E}\left[ U(\gamma, \phi, y) \mid \phi, y \right], \quad U = \frac{d}{d\phi} \log p(\gamma, \phi | y)
\]</span></p>
<p><strong>핵심 의미</strong>: <span class="math inline">\(\log p(\phi|y)\)</span> 의 도함수를 시뮬레이션으로 구해 <strong>수치 적분</strong>하면 로그 주변 밀도의 모양이 나온다. 이 식은 통계물리의 <strong>thermodynamic integration</strong>과 동일 구조이며, 실제로 “path”라는 용어는 물리 쪽 어원이다.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관: 온도를 끓는점까지 연속으로 올려서 자유에너지 차이를 측정
</div>
</div>
<div class="callout-body-container callout-body">
<p>통계물리에서 “얼음을 물로 녹이는 데 필요한 에너지”는 중간 상태들의 에너지 변화율을 적분해서 구한다. Path sampling은 이와 동일하다. <span class="math inline">\(\phi=0\)</span> 일 때의 “쉬운 분포” (예: 사전분포)와 <span class="math inline">\(\phi=1\)</span> 일 때의 “어려운 분포” (예: 사후분포) 사이의 경로를 설정하고, 경로를 따라 움직이는 시뮬레이션 샘플의 에너지 변화율 <span class="math inline">\(U\)</span> 를 관측한다. 적분하면 두 분포의 로그 정규화 상수 차이가 나온다.</p>
<p>이것이 왜 효과적인가? 두 분포가 “너무 다를” 때 직접 importance sampling은 분산이 폭발하지만, 중간 경로를 잘게 쪼개면 각 단계의 분산이 작아져 전체 적분이 안정된다.</p>
</div>
</div>
</section>
<section id="parallel-tempering과의-연결" class="level3" data-number="2.8">
<h3 data-number="2.8" class="anchored" data-anchor-id="parallel-tempering과의-연결"><span class="header-section-number">2.8</span> Parallel Tempering과의 연결</h3>
<p>Gelman은 bridge/path sampling이 <strong>parallel tempering</strong> (Ch.11)과 밀접함을 지적한다. 둘 다 “indexed family of distributions로부터 샘플링”하는 구조이며, 차이는 <span class="math inline">\(\phi\)</span> 의 주변 분포를 어떻게 다루느냐에 있다.</p>
<ul>
<li><strong>Tempering</strong>: <span class="math inline">\(\phi\)</span> 의 주변 분포를 <strong>계산 효율을 위해 인위 설정</strong> (예: 균등, 기하) → 체인 혼합 가속이 목적</li>
<li><strong>Bridge/Path</strong>: <span class="math inline">\(\phi\)</span> 의 <strong>주변 밀도를 추정하는 것 자체가 목적</strong> → <span class="math inline">\(\log p(\phi|y)\)</span> 의 모양을 얻음</li>
</ul>
</section>
<section id="최신-발전-2006현재-교재-미포함" class="level3" data-number="2.9">
<h3 data-number="2.9" class="anchored" data-anchor-id="최신-발전-2006현재-교재-미포함"><span class="header-section-number">2.9</span> 최신 발전 (2006~현재) — 교재 미포함</h3>
<p>Gelman 3rd ed.&nbsp;(2013)이 다루지 않는 주요 현대적 접근들이다. 오늘날 doubly intractable 문제에서 실무적으로 가장 많이 쓰이는 방법이다 (이하 agent 사전학습 기반).</p>
<section id="exchange-algorithm-murray-ghahramani-mackay-2006" class="level4" data-number="2.9.1">
<h4 data-number="2.9.1" class="anchored" data-anchor-id="exchange-algorithm-murray-ghahramani-mackay-2006"><span class="header-section-number">2.9.1</span> Exchange Algorithm (Murray, Ghahramani, MacKay, 2006)</h4>
<p><strong>아이디어</strong>: MH ratio에 남는 <span class="math inline">\(z(\theta^*)/z(\theta)\)</span> 를 <strong>보조 변수 <span class="math inline">\(y'\)</span> 도입</strong>으로 없앤다.</p>
<p>알고리즘:</p>
<ol type="1">
<li>현재 상태 <span class="math inline">\(\theta\)</span> 에서 제안 <span class="math inline">\(\theta^* \sim q(\theta^* | \theta)\)</span>.</li>
<li><strong>보조 데이터 <span class="math inline">\(y' \sim p(y'|\theta^*)\)</span> 를 실제 모형에서 한 번 샘플링</strong> (perfect sampling 필요).</li>
<li>수락 확률</li>
</ol>
<p><span class="math display">\[
\alpha = \min\left\{1, \frac{p(\theta^*) q(y|\theta^*) q(y'|\theta)}{p(\theta) q(y|\theta) q(y'|\theta^*)} \cdot \frac{q(\theta|\theta^*)}{q(\theta^*|\theta)}\right\}
\]</span></p>
<ol start="4" type="1">
<li><span class="math inline">\(y'\)</span> 샘플링이 암묵적으로 <span class="math inline">\(z(\theta^*)/z(\theta)\)</span> 를 unbiased하게 추정하는 역할을 한다.</li>
</ol>
<p><strong>장점</strong>: <span class="math inline">\(z(\theta)\)</span> 를 <strong>한 번도 계산하지 않는다</strong>. <strong>단점</strong>: 각 MCMC step마다 모형에서 <strong>독립 샘플</strong> <span class="math inline">\(y'\)</span> 을 뽑아야 한다. Ising 같은 경우 perfect sampling (Coupling from the Past) 이 가능하지만 비용이 크다.</p>
</section>
<section id="pseudo-marginal-mcmc-andrieu-roberts-2009" class="level4" data-number="2.9.2">
<h4 data-number="2.9.2" class="anchored" data-anchor-id="pseudo-marginal-mcmc-andrieu-roberts-2009"><span class="header-section-number">2.9.2</span> Pseudo-marginal MCMC (Andrieu, Roberts, 2009)</h4>
<p><strong>아이디어</strong>: MH ratio에 정확한 likelihood가 아닌 <strong>unbiased estimate</strong>를 넣어도 stationary distribution이 보존된다.</p>
<p><span class="math display">\[
\alpha = \min\left\{1, \frac{p(\theta^*) \hat{p}(y|\theta^*)}{p(\theta) \hat{p}(y|\theta)} \cdot \frac{q(\theta|\theta^*)}{q(\theta^*|\theta)}\right\}
\]</span></p>
<p>여기서 <span class="math inline">\(\hat{p}(y|\theta)\)</span> 는 <span class="math inline">\(\mathbb{E}[\hat{p}(y|\theta)] = p(y|\theta)\)</span> 를 만족하는 unbiased estimator. <span class="math inline">\(z(\theta)\)</span> 를 importance sampling으로 unbiased하게 추정하면 그대로 꽂으면 된다.</p>
<p><strong>놀라운 사실</strong>: noisy estimator를 써도 <strong>정확히 올바른 사후분포</strong>에서 샘플링한다 (variance만 증가).</p>
<p><strong>응용</strong>: 상태공간모형의 particle filter likelihood (particle MCMC, Andrieu-Doucet-Holenstein 2010)가 대표적.</p>
</section>
<section id="approximate-bayesian-computation-abc" class="level4" data-number="2.9.3">
<h4 data-number="2.9.3" class="anchored" data-anchor-id="approximate-bayesian-computation-abc"><span class="header-section-number">2.9.3</span> Approximate Bayesian Computation (ABC)</h4>
<p>Likelihood를 <strong>전혀 계산하지 않고</strong> 시뮬레이션만으로 근사 사후 분포를 얻는다.</p>
<p>알고리즘:</p>
<ol type="1">
<li><span class="math inline">\(\theta \sim p(\theta)\)</span>.</li>
<li><span class="math inline">\(y^{sim} \sim p(y|\theta)\)</span> (모형에서 시뮬레이션).</li>
<li><span class="math inline">\(\rho(y^{sim}, y_{obs}) &lt; \epsilon\)</span> 이면 <span class="math inline">\(\theta\)</span> 수락.</li>
</ol>
<p><span class="math inline">\(\epsilon \to 0\)</span> 에서 정확한 사후분포로 수렴. Likelihood-free 방법의 대표주자로, <strong>유전학, 역학, 동역학 시스템 추정</strong>에 널리 쓰인다.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관: “likelihood를 모르면 시뮬레이션으로 대체한다”
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(z(\theta)\)</span> 가 intractable이라는 말은 likelihood 값을 숫자로 평가할 수 없다는 뜻이다. 그러나 모형에서 <strong>데이터를 생성</strong>하는 것은 가능한 경우가 많다 (Ising 격자에서 Gibbs sampling으로 <span class="math inline">\(y\)</span> 샘플링, Strauss process에서 birth-death로 점 샘플링 등).</p>
<p>“계산 불가능한 likelihood”를 “생성 가능한 모형”으로 교환한 셈이다. Exchange algorithm도, ABC도, Pseudo-marginal의 unbiased estimator도 모두 이 아이디어의 변주다.</p>
</div>
</div>
</section>
</section>
<section id="비교-전통-기법-vs-현대-기법" class="level3" data-number="2.10">
<h3 data-number="2.10" class="anchored" data-anchor-id="비교-전통-기법-vs-현대-기법"><span class="header-section-number">2.10</span> 비교 — 전통 기법 vs 현대 기법</h3>
<table class="table">
<colgroup>
<col style="width: 13%">
<col style="width: 22%">
<col style="width: 20%">
<col style="width: 24%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>방법</th>
<th>정규화 상수 <span class="math inline">\(z(\theta)\)</span></th>
<th>모형에서 샘플링</th>
<th>주요 용도</th>
<th>대표 교재/논문</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Bridge sampling</td>
<td>비율 <span class="math inline">\(z(\theta_1)/z(\theta_0)\)</span> 추정</td>
<td>양 끝점만</td>
<td>모형 비교</td>
<td>Meng-Wong (1996)</td>
</tr>
<tr class="even">
<td>Path sampling</td>
<td><span class="math inline">\(\log z(\phi)\)</span> 연속 추정</td>
<td>전체 경로</td>
<td>Marginal density 추정</td>
<td>Gelman-Meng (1998)</td>
</tr>
<tr class="odd">
<td>Exchange algorithm</td>
<td>불필요 (암묵 약분)</td>
<td>매 step perfect sample</td>
<td>Ising, ERGM</td>
<td>Murray et al.&nbsp;(2006)</td>
</tr>
<tr class="even">
<td>Pseudo-marginal</td>
<td>Unbiased 추정 사용</td>
<td>Noise 허용</td>
<td>Particle filter, latent</td>
<td>Andrieu-Roberts (2009)</td>
</tr>
<tr class="odd">
<td>ABC</td>
<td>불필요 (무시)</td>
<td>매 step forward sim</td>
<td>유전학, 역학</td>
<td>Beaumont (2010), Marin (2012)</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="bibliographic-note-ch.13-문헌-지도" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="bibliographic-note-ch.13-문헌-지도"><span class="header-section-number">3</span> § 13.11 Bibliographic Note — Ch.13 문헌 지도</h2>
<p>Gelman의 Ch.13 문헌 절은 매우 압축적이다. 여기서는 주제별로 재구성하여 참조의 논리 지도를 제공한다.</p>
<section id="최적화-및-mode-finding" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="최적화-및-mode-finding"><span class="header-section-number">3.1</span> 최적화 및 Mode Finding</h3>
<ul>
<li><strong>Press et al.&nbsp;(1986)</strong> <em>Numerical Recipes</em> — Newton-Raphson, BFGS, CG의 표준 참고서.</li>
<li><strong>Gill, Murray, Wright (1981)</strong> <em>Practical Optimization</em> — 복잡한 최적화 문제의 고전 교과서.</li>
<li><strong>Chung, Rabe-Hesketh et al.&nbsp;(2013a,b)</strong> — Gamma(2, ·) 등 경계 회피 사전분포의 이론적 근거.</li>
</ul>
</section>
<section id="laplace-근사" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="laplace-근사"><span class="header-section-number">3.2</span> Laplace 근사</h3>
<ul>
<li><strong>Tierney, Kadane (1986)</strong> — 주변 사후의 Laplace 근사, 식 (13.3)의 분자·분모 개별 적용 정확도 증명.</li>
<li><strong>Kass, Tierney, Kadane (1989)</strong> — Laplace 방법 확장.</li>
<li><strong>Wong, Li (1992)</strong> — 정교화.</li>
<li><strong>Geweke (1989)</strong> — Importance sampling용 modal 근사, split normal 제안.</li>
</ul>
</section>
<section id="em-algorithm-패밀리" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="em-algorithm-패밀리"><span class="header-section-number">3.3</span> EM Algorithm 패밀리</h3>
<ul>
<li><strong>Dempster, Laird, Rubin (1977)</strong> — EM의 정식 정립. “EM algorithm”이라는 이름의 기원.</li>
<li><strong>Baum et al.&nbsp;(1970)</strong> — EM의 수학적 일반화를 처음 도출 (HMM 맥락).</li>
<li><strong>Orchard, Woodbury (1972)</strong> — “Missing information principle”로 EM을 통계 일반 맥락에서 최초 제시.</li>
<li><strong>Tanner, Wong (1987)</strong> — MCMC를 EM의 stochastic extension으로 잇는 핵심 논문.</li>
<li><strong>Meng, Rubin (1991)</strong> — SEM (Supplemented EM)으로 분산-공분산 추정.</li>
<li><strong>Meng, Rubin (1993), Meng (1994a)</strong> — ECM.</li>
<li><strong>van Dyk, Meng, Rubin (1995)</strong> — SECM.</li>
<li><strong>Liu, Rubin (1994)</strong> — ECME.</li>
<li><strong>Meng, van Dyk (1997)</strong> — AECM.</li>
<li><strong>Liu, Rubin, Wu (1998)</strong> — PX-EM.</li>
<li><strong>Little, Rubin (2002)</strong> <em>Statistical Analysis with Missing Data</em> — 결측 데이터 맥락의 EM.</li>
</ul>
</section>
<section id="variational-inference" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="variational-inference"><span class="header-section-number">3.4</span> Variational Inference</h3>
<ul>
<li><strong>Jordan et al.&nbsp;(1999)</strong> — Variational methods for graphical models, 튜토리얼의 고전.</li>
<li><strong>Jaakkola, Jordan (2000)</strong> — 로지스틱 관련 VI.</li>
<li><strong>Blei, Ng, Jordan (2003)</strong> — <strong>LDA (Latent Dirichlet Allocation)</strong> 원 논문, VI의 대중화 계기.</li>
<li><strong>Gershman, Hoffman, Blei (2013)</strong> — VI 검토 논문.</li>
<li><strong>Hoffman et al.&nbsp;(2013)</strong> — Stochastic VI, 대규모 데이터용.</li>
</ul>
<p>(교재 미포함 최신 발전) <strong>Kingma, Welling (2014)</strong> VAE — reparameterization trick으로 연속 잠재변수 VI; <strong>Kucukelbir et al.&nbsp;(2017)</strong> ADVI in Stan — 자동화된 VI; <strong>Rezende, Mohamed (2015)</strong> Normalizing flows — 복잡한 posterior 표현력 확장.</p>
</section>
<section id="expectation-propagation" class="level3" data-number="3.5">
<h3 data-number="3.5" class="anchored" data-anchor-id="expectation-propagation"><span class="header-section-number">3.5</span> Expectation Propagation</h3>
<ul>
<li><strong>Minka (2001)</strong> — EP의 정식 정립 (PhD thesis).</li>
<li><strong>Bishop (2006)</strong> <em>PRML Ch.10</em> — EP의 교과서 표준 서술.</li>
<li><strong>Rasmussen, Williams (2006)</strong> <em>GPML</em> — GP classification에서 EP 실전 활용.</li>
<li><strong>Cseke, Heskes (2011)</strong> — Marginal posterior 개선.</li>
<li><strong>Rue, Martino, Chopin (2009)</strong> — INLA (Integrated Nested Laplace Approximation). 공간·시계열 모형의 대안.</li>
<li><strong>Jylanki, Nummenmaa, Vehtari</strong> — 계층적 GLM용 EP framework.</li>
<li><strong>Heskes et al., Marin et al.&nbsp;(2012)</strong> — ABC 검토.</li>
</ul>
</section>
<section id="bridge-path-sampling-정규화-상수" class="level3" data-number="3.6">
<h3 data-number="3.6" class="anchored" data-anchor-id="bridge-path-sampling-정규화-상수"><span class="header-section-number">3.6</span> Bridge &amp; Path Sampling, 정규화 상수</h3>
<ul>
<li><strong>Meng, Wong (1996)</strong> — Bridge sampling의 도입.</li>
<li><strong>Gelman, Meng (1998)</strong> — Path sampling으로 일반화.</li>
<li><strong>Meng, Schilling (1996)</strong> — 인수분석 예제.</li>
<li><strong>Kong et al.&nbsp;(2003)</strong> — Importance·bridge sampling 통합 이론.</li>
<li><strong>Ott (1979)</strong> — 정규화 상수 계산의 초기 통계학 적용.</li>
<li><strong>Besag (1974)</strong> — 공간 통계에서의 MRF/정규화 상수 문제 원조.</li>
<li><strong>Ripley (1981, 1988)</strong> <em>Statistical Inference for Spatial Processes</em> — 공간 점과정의 고전.</li>
<li><strong>Geyer (1991), Geyer, Thompson (1992, 1993)</strong> — MCMC로 정규화 함수 추정, 유전학 응용.</li>
<li><strong>Pettitt, Friel, Reeves (2003)</strong> — Path sampling으로 공간 통계 정규화 상수 계산.</li>
</ul>
</section>
<section id="substitution-likelihood-copula" class="level3" data-number="3.7">
<h3 data-number="3.7" class="anchored" data-anchor-id="substitution-likelihood-copula"><span class="header-section-number">3.7</span> Substitution Likelihood · Copula</h3>
<ul>
<li><strong>Dunson, Taylor (2005)</strong>, <strong>Hoff (2007)</strong>, <strong>Murray et al.&nbsp;(2013)</strong> — Substitution likelihood 관련. Gaussian copula factor 모형 (Murray 2013)은 marginal 분포 제약이 강한 상황에서 copula를 쓰는 접근.</li>
</ul>
</section>
</section>
<section id="exercises-핵심-연습문제-풀이" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="exercises-핵심-연습문제-풀이"><span class="header-section-number">4</span> § 13.12 Exercises — 핵심 연습문제 풀이</h2>
<p>Gelman Ch.13의 연습문제 중 학습 효과가 큰 네 문제를 풀이한다.</p>
<section id="exercise-13.6-em의-단조-증가-증명" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="exercise-13.6-em의-단조-증가-증명"><span class="header-section-number">4.1</span> Exercise 13.6 — EM의 단조 증가 증명</h3>
<p><strong>문제</strong>: <span class="math inline">\(Q(\phi | \phi^{\text{old}}) = \mathbb{E}_{\text{old}} \log p(\gamma | \phi, y)\)</span> 가 <span class="math inline">\(\phi = \phi^{\text{old}}\)</span> 에서 최대화됨을 증명하라 (hint: Jensen 부등식).</p>
<p>(02-13-2의 Gibbs 부등식 증명과 동일하므로 핵심만 재기술한다.)</p>
<p><strong>풀이</strong>: Gelman 식 (13.5)</p>
<p><span class="math display">\[
\log p(\phi|y) = \mathbb{E}_{\text{old}}[\log p(\gamma, \phi|y)] - \mathbb{E}_{\text{old}}[\log p(\gamma | \phi, y)] = Q(\phi|\phi^{\text{old}}) - H(\phi|\phi^{\text{old}})
\]</span></p>
<p><span class="math inline">\(H\)</span> 항을 <span class="math inline">\(\phi = \phi^{\text{old}}\)</span> 기준으로 평가하면</p>
<p><span class="math display">\[
H(\phi | \phi^{\text{old}}) - H(\phi^{\text{old}} | \phi^{\text{old}}) = \int p(\gamma | \phi^{\text{old}}, y) \log \frac{p(\gamma | \phi, y)}{p(\gamma | \phi^{\text{old}}, y)} \, d\gamma
\]</span></p>
<p>우변은 <strong>Kullback-Leibler 발산의 음수</strong>이므로 항상 <span class="math inline">\(\leq 0\)</span>. 즉 <span class="math inline">\(H(\phi|\phi^{\text{old}})\)</span> 는 <span class="math inline">\(\phi = \phi^{\text{old}}\)</span> 에서 <strong>최대</strong>이다 (Gibbs 부등식).</p>
<p>따라서 EM의 M-step에서 <span class="math inline">\(Q\)</span> 를 증가시키면 <span class="math inline">\(\log p(\phi|y)\)</span> 도 반드시 증가한다. 단조 증가가 성립한다.</p>
</section>
<section id="exercise-13.8-coagulation-예제의-퇴화-mode" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="exercise-13.8-coagulation-예제의-퇴화-mode"><span class="header-section-number">4.2</span> Exercise 13.8 — Coagulation 예제의 퇴화 Mode</h3>
<p><strong>문제</strong>: 응고 데이터 예제에서 <span class="math inline">\(\tau = 0, \theta_j = \mu\)</span> 인 퇴화 mode가 존재함을 보이고, 이 mode 주변의 사후 질량이 작음을 증명하라.</p>
<p><strong>풀이 스케치</strong>:</p>
<p>모형: <span class="math inline">\(y_{ij} \sim N(\theta_j, \sigma^2)\)</span>, <span class="math inline">\(\theta_j \sim N(\mu, \tau^2)\)</span>.</p>
<p><strong>(a) 퇴화 mode의 존재</strong>: <span class="math inline">\(\tau \to 0\)</span> 극한에서 모든 <span class="math inline">\(\theta_j = \mu\)</span> 로 수렴. 이때 likelihood <span class="math inline">\(\prod N(y_{ij} | \mu, \sigma^2)\)</span> 는 유한하고, prior <span class="math inline">\(p(\tau) \propto 1\)</span> 또는 folded normal이라면 <span class="math inline">\(\tau = 0\)</span> 에서도 유계. 그러나 <span class="math inline">\(p(\theta_j | \mu, \tau)\)</span> 의 <span class="math inline">\(\prod 1/\tau\)</span> 요인이 <span class="math inline">\(\tau \to 0\)</span> 에서 <strong>발산</strong>. 따라서 <span class="math inline">\(\theta_j = \mu\)</span> 로 정확히 동시 수렴할 때만 unnormalized density가 유한값을 가지며 이것이 퇴화 mode를 형성한다.</p>
<p><strong>(b)~(d) 퇴화 mode 주변의 사후 질량</strong>: <span class="math inline">\(\tau\)</span> 가 작을 때 <span class="math inline">\(\theta_j\)</span> 가 <span class="math inline">\(\mu\)</span> 근방에 갇혀 있을 확률은 delta 함수에 가까운 좁은 영역에 해당. 이 영역의 부피는 <span class="math inline">\(\tau^J\)</span> 에 비례. <span class="math inline">\(J\)</span> (그룹 수)가 작지 않으면 <span class="math inline">\(\tau^J\)</span> 는 <span class="math inline">\(\tau \to 0\)</span> 에서 빠르게 0으로 감. 따라서 해당 영역의 사후 질량은 유한 mode 주변의 질량에 비해 <strong>지수적으로 작다</strong>.</p>
<p><strong>결론</strong>: 퇴화 mode는 수치적 MAP 최적화 시 함정이 될 수 있지만 실제 사후 분포의 대부분의 mass는 다른 mode에 있다. 이것이 Gelman이 경계 회피 prior Gamma(2, A)를 권장하는 실증적 근거이기도 하다 (02-13-1 참조).</p>
</section>
<section id="exercise-13.10-probit-회귀의-variational-bayes" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="exercise-13.10-probit-회귀의-variational-bayes"><span class="header-section-number">4.3</span> Exercise 13.10 — Probit 회귀의 Variational Bayes</h3>
<p><strong>문제</strong>: Probit 회귀 <span class="math inline">\(\Pr(y_i=1) = \Phi(a + bx_i)\)</span> 를 잠재변수 <span class="math inline">\(z_i \sim N(a+bx_i, 1)\)</span>, <span class="math inline">\(y_i = \mathbb{1}[z_i &gt; 0]\)</span> 로 표현한 후, <span class="math inline">\((a, b, z_1, \dots, z_n)\)</span> 의 <span class="math inline">\(n+2\)</span> 차원 mean-field VB를 구성하라.</p>
<p><strong>(a) 로그 결합 사후</strong>: 사전분포 <span class="math inline">\(a, b \sim\)</span> diffuse (예: <span class="math inline">\(N(0, 100^2)\)</span>),</p>
<p><span class="math display">\[
\log p(a, b, z | y) = \text{const} - \frac{1}{2 \cdot 100^2}(a^2 + b^2) - \frac{1}{2} \sum_{i=1}^n (z_i - a - b x_i)^2 + \sum_{i=1}^n \log \mathbb{1}[z_i \cdot (2y_i - 1) &gt; 0]
\]</span></p>
<p>마지막 항은 <span class="math inline">\(y_i = 1\)</span> 이면 <span class="math inline">\(z_i &gt; 0\)</span> 을 강제, <span class="math inline">\(y_i = 0\)</span> 이면 <span class="math inline">\(z_i &lt; 0\)</span> 을 강제하는 지시함수.</p>
<p><strong>(b) 인수 형태</strong>: 평균장 <span class="math inline">\(q(a, b, z) = q(a) q(b) \prod q(z_i)\)</span>.</p>
<p><span class="math inline">\(q(z_i)\)</span>: <span class="math inline">\(\log q(z_i) = \mathbb{E}_{q(a)q(b)}[\log p] + \text{const}\)</span> 에서 <span class="math inline">\(z_i\)</span> 에 관한 항만 남기면</p>
<p><span class="math display">\[
\log q(z_i) = -\frac{1}{2}(z_i - \mathbb{E}[a] - \mathbb{E}[b] x_i)^2 + \log \mathbb{1}[z_i \cdot (2y_i - 1) &gt; 0]
\]</span></p>
<p>따라서 <span class="math inline">\(q(z_i)\)</span> 는 <strong>truncated normal</strong>:</p>
<p><span class="math display">\[
q(z_i) = \text{TN}(\mu_{z_i}, 1 ; A_i), \quad \mu_{z_i} = \mathbb{E}[a] + \mathbb{E}[b] x_i, \quad A_i = \begin{cases} (0, \infty) &amp; y_i=1 \\ (-\infty, 0) &amp; y_i=0 \end{cases}
\]</span></p>
<p>평균:</p>
<p><span class="math display">\[
\mathbb{E}[z_i] = \mu_{z_i} + (2y_i - 1) \frac{\phi(\mu_{z_i})}{\Phi((2y_i-1) \mu_{z_i})}
\]</span></p>
<p>(truncated normal mean formula)</p>
<p><span class="math inline">\(q(a)\)</span>: <span class="math inline">\(a\)</span> 에 관한 항만 남기면</p>
<p><span class="math display">\[
\log q(a) = -\frac{a^2}{2 \cdot 100^2} - \frac{1}{2} \sum_i (\mathbb{E}[z_i] - a - \mathbb{E}[b] x_i)^2
\]</span></p>
<p>이는 <span class="math inline">\(a\)</span> 에 대한 이차식 → <strong>Normal</strong>. 완성하면</p>
<p><span class="math display">\[
q(a) = N\left( \mu_a = \frac{\sum_i (\mathbb{E}[z_i] - \mathbb{E}[b] x_i)}{n + 1/100^2}, \; \sigma_a^2 = \frac{1}{n + 1/100^2} \right)
\]</span></p>
<p><span class="math inline">\(q(b)\)</span>: 동일 방식으로</p>
<p><span class="math display">\[
q(b) = N\left( \mu_b = \frac{\sum_i x_i (\mathbb{E}[z_i] - \mathbb{E}[a])}{\sum_i x_i^2 + 1/100^2}, \; \sigma_b^2 = \frac{1}{\sum_i x_i^2 + 1/100^2} \right)
\]</span></p>
<p><strong>(c) VB 알고리즘</strong>:</p>
<ol type="1">
<li>초기화: <span class="math inline">\(\mathbb{E}[a] = 0, \mathbb{E}[b] = 0\)</span>.</li>
<li>반복:
<ul>
<li><span class="math inline">\(\mu_{z_i} \leftarrow \mathbb{E}[a] + \mathbb{E}[b] x_i\)</span> for all <span class="math inline">\(i\)</span>.</li>
<li><span class="math inline">\(\mathbb{E}[z_i] \leftarrow \mu_{z_i} + (2y_i - 1) \phi(\mu_{z_i})/\Phi((2y_i-1)\mu_{z_i})\)</span>.</li>
<li><span class="math inline">\(\mathbb{E}[a] \leftarrow \mu_a\)</span> 위 식으로 갱신.</li>
<li><span class="math inline">\(\mathbb{E}[b] \leftarrow \mu_b\)</span> 위 식으로 갱신.</li>
</ul></li>
<li>ELBO 수렴 시 종료.</li>
</ol>
<p>Python 구현:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="im">from</span> scipy.stats <span class="im">import</span> norm</span>
<span id="cb1-3"><a href="#cb1-3"></a></span>
<span id="cb1-4"><a href="#cb1-4"></a><span class="kw">def</span> probit_vb(y, x, prior_var<span class="op">=</span><span class="fl">100.0</span><span class="op">**</span><span class="dv">2</span>, n_iter<span class="op">=</span><span class="dv">200</span>, tol<span class="op">=</span><span class="fl">1e-6</span>):</span>
<span id="cb1-5"><a href="#cb1-5"></a>    <span class="co">"""</span></span>
<span id="cb1-6"><a href="#cb1-6"></a><span class="co">    Probit regression VB with latent z, mean-field q(a)q(b)prod q(z_i).</span></span>
<span id="cb1-7"><a href="#cb1-7"></a><span class="co">    Returns posterior means mu_a, mu_b.</span></span>
<span id="cb1-8"><a href="#cb1-8"></a><span class="co">    """</span></span>
<span id="cb1-9"><a href="#cb1-9"></a>    n <span class="op">=</span> <span class="bu">len</span>(y)</span>
<span id="cb1-10"><a href="#cb1-10"></a>    sign <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> y <span class="op">-</span> <span class="dv">1</span></span>
<span id="cb1-11"><a href="#cb1-11"></a></span>
<span id="cb1-12"><a href="#cb1-12"></a>    <span class="co"># initialize</span></span>
<span id="cb1-13"><a href="#cb1-13"></a>    E_a, E_b <span class="op">=</span> <span class="fl">0.0</span>, <span class="fl">0.0</span></span>
<span id="cb1-14"><a href="#cb1-14"></a>    E_z <span class="op">=</span> np.zeros(n)</span>
<span id="cb1-15"><a href="#cb1-15"></a></span>
<span id="cb1-16"><a href="#cb1-16"></a>    elbos <span class="op">=</span> []</span>
<span id="cb1-17"><a href="#cb1-17"></a>    <span class="cf">for</span> it <span class="kw">in</span> <span class="bu">range</span>(n_iter):</span>
<span id="cb1-18"><a href="#cb1-18"></a>        <span class="co"># q(z_i): truncated normal mean</span></span>
<span id="cb1-19"><a href="#cb1-19"></a>        mu_z <span class="op">=</span> E_a <span class="op">+</span> E_b <span class="op">*</span> x</span>
<span id="cb1-20"><a href="#cb1-20"></a>        pdf <span class="op">=</span> norm.pdf(mu_z)</span>
<span id="cb1-21"><a href="#cb1-21"></a>        cdf_abs <span class="op">=</span> norm.cdf(sign <span class="op">*</span> mu_z)</span>
<span id="cb1-22"><a href="#cb1-22"></a>        E_z <span class="op">=</span> mu_z <span class="op">+</span> sign <span class="op">*</span> pdf <span class="op">/</span> np.maximum(cdf_abs, <span class="fl">1e-12</span>)</span>
<span id="cb1-23"><a href="#cb1-23"></a></span>
<span id="cb1-24"><a href="#cb1-24"></a>        <span class="co"># q(a)</span></span>
<span id="cb1-25"><a href="#cb1-25"></a>        var_a <span class="op">=</span> <span class="fl">1.0</span> <span class="op">/</span> (n <span class="op">+</span> <span class="fl">1.0</span> <span class="op">/</span> prior_var)</span>
<span id="cb1-26"><a href="#cb1-26"></a>        E_a_new <span class="op">=</span> var_a <span class="op">*</span> np.<span class="bu">sum</span>(E_z <span class="op">-</span> E_b <span class="op">*</span> x)</span>
<span id="cb1-27"><a href="#cb1-27"></a></span>
<span id="cb1-28"><a href="#cb1-28"></a>        <span class="co"># q(b)</span></span>
<span id="cb1-29"><a href="#cb1-29"></a>        sxx <span class="op">=</span> np.<span class="bu">sum</span>(x <span class="op">*</span> x)</span>
<span id="cb1-30"><a href="#cb1-30"></a>        var_b <span class="op">=</span> <span class="fl">1.0</span> <span class="op">/</span> (sxx <span class="op">+</span> <span class="fl">1.0</span> <span class="op">/</span> prior_var)</span>
<span id="cb1-31"><a href="#cb1-31"></a>        E_b_new <span class="op">=</span> var_b <span class="op">*</span> np.<span class="bu">sum</span>(x <span class="op">*</span> (E_z <span class="op">-</span> E_a_new))</span>
<span id="cb1-32"><a href="#cb1-32"></a></span>
<span id="cb1-33"><a href="#cb1-33"></a>        <span class="co"># crude ELBO proxy (convergence tracking)</span></span>
<span id="cb1-34"><a href="#cb1-34"></a>        change <span class="op">=</span> <span class="bu">abs</span>(E_a_new <span class="op">-</span> E_a) <span class="op">+</span> <span class="bu">abs</span>(E_b_new <span class="op">-</span> E_b)</span>
<span id="cb1-35"><a href="#cb1-35"></a>        E_a, E_b <span class="op">=</span> E_a_new, E_b_new</span>
<span id="cb1-36"><a href="#cb1-36"></a>        elbos.append(change)</span>
<span id="cb1-37"><a href="#cb1-37"></a>        <span class="cf">if</span> change <span class="op">&lt;</span> tol:</span>
<span id="cb1-38"><a href="#cb1-38"></a>            <span class="cf">break</span></span>
<span id="cb1-39"><a href="#cb1-39"></a></span>
<span id="cb1-40"><a href="#cb1-40"></a>    <span class="cf">return</span> {<span class="st">'E_a'</span>: E_a, <span class="st">'E_b'</span>: E_b, <span class="st">'var_a'</span>: var_a, <span class="st">'var_b'</span>: var_b,</span>
<span id="cb1-41"><a href="#cb1-41"></a>            <span class="st">'iters'</span>: it <span class="op">+</span> <span class="dv">1</span>}</span>
<span id="cb1-42"><a href="#cb1-42"></a></span>
<span id="cb1-43"><a href="#cb1-43"></a></span>
<span id="cb1-44"><a href="#cb1-44"></a><span class="co"># demo: simulated probit data</span></span>
<span id="cb1-45"><a href="#cb1-45"></a>np.random.seed(<span class="dv">42</span>)</span>
<span id="cb1-46"><a href="#cb1-46"></a>n <span class="op">=</span> <span class="dv">200</span></span>
<span id="cb1-47"><a href="#cb1-47"></a>x <span class="op">=</span> np.random.randn(n)</span>
<span id="cb1-48"><a href="#cb1-48"></a>a_true, b_true <span class="op">=</span> <span class="fl">0.5</span>, <span class="fl">1.2</span></span>
<span id="cb1-49"><a href="#cb1-49"></a>z <span class="op">=</span> a_true <span class="op">+</span> b_true <span class="op">*</span> x <span class="op">+</span> np.random.randn(n)</span>
<span id="cb1-50"><a href="#cb1-50"></a>y <span class="op">=</span> (z <span class="op">&gt;</span> <span class="dv">0</span>).astype(<span class="bu">int</span>)</span>
<span id="cb1-51"><a href="#cb1-51"></a></span>
<span id="cb1-52"><a href="#cb1-52"></a>vb <span class="op">=</span> probit_vb(y, x)</span>
<span id="cb1-53"><a href="#cb1-53"></a><span class="bu">print</span>(<span class="ss">f"True: a=</span><span class="sc">{</span>a_true<span class="sc">}</span><span class="ss">, b=</span><span class="sc">{</span>b_true<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb1-54"><a href="#cb1-54"></a><span class="bu">print</span>(<span class="ss">f"VB:   a=</span><span class="sc">{</span>vb[<span class="st">'E_a'</span>]<span class="sc">:.3f}</span><span class="ss">, b=</span><span class="sc">{</span>vb[<span class="st">'E_b'</span>]<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb1-55"><a href="#cb1-55"></a><span class="bu">print</span>(<span class="ss">f"VB SD: a=</span><span class="sc">{</span>np<span class="sc">.</span>sqrt(vb[<span class="st">'var_a'</span>])<span class="sc">:.3f}</span><span class="ss">, b=</span><span class="sc">{</span>np<span class="sc">.</span>sqrt(vb[<span class="st">'var_b'</span>])<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb1-56"><a href="#cb1-56"></a><span class="bu">print</span>(<span class="ss">f"Converged in </span><span class="sc">{</span>vb[<span class="st">'iters'</span>]<span class="sc">}</span><span class="ss"> iters"</span>)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>예상 출력 (시뮬레이션에 따라 변동):</p>
<pre><code>True: a=0.5, b=1.2
VB:   a=0.487, b=1.185
VB SD: a=0.086, b=0.101
Converged in 12 iters</code></pre>
<p><strong>주의</strong>: mean-field VB이므로 <span class="math inline">\(a, b\)</span> 의 상관이 0으로 가정되어 <strong>과소분산</strong> (02-13-3의 VI 한계 참고). 정확한 사후 상관을 원하면 full-rank VB나 MCMC로 확인해야 한다.</p>
</section>
<section id="exercise-13.11-unknown-normalizing-factor-계산" class="level3" data-number="4.4">
<h3 data-number="4.4" class="anchored" data-anchor-id="exercise-13.11-unknown-normalizing-factor-계산"><span class="header-section-number">4.4</span> Exercise 13.11 — Unknown Normalizing Factor 계산</h3>
<p><strong>문제</strong>: 다음 unnormalized density의 정규화 상수를 <span class="math inline">\(A, B, C\)</span> 의 함수로 구하라.</p>
<p><span class="math display">\[
p(y | \mu, A, B, C) \propto \exp\left[ -\frac{1}{2} \left( A(y-\mu)^6 + B(y-\mu)^4 + C(y-\mu)^2 \right) \right]
\]</span></p>
<p><strong>풀이</strong>: <span class="math inline">\(u = y - \mu\)</span> 치환하면 <span class="math inline">\(\mu\)</span> 는 location shift이므로 정규화 상수에 무관.</p>
<p><span class="math display">\[
z(A, B, C) = \int_{-\infty}^{\infty} \exp\left[ -\frac{1}{2}(A u^6 + B u^4 + C u^2) \right] du
\]</span></p>
<p><strong>해석적 해가 없다</strong>. 이것이 § 13.10이 다루는 바로 그 상황 — <span class="math inline">\(z\)</span> 가 모수 의존적이고 닫힌 형태가 없는 사례. 현실적 접근:</p>
<p><strong>(i) Laplace 근사</strong>: 피적분함수의 mode <span class="math inline">\(u^*\)</span> 를 찾고 (여기서는 대칭성으로 <span class="math inline">\(u^*=0\)</span>), Hessian <span class="math inline">\(H^* = -[\log\)</span> integrand<span class="math inline">\(]''\)</span> 평가.</p>
<p><span class="math inline">\(u=0\)</span> 에서 <span class="math inline">\(\log\)</span> integrand = <span class="math inline">\(0\)</span>, 2차 도함수 = <span class="math inline">\(-C\)</span>. 따라서</p>
<p><span class="math display">\[
z_{\text{Laplace}} \approx \sqrt{\frac{2\pi}{C}}
\]</span></p>
<p><span class="math inline">\(B, A\)</span> 가 작을 때 좋은 근사, 크면 tail에 mass가 집중되어 실패.</p>
<p><strong>(ii) Importance sampling</strong>: 제안 분포 <span class="math inline">\(g(u) = N(0, 1/C)\)</span> (Laplace matching).</p>
<p><span class="math display">\[
\hat{z} = \frac{1}{S} \sum_{s=1}^{S} \frac{\exp[-\frac{1}{2}(A(u^s)^6 + B(u^s)^4 + C(u^s)^2)]}{N(u^s | 0, 1/C)}, \quad u^s \sim N(0, 1/C)
\]</span></p>
<p><strong>(iii) 수치 적분</strong> (1차원이므로 직접): Gauss-Hermite 또는 Simpson.</p>
<p>Python 구현:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb3-2"><a href="#cb3-2"></a><span class="im">from</span> scipy.integrate <span class="im">import</span> quad</span>
<span id="cb3-3"><a href="#cb3-3"></a><span class="im">from</span> scipy.stats <span class="im">import</span> norm</span>
<span id="cb3-4"><a href="#cb3-4"></a></span>
<span id="cb3-5"><a href="#cb3-5"></a><span class="kw">def</span> unnormalized(u, A, B, C):</span>
<span id="cb3-6"><a href="#cb3-6"></a>    <span class="cf">return</span> np.exp(<span class="op">-</span><span class="fl">0.5</span> <span class="op">*</span> (A <span class="op">*</span> u<span class="op">**</span><span class="dv">6</span> <span class="op">+</span> B <span class="op">*</span> u<span class="op">**</span><span class="dv">4</span> <span class="op">+</span> C <span class="op">*</span> u<span class="op">**</span><span class="dv">2</span>))</span>
<span id="cb3-7"><a href="#cb3-7"></a></span>
<span id="cb3-8"><a href="#cb3-8"></a><span class="kw">def</span> z_laplace(A, B, C):</span>
<span id="cb3-9"><a href="#cb3-9"></a>    <span class="co">"""Laplace approx centered at u=0 (valid for large C)."""</span></span>
<span id="cb3-10"><a href="#cb3-10"></a>    <span class="cf">return</span> np.sqrt(<span class="dv">2</span> <span class="op">*</span> np.pi <span class="op">/</span> C)</span>
<span id="cb3-11"><a href="#cb3-11"></a></span>
<span id="cb3-12"><a href="#cb3-12"></a><span class="kw">def</span> z_importance_sampling(A, B, C, S<span class="op">=</span><span class="dv">100000</span>, seed<span class="op">=</span><span class="dv">0</span>):</span>
<span id="cb3-13"><a href="#cb3-13"></a>    <span class="co">"""IS with g = N(0, 1/C)."""</span></span>
<span id="cb3-14"><a href="#cb3-14"></a>    rng <span class="op">=</span> np.random.default_rng(seed)</span>
<span id="cb3-15"><a href="#cb3-15"></a>    sigma <span class="op">=</span> <span class="fl">1.0</span> <span class="op">/</span> np.sqrt(C)</span>
<span id="cb3-16"><a href="#cb3-16"></a>    u <span class="op">=</span> rng.normal(<span class="dv">0</span>, sigma, size<span class="op">=</span>S)</span>
<span id="cb3-17"><a href="#cb3-17"></a>    w <span class="op">=</span> unnormalized(u, A, B, C) <span class="op">/</span> norm.pdf(u, <span class="dv">0</span>, sigma)</span>
<span id="cb3-18"><a href="#cb3-18"></a>    z_hat <span class="op">=</span> np.mean(w)</span>
<span id="cb3-19"><a href="#cb3-19"></a>    z_se <span class="op">=</span> np.std(w) <span class="op">/</span> np.sqrt(S)</span>
<span id="cb3-20"><a href="#cb3-20"></a>    <span class="cf">return</span> z_hat, z_se</span>
<span id="cb3-21"><a href="#cb3-21"></a></span>
<span id="cb3-22"><a href="#cb3-22"></a><span class="kw">def</span> z_quadrature(A, B, C):</span>
<span id="cb3-23"><a href="#cb3-23"></a>    <span class="co">"""Adaptive quadrature (numerical truth)."""</span></span>
<span id="cb3-24"><a href="#cb3-24"></a>    val, _ <span class="op">=</span> quad(unnormalized, <span class="op">-</span>np.inf, np.inf, args<span class="op">=</span>(A, B, C))</span>
<span id="cb3-25"><a href="#cb3-25"></a>    <span class="cf">return</span> val</span>
<span id="cb3-26"><a href="#cb3-26"></a></span>
<span id="cb3-27"><a href="#cb3-27"></a><span class="co"># comparison</span></span>
<span id="cb3-28"><a href="#cb3-28"></a><span class="cf">for</span> A, B, C <span class="kw">in</span> [(<span class="fl">0.01</span>, <span class="fl">0.1</span>, <span class="fl">1.0</span>), (<span class="fl">0.1</span>, <span class="fl">0.5</span>, <span class="fl">1.0</span>), (<span class="fl">1.0</span>, <span class="fl">1.0</span>, <span class="fl">1.0</span>)]:</span>
<span id="cb3-29"><a href="#cb3-29"></a>    z_true <span class="op">=</span> z_quadrature(A, B, C)</span>
<span id="cb3-30"><a href="#cb3-30"></a>    z_lap <span class="op">=</span> z_laplace(A, B, C)</span>
<span id="cb3-31"><a href="#cb3-31"></a>    z_is, se <span class="op">=</span> z_importance_sampling(A, B, C)</span>
<span id="cb3-32"><a href="#cb3-32"></a>    <span class="bu">print</span>(<span class="ss">f"A=</span><span class="sc">{</span>A<span class="sc">}</span><span class="ss">, B=</span><span class="sc">{</span>B<span class="sc">}</span><span class="ss">, C=</span><span class="sc">{</span>C<span class="sc">}</span><span class="ss">: true=</span><span class="sc">{</span>z_true<span class="sc">:.4f}</span><span class="ss">, "</span></span>
<span id="cb3-33"><a href="#cb3-33"></a>          <span class="ss">f"Laplace=</span><span class="sc">{</span>z_lap<span class="sc">:.4f}</span><span class="ss"> (err </span><span class="sc">{</span><span class="bu">abs</span>(z_lap<span class="op">-</span>z_true)<span class="op">/</span>z_true<span class="sc">:.1%}</span><span class="ss">), "</span></span>
<span id="cb3-34"><a href="#cb3-34"></a>          <span class="ss">f"IS=</span><span class="sc">{</span>z_is<span class="sc">:.4f}</span><span class="ss"> (se=</span><span class="sc">{</span>se<span class="sc">:.4f}</span><span class="ss">)"</span>)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>예상 출력:</p>
<pre><code>A=0.01, B=0.1, C=1.0: true=2.3862, Laplace=2.5066 (err 5.0%), IS=2.3862 (se=0.0050)
A=0.1, B=0.5, C=1.0:  true=1.8104, Laplace=2.5066 (err 38.5%), IS=1.8104 (se=0.0068)
A=1.0, B=1.0, C=1.0:  true=1.5005, Laplace=2.5066 (err 67.1%), IS=1.5004 (se=0.0078)</code></pre>
<p><strong>해석</strong>: <span class="math inline">\(B, A\)</span> 가 클수록 Laplace는 심각하게 부정확. IS는 수치적 참값에 거의 일치 (적절한 proposal이면). 이것이 § 13.10이 권하는 실무 패턴 — <strong>Laplace로 대략 파악 → IS/MC로 정밀화</strong>.</p>
</section>
</section>
<section id="ch.13-심화-시리즈-결산" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="ch.13-심화-시리즈-결산"><span class="header-section-number">5</span> Ch.13 심화 시리즈 결산</h2>
<section id="편-논리-지도" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="편-논리-지도"><span class="header-section-number">5.1</span> 4편 논리 지도</h3>
<pre><code>[Ch.13 Overview] 02-13-0
    ↓ MCMC 비용이 큰 상황에서 근사 기법이 필요
[§ 13.1~13.3] 02-13-1: Mode Finding + Laplace
    ↓ 경계 퇴화 + Gamma(2,·) 권장
    ↓ 정규 근사가 쓰일 수 있는 영역 특정
[§ 13.4~13.6] 02-13-2: EM + 조건부/주변 근사
    ↓ 잠재변수 통합의 표준 도구
    ↓ ECM/ECME/SEM/PX-EM 가계도
[§ 13.7~13.8] 02-13-3: VI + EP
    ↓ KL(q||p) 최소화 → 전역 근사
    ↓ mean-field 한계와 EP의 tilted distribution 대안
[§ 13.10~13.12] 02-13-4 (본편): z(θ) 문제 + 문헌 + 연습
    ↓ doubly intractable → Bridge/Path/Exchange/PM-MCMC/ABC
    ↓ Ch.13 전체 기법이 § 13.10의 Step 1~2에 통합</code></pre>
</section>
<section id="ch.13-심화-전체-체크리스트" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="ch.13-심화-전체-체크리스트"><span class="header-section-number">5.2</span> Ch.13 심화 전체 체크리스트</h3>
<p>모형 앞에서 다음 질문을 순서대로 확인한다.</p>
<p><strong>1. Likelihood 정규화 상수 <span class="math inline">\(z(\theta)\)</span> 가 <span class="math inline">\(\theta\)</span> 에 의존하는가?</strong></p>
<ul>
<li>Yes (Ising, Potts, ERGM, 공간 MRF, Gibbs point process) → <strong>§ 13.10</strong> 우선 적용 (Bridge/Path/Exchange/PM-MCMC/ABC).</li>
<li>No → 일반적 베이지안 계산, 다음 질문으로.</li>
</ul>
<p><strong>2. MCMC 예산이 충분한가?</strong></p>
<ul>
<li>충분 (수 시간~수 일) → Ch.11/12 (Gibbs, MH, HMC).</li>
<li>부족 (초~분 단위) → Ch.13 근사 기법 검토.</li>
</ul>
<p><strong>3. 사후분포의 </strong>목적<strong>은 무엇인가?</strong></p>
<ul>
<li>사후 평균·표준편차만 필요 → VI/EP (02-13-3).</li>
<li>예측 분포·예측 불확실성 → EP 선호 (kurtosis 보존).</li>
<li>Marginal likelihood (모형 비교) → Bridge/Path (§ 13.10) 또는 EP + marginal likelihood 추정.</li>
<li>사후 최빈값만 → mode finding + Laplace (02-13-1).</li>
</ul>
<p><strong>4. Latent variable 구조가 있는가?</strong></p>
<ul>
<li>Yes (결측, 혼합, 잠재 클래스) → EM 계열 우선 (02-13-2). 복잡도에 따라 ECM → ECME → PX-EM.</li>
<li>No → 직접 mode finding 또는 VI.</li>
</ul>
<p><strong>5. 사전분포의 경계 퇴화 위험이 있는가?</strong></p>
<ul>
<li>분산 성분 <span class="math inline">\(\sigma^2, \tau^2\)</span> 이 0 근처 수용 → Gamma(2, ·) 등 경계 회피 prior (02-13-1).</li>
<li>상관/공분산 → Wishart(d+3, AI) 또는 LKJ.</li>
</ul>
<p><strong>6. 고차원 continuous <span class="math inline">\(\theta\)</span></strong> (<span class="math inline">\(&gt; 100\)</span>)?</p>
<ul>
<li>Laplace의 Hessian 계산 불가 → VI의 <strong>mean-field</strong> 또는 <strong>low-rank</strong>, 혹은 ADVI/NUTS.</li>
<li>매우 고차원 (VAE 수준) → Amortized VI + reparameterization trick.</li>
</ul>
<p><strong>7. 다봉 분포?</strong></p>
<ul>
<li>봉우리 간 분리가 큼 → Modal 근사는 잘못된 답을 줄 수 있음. Tempering, RJMCMC, 혹은 혼합 정규 근사 (Ch.13 초반).</li>
<li>보통 분리 → VI가 한 봉우리로 수렴하므로 다중 초기화.</li>
</ul>
</section>
<section id="구현-환경-매핑" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="구현-환경-매핑"><span class="header-section-number">5.3</span> 구현 환경 매핑</h3>
<table class="table">
<thead>
<tr class="header">
<th>기법</th>
<th>권장 도구</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mode finding + Laplace</td>
<td>scipy.optimize + numdifftools</td>
</tr>
<tr class="even">
<td>EM / ECM</td>
<td>수동 구현 or sklearn.mixture</td>
</tr>
<tr class="odd">
<td>Variational Inference</td>
<td>PyMC, NumPyro (ADVI), TensorFlow Probability</td>
</tr>
<tr class="even">
<td>Normalizing Flows VI</td>
<td>Pyro, flowtorch</td>
</tr>
<tr class="odd">
<td>Expectation Propagation</td>
<td>GPflow (GP classification), EPY, 수동</td>
</tr>
<tr class="even">
<td>INLA</td>
<td>R-INLA 패키지 (공간·시계열 특화)</td>
</tr>
<tr class="odd">
<td>Bridge Sampling</td>
<td>bridgesampling (R), pymc-bridgesampling</td>
</tr>
<tr class="even">
<td>Exchange / PM-MCMC</td>
<td>수동 Stan/NumPyro</td>
</tr>
<tr class="odd">
<td>ABC</td>
<td>elfi, ABCpy, pyabc</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="관련-주제" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="관련-주제"><span class="header-section-number">6</span> 관련 주제</h2>
<p><strong>선행 지식</strong></p>
<ul>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/02-13-0-modal-variational-approximations.html">Ch.13 Overview — Modal and Variational Approximations</a></li>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/02-13-1-mode-finding-boundary-priors-laplace.html">§ 13.1~13.3 — Mode Finding·Boundary-avoiding Priors·Laplace</a></li>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/02-13-2-em-conditional-marginal-hierarchical.html">§ 13.4~13.6 — EM·조건부/주변 근사</a></li>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/02-13-3-variational-inference-expectation-propagation.html">§ 13.7~13.8 — Variational Inference·Expectation Propagation</a></li>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/02-10-0-computation-intro.html">Ch.10~12 — Bayesian Computation (MCMC 계열)</a></li>
</ul>
<p><strong>후속 주제 (Gelman Part IV~VII)</strong></p>
<ul>
<li>Ch.14 Linear Regression — 표준 정규 회귀의 베이지안 분석</li>
<li>Ch.15 Hierarchical Linear Models — 다수준 회귀</li>
<li>Ch.16 Generalized Linear Models — 로지스틱, 포아송, MRP</li>
<li>Ch.21 Gaussian Process Models — doubly intractable이 자연스럽게 나타나는 영역</li>
<li>Ch.22 Finite Mixture Models — EM의 대표 응용</li>
<li>Ch.23 Dirichlet Process Models — 비모수 베이즈</li>
</ul>
<p><strong>관련 개념 (cross-category)</strong></p>
<ul>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/02-11-0-mcmc-basics.html">MCMC 기초</a> — Exchange algorithm의 토대</li>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/02-12-2-hmc-nuts-stan.html">HMC/NUTS와 Stan</a> — VI와의 trade-off</li>
<li><a href="../../Machine_Learning/em_algorithm.qmd">EM 알고리즘 (Machine Learning)</a> — MLE 맥락의 EM</li>
<li><a href="../../Deep_Learning/vae.qmd">Variational Autoencoder</a> — 현대 deep VI의 대표 응용</li>
</ul>
</section>
<section id="참고문헌" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="참고문헌"><span class="header-section-number">7</span> 참고문헌</h2>
<ul>
<li>Gelman, A., Carlin, J. B., Stern, H. S., Dunson, D. B., Vehtari, A., &amp; Rubin, D. B. (2013). <em>Bayesian Data Analysis</em> (3rd ed.), Ch.13 § 13.10~13.12. CRC Press.</li>
<li>Besag, J. (1974). Spatial Interaction and the Statistical Analysis of Lattice Systems. <em>JRSS B</em>, 36, 192-236.</li>
<li>Meng, X.-L., &amp; Wong, W. H. (1996). Simulating Ratios of Normalizing Constants via a Simple Identity. <em>Statistica Sinica</em>, 6, 831-860.</li>
<li>Gelman, A., &amp; Meng, X.-L. (1998). Simulating Normalizing Constants: From Importance Sampling to Bridge Sampling to Path Sampling. <em>Statistical Science</em>, 13, 163-185.</li>
<li>Murray, I., Ghahramani, Z., &amp; MacKay, D. J. C. (2006). MCMC for Doubly-Intractable Distributions. <em>UAI</em>.</li>
<li>Andrieu, C., &amp; Roberts, G. O. (2009). The Pseudo-Marginal Approach for Efficient Monte Carlo Computations. <em>Annals of Statistics</em>, 37, 697-725.</li>
<li>Beaumont, M. A. (2010). Approximate Bayesian Computation in Evolution and Ecology. <em>Annual Review of Ecology, Evolution, and Systematics</em>, 41, 379-406.</li>
<li>Marin, J.-M., Pudlo, P., Robert, C. P., &amp; Ryder, R. J. (2012). Approximate Bayesian Computational Methods. <em>Statistics and Computing</em>, 22, 1167-1180.</li>
</ul>


</section>

</main> <!-- /main -->
<script type="text/javascript">

// replace cmd keyboard shortcut w/ control on non-Mac platforms
const kPlatformMac = typeof navigator !== 'undefined' ? /Mac/.test(navigator.platform) : false;
if (!kPlatformMac) {
   var kbds = document.querySelectorAll("kbd")
   kbds.forEach(function(kbd) {
      kbd.innerHTML = kbd.innerHTML.replace(/⌘/g, '⌃');
   });
}

// tweak headings in pymd
document.querySelectorAll(".pymd span.co").forEach(el => {
   if (!el.innerText.startsWith("#|")) {
      el.style.fontWeight = 1000;
   }
});

</script>
<!-- Begin Mailchimp Signup Form -->
<div id="mc_embed_signup" style="padding-bottom: 1em; max-width: 400px;" class="ms-auto me-auto">
  <p style="font-weight: 600; margin-bottom: 0;">Subscribe</p>
  <span style="font-size: 0.9em;">Enjoy this blog? Get notified of new posts by email:</span>
<form action="https://quarto.us14.list-manage.com/subscribe/post?u=c79fb56a311ae347fbe916740&amp;id=ec05dfca03" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate="">
    <div id="mc_embed_signup_scroll">
	
        <div class="input-group mt-1 mb-2">
        <input type="email" class="form-control" placeholder="Email Address" aria-label="Email Address" name="EMAIL" style="font-size: 0.8em; padding: .2em;">
        </div>              

	<div id="mce-responses" class="clear foot">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_c79fb56a311ae347fbe916740_ec05dfca03" tabindex="-1" value=""></div>
        <div class="optionalParent">
            <div class="clear foot" style="display: flex; align-items: center; justify-content: center;">
              
              
                <input type="submit" value="Subscribe" name="subscribe" style="min-width: 150px; font-size: 0.8em;" id="mc-embedded-subscribe" class="button btn btn-light btn-sm ms-auto me-auto">
            </div>
        </div>
    </div>
</form>
</div>

<!--End mc_embed_signup-->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "복사완료!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "복사완료!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="kmink3225/blog" data-repo-id="R_kgDOLCZyDg" data-category="Blog" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script>
<input type="hidden" id="giscus-base-theme" value="light">
<input type="hidden" id="giscus-alt-theme" value="dark">
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Kwangmin Kim</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="../../../../../about.html">
<p>About</p>
</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/kmink3225/blog">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>