<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ko" xml:lang="ko"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.543">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kwangmin Kim">
<meta name="description" content="Gelman BDA Ch.14의 마지막 네 절을 한 편으로 마무리한다. § 14.7 불등 분산/상관 오차 회귀 — Σ_y known의 Cholesky 변환, 스칼라 팩터만 unknown (14.16)~(14.19), weighted linear regression, parametric variance v(w_i, φ) (14.20)~(14.22), 여러 분산 컴포넌트의 incumbency 예제 확장, § 14.8 수치적 prior 정보 — “prior = 추가 데이터 점”이라는 핵심 트릭과 식 (14.24) 유도, variance prior Inv-χ²(n_0, σ_0²), inequality 제약은 rejection으로, § 14.9 주제별 재구성한 문헌 지도, § 14.10 연습문제 핵심 풀이 (식 (14.4)(14.5)(14.7) OLS 유도, predictive 정규성, 식 (14.24) 증명, LASSO 1D), 마지막으로 Ch.14 심화 4편 시리즈의 로직맵과 결산 체크리스트를 정리한다.">

<title>Kwangmin Kim - Ch.14 § 14.7~14.10 심화 — Unequal Variances·Numerical Prior·문헌·연습 + Ch.14 결산</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../../../">
<script src="../../../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../../../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../../../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": true,
  "language": {
    "search-no-results-text": "일치 없음",
    "search-matching-documents-text": "일치된 문서",
    "search-copy-link-title": "검색 링크 복사",
    "search-hide-matches-text": "추가 검색 결과 숨기기",
    "search-more-match-text": "추가 검색결과",
    "search-more-matches-text": "추가 검색결과",
    "search-clear-button-title": "제거",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "취소",
    "search-submit-button-title": "검색",
    "search-label": "검색"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-6W0EKFMWBN"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-6W0EKFMWBN', { 'anonymize_ip': true});
</script>
<style>

      .quarto-title-block .quarto-title-banner h1,
      .quarto-title-block .quarto-title-banner h2,
      .quarto-title-block .quarto-title-banner h3,
      .quarto-title-block .quarto-title-banner h4,
      .quarto-title-block .quarto-title-banner h5,
      .quarto-title-block .quarto-title-banner h6
      {
        color: black;
      }

      .quarto-title-block .quarto-title-banner {
        color: black;
background: #EDF3F9;
      }
</style>
<style>
.custom-footer { 
  text-align: center; 
  font-size: 0.8em; 
  color: #666; 
  margin-top: 2rem; 
}
</style>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../../../styles.css">
<meta property="og:title" content="Kwangmin Kim - Ch.14 § 14.7~14.10 심화 — Unequal Variances·Numerical Prior·문헌·연습 + Ch.14 결산">
<meta property="og:description" content="Gelman BDA Ch.14의 마지막 네 절을 한 편으로 마무리한다. § 14.7 불등 분산/상관 오차 회귀 — Σ_y known의 Cholesky 변환, 스칼라 팩터만 unknown (14.16)~(14.19), weighted linear regression, parametric variance v(w_i, φ) (14.20)~(14.22), 여러 분산 컴포넌트의 incumbency 예제 확장, § 14.8 수치적 prior 정보 — “prior = 추가 데이터 점”이라는 핵심 트릭과 식 (14.24) 유도, variance prior Inv-χ²(n_0, σ_0²), inequality 제약은 rejection으로, § 14.9 주제별 재구성한 문헌 지도, § 14.10 연습문제 핵심 풀이 (식 (14.4)(14.5)(14.7) OLS 유도, predictive 정규성, 식 (14.24) 증명, LASSO 1D), 마지막으로 Ch.14 심화 4편 시리즈의 로직맵과 결산 체크리스트를 정리한다.">
<meta property="og:site_name" content="Kwangmin Kim">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../../../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../../../.././images/logo.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../../../../index.html">
    <span class="navbar-title">Kwangmin Kim</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="검색"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="탐색 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../../docs/blog/index.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../../../about.html"> 
<span class="menu-text">Me</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/kmink3225"> <i class="bi bi-github" role="img" aria-label="Github">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/kwangmin-kim-a5241b200/"> <i class="bi bi-linkedin" role="img" aria-label="Linkedin">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../../../../docs/blog/index.xml"> <i class="bi bi-rss" role="img" aria-label="RSS">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="다크 모드 전환"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Ch.14 § 14.7~14.10 심화 — Unequal Variances·Numerical Prior·문헌·연습 + Ch.14 결산</h1>
            <p class="subtitle lead">GLS Cholesky 변환·가중 회귀·parametric variance·식 (14.12)~(14.24) 완전 유도·Prior as extra data·연습문제 풀이 + Ch.14 심화 시리즈 총결산</p>
                  <div>
        <div class="description">
          <p>Gelman BDA Ch.14의 마지막 네 절을 한 편으로 마무리한다. § 14.7 불등 분산/상관 오차 회귀 — Σ_y known의 Cholesky 변환, 스칼라 팩터만 unknown (14.16)~(14.19), weighted linear regression, parametric variance v(w_i, φ) (14.20)~(14.22), 여러 분산 컴포넌트의 incumbency 예제 확장, § 14.8 수치적 prior 정보 — “prior = 추가 데이터 점”이라는 핵심 트릭과 식 (14.24) 유도, variance prior Inv-χ²(n_0, σ_0²), inequality 제약은 rejection으로, § 14.9 주제별 재구성한 문헌 지도, § 14.10 연습문제 핵심 풀이 (식 (14.4)(14.5)(14.7) OLS 유도, predictive 정규성, 식 (14.24) 증명, LASSO 1D), 마지막으로 Ch.14 심화 4편 시리즈의 로직맵과 결산 체크리스트를 정리한다.</p>
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">Statistics</div>
                <div class="quarto-category">Bayesian</div>
                <div class="quarto-category">Linear-Regression</div>
                <div class="quarto-category">Generalized-Least-Squares</div>
                <div class="quarto-category">Prior-Information</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">저자</div>
      <div class="quarto-title-meta-contents">
               <p>Kwangmin Kim </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">공개</div>
      <div class="quarto-title-meta-contents">
        <p class="date">2026년 04월 23일</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">목차</h2>
   
  <ul>
  <li><a href="#개요-ch.14-심화-시리즈의-마지막-편" id="toc-개요-ch.14-심화-시리즈의-마지막-편" class="nav-link active" data-scroll-target="#개요-ch.14-심화-시리즈의-마지막-편"><span class="header-section-number">1</span> 개요 — Ch.14 심화 시리즈의 마지막 편</a></li>
  <li><a href="#unequal-variances-and-correlations" id="toc-unequal-variances-and-correlations" class="nav-link" data-scroll-target="#unequal-variances-and-correlations"><span class="header-section-number">2</span> § 14.7 Unequal Variances and Correlations</a>
  <ul class="collapse">
  <li><a href="#일반-모형-식-14.11" id="toc-일반-모형-식-14.11" class="nav-link" data-scroll-target="#일반-모형-식-14.11"><span class="header-section-number">2.1</span> 일반 모형 — 식 (14.11)</a></li>
  <li><a href="#sigma_y-known-경우-cholesky-변환" id="toc-sigma_y-known-경우-cholesky-변환" class="nav-link" data-scroll-target="#sigma_y-known-경우-cholesky-변환"><span class="header-section-number">2.2</span> <span class="math inline">\(\Sigma_y\)</span> Known 경우 — Cholesky 변환</a></li>
  <li><a href="#unknown-sigma_y-일반-논의" id="toc-unknown-sigma_y-일반-논의" class="nav-link" data-scroll-target="#unknown-sigma_y-일반-논의"><span class="header-section-number">2.3</span> Unknown <span class="math inline">\(\Sigma_y\)</span> — 일반 논의</a></li>
  <li><a href="#특수-경우-1-스칼라-팩터만-unknown-식-14.1614.19" id="toc-특수-경우-1-스칼라-팩터만-unknown-식-14.1614.19" class="nav-link" data-scroll-target="#특수-경우-1-스칼라-팩터만-unknown-식-14.1614.19"><span class="header-section-number">2.4</span> 특수 경우 1: 스칼라 팩터만 Unknown — 식 (14.16)~(14.19)</a></li>
  <li><a href="#특수-경우-2-weighted-linear-regression" id="toc-특수-경우-2-weighted-linear-regression" class="nav-link" data-scroll-target="#특수-경우-2-weighted-linear-regression"><span class="header-section-number">2.5</span> 특수 경우 2: Weighted Linear Regression</a></li>
  <li><a href="#특수-경우-3-parametric-variance-식-14.2014.21" id="toc-특수-경우-3-parametric-variance-식-14.2014.21" class="nav-link" data-scroll-target="#특수-경우-3-parametric-variance-식-14.2014.21"><span class="header-section-number">2.6</span> 특수 경우 3: Parametric Variance — 식 (14.20)(14.21)</a></li>
  <li><a href="#특수-경우-4-여러-분산-컴포넌트-incumbency-재방문" id="toc-특수-경우-4-여러-분산-컴포넌트-incumbency-재방문" class="nav-link" data-scroll-target="#특수-경우-4-여러-분산-컴포넌트-incumbency-재방문"><span class="header-section-number">2.7</span> 특수 경우 4: 여러 분산 컴포넌트 (Incumbency 재방문)</a></li>
  <li><a href="#일반-형태-general-variance-model" id="toc-일반-형태-general-variance-model" class="nav-link" data-scroll-target="#일반-형태-general-variance-model"><span class="header-section-number">2.8</span> 일반 형태 — General Variance Model</a></li>
  </ul></li>
  <li><a href="#including-numerical-prior-information" id="toc-including-numerical-prior-information" class="nav-link" data-scroll-target="#including-numerical-prior-information"><span class="header-section-number">3</span> § 14.8 Including Numerical Prior Information</a>
  <ul class="collapse">
  <li><a href="#철학-prior-정보는-암묵적으로-이미-있다" id="toc-철학-prior-정보는-암묵적으로-이미-있다" class="nav-link" data-scroll-target="#철학-prior-정보는-암묵적으로-이미-있다"><span class="header-section-number">3.1</span> 철학: Prior 정보는 암묵적으로 이미 있다</a></li>
  <li><a href="#핵심-트릭-prior-추가-데이터-점" id="toc-핵심-트릭-prior-추가-데이터-점" class="nav-link" data-scroll-target="#핵심-트릭-prior-추가-데이터-점"><span class="header-section-number">3.2</span> 핵심 트릭: Prior = 추가 데이터 점</a></li>
  <li><a href="#극한-해석" id="toc-극한-해석" class="nav-link" data-scroll-target="#극한-해석"><span class="header-section-number">3.3</span> 극한 해석</a></li>
  <li><a href="#다차원-prior-식-14.24" id="toc-다차원-prior-식-14.24" class="nav-link" data-scroll-target="#다차원-prior-식-14.24"><span class="header-section-number">3.4</span> 다차원 Prior — 식 (14.24)</a></li>
  <li><a href="#sigma_beta-의-특수-형태-regularization과의-연결" id="toc-sigma_beta-의-특수-형태-regularization과의-연결" class="nav-link" data-scroll-target="#sigma_beta-의-특수-형태-regularization과의-연결"><span class="header-section-number">3.5</span> <span class="math inline">\(\Sigma_\beta\)</span> 의 특수 형태 — Regularization과의 연결</a></li>
  <li><a href="#variance-prior-conjugate-inverse-χ²" id="toc-variance-prior-conjugate-inverse-χ²" class="nav-link" data-scroll-target="#variance-prior-conjugate-inverse-χ²"><span class="header-section-number">3.6</span> Variance Prior — Conjugate Inverse-χ²</a></li>
  <li><a href="#부등식-제약-inequality-constraints" id="toc-부등식-제약-inequality-constraints" class="nav-link" data-scroll-target="#부등식-제약-inequality-constraints"><span class="header-section-number">3.7</span> 부등식 제약 (Inequality Constraints)</a></li>
  </ul></li>
  <li><a href="#bibliographic-note-주제별-재구성" id="toc-bibliographic-note-주제별-재구성" class="nav-link" data-scroll-target="#bibliographic-note-주제별-재구성"><span class="header-section-number">4</span> § 14.9 Bibliographic Note — 주제별 재구성</a>
  <ul class="collapse">
  <li><a href="#정규-선형-회귀-빈도주의" id="toc-정규-선형-회귀-빈도주의" class="nav-link" data-scroll-target="#정규-선형-회귀-빈도주의"><span class="header-section-number">4.1</span> 정규 선형 회귀 (빈도주의)</a></li>
  <li><a href="#베이지안-선형-회귀" id="toc-베이지안-선형-회귀" class="nav-link" data-scroll-target="#베이지안-선형-회귀"><span class="header-section-number">4.2</span> 베이지안 선형 회귀</a></li>
  <li><a href="#계산-qr-행렬-분해" id="toc-계산-qr-행렬-분해" class="nav-link" data-scroll-target="#계산-qr-행렬-분해"><span class="header-section-number">4.3</span> 계산 (QR, 행렬 분해)</a></li>
  <li><a href="#회귀-진단-베이즈-잔차" id="toc-회귀-진단-베이즈-잔차" class="nav-link" data-scroll-target="#회귀-진단-베이즈-잔차"><span class="header-section-number">4.4</span> 회귀 진단 (베이즈 잔차)</a></li>
  <li><a href="#incumbency-인과-추론" id="toc-incumbency-인과-추론" class="nav-link" data-scroll-target="#incumbency-인과-추론"><span class="header-section-number">4.5</span> Incumbency &amp; 인과 추론</a></li>
  <li><a href="#regularization-lassohorseshoe" id="toc-regularization-lassohorseshoe" class="nav-link" data-scroll-target="#regularization-lassohorseshoe"><span class="header-section-number">4.6</span> Regularization (LASSO·Horseshoe)</a></li>
  <li><a href="#latent-covariance-structures" id="toc-latent-covariance-structures" class="nav-link" data-scroll-target="#latent-covariance-structures"><span class="header-section-number">4.7</span> Latent Covariance Structures</a></li>
  <li><a href="#불등-분산-parametric-variance" id="toc-불등-분산-parametric-variance" class="nav-link" data-scroll-target="#불등-분산-parametric-variance"><span class="header-section-number">4.8</span> 불등 분산 (Parametric Variance)</a></li>
  <li><a href="#상관-모형-카테고리별" id="toc-상관-모형-카테고리별" class="nav-link" data-scroll-target="#상관-모형-카테고리별"><span class="header-section-number">4.9</span> 상관 모형 — 카테고리별</a></li>
  </ul></li>
  <li><a href="#exercises-핵심-풀이" id="toc-exercises-핵심-풀이" class="nav-link" data-scroll-target="#exercises-핵심-풀이"><span class="header-section-number">5</span> § 14.10 Exercises — 핵심 풀이</a>
  <ul class="collapse">
  <li><a href="#exercise-14.3-14.4-식-유도-ols-hatbeta" id="toc-exercise-14.3-14.4-식-유도-ols-hatbeta" class="nav-link" data-scroll-target="#exercise-14.3-14.4-식-유도-ols-hatbeta"><span class="header-section-number">5.1</span> Exercise 14.3 — (14.4) 식 유도: OLS <span class="math inline">\(\hat{\beta}\)</span></a></li>
  <li><a href="#exercise-14.4-14.7-식-유도-s2" id="toc-exercise-14.4-14.7-식-유도-s2" class="nav-link" data-scroll-target="#exercise-14.4-14.7-식-유도-s2"><span class="header-section-number">5.2</span> Exercise 14.4 — (14.7) 식 유도: <span class="math inline">\(s^2\)</span></a></li>
  <li><a href="#exercise-14.6-사후-proper-조건" id="toc-exercise-14.6-사후-proper-조건" class="nav-link" data-scroll-target="#exercise-14.6-사후-proper-조건"><span class="header-section-number">5.3</span> Exercise 14.6 — 사후 Proper 조건</a></li>
  <li><a href="#exercise-14.7-ptildey-sigma-y-의-정규성" id="toc-exercise-14.7-ptildey-sigma-y-의-정규성" class="nav-link" data-scroll-target="#exercise-14.7-ptildey-sigma-y-의-정규성"><span class="header-section-number">5.4</span> Exercise 14.7 — <span class="math inline">\(p(\tilde{y} | \sigma, y)\)</span> 의 정규성</a></li>
  <li><a href="#exercise-14.8-14.24-식-증명" id="toc-exercise-14.8-14.24-식-증명" class="nav-link" data-scroll-target="#exercise-14.8-14.24-식-증명"><span class="header-section-number">5.5</span> Exercise 14.8 — (14.24) 식 증명</a></li>
  <li><a href="#exercise-14.9ab-lasso-1차원" id="toc-exercise-14.9ab-lasso-1차원" class="nav-link" data-scroll-target="#exercise-14.9ab-lasso-1차원"><span class="header-section-number">5.6</span> Exercise 14.9(a)(b) — LASSO 1차원</a></li>
  </ul></li>
  <li><a href="#ch.14-심화-시리즈-결산" id="toc-ch.14-심화-시리즈-결산" class="nav-link" data-scroll-target="#ch.14-심화-시리즈-결산"><span class="header-section-number">6</span> Ch.14 심화 시리즈 결산</a>
  <ul class="collapse">
  <li><a href="#편-논리-지도" id="toc-편-논리-지도" class="nav-link" data-scroll-target="#편-논리-지도"><span class="header-section-number">6.1</span> 4편 논리 지도</a></li>
  <li><a href="#ch.14-결산-실전-체크리스트" id="toc-ch.14-결산-실전-체크리스트" class="nav-link" data-scroll-target="#ch.14-결산-실전-체크리스트"><span class="header-section-number">6.2</span> Ch.14 결산 실전 체크리스트</a></li>
  <li><a href="#구현-환경-정리" id="toc-구현-환경-정리" class="nav-link" data-scroll-target="#구현-환경-정리"><span class="header-section-number">6.3</span> 구현 환경 정리</a></li>
  </ul></li>
  <li><a href="#part-iv-다음-편-예고" id="toc-part-iv-다음-편-예고" class="nav-link" data-scroll-target="#part-iv-다음-편-예고"><span class="header-section-number">7</span> Part IV 다음 편 예고</a></li>
  <li><a href="#관련-주제" id="toc-관련-주제" class="nav-link" data-scroll-target="#관련-주제"><span class="header-section-number">8</span> 관련 주제</a></li>
  <li><a href="#참고문헌" id="toc-참고문헌" class="nav-link" data-scroll-target="#참고문헌"><span class="header-section-number">9</span> 참고문헌</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="개요-ch.14-심화-시리즈의-마지막-편" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="개요-ch.14-심화-시리즈의-마지막-편"><span class="header-section-number">1</span> 개요 — Ch.14 심화 시리즈의 마지막 편</h2>
<p>Ch.14 심화 시리즈의 구성:</p>
<ul>
<li><strong>03-14-0</strong> — Ch.14 Overview (전 10절 조망)</li>
<li><strong>03-14-1</strong> — § 14.1~14.3 (Conditional modeling + Classical regression + Incumbency causal)</li>
<li><strong>03-14-2</strong> — § 14.4~14.6 (Goals + X matrix + Regularization)</li>
<li><strong>03-14-3 (본편)</strong> — § 14.7~14.10 (Unequal variances + Prior info + 문헌 + 연습)</li>
</ul>
<p>지금까지 § 14.1~14.6 은 <strong>등분산·독립 오차</strong> (<span class="math inline">\(\Sigma_y = \sigma^2 I\)</span>) 와 <strong>noninformative prior</strong> 또는 <strong>regularization prior</strong> 조합을 다뤘다. 이 편에서는 두 가정을 모두 일반화한다.</p>
<ul>
<li><strong>§ 14.7</strong> — 분산이 관측치마다 다르거나 서로 상관되면? GLS의 베이즈 유도와 parametric variance 모형.</li>
<li><strong>§ 14.8</strong> — 계수에 선행 지식이 있으면? “prior를 추가 데이터 점으로 코딩” 이라는 Gelman의 우아한 트릭.</li>
<li><strong>§ 14.9</strong> — Ch.14의 문헌 지도.</li>
<li><strong>§ 14.10</strong> — 연습문제 풀이 (OLS 유도 검증·prior data 트릭 증명·LASSO 1D 등).</li>
</ul>
<p>마지막에 Ch.14 심화 시리즈 <strong>4편 결산</strong>을 배치하여 Part IV의 첫 장을 닫는다.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관: 두 일반화의 공통점
</div>
</div>
<div class="callout-body-container callout-body">
<p>§ 14.7과 § 14.8은 모두 <strong>“이미 알고 있는 베이즈 선형 회귀 기계에 새 정보를 얹는 문제”</strong> 다.</p>
<ul>
<li>§ 14.7: 분산 구조에 대한 추가 가정 → Cholesky 변환으로 등분산 문제로 환원.</li>
<li>§ 14.8: 모수에 대한 선행 지식 → 가상 데이터 점으로 코딩하여 가중 회귀로 환원.</li>
</ul>
<p>두 경우 모두 Gelman의 전략은 <strong>“문제를 이미 풀어본 형태로 변환”</strong>. 이것이 베이즈 선형 모형 설계의 일관된 철학이다.</p>
</div>
</div>
</section>
<section id="unequal-variances-and-correlations" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="unequal-variances-and-correlations"><span class="header-section-number">2</span> § 14.7 Unequal Variances and Correlations</h2>
<section id="일반-모형-식-14.11" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="일반-모형-식-14.11"><span class="header-section-number">2.1</span> 일반 모형 — 식 (14.11)</h3>
<p>표준 OLS 가정 중 <strong>등분산·독립</strong> 을 완화한다.</p>
<p><span class="math display">\[
y \sim N(X\beta, \Sigma_y) \quad \text{(14.11)}
\]</span></p>
<p><span class="math inline">\(\Sigma_y\)</span> 는 <span class="math inline">\(n \times n\)</span> symmetric positive definite. 이제 <span class="math inline">\(\sigma^2 I\)</span> 대신 일반 공분산 행렬이다.</p>
<p><strong>실무 동기</strong>:</p>
<table class="table">
<thead>
<tr class="header">
<th>상황</th>
<th><span class="math inline">\(\Sigma_y\)</span> 구조</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>병원별 평균 (<span class="math inline">\(n_i\)</span> 환자의 평균)</td>
<td>대각, <span class="math inline">\(\Sigma_{ii} \propto 1/n_i\)</span></td>
</tr>
<tr class="even">
<td>시계열 데이터</td>
<td>AR(1): <span class="math inline">\(\Sigma_{ij} = \sigma^2 \rho^{|i-j|}\)</span></td>
</tr>
<tr class="odd">
<td>공간 데이터</td>
<td>거리 기반 covariance kernel</td>
</tr>
<tr class="even">
<td>가족 구성원 키</td>
<td>블록 대각 (가족 단위)</td>
</tr>
<tr class="odd">
<td>두 기술자가 측정</td>
<td>기술자별 다른 분산</td>
</tr>
</tbody>
</table>
</section>
<section id="sigma_y-known-경우-cholesky-변환" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="sigma_y-known-경우-cholesky-변환"><span class="header-section-number">2.2</span> <span class="math inline">\(\Sigma_y\)</span> Known 경우 — Cholesky 변환</h3>
<p>03-14-1의 복습 + 완전 유도.</p>
<p><span class="math inline">\(\Sigma_y = L L^T\)</span> (Cholesky, <span class="math inline">\(L\)</span> 상삼각). 양변에 <span class="math inline">\(L^{-1}\)</span> 곱:</p>
<p><span class="math display">\[
L^{-1} y = L^{-1} X \beta + L^{-1} \epsilon, \quad L^{-1} \epsilon \sim N(0, I)
\]</span></p>
<p>이는 <strong>변환된 ordinary linear regression</strong>. <span class="math inline">\(y^* = L^{-1} y\)</span>, <span class="math inline">\(X^* = L^{-1} X\)</span> 에 § 14.2 결과를 적용.</p>
<p><strong>GLS 추정량</strong>:</p>
<p><span class="math display">\[
\hat{\beta} = (X^{*T} X^*)^{-1} X^{*T} y^* = (X^T L^{-T} L^{-1} X)^{-1} X^T L^{-T} L^{-1} y = (X^T \Sigma_y^{-1} X)^{-1} X^T \Sigma_y^{-1} y \quad \text{(14.12)}
\]</span></p>
<p><span class="math display">\[
V_\beta = (X^T \Sigma_y^{-1} X)^{-1} \quad \text{(14.13)}
\]</span></p>
<p><span class="math inline">\(\Sigma_y = I\)</span> 이면 OLS 복원. <strong>GLS = weighted OLS with weight <span class="math inline">\(\Sigma_y^{-1}\)</span></strong>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관: 왜 <span class="math inline">\(\Sigma_y^{-1}\)</span> 가중치가 “맞는” 가중치인가
</div>
</div>
<div class="callout-body-container callout-body">
<p>Gauss-Markov 정리의 GLS 버전: “오차 공분산이 <span class="math inline">\(\Sigma_y\)</span> 인 선형 모형에서 <strong>best linear unbiased estimator (BLUE)</strong> 는 <span class="math inline">\(\hat{\beta}_{\text{GLS}}\)</span>.” 즉 <span class="math inline">\(\Sigma_y^{-1}\)</span> 을 제외한 다른 가중치를 쓰면 분산이 더 커진다.</p>
<p>기하학적 의미: 분산이 큰 관측치는 “noisy”하므로 <strong>정보 가치가 낮다</strong> → 가중치를 줄인다. <span class="math inline">\(\Sigma_y^{-1}\)</span> 의 대각 성분이 작은 행이 “덜 중요한” 관측.</p>
<p>상관 구조도 마찬가지. 상관된 관측치는 독립 관측치 <span class="math inline">\(n\)</span> 개보다 적은 정보를 가진다 (“effective sample size” 가 <span class="math inline">\(n\)</span> 보다 작음). <span class="math inline">\(\Sigma_y^{-1}\)</span> 이 이 정보 손실을 정확히 보정한다.</p>
</div>
</div>
</section>
<section id="unknown-sigma_y-일반-논의" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="unknown-sigma_y-일반-논의"><span class="header-section-number">2.3</span> Unknown <span class="math inline">\(\Sigma_y\)</span> — 일반 논의</h3>
<p><span class="math inline">\(\Sigma_y\)</span> 가 unknown이면 문제가 훨씬 복잡해진다. Uniform prior <span class="math inline">\(p(\beta | \Sigma_y) \propto 1\)</span> 가정 시 <span class="math inline">\(\Sigma_y\)</span> 의 주변 사후:</p>
<p><span class="math display">\[
p(\Sigma_y | y) \propto p(\Sigma_y) \cdot \frac{N(y | X\beta, \Sigma_y)}{N(\beta | \hat{\beta}, V_\beta)} \quad \text{(14.14)}
\]</span></p>
<p><span class="math inline">\(\beta = \hat{\beta}\)</span> 를 대입하면 (LHS는 <span class="math inline">\(\beta\)</span> 무관이므로 임의의 <span class="math inline">\(\beta\)</span> 에서 평가 가능):</p>
<p><span class="math display">\[
p(\Sigma_y | y) \propto p(\Sigma_y) \cdot |\Sigma_y|^{-1/2} |V_\beta|^{1/2} \exp\left( -\frac{1}{2} (y - X\hat{\beta})^T \Sigma_y^{-1} (y - X\hat{\beta}) \right) \quad \text{(14.15)}
\]</span></p>
<p><strong>어려움</strong>: <span class="math inline">\(\hat{\beta}\)</span> 와 <span class="math inline">\(V_\beta\)</span> 자체가 <span class="math inline">\(\Sigma_y\)</span> 에 의존. 또 <span class="math inline">\(\Sigma_y\)</span> 의 prior를 일반 <span class="math inline">\(n \times n\)</span> 공분산 행렬로 설정하는 것이 실무적으로 어렵다 (예: Inverse-Wishart의 scale matrix 선택).</p>
<p><strong>실용적 접근</strong>: <span class="math inline">\(\Sigma_y\)</span> 를 <strong>저차원 모수화</strong>. 아래 특수 경우들이 대표적.</p>
</section>
<section id="특수-경우-1-스칼라-팩터만-unknown-식-14.1614.19" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="특수-경우-1-스칼라-팩터만-unknown-식-14.1614.19"><span class="header-section-number">2.4</span> 특수 경우 1: 스칼라 팩터만 Unknown — 식 (14.16)~(14.19)</h3>
<p><span class="math display">\[
\Sigma_y = Q_y \sigma^2 \quad \text{(14.16)}
\]</span></p>
<p><span class="math inline">\(Q_y\)</span> (구조) 는 알려져 있고 <span class="math inline">\(\sigma^2\)</span> (스케일) 만 unknown. 이는 “분산 비율은 아는데 절대 크기는 모른다” 상황.</p>
<p><strong>예</strong>:</p>
<ul>
<li>각 관측이 <span class="math inline">\(n_i\)</span> 개 개별 관측의 평균이면 <span class="math inline">\(Q_{ii} = 1/n_i\)</span>.</li>
<li>시계열에서 <span class="math inline">\(\rho\)</span> 가 알려져 있고 <span class="math inline">\(\sigma^2\)</span> 만 unknown.</li>
</ul>
<p>Noninformative prior <span class="math inline">\(p(\beta, \sigma^2) \propto \sigma^{-2}\)</span> 에서 <span class="math inline">\(y \to Q_y^{-1/2} y\)</span>, <span class="math inline">\(X \to Q_y^{-1/2} X\)</span> 변환하면 § 14.2의 결과를 그대로 적용:</p>
<p><span class="math display">\[
\hat{\beta} = (X^T Q_y^{-1} X)^{-1} X^T Q_y^{-1} y \quad \text{(14.17)}
\]</span></p>
<p><span class="math display">\[
V_\beta = (X^T Q_y^{-1} X)^{-1} \quad \text{(14.18)}
\]</span></p>
<p><span class="math display">\[
s^2 = \frac{1}{n-k} (y - X\hat{\beta})^T Q_y^{-1} (y - X\hat{\beta}) \quad \text{(14.19)}
\]</span></p>
<p>사후 분포:</p>
<p><span class="math display">\[
\beta | \sigma^2, y \sim N(\hat{\beta}, V_\beta \sigma^2), \quad \sigma^2 | y \sim \text{Inv-}\chi^2(n-k, s^2)
\]</span></p>
<p>즉 <strong>GLS + σ² 주변화</strong>가 그대로 이어짐.</p>
</section>
<section id="특수-경우-2-weighted-linear-regression" class="level3" data-number="2.5">
<h3 data-number="2.5" class="anchored" data-anchor-id="특수-경우-2-weighted-linear-regression"><span class="header-section-number">2.5</span> 특수 경우 2: Weighted Linear Regression</h3>
<p><span class="math inline">\(Q_y\)</span> 가 <strong>대각</strong>이면 (상관 없음, 불등 분산만):</p>
<p><span class="math display">\[
\Sigma_{ii} = \sigma^2 / w_i, \quad Q_y^{-1} = \text{diag}(w_1, \dots, w_n)
\]</span></p>
<p><span class="math inline">\(w_i\)</span> 는 “가중치”. <span class="math inline">\(w_i\)</span> 가 크면 해당 관측이 정밀 → 회귀에서 더 영향.</p>
<p><strong>직관적 전형</strong>:</p>
<ul>
<li><span class="math inline">\(y_i\)</span> 가 <span class="math inline">\(m_i\)</span> 개 측정의 평균 → <span class="math inline">\(\Sigma_{ii} = \sigma^2 / m_i\)</span> → <span class="math inline">\(w_i = m_i\)</span>.</li>
<li>“더 많이 측정한 관측치일수록 높은 신뢰도로 회귀에 반영.”</li>
</ul>
<p>이 경우 (14.17)은</p>
<p><span class="math display">\[
\hat{\beta} = (X^T W X)^{-1} X^T W y, \quad W = \text{diag}(w_1, \dots, w_n)
\]</span></p>
<p>= <strong>Weighted Least Squares (WLS)</strong>.</p>
</section>
<section id="특수-경우-3-parametric-variance-식-14.2014.21" class="level3" data-number="2.6">
<h3 data-number="2.6" class="anchored" data-anchor-id="특수-경우-3-parametric-variance-식-14.2014.21"><span class="header-section-number">2.6</span> 특수 경우 3: Parametric Variance — 식 (14.20)(14.21)</h3>
<p><span class="math inline">\(Q_y\)</span> 가 알려져 있지 않지만 <strong>저차원 모수 <span class="math inline">\(\phi\)</span> 로 표현</strong> 가능:</p>
<p><span class="math display">\[
\Sigma_{ii} = \sigma^2 \, v(w_i, \phi) \quad \text{(14.20)}
\]</span></p>
<p><strong>전형적 선택</strong>:</p>
<ul>
<li><span class="math inline">\(v(w_i, \phi) = w_i^{-\phi}\)</span>: <span class="math inline">\(\phi = 0\)</span> 이면 등분산, <span class="math inline">\(\phi = 1\)</span> 이면 WLS, 연속 보간.</li>
<li><span class="math inline">\(v(w_i, \phi) = (1-\phi) + \phi/w_i\)</span>: 선형 보간 버전.</li>
</ul>
<p><strong>Prior</strong>: <span class="math inline">\(\phi \sim U[0, 1]\)</span> (비정보).</p>
<p><strong>사후</strong>:</p>
<p><span class="math display">\[
p(\beta, \sigma^2, \phi | y) \propto p(\phi) p(\beta, \sigma^2 | \phi) \prod_{i=1}^n N(y_i | X_i \beta, \sigma^2 v(w_i, \phi)) \quad \text{(14.21)}
\]</span></p>
<p><strong>전략</strong>: <span class="math inline">\(\phi\)</span> 조건부로 WLS, 그 다음 <span class="math inline">\(\phi\)</span> 주변화.</p>
<p><strong><span class="math inline">\(\phi\)</span> 주변 사후</strong> — 식 (14.22):</p>
<p><span class="math display">\[
p(\phi | y) \propto \frac{p(\phi) \cdot \sigma^{-2} \prod_i N(y_i | X_i \beta, \sigma^2 v(w_i, \phi))}{\text{Inv-}\chi^2(\sigma^2 | n-k, s^2) \cdot N(\beta | \hat{\beta}, V_\beta \sigma^2)}
\]</span></p>
<p>분모의 조건부 분포들에 <span class="math inline">\((\hat{\beta}, s^2)\)</span> 를 대입해 정리하면</p>
<p><span class="math display">\[
p(\phi | y) \propto p(\phi) \cdot |V_\beta|^{1/2} \cdot s^{-(n-k)} \quad \text{(14.22)}
\]</span></p>
<p><strong>샘플링 절차</strong>:</p>
<ol type="1">
<li><span class="math inline">\(\phi\)</span> 그리드 <span class="math inline">\([0, 1]\)</span> 에서 (14.22) 평가, normalize → <span class="math inline">\(p(\phi | y)\)</span> 근사.</li>
<li><span class="math inline">\(\phi^{(s)} \sim p(\phi | y)\)</span> inverse-CDF로 추출.</li>
<li><span class="math inline">\(\phi^{(s)}\)</span> 조건부 <span class="math inline">\(\sigma^{2(s)} \sim \text{Inv-}\chi^2(n-k, s^2(\phi^{(s)}))\)</span>.</li>
<li><span class="math inline">\(\beta^{(s)} \sim N(\hat{\beta}(\phi^{(s)}), V_\beta(\phi^{(s)}) \sigma^{2(s)})\)</span>.</li>
</ol>
<p>1차원 <span class="math inline">\(\phi\)</span> 라서 그리드 방식이 실용적. 다차원이면 MCMC.</p>
</section>
<section id="특수-경우-4-여러-분산-컴포넌트-incumbency-재방문" class="level3" data-number="2.7">
<h3 data-number="2.7" class="anchored" data-anchor-id="특수-경우-4-여러-분산-컴포넌트-incumbency-재방문"><span class="header-section-number">2.7</span> 특수 경우 4: 여러 분산 컴포넌트 (Incumbency 재방문)</h3>
<p>Gelman의 실제 incumbency 분석에서는 <strong>현직 재출마 선거</strong> 와 <strong>공석 선거</strong>에 다른 분산을 허용:</p>
<ul>
<li><span class="math inline">\(I = 2\)</span> 개 그룹, 각 그룹 크기 <span class="math inline">\(n_1, n_2\)</span>, <span class="math inline">\(\sum n_i = n\)</span>.</li>
<li><span class="math inline">\(\Sigma_y\)</span> 는 대각, 처음 <span class="math inline">\(n_1\)</span> 개 관측이 <span class="math inline">\(\sigma_1^2\)</span>, 다음 <span class="math inline">\(n_2\)</span> 개가 <span class="math inline">\(\sigma_2^2\)</span>.</li>
</ul>
<p>Noninformative prior: <span class="math inline">\(I\)</span> 개 그룹을 <span class="math inline">\(I\)</span> 개 독립 실험으로 취급</p>
<p><span class="math display">\[
p(\beta, \Sigma_y) \propto \prod_{i=1}^{I} \sigma_i^{-2}
\]</span></p>
<p><strong>Proper 조건</strong>: <span class="math inline">\(n_i \geq 2\)</span> (그룹당 최소 2개 관측). 그룹에 관측이 1개뿐이면 해당 <span class="math inline">\(\sigma_i^2\)</span> 에 informative prior 필수.</p>
<p><strong>결합 사후</strong> — 식 (14.23):</p>
<p><span class="math display">\[
p(\beta, \sigma_1^2, \dots, \sigma_I^2 | y) \propto \left( \prod_i \sigma_i^{-n_i - 2} \right) \exp\left( -\frac{1}{2} (y - X\beta)^T \Sigma_y^{-1} (y - X\beta) \right)
\]</span></p>
<p><strong>샘플링</strong>: 직접 해석적으로 쓸 수 없음. <strong>Gibbs sampler</strong>:</p>
<ul>
<li><span class="math inline">\(\beta | \Sigma_y, y\)</span>: 가중 회귀 결과 (정규).</li>
<li><span class="math inline">\(\sigma_i^2 | \beta, y\)</span>: 해당 그룹 잔차 제곱합의 scaled inverse-χ².</li>
</ul>
<p>Gelman은 EM으로 사후 mode 찾아 정규 근사 시작점으로 → Gibbs sampler 3개 체인, 100 iterations → <span class="math inline">\(\hat{R} &lt; 1.1\)</span> 확인.</p>
<p><strong>결과</strong>:</p>
<ul>
<li>현직 효과 계수 추정 자체는 거의 변하지 않음 (주된 관심사에 영향 적음).</li>
<li><strong>예측 분포는 의미있게 개선</strong> — 공석 선거의 불확실성이 제대로 반영.</li>
<li>추가 개선: <span class="math inline">\(\sigma_1^2, \sigma_2^2\)</span> 에 <strong>계층적 시계열 prior</strong> (Ch.15) 를 두면 spiky 변동이 매끄러워짐.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관: 언제 이런 모델을 쓰는가
</div>
</div>
<div class="callout-body-container callout-body">
<p>“점 추정 정확도 자체는 거의 안 바뀌는데 왜 굳이 <span class="math inline">\(\sigma\)</span> 를 분리?”</p>
<p>답: <strong>예측 분포의 정직성</strong>. 공석 선거의 실제 변동성이 현직 선거보다 크면, 등분산 모형은 공석 선거 예측 구간을 <strong>너무 좁게</strong> (과신) 내놓는다. 의사결정용 모형이라면 구간이 맞아야 한다.</p>
<p>일반 교훈: <strong>점 추정에 영향 적은 모델 개선도 구간 예측에는 결정적</strong>일 수 있다. Gelman이 반복 강조하는 “예측 구간 정직성”의 중요성.</p>
</div>
</div>
</section>
<section id="일반-형태-general-variance-model" class="level3" data-number="2.8">
<h3 data-number="2.8" class="anchored" data-anchor-id="일반-형태-general-variance-model"><span class="header-section-number">2.8</span> 일반 형태 — General Variance Model</h3>
<p>더 일반적으로:</p>
<p><span class="math display">\[
\mathbb{E}(y | X, \theta) = X\beta, \quad \log(\mathrm{Var}(y | X, \theta)) = W\phi
\]</span></p>
<p><span class="math inline">\(W\)</span> 는 분산 모수에 대한 “design matrix” (지시변수 또는 연속 변수), <span class="math inline">\(\phi\)</span> 는 분산 모수 벡터.</p>
<p>이 형태는 <strong>이분산을 공변량으로 모델링</strong>. GLM과 유사한 구조 (Ch.16)이지만 mean이 아닌 variance에 적용.</p>
<p>Metropolis 또는 HMC로 <span class="math inline">\((\beta, \phi)\)</span> 사후 샘플링.</p>
</section>
</section>
<section id="including-numerical-prior-information" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="including-numerical-prior-information"><span class="header-section-number">3</span> § 14.8 Including Numerical Prior Information</h2>
<section id="철학-prior-정보는-암묵적으로-이미-있다" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="철학-prior-정보는-암묵적으로-이미-있다"><span class="header-section-number">3.1</span> 철학: Prior 정보는 암묵적으로 이미 있다</h3>
<p>Gelman의 관찰: 회귀에 <strong>변수를 포함 여부 자체가 prior 정보</strong>다. “이 변수가 중요할 것” 이라는 판단이 없으면 데이터에 넣지 않는다.</p>
<p>§ 14.8은 이를 <strong>수치화</strong> 한다. 선행 연구에서 얻은 추정치를 회귀에 정식으로 포함시키는 방법.</p>
</section>
<section id="핵심-트릭-prior-추가-데이터-점" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="핵심-트릭-prior-추가-데이터-점"><span class="header-section-number">3.2</span> 핵심 트릭: Prior = 추가 데이터 점</h3>
<p>정규 prior <span class="math inline">\(\beta_j \sim N(\beta_{j0}, \sigma_{\beta_j}^2)\)</span> 의 밀도:</p>
<p><span class="math display">\[
p(\beta_j) \propto \frac{1}{\sigma_{\beta_j}} \exp\left( -\frac{(\beta_j - \beta_{j0})^2}{2 \sigma_{\beta_j}^2} \right)
\]</span></p>
<p><strong>관찰</strong>: 이 식은 “관측값 <span class="math inline">\(\beta_{j0}\)</span>, 평균 <span class="math inline">\(\beta_j\)</span>, 분산 <span class="math inline">\(\sigma_{\beta_j}^2\)</span> 인 정규 관측 우도”와 동일 형태.</p>
<p>즉 <strong>prior를 가상의 추가 데이터 점</strong>으로 볼 수 있다:</p>
<ul>
<li>“관측값” = <span class="math inline">\(\beta_{j0}\)</span>.</li>
<li>“설명변수” = <span class="math inline">\(j\)</span>-번째만 1, 나머지 0인 <span class="math inline">\(k\)</span>-차원 벡터.</li>
<li>“분산” = <span class="math inline">\(\sigma_{\beta_j}^2\)</span>.</li>
</ul>
<p><strong>구현</strong>: 원 데이터 <span class="math inline">\((y, X, \Sigma_y)\)</span> 에 이 가상 점을 <strong>마지막 행으로 추가</strong>:</p>
<p><span class="math display">\[
y_* = \begin{pmatrix} y \\ \beta_{j0} \end{pmatrix}, \quad X_* = \begin{pmatrix} X \\ e_j^T \end{pmatrix}, \quad \Sigma_* = \begin{pmatrix} \Sigma_y &amp; 0 \\ 0 &amp; \sigma_{\beta_j}^2 \end{pmatrix}
\]</span></p>
<p><span class="math inline">\(e_j\)</span> 는 <span class="math inline">\(j\)</span>-번째만 1인 <span class="math inline">\(k\)</span>-차원 표준 기저 벡터. 그 후 <span class="math inline">\(y_*\)</span> 를 <span class="math inline">\(X_*\)</span> 에 <strong>가중 회귀 (known <span class="math inline">\(\Sigma_*\)</span>)</strong>.</p>
</section>
<section id="극한-해석" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="극한-해석"><span class="header-section-number">3.3</span> 극한 해석</h3>
<p><strong>Noninformative 극한</strong> <span class="math inline">\(\sigma_{\beta_j}^2 \to \infty\)</span>: 가중치 <span class="math inline">\(1/\sigma_{\beta_j}^2 \to 0\)</span> → 가상 점이 추론에 <strong>영향 없음</strong>. 원 회귀와 동일.</p>
<p><strong>Perfect 정보 극한</strong> <span class="math inline">\(\sigma_{\beta_j}^2 \to 0\)</span>: 가중치 <span class="math inline">\(\to \infty\)</span> → <span class="math inline">\(\beta_j = \beta_{j0}\)</span> <strong>강제</strong>. 해당 계수 고정.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관: “Prior scale은 정보의 양을 결정한다”
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(\sigma_{\beta_j}^2 = 0.01\)</span> 정도면 “<span class="math inline">\(\beta_j\)</span> 가 <span class="math inline">\(\beta_{j0}\)</span> 에서 ±0.2 이내일 가능성 95%” 라는 강한 제약.</p>
<p><span class="math inline">\(\sigma_{\beta_j}^2 = 100\)</span> 이면 “<span class="math inline">\(\beta_{j0}\)</span> 가 매우 대략적 추측” 에 해당.</p>
<p>실무 가이드: 선행 연구의 <strong>표준오차 제곱</strong>을 <span class="math inline">\(\sigma_{\beta_j}^2\)</span> 에 쓴다. “이전 연구가 내놓은 증거만큼” 의 정보량.</p>
<p>여러 선행 연구가 있으면 meta-analysis로 통합한 뒤 쓸 수 있다. Ch.5 exchangeable 계층 모형과 자연스럽게 연결.</p>
</div>
</div>
</section>
<section id="다차원-prior-식-14.24" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="다차원-prior-식-14.24"><span class="header-section-number">3.4</span> 다차원 Prior — 식 (14.24)</h3>
<p><span class="math inline">\(\beta\)</span> 전체에 대한 prior <span class="math inline">\(\beta \sim N(\beta_0, \Sigma_\beta)\)</span>. 같은 트릭을 <span class="math inline">\(k\)</span> 차원으로 확장:</p>
<p><span class="math display">\[
y_* = \begin{pmatrix} y \\ \beta_0 \end{pmatrix}, \quad X_* = \begin{pmatrix} X \\ I_k \end{pmatrix}, \quad \Sigma_* = \begin{pmatrix} \Sigma_y &amp; 0 \\ 0 &amp; \Sigma_\beta \end{pmatrix} \quad \text{(14.24)}
\]</span></p>
<p>즉 <span class="math inline">\(k\)</span> 개 가상 데이터 점을 추가. 각 점이 한 성분 <span class="math inline">\(\beta_j\)</span> 에 정보를 주고, <span class="math inline">\(\Sigma_\beta\)</span> 의 비대각 성분이 계수 간 상관 정보.</p>
<p><strong>Proper 조건</strong>: <span class="math inline">\(\Sigma_\beta^{-1}\)</span> 의 rank가 <span class="math inline">\(k\)</span> (모든 계수에 proper prior). 일부 성분만 정보가 있으면 해당 행만 augment.</p>
</section>
<section id="sigma_beta-의-특수-형태-regularization과의-연결" class="level3" data-number="3.5">
<h3 data-number="3.5" class="anchored" data-anchor-id="sigma_beta-의-특수-형태-regularization과의-연결"><span class="header-section-number">3.5</span> <span class="math inline">\(\Sigma_\beta\)</span> 의 특수 형태 — Regularization과의 연결</h3>
<ul>
<li><strong><span class="math inline">\(\Sigma_\beta = \tau^2 I\)</span>, <span class="math inline">\(\beta_0 = 0\)</span></strong> → Ridge regression prior (§ 14.6 재현).</li>
<li><strong><span class="math inline">\(\Sigma_\beta\)</span> 가 Laplace scale mixture</strong> → LASSO (§ 14.6).</li>
<li><strong><span class="math inline">\(\Sigma_\beta\)</span> 가 데이터 기반 계층적</strong> → Ch.15 hierarchical linear model.</li>
</ul>
<p><strong>결론</strong>: § 14.6 regularization은 <strong>§ 14.8의 특수 사례</strong> — prior scale <span class="math inline">\(\tau\)</span> 를 0으로 놓고 (강한 축소) 점 prior <span class="math inline">\(\beta_0 = 0\)</span> 으로 놓은 것.</p>
</section>
<section id="variance-prior-conjugate-inverse-χ²" class="level3" data-number="3.6">
<h3 data-number="3.6" class="anchored" data-anchor-id="variance-prior-conjugate-inverse-χ²"><span class="header-section-number">3.6</span> Variance Prior — Conjugate Inverse-χ²</h3>
<p><span class="math inline">\(\sigma^2\)</span> 에 대한 conjugate prior:</p>
<p><span class="math display">\[
\sigma^2 \sim \text{Inv-}\chi^2(n_0, \sigma_0^2)
\]</span></p>
<p>사후는 (데이터와 합치면):</p>
<p><span class="math display">\[
\sigma^2 | y \sim \text{Inv-}\chi^2\left( n_0 + n, \frac{n_0 \sigma_0^2 + n s^2}{n_0 + n} \right)
\]</span></p>
<p><strong>해석</strong>: prior가 “<span class="math inline">\(n_0\)</span> 개 가상 관측, sample variance <span class="math inline">\(\sigma_0^2\)</span>”에 해당. <span class="math inline">\(n_0 = 0\)</span> 이면 noninformative.</p>
<p><strong>수식 구조</strong>: 분산 자유도와 pooled MSE가 prior와 데이터의 가중 평균. Ch.3에서 다룬 정규 conjugate 결과의 회귀 버전.</p>
</section>
<section id="부등식-제약-inequality-constraints" class="level3" data-number="3.7">
<h3 data-number="3.7" class="anchored" data-anchor-id="부등식-제약-inequality-constraints"><span class="header-section-number">3.7</span> 부등식 제약 (Inequality Constraints)</h3>
<p><span class="math inline">\(\beta_1 \geq 0\)</span>, <span class="math inline">\(\beta_2 \leq \beta_3\)</span> 등 부등식 형태의 prior.</p>
<p><strong>Gelman의 실용 접근</strong>:</p>
<ol type="1">
<li>제약 없이 사후 <span class="math inline">\((\beta, \sigma)\)</span> 시뮬레이션.</li>
<li>제약 위배하는 draws를 <strong>버린다 (rejection)</strong>.</li>
</ol>
<p><strong>유효성</strong>: 제약이 사후 probability mass의 작은 부분만 절단하면 효율적. 제약이 많은 질량을 자르면 “데이터가 제약과 충돌” → 모형 재검토 신호.</p>
<p><strong>한계</strong>: 제약이 사후의 99%를 잘라내면 rejection 효율이 1%로 떨어짐. 이 경우 제약 영역에서 직접 샘플링 (Hamiltonian Monte Carlo with reflective bounds, slice sampler).</p>
</section>
</section>
<section id="bibliographic-note-주제별-재구성" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="bibliographic-note-주제별-재구성"><span class="header-section-number">4</span> § 14.9 Bibliographic Note — 주제별 재구성</h2>
<p>Gelman의 Ch.14 참고문헌을 주제별로 재정리.</p>
<section id="정규-선형-회귀-빈도주의" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="정규-선형-회귀-빈도주의"><span class="header-section-number">4.1</span> 정규 선형 회귀 (빈도주의)</h3>
<ul>
<li>Weisberg (1985) <em>Applied Linear Regression</em> — 교과서.</li>
<li>Neter, Kutner, Nachtsheim, Wasserman (1996) <em>Applied Linear Statistical Models</em> — 실무 표준.</li>
<li>Fox (2002) <em>An R and S-Plus Companion to Applied Regression</em> — R 코드 표준.</li>
</ul>
</section>
<section id="베이지안-선형-회귀" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="베이지안-선형-회귀"><span class="header-section-number">4.2</span> 베이지안 선형 회귀</h3>
<ul>
<li>Zellner (1971) <em>Introduction to Bayesian Inference in Econometrics</em> — 베이즈 회귀의 고전.</li>
<li>Box, Tiao (1973) <em>Bayesian Inference in Statistical Analysis</em> — normal-inverse-χ² conjugate 완전 유도.</li>
<li>Gelman, Hill (2007) <em>Data Analysis Using Regression and Multilevel Models</em> — 실무 베이즈 회귀.</li>
<li>O’Hagan, Forster (2004) <em>Kendall’s Advanced Theory of Statistics Vol 2B</em> — Bayesian inference 교과서.</li>
</ul>
</section>
<section id="계산-qr-행렬-분해" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="계산-qr-행렬-분해"><span class="header-section-number">4.3</span> 계산 (QR, 행렬 분해)</h3>
<ul>
<li>Gill, Murray, Wright (1981) <em>Practical Optimization</em> — Ch.13에서 이미 언급.</li>
<li>Golub, van Loan (1983) <em>Matrix Computations</em> — 수치 선형대수의 바이블.</li>
</ul>
</section>
<section id="회귀-진단-베이즈-잔차" class="level3" data-number="4.4">
<h3 data-number="4.4" class="anchored" data-anchor-id="회귀-진단-베이즈-잔차"><span class="header-section-number">4.4</span> 회귀 진단 (베이즈 잔차)</h3>
<ul>
<li>Zellner (1975) — 베이즈 잔차 분석 고전.</li>
<li>Chaloner, Brant (1988), Chaloner (1991) — outlier 검출의 베이즈 접근.</li>
<li>Gelman, Goegebeur et al.&nbsp;(2000), Pardoe (2001), Pardoe, Cook (2002) — 그래픽 모델 검사.</li>
</ul>
</section>
<section id="incumbency-인과-추론" class="level3" data-number="4.5">
<h3 data-number="4.5" class="anchored" data-anchor-id="incumbency-인과-추론"><span class="header-section-number">4.5</span> Incumbency &amp; 인과 추론</h3>
<ul>
<li>Gelman, King (1990a) — 원 incumbency 연구.</li>
<li>Cox, Katz (1996), Ansolabehere, Snyder (2002) — 후속 연구.</li>
<li>Gelman, Huang (2008) — 계층 모형 확장.</li>
<li>Rubin (1974b, 1978a) — potential outcomes framework.</li>
<li>Pearl (2010) — do-calculus 관점.</li>
</ul>
</section>
<section id="regularization-lassohorseshoe" class="level3" data-number="4.6">
<h3 data-number="4.6" class="anchored" data-anchor-id="regularization-lassohorseshoe"><span class="header-section-number">4.6</span> Regularization (LASSO·Horseshoe)</h3>
<ul>
<li>Tibshirani (1996) — LASSO 원 논문.</li>
<li>Park, Casella (2008) — Bayesian lasso (MCMC).</li>
<li>Seeger (2008) — Bayesian lasso (EP).</li>
<li>Carvalho, Polson, Scott (2010) — Horseshoe prior.</li>
<li>Polson, Scott (2012) — shrinkage prior 일반론.</li>
</ul>
</section>
<section id="latent-covariance-structures" class="level3" data-number="4.7">
<h3 data-number="4.7" class="anchored" data-anchor-id="latent-covariance-structures"><span class="header-section-number">4.7</span> Latent Covariance Structures</h3>
<ul>
<li>Arminger (1998), Murray et al.&nbsp;(2013), Hoff, Niu (2012) — latent covariance, 차원 축소.</li>
</ul>
</section>
<section id="불등-분산-parametric-variance" class="level3" data-number="4.8">
<h3 data-number="4.8" class="anchored" data-anchor-id="불등-분산-parametric-variance"><span class="header-section-number">4.8</span> 불등 분산 (Parametric Variance)</h3>
<ul>
<li>Boscardin, Gelman (1996) — 대통령 선거 예측에서 parametric variance 모형.</li>
</ul>
</section>
<section id="상관-모형-카테고리별" class="level3" data-number="4.9">
<h3 data-number="4.9" class="anchored" data-anchor-id="상관-모형-카테고리별"><span class="header-section-number">4.9</span> 상관 모형 — 카테고리별</h3>
<ul>
<li><strong>시계열</strong>: Box, Jenkins (1976); Brillinger (1981); Pole, West, Harrison (1994).</li>
<li><strong>공간 통계</strong>: Kunsch (1987); Cressie (1993).</li>
<li><strong>공간-시간</strong>: Mugglin, Carlin, Gelfand (2000); Banerjee, Carlin, Gelfand (2004).</li>
</ul>
</section>
</section>
<section id="exercises-핵심-풀이" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="exercises-핵심-풀이"><span class="header-section-number">5</span> § 14.10 Exercises — 핵심 풀이</h2>
<p>Ch.14의 14문제 중 이론적으로 중요한 5문제를 풀이한다.</p>
<section id="exercise-14.3-14.4-식-유도-ols-hatbeta" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="exercise-14.3-14.4-식-유도-ols-hatbeta"><span class="header-section-number">5.1</span> Exercise 14.3 — (14.4) 식 유도: OLS <span class="math inline">\(\hat{\beta}\)</span></h3>
<p><strong>문제</strong>: <span class="math inline">\(\hat{\beta} = (X^T X)^{-1} X^T y\)</span> 가 사후 분포 <span class="math inline">\(p(\beta | \sigma^2, y)\)</span> 의 평균임을 유도하라.</p>
<p><strong>풀이</strong>:</p>
<p><span class="math display">\[
p(\beta | \sigma^2, y) \propto \exp\left\{ -\frac{1}{2\sigma^2} (y - X\beta)^T (y - X\beta) \right\}
\]</span></p>
<p><span class="math inline">\(\beta\)</span> 에 관한 2차식. 그래디언트 = 0:</p>
<p><span class="math display">\[
\nabla_\beta \left[ (y - X\beta)^T (y - X\beta) \right] = -2 X^T (y - X\beta) = 0
\]</span></p>
<p><span class="math display">\[
X^T X \beta = X^T y \Rightarrow \hat{\beta} = (X^T X)^{-1} X^T y
\]</span></p>
<p>정규분포의 mode = mean이므로 <span class="math inline">\(\hat{\beta}\)</span> 는 사후 평균.</p>
</section>
<section id="exercise-14.4-14.7-식-유도-s2" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="exercise-14.4-14.7-식-유도-s2"><span class="header-section-number">5.2</span> Exercise 14.4 — (14.7) 식 유도: <span class="math inline">\(s^2\)</span></h3>
<p><strong>문제</strong>: <span class="math inline">\(s^2 = \frac{1}{n-k} (y - X\hat{\beta})^T (y - X\hat{\beta})\)</span> 가 (14.6) 의 scale parameter임을 유도하라.</p>
<p><strong>풀이 개요</strong>: 03-14-1의 Step 2 유도 참조. 요점:</p>
<ul>
<li>사후 factorization <span class="math inline">\(p(\sigma^2|y) = p(\beta, \sigma^2|y) / p(\beta|\sigma^2, y)\)</span>.</li>
<li><span class="math inline">\(\beta = \hat{\beta}\)</span> 대입 → 분자의 <span class="math inline">\((y - X\hat{\beta})^T(y - X\hat{\beta}) = r^T r\)</span>.</li>
<li>분모에서 <span class="math inline">\((\sigma^2)^{k/2}\)</span> 약분 → <span class="math inline">\((\sigma^2)^{-(n-k)/2 - 1} \exp(-r^T r / (2\sigma^2))\)</span>.</li>
<li>Scaled inverse-χ² 의 정의에 맞추면 <span class="math inline">\(s^2 = r^T r / (n-k)\)</span> 가 scale.</li>
</ul>
</section>
<section id="exercise-14.6-사후-proper-조건" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="exercise-14.6-사후-proper-조건"><span class="header-section-number">5.3</span> Exercise 14.6 — 사후 Proper 조건</h3>
<p><strong>문제</strong>: (14.2) noninformative prior 하의 사후가 proper인 조건을 유도.</p>
<p><strong>풀이</strong>: Unnormalized 사후</p>
<p><span class="math display">\[
p(\beta, \sigma^2 | y) \propto \sigma^{-(n+2)} \exp\{-(y - X\beta)^T(y - X\beta) / (2\sigma^2)\}
\]</span></p>
<p>전체 적분:</p>
<p><span class="math display">\[
\int_0^\infty \int_{\mathbb{R}^k} \sigma^{-(n+2)} \exp\{-(y - X\beta)^T(y - X\beta) / (2\sigma^2)\} \, d\beta \, d\sigma^2
\]</span></p>
<p><strong><span class="math inline">\(\beta\)</span> 적분</strong>: Completing the square →</p>
<p><span class="math display">\[
(y - X\beta)^T(y - X\beta) = (\beta - \hat{\beta})^T (X^T X) (\beta - \hat{\beta}) + r^T r
\]</span></p>
<p><span class="math inline">\(\int_{\mathbb{R}^k} \exp\{-(\beta - \hat{\beta})^T (X^T X) (\beta - \hat{\beta}) / (2\sigma^2)\} d\beta = (2\pi\sigma^2)^{k/2} |X^T X|^{-1/2}\)</span> (정규 적분, <strong><span class="math inline">\(X^T X\)</span> invertible</strong> 가정 필요).</p>
<p>→ <span class="math inline">\(X^T X\)</span> invertible ⟺ <span class="math inline">\(\mathrm{rank}(X) = k\)</span> (<strong>조건 1</strong>).</p>
<p><span class="math inline">\(\beta\)</span> 적분 후</p>
<p><span class="math display">\[
\propto \sigma^{-(n+2)} \cdot \sigma^k \cdot \exp\{-r^T r / (2\sigma^2)\} = \sigma^{-(n-k+2)} \exp\{-r^T r / (2\sigma^2)\}
\]</span></p>
<p><strong><span class="math inline">\(\sigma^2\)</span> 적분</strong>: <span class="math inline">\(\int_0^\infty (\sigma^2)^{-(n-k+2)/2} \exp\{-r^T r / (2\sigma^2)\} d\sigma^2 &lt; \infty\)</span> ⟺ <span class="math inline">\((n-k+2)/2 &gt; 1\)</span> ⟺ <span class="math inline">\(n &gt; k\)</span> (<strong>조건 2</strong>).</p>
<p><strong>결론</strong>: 사후 proper ⟺ <span class="math inline">\(n &gt; k\)</span> <strong>AND</strong> <span class="math inline">\(\mathrm{rank}(X) = k\)</span>.</p>
</section>
<section id="exercise-14.7-ptildey-sigma-y-의-정규성" class="level3" data-number="5.4">
<h3 data-number="5.4" class="anchored" data-anchor-id="exercise-14.7-ptildey-sigma-y-의-정규성"><span class="header-section-number">5.4</span> Exercise 14.7 — <span class="math inline">\(p(\tilde{y} | \sigma, y)\)</span> 의 정규성</h3>
<p><strong>문제</strong>: <span class="math inline">\(p(\tilde{y} | \sigma, y)\)</span> 가 정규분포임을 보이라.</p>
<p><strong>풀이</strong>: <span class="math inline">\(p(\tilde{y}, \beta | \sigma, y)\)</span> 가 <span class="math inline">\((\tilde{y}, \beta)\)</span> 에 대한 quadratic form의 지수 함수임을 보이면 충분.</p>
<p><span class="math display">\[
p(\tilde{y}, \beta | \sigma, y) = p(\tilde{y} | \beta, \sigma) \cdot p(\beta | \sigma, y)
\]</span></p>
<p><span class="math inline">\(p(\tilde{y} | \beta, \sigma) \propto \exp\{-(\tilde{y} - \tilde{X}\beta)^T(\tilde{y} - \tilde{X}\beta) / (2\sigma^2)\}\)</span> — <span class="math inline">\((\tilde{y}, \beta)\)</span> 의 2차형.</p>
<p><span class="math inline">\(p(\beta | \sigma, y) \propto \exp\{-(\beta - \hat{\beta})^T (X^T X) (\beta - \hat{\beta}) / (2\sigma^2)\}\)</span> — <span class="math inline">\(\beta\)</span> 의 2차형.</p>
<p>합하면 여전히 <span class="math inline">\((\tilde{y}, \beta)\)</span> 의 2차형 → <strong>결합 정규</strong>. 정규의 조건부·주변은 정규이므로</p>
<p><span class="math display">\[
p(\tilde{y} | \sigma, y) = \int p(\tilde{y}, \beta | \sigma, y) d\beta \text{ 도 정규.}
\]</span></p>
<p>평균·분산은 03-14-1에서 구한 <span class="math inline">\(\tilde{X}\hat{\beta}\)</span> 와 <span class="math inline">\(\sigma^2 (I + \tilde{X} V_\beta \tilde{X}^T)\)</span>.</p>
</section>
<section id="exercise-14.8-14.24-식-증명" class="level3" data-number="5.5">
<h3 data-number="5.5" class="anchored" data-anchor-id="exercise-14.8-14.24-식-증명"><span class="header-section-number">5.5</span> Exercise 14.8 — (14.24) 식 증명</h3>
<p><strong>문제</strong>: Prior <span class="math inline">\(\beta \sim N(\beta_0, \Sigma_\beta)\)</span> 를 augmented data <span class="math inline">\((y_*, X_*, \Sigma_*)\)</span> 로 코딩하는 것이 수학적으로 동등함을 증명.</p>
<p><strong>풀이</strong>: Augmented likelihood</p>
<p><span class="math display">\[
p(y_* | \beta, \Sigma_*) = p(y | \beta, \Sigma_y) \cdot p(\beta_0 | \beta, \Sigma_\beta)
\]</span></p>
<p>두 요소를 풀어쓰면</p>
<p><span class="math display">\[
= N(y | X\beta, \Sigma_y) \cdot N(\beta_0 | \beta, \Sigma_\beta)
\]</span></p>
<p>두 번째 항: “관측 <span class="math inline">\(\beta_0\)</span> 가 평균 <span class="math inline">\(\beta\)</span>, 공분산 <span class="math inline">\(\Sigma_\beta\)</span> 인 정규에서 나옴” = “<span class="math inline">\(\beta\)</span> 가 평균 <span class="math inline">\(\beta_0\)</span>, 공분산 <span class="math inline">\(\Sigma_\beta\)</span> 인 정규” (대칭). 즉 <span class="math inline">\(N(\beta_0 | \beta, \Sigma_\beta) = N(\beta | \beta_0, \Sigma_\beta)\)</span> (정규 대칭성).</p>
<p>따라서</p>
<p><span class="math display">\[
p(y_* | \beta, \Sigma_*) = N(y | X\beta, \Sigma_y) \cdot N(\beta | \beta_0, \Sigma_\beta) = p(y | \beta, \Sigma_y) \cdot p(\beta)
\]</span></p>
<p>= <strong>원 모형의 likelihood × prior</strong> = posterior의 분자.</p>
<p><strong>Noninformative augmented prior</strong> <span class="math inline">\(p(\beta) \propto 1\)</span> 에 augmented likelihood를 곱하면 <strong>원 posterior</strong>를 얻는다. QED.</p>
</section>
<section id="exercise-14.9ab-lasso-1차원" class="level3" data-number="5.6">
<h3 data-number="5.6" class="anchored" data-anchor-id="exercise-14.9ab-lasso-1차원"><span class="header-section-number">5.6</span> Exercise 14.9(a)(b) — LASSO 1차원</h3>
<p><strong>문제 (a)</strong>: LASSO prior 하 unnormalized posterior를 써라.</p>
<p><span class="math display">\[
p(\beta | y) \propto \exp\left\{ -\frac{1}{2\sigma^2} (y - X\beta)^T(y - X\beta) - \lambda \|\beta\|_1 \right\}
\]</span></p>
<p><strong>문제 (b)</strong>: 1차원 <span class="math inline">\(\beta\)</span> 의 LASSO posterior mode.</p>
<p><span class="math inline">\(\hat{\beta}_{\text{OLS}} = z\)</span> 로 놓으면 1차원 penalty:</p>
<p><span class="math display">\[
L(\beta) = \frac{1}{2\sigma^2 V_\beta} (\beta - z)^2 + \lambda |\beta|
\]</span></p>
<p><span class="math inline">\(\beta &gt; 0\)</span>: <span class="math inline">\(L'(\beta) = (\beta - z)/(\sigma^2 V_\beta) + \lambda = 0 \Rightarrow \beta = z - \lambda \sigma^2 V_\beta\)</span>. 단, <span class="math inline">\(z &gt; \lambda \sigma^2 V_\beta\)</span> 에서 양수 유지.</p>
<p><span class="math inline">\(\beta &lt; 0\)</span>: <span class="math inline">\(\beta = z + \lambda \sigma^2 V_\beta\)</span>. 단, <span class="math inline">\(z &lt; -\lambda \sigma^2 V_\beta\)</span>.</p>
<p><span class="math inline">\(|z| \leq \lambda \sigma^2 V_\beta\)</span>: <span class="math inline">\(\beta = 0\)</span>.</p>
<p><strong>Soft-thresholding</strong> (03-14-2 재확인):</p>
<p><span class="math display">\[
\hat{\beta}_{\text{LASSO}} = \text{sign}(z) \cdot (|z| - \lambda \sigma^2 V_\beta)_+
\]</span></p>
<p><strong>문제 (c)</strong>: 다차원에서는 “각 성분을 <span class="math inline">\(\lambda\)</span> 만큼 끌어당기는” 것으로는 부정확. 상관 있는 <span class="math inline">\(X\)</span> 에서는 한 <span class="math inline">\(\beta_j\)</span> 의 이동이 다른 <span class="math inline">\(\beta_l\)</span> 의 최적값을 바꾼다. 따라서 coordinate descent 또는 LARS 같은 반복 알고리즘이 필요.</p>
</section>
</section>
<section id="ch.14-심화-시리즈-결산" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="ch.14-심화-시리즈-결산"><span class="header-section-number">6</span> Ch.14 심화 시리즈 결산</h2>
<section id="편-논리-지도" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="편-논리-지도"><span class="header-section-number">6.1</span> 4편 논리 지도</h3>
<pre><code>[Ch.14 Overview] 03-14-0
    ↓ 10개 절 조망, 핵심 수식 모음
[§ 14.1~14.3] 03-14-1: Conditional modeling·Classical·Causal
    ↓ 식 (14.1)~(14.9) 완전 유도
    ↓ Incumbency potential outcomes
[§ 14.4~14.6] 03-14-2: Goals·X Matrix·Regularization
    ↓ 3대 목표·Collinearity
    ↓ Ridge/LASSO/Horseshoe 완전 유도
[§ 14.7~14.10] 03-14-3 (본편): Unequal Var·Prior·연습
    ↓ GLS·parametric variance
    ↓ prior as extra data 트릭
    ↓ Ch.14 결산</code></pre>
</section>
<section id="ch.14-결산-실전-체크리스트" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="ch.14-결산-실전-체크리스트"><span class="header-section-number">6.2</span> Ch.14 결산 실전 체크리스트</h3>
<p><strong>모형 설계 단계</strong></p>
<ol type="1">
<li>연구 목표 (이해·예측·인과) 를 명시했는가?</li>
<li>목표에 맞는 변수 집합을 선택했는가? (인과면 post-treatment 배제)</li>
<li><span class="math inline">\(X\)</span> matrix의 collinearity를 점검했는가? (VIF 또는 조건수)</li>
<li>비선형 관계 의심 시 변환 또는 polynomial 검토했는가?</li>
<li>상호작용 항이 필요한지 이론 근거로 판단했는가?</li>
</ol>
<p><strong>Prior 선택</strong></p>
<ol start="6" type="1">
<li>Noninformative prior 적용 가능한가? (<span class="math inline">\(n &gt; k\)</span> 조건)</li>
<li>선행 연구가 있으면 numerical prior로 포함 (§ 14.8, 식 (14.24))</li>
<li>고차원 (<span class="math inline">\(k\)</span> 큰) 경우 regularization 적용 (§ 14.6)</li>
<li>부등식 제약은 rejection sampling으로 처리</li>
</ol>
<p><strong>분산 구조</strong></p>
<ol start="10" type="1">
<li>등분산 가정이 합리적인가? 잔차 plot 절대값 확인.</li>
<li>불등 분산 의심 시: WLS, parametric variance (14.20), 또는 여러 컴포넌트 (14.23).</li>
<li>상관 구조 의심 시: 적절한 <span class="math inline">\(\Sigma_y\)</span> 모수화 (AR, spatial kernel, 계층 모형).</li>
</ol>
<p><strong>계산</strong></p>
<ol start="13" type="1">
<li><span class="math inline">\(X^T X\)</span> 직접 inversion 피하고 QR 분해 사용.</li>
<li>고차원에서는 iterative 방법 (CG, stochastic VI) 검토.</li>
<li>수치 안정성: <span class="math inline">\(X\)</span> 표준화 후 모델링.</li>
</ol>
<p><strong>검증</strong></p>
<ol start="16" type="1">
<li>OLS 점 추정과 베이즈 사후 평균 수치 일치 확인 (구현 검증).</li>
<li>잔차 plot으로 선형성·등분산 점검.</li>
<li>Posterior predictive check: 이상치 비율·예측 구간 커버리지.</li>
<li>민감도 분석: prior 변경 시 결론이 robust한가?</li>
</ol>
<p><strong>해석</strong></p>
<ol start="20" type="1">
<li>점 추정만 보지 말고 credible interval 보고.</li>
<li>예측 구간과 평균 response 구간 구분.</li>
<li>인과 주장 시 ignorability, confounding, mediation 명시.</li>
<li>모형의 적용 한계 (훈련 범위 밖 예측, 이상치 민감도) 를 투명하게 공개.</li>
</ol>
</section>
<section id="구현-환경-정리" class="level3" data-number="6.3">
<h3 data-number="6.3" class="anchored" data-anchor-id="구현-환경-정리"><span class="header-section-number">6.3</span> 구현 환경 정리</h3>
<table class="table">
<colgroup>
<col style="width: 35%">
<col style="width: 47%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>기능</th>
<th>Python</th>
<th>R</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>OLS + 사후 샘플링</td>
<td><code>numpy.linalg.qr</code>, 수동 구현</td>
<td><code>lm()</code>, <code>BayesLinear</code></td>
</tr>
<tr class="even">
<td>Bayesian 선형 회귀</td>
<td><code>scipy.stats</code>, <code>pymc</code>, <code>numpyro</code></td>
<td><code>rstanarm::stan_glm</code>, <code>brms</code></td>
</tr>
<tr class="odd">
<td>Ridge</td>
<td><code>sklearn.linear_model.Ridge</code>, <code>pymc</code></td>
<td><code>glmnet</code>, <code>rstanarm</code></td>
</tr>
<tr class="even">
<td>LASSO</td>
<td><code>sklearn.linear_model.Lasso</code>, <code>pymc</code></td>
<td><code>glmnet</code>, <code>monomvn::blasso</code></td>
</tr>
<tr class="odd">
<td>Horseshoe</td>
<td><code>numpyro</code>, <code>pymc</code></td>
<td><code>rstanarm::stan_glm(prior=hs())</code></td>
</tr>
<tr class="even">
<td>GLS</td>
<td><code>statsmodels.gls</code></td>
<td><code>nlme::gls</code>, <code>rstanarm</code></td>
</tr>
<tr class="odd">
<td>계층 모형 (Ch.15)</td>
<td><code>pymc</code>, <code>numpyro</code></td>
<td><code>brms</code>, <code>lme4</code>, <code>rstanarm</code></td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="part-iv-다음-편-예고" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="part-iv-다음-편-예고"><span class="header-section-number">7</span> Part IV 다음 편 예고</h2>
<p>Ch.14는 여기서 끝난다. Part IV의 다음 목적지:</p>
<ul>
<li><strong>Ch.15 Hierarchical Linear Models</strong> — “varying intercepts/slopes, ANOVA의 베이즈 재해석, partial pooling” → Ch.14 기본 회귀를 <strong>계층적</strong>으로 확장.</li>
<li><strong>Ch.16 Generalized Linear Models</strong> — 로지스틱·Poisson·MRP → Ch.14의 정규성 가정을 완화.</li>
<li><strong>Ch.17 Robust Inference</strong> — <span class="math inline">\(t\)</span> 오차, 혼합 모형 → Ch.14의 이상치 문제 (incumbency Table 14.2) 의 일반 해법.</li>
<li><strong>Ch.18 Missing Data</strong> — multiple imputation, data augmentation → Ch.14의 “<span class="math inline">\(X\)</span> 완전 관측” 가정 완화.</li>
</ul>
<p>Part IV 전체가 Ch.14의 <strong>네 방향 확장</strong>으로 구성되어 있다. Ch.14를 베이즈로 완전히 이해하면 Part IV 나머지는 같은 문법의 변주라는 Gelman의 주장이 현실이다.</p>
</section>
<section id="관련-주제" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="관련-주제"><span class="header-section-number">8</span> 관련 주제</h2>
<p><strong>선행 지식</strong></p>
<ul>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/03-14-0-regression-overview.html">Ch.14 Overview</a></li>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/03-14-1-conditional-modeling-classical-regression-causal.html">Ch.14 § 14.1~14.3 — Classical Regression·Causal</a></li>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/03-14-2-goals-x-matrix-regularization.html">Ch.14 § 14.4~14.6 — Goals·X Matrix·Regularization</a></li>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/02-11-0-mcmc-basics.html">Ch.11~13 — Computation</a></li>
</ul>
<p><strong>후속 주제 (Part IV)</strong></p>
<ul>
<li>Ch.15 Hierarchical Linear Models</li>
<li>Ch.16 GLM</li>
<li>Ch.17 Robust Inference</li>
<li>Ch.18 Missing Data</li>
</ul>
<p><strong>관련 개념 (cross-category)</strong></p>
<ul>
<li><a href="../../Math/gls-cholesky.qmd">Generalized Least Squares</a></li>
<li><a href="../wls-heteroscedasticity.qmd">Weighted Least Squares</a></li>
<li><a href="../../Deep_Learning/kalman-filter.qmd">Kalman Filter (시계열 GLS)</a></li>
<li><a href="../mixed-model-overview.qmd">Mixed-effects Models</a></li>
</ul>
</section>
<section id="참고문헌" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="참고문헌"><span class="header-section-number">9</span> 참고문헌</h2>
<ul>
<li>Gelman, A., Carlin, J. B., Stern, H. S., Dunson, D. B., Vehtari, A., &amp; Rubin, D. B. (2013). <em>Bayesian Data Analysis</em> (3rd ed.), Ch.14 § 14.7~14.10. CRC Press.</li>
<li>Zellner, A. (1971). <em>An Introduction to Bayesian Inference in Econometrics</em>. Wiley.</li>
<li>Box, G. E. P., &amp; Tiao, G. C. (1973). <em>Bayesian Inference in Statistical Analysis</em>. Addison-Wesley.</li>
<li>Gelman, A., &amp; Hill, J. (2007). <em>Data Analysis Using Regression and Multilevel/Hierarchical Models</em>. Cambridge.</li>
<li>Boscardin, W. J., &amp; Gelman, A. (1996). Bayesian Regression with Parametric Models for Heteroscedasticity. <em>Advances in Econometrics</em>, 11, 87-109.</li>
<li>Golub, G. H., &amp; van Loan, C. F. (1983). <em>Matrix Computations</em>. Johns Hopkins.</li>
<li>Cressie, N. (1993). <em>Statistics for Spatial Data</em>. Wiley.</li>
<li>Banerjee, S., Carlin, B. P., &amp; Gelfand, A. E. (2004). <em>Hierarchical Modeling and Analysis for Spatial Data</em>. CRC Press.</li>
</ul>


</section>

</main> <!-- /main -->
<script type="text/javascript">

// replace cmd keyboard shortcut w/ control on non-Mac platforms
const kPlatformMac = typeof navigator !== 'undefined' ? /Mac/.test(navigator.platform) : false;
if (!kPlatformMac) {
   var kbds = document.querySelectorAll("kbd")
   kbds.forEach(function(kbd) {
      kbd.innerHTML = kbd.innerHTML.replace(/⌘/g, '⌃');
   });
}

// tweak headings in pymd
document.querySelectorAll(".pymd span.co").forEach(el => {
   if (!el.innerText.startsWith("#|")) {
      el.style.fontWeight = 1000;
   }
});

</script>
<!-- Begin Mailchimp Signup Form -->
<div id="mc_embed_signup" style="padding-bottom: 1em; max-width: 400px;" class="ms-auto me-auto">
  <p style="font-weight: 600; margin-bottom: 0;">Subscribe</p>
  <span style="font-size: 0.9em;">Enjoy this blog? Get notified of new posts by email:</span>
<form action="https://quarto.us14.list-manage.com/subscribe/post?u=c79fb56a311ae347fbe916740&amp;id=ec05dfca03" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate="">
    <div id="mc_embed_signup_scroll">
	
        <div class="input-group mt-1 mb-2">
        <input type="email" class="form-control" placeholder="Email Address" aria-label="Email Address" name="EMAIL" style="font-size: 0.8em; padding: .2em;">
        </div>              

	<div id="mce-responses" class="clear foot">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_c79fb56a311ae347fbe916740_ec05dfca03" tabindex="-1" value=""></div>
        <div class="optionalParent">
            <div class="clear foot" style="display: flex; align-items: center; justify-content: center;">
              
              
                <input type="submit" value="Subscribe" name="subscribe" style="min-width: 150px; font-size: 0.8em;" id="mc-embedded-subscribe" class="button btn btn-light btn-sm ms-auto me-auto">
            </div>
        </div>
    </div>
</form>
</div>

<!--End mc_embed_signup-->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "복사완료!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "복사완료!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="kmink3225/blog" data-repo-id="R_kgDOLCZyDg" data-category="Blog" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script>
<input type="hidden" id="giscus-base-theme" value="light">
<input type="hidden" id="giscus-alt-theme" value="dark">
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Kwangmin Kim</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="../../../../../about.html">
<p>About</p>
</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/kmink3225/blog">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>