<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ko" xml:lang="ko"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.543">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kwangmin Kim">
<meta name="description" content="Gelman BDA Ch.21 의 § 21.1~21.3 을 한 편으로 깊게 다룬다. § 21.1 GP regression 의 Kolmogorov consistency, mean·kernel 설계, kernel 대수, 다변량 정규 조건부 공식 적용을 통한 사후 평균·분산 완전 유도, 식 (21.1) marginal likelihood 의 단계별 유도와 Cholesky 기반 수치 안정 구현, O(n^3) 의 근원과 근사 기법 (inducing points, SOR/DTC/FITC, KISS-GP), ARD anisotropic kernel 의 변수 선택 의미를 다룬다. § 21.2 미국 1969~1988 출생 데이터의 5-component 가법 분해 (장기 추세·단기 비주기·주간 quasi-periodic·연간 계절·특별일), periodic kernel k(t,t') = \sigma^2 \exp(-2\sin^2(\pi(t-t')/p)/\ell^2) 의 사상 유도, kernel 곱이 표현하는 “AND” 의미, 식 (21.2) component-wise prediction, improved 8-component 모델과 LOO-CV lppd 비교를 정리한다. § 21.3 비가우시안 우도에서의 latent GP, Laplace 근사 식 (21.3) 의 step-by-step 유도, EP·VI 와의 비교, 1043 명 AML 환자 데이터의 log-logistic + GP latent 분석에서 WBC × TDI 암묵적 상호작용 발견 사례를 다룬다.">

<title>Kwangmin Kim - Ch.21 § 21.1~21.3 심화 — GP Regression · Birthdays · Latent GP</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../../../">
<script src="../../../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../../../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../../../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": true,
  "language": {
    "search-no-results-text": "일치 없음",
    "search-matching-documents-text": "일치된 문서",
    "search-copy-link-title": "검색 링크 복사",
    "search-hide-matches-text": "추가 검색 결과 숨기기",
    "search-more-match-text": "추가 검색결과",
    "search-more-matches-text": "추가 검색결과",
    "search-clear-button-title": "제거",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "취소",
    "search-submit-button-title": "검색",
    "search-label": "검색"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-6W0EKFMWBN"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-6W0EKFMWBN', { 'anonymize_ip': true});
</script>
<style>

      .quarto-title-block .quarto-title-banner h1,
      .quarto-title-block .quarto-title-banner h2,
      .quarto-title-block .quarto-title-banner h3,
      .quarto-title-block .quarto-title-banner h4,
      .quarto-title-block .quarto-title-banner h5,
      .quarto-title-block .quarto-title-banner h6
      {
        color: black;
      }

      .quarto-title-block .quarto-title-banner {
        color: black;
background: #EDF3F9;
      }
</style>
<style>
.custom-footer { 
  text-align: center; 
  font-size: 0.8em; 
  color: #666; 
  margin-top: 2rem; 
}
</style>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../../../styles.css">
<meta property="og:title" content="Kwangmin Kim - Ch.21 § 21.1~21.3 심화 — GP Regression · Birthdays · Latent GP">
<meta property="og:description" content="Gelman BDA Ch.21 의 § 21.1~21.3 을 한 편으로 깊게 다룬다. § 21.1 GP regression 의 Kolmogorov consistency, mean·kernel 설계, kernel 대수, 다변량 정규 조건부 공식 적용을 통한 사후 평균·분산 완전 유도, 식 (21.1) marginal likelihood 의 단계별 유도와 Cholesky 기반 수치 안정 구현, \(O(n^3)\) 의 근원과 근사 기법 (inducing points, SOR/DTC/FITC, KISS-GP), ARD anisotropic kernel 의 변수 선택 의미를 다룬다. § 21.2 미국 1969~1988 출생 데이터의 5-component 가법 분해 (장기 추세·단기 비주기·주간 quasi-periodic·연간 계절·특별일), periodic kernel \(k(t,t') = \sigma^2 \exp(-2\sin^2(\pi(t-t')/p)/\ell^2)\) 의 사상 유도, kernel 곱이 표현하는 “AND” 의미, 식 (21.2) component-wise prediction, improved 8-component 모델과 LOO-CV lppd 비교를 정리한다. § 21.3 비가우시안 우도에서의 latent GP, Laplace 근사 식 (21.3) 의 step-by-step 유도, EP·VI 와의 비교, 1043 명 AML 환자 데이터의 log-logistic + GP latent 분석에서 WBC × TDI 암묵적 상호작용 발견 사례를 다룬다.">
<meta property="og:site_name" content="Kwangmin Kim">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../../../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../../../.././images/logo.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../../../../index.html">
    <span class="navbar-title">Kwangmin Kim</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="검색"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="탐색 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../../docs/blog/index.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../../../about.html"> 
<span class="menu-text">Me</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/kmink3225"> <i class="bi bi-github" role="img" aria-label="Github">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/kwangmin-kim-a5241b200/"> <i class="bi bi-linkedin" role="img" aria-label="Linkedin">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../../../../docs/blog/index.xml"> <i class="bi bi-rss" role="img" aria-label="RSS">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="다크 모드 전환"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Ch.21 § 21.1~21.3 심화 — GP Regression · Birthdays · Latent GP</h1>
            <p class="subtitle lead">다변량 정규의 조건부 공식·식 (21.1) marginal likelihood 완전 유도·Cholesky 구현·Birthday 5-component·Quasi-periodic kernel·Laplace 식 (21.3)·Leukemia 생존 분석</p>
                  <div>
        <div class="description">
          <p>Gelman BDA Ch.21 의 § 21.1~21.3 을 한 편으로 깊게 다룬다. § 21.1 GP regression 의 Kolmogorov consistency, mean·kernel 설계, kernel 대수, 다변량 정규 조건부 공식 적용을 통한 사후 평균·분산 완전 유도, 식 (21.1) marginal likelihood 의 단계별 유도와 Cholesky 기반 수치 안정 구현, <span class="math inline">\(O(n^3)\)</span> 의 근원과 근사 기법 (inducing points, SOR/DTC/FITC, KISS-GP), ARD anisotropic kernel 의 변수 선택 의미를 다룬다. § 21.2 미국 1969~1988 출생 데이터의 5-component 가법 분해 (장기 추세·단기 비주기·주간 quasi-periodic·연간 계절·특별일), periodic kernel <span class="math inline">\(k(t,t') = \sigma^2 \exp(-2\sin^2(\pi(t-t')/p)/\ell^2)\)</span> 의 사상 유도, kernel 곱이 표현하는 “AND” 의미, 식 (21.2) component-wise prediction, improved 8-component 모델과 LOO-CV lppd 비교를 정리한다. § 21.3 비가우시안 우도에서의 latent GP, Laplace 근사 식 (21.3) 의 step-by-step 유도, EP·VI 와의 비교, 1043 명 AML 환자 데이터의 log-logistic + GP latent 분석에서 WBC × TDI 암묵적 상호작용 발견 사례를 다룬다.</p>
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">Statistics</div>
                <div class="quarto-category">Bayesian</div>
                <div class="quarto-category">Gaussian-Process</div>
                <div class="quarto-category">Kernel-Methods</div>
                <div class="quarto-category">Survival-Analysis</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">저자</div>
      <div class="quarto-title-meta-contents">
               <p>Kwangmin Kim </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">공개</div>
      <div class="quarto-title-meta-contents">
        <p class="date">2026년 04월 27일</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">목차</h2>
   
  <ul>
  <li><a href="#들어가며-왜-21.121.3-을-한-묶음으로" id="toc-들어가며-왜-21.121.3-을-한-묶음으로" class="nav-link active" data-scroll-target="#들어가며-왜-21.121.3-을-한-묶음으로"><span class="header-section-number">1</span> 들어가며 — 왜 § 21.1~21.3 을 한 묶음으로</a></li>
  <li><a href="#gaussian-process-regression-완전-유도" id="toc-gaussian-process-regression-완전-유도" class="nav-link" data-scroll-target="#gaussian-process-regression-완전-유도"><span class="header-section-number">2</span> § 21.1 Gaussian Process Regression — 완전 유도</a>
  <ul class="collapse">
  <li><a href="#kolmogorov-consistency-함수의-분포-를-정당화하기" id="toc-kolmogorov-consistency-함수의-분포-를-정당화하기" class="nav-link" data-scroll-target="#kolmogorov-consistency-함수의-분포-를-정당화하기"><span class="header-section-number">2.1</span> Kolmogorov Consistency — “함수의 분포” 를 정당화하기</a></li>
  <li><a href="#kernel-의-psd-요구" id="toc-kernel-의-psd-요구" class="nav-link" data-scroll-target="#kernel-의-psd-요구"><span class="header-section-number">2.2</span> Kernel 의 PSD 요구</a></li>
  <li><a href="#kernel-대수-합곱warping" id="toc-kernel-대수-합곱warping" class="nav-link" data-scroll-target="#kernel-대수-합곱warping"><span class="header-section-number">2.3</span> Kernel 대수 — 합·곱·warping</a></li>
  <li><a href="#대표-kernel-비교표" id="toc-대표-kernel-비교표" class="nav-link" data-scroll-target="#대표-kernel-비교표"><span class="header-section-number">2.4</span> 대표 Kernel 비교표</a></li>
  <li><a href="#mean-function-설계-0-vs-선형-vs-parametric" id="toc-mean-function-설계-0-vs-선형-vs-parametric" class="nav-link" data-scroll-target="#mean-function-설계-0-vs-선형-vs-parametric"><span class="header-section-number">2.5</span> Mean Function 설계 — 0 vs 선형 vs parametric</a></li>
  <li><a href="#사후-추론-다변량-정규의-조건부-공식-적용" id="toc-사후-추론-다변량-정규의-조건부-공식-적용" class="nav-link" data-scroll-target="#사후-추론-다변량-정규의-조건부-공식-적용"><span class="header-section-number">2.6</span> 사후 추론 — 다변량 정규의 조건부 공식 적용</a></li>
  <li><a href="#식-21.1-marginal-likelihood-단계별-유도" id="toc-식-21.1-marginal-likelihood-단계별-유도" class="nav-link" data-scroll-target="#식-21.1-marginal-likelihood-단계별-유도"><span class="header-section-number">2.7</span> 식 (21.1) Marginal Likelihood — 단계별 유도</a></li>
  <li><a href="#cholesky-기반-수치-안정-구현" id="toc-cholesky-기반-수치-안정-구현" class="nav-link" data-scroll-target="#cholesky-기반-수치-안정-구현"><span class="header-section-number">2.8</span> Cholesky 기반 수치 안정 구현</a></li>
  <li><a href="#on3-의-본질과-근사-기법" id="toc-on3-의-본질과-근사-기법" class="nav-link" data-scroll-target="#on3-의-본질과-근사-기법"><span class="header-section-number">2.9</span> <span class="math inline">\(O(n^3)\)</span> 의 본질과 근사 기법</a></li>
  <li><a href="#anisotropic-ard-의-변수-선택" id="toc-anisotropic-ard-의-변수-선택" class="nav-link" data-scroll-target="#anisotropic-ard-의-변수-선택"><span class="header-section-number">2.10</span> Anisotropic ARD 의 변수 선택</a></li>
  </ul></li>
  <li><a href="#birthday-데이터-component-가법-분해-완전-분석" id="toc-birthday-데이터-component-가법-분해-완전-분석" class="nav-link" data-scroll-target="#birthday-데이터-component-가법-분해-완전-분석"><span class="header-section-number">3</span> § 21.2 Birthday 데이터 — Component 가법 분해 완전 분석</a>
  <ul class="collapse">
  <li><a href="#데이터와-모델링-철학" id="toc-데이터와-모델링-철학" class="nav-link" data-scroll-target="#데이터와-모델링-철학"><span class="header-section-number">3.1</span> 데이터와 모델링 철학</a></li>
  <li><a href="#component-가법-모델" id="toc-component-가법-모델" class="nav-link" data-scroll-target="#component-가법-모델"><span class="header-section-number">3.2</span> 5-Component 가법 모델</a></li>
  <li><a href="#component-1-2-장단기-추세" id="toc-component-1-2-장단기-추세" class="nav-link" data-scroll-target="#component-1-2-장단기-추세"><span class="header-section-number">3.3</span> Component 1, 2 — 장단기 추세</a></li>
  <li><a href="#component-3-주간-quasi-periodic-kernel" id="toc-component-3-주간-quasi-periodic-kernel" class="nav-link" data-scroll-target="#component-3-주간-quasi-periodic-kernel"><span class="header-section-number">3.4</span> Component 3 — 주간 quasi-periodic kernel</a></li>
  <li><a href="#component-4-연간-계절" id="toc-component-4-연간-계절" class="nav-link" data-scroll-target="#component-4-연간-계절"><span class="header-section-number">3.5</span> Component 4 — 연간 계절</a></li>
  <li><a href="#component-5-특별일" id="toc-component-5-특별일" class="nav-link" data-scroll-target="#component-5-특별일"><span class="header-section-number">3.6</span> Component 5 — 특별일</a></li>
  <li><a href="#식-21.2-component-wise-prediction" id="toc-식-21.2-component-wise-prediction" class="nav-link" data-scroll-target="#식-21.2-component-wise-prediction"><span class="header-section-number">3.7</span> 식 (21.2) — Component-wise Prediction</a></li>
  <li><a href="#improved-8-component-모델" id="toc-improved-8-component-모델" class="nav-link" data-scroll-target="#improved-8-component-모델"><span class="header-section-number">3.8</span> Improved 8-Component 모델</a></li>
  </ul></li>
  <li><a href="#latent-gaussian-process-models" id="toc-latent-gaussian-process-models" class="nav-link" data-scroll-target="#latent-gaussian-process-models"><span class="header-section-number">4</span> § 21.3 Latent Gaussian Process Models</a>
  <ul class="collapse">
  <li><a href="#동기-비가우시안-우도" id="toc-동기-비가우시안-우도" class="nav-link" data-scroll-target="#동기-비가우시안-우도"><span class="header-section-number">4.1</span> 동기 — 비가우시안 우도</a></li>
  <li><a href="#latent-gp-모델-구조" id="toc-latent-gp-모델-구조" class="nav-link" data-scroll-target="#latent-gp-모델-구조"><span class="header-section-number">4.2</span> Latent GP 모델 구조</a></li>
  <li><a href="#laplace-근사-식-21.3-유도" id="toc-laplace-근사-식-21.3-유도" class="nav-link" data-scroll-target="#laplace-근사-식-21.3-유도"><span class="header-section-number">4.3</span> Laplace 근사 — 식 (21.3) 유도</a></li>
  <li><a href="#ep-와-vi-laplace-가-부족할-때" id="toc-ep-와-vi-laplace-가-부족할-때" class="nav-link" data-scroll-target="#ep-와-vi-laplace-가-부족할-때"><span class="header-section-number">4.4</span> EP 와 VI — Laplace 가 부족할 때</a></li>
  <li><a href="#leukemia-생존-분석-latent-gp-의-위력" id="toc-leukemia-생존-분석-latent-gp-의-위력" class="nav-link" data-scroll-target="#leukemia-생존-분석-latent-gp-의-위력"><span class="header-section-number">4.5</span> Leukemia 생존 분석 — Latent GP 의 위력</a></li>
  </ul></li>
  <li><a href="#핵심-수식-유도-부록" id="toc-핵심-수식-유도-부록" class="nav-link" data-scroll-target="#핵심-수식-유도-부록"><span class="header-section-number">5</span> 핵심 수식 유도 부록</a>
  <ul class="collapse">
  <li><a href="#다변량-정규-조건부-공식-schur-complement" id="toc-다변량-정규-조건부-공식-schur-complement" class="nav-link" data-scroll-target="#다변량-정규-조건부-공식-schur-complement"><span class="header-section-number">5.1</span> 다변량 정규 조건부 공식 — Schur Complement</a></li>
  <li><a href="#marginal-likelihood-의-또다른-형태" id="toc-marginal-likelihood-의-또다른-형태" class="nav-link" data-scroll-target="#marginal-likelihood-의-또다른-형태"><span class="header-section-number">5.2</span> Marginal Likelihood 의 또다른 형태</a></li>
  <li><a href="#periodic-kernel-의-mercer-분해" id="toc-periodic-kernel-의-mercer-분해" class="nav-link" data-scroll-target="#periodic-kernel-의-mercer-분해"><span class="header-section-number">5.3</span> Periodic Kernel 의 Mercer 분해</a></li>
  </ul></li>
  <li><a href="#코드-풀-구현-numpy-pymc-scikit-learn" id="toc-코드-풀-구현-numpy-pymc-scikit-learn" class="nav-link" data-scroll-target="#코드-풀-구현-numpy-pymc-scikit-learn"><span class="header-section-number">6</span> 코드 — 풀 구현 (NumPy + PyMC + scikit-learn)</a>
  <ul class="collapse">
  <li><a href="#section-a-1d-gp-regression-with-marginal-likelihood" id="toc-section-a-1d-gp-regression-with-marginal-likelihood" class="nav-link" data-scroll-target="#section-a-1d-gp-regression-with-marginal-likelihood"><span class="header-section-number">6.1</span> Section A — 1D GP regression with marginal likelihood</a></li>
  <li><a href="#section-b-hyperparameter-optimization-type-ii-mle" id="toc-section-b-hyperparameter-optimization-type-ii-mle" class="nav-link" data-scroll-target="#section-b-hyperparameter-optimization-type-ii-mle"><span class="header-section-number">6.2</span> Section B — Hyperparameter optimization (Type-II MLE)</a></li>
  <li><a href="#section-c-birthday-style-additive-model-toy" id="toc-section-c-birthday-style-additive-model-toy" class="nav-link" data-scroll-target="#section-c-birthday-style-additive-model-toy"><span class="header-section-number">6.3</span> Section C — Birthday-style additive model (toy)</a></li>
  <li><a href="#section-d-latent-gp-for-binary-classification-pymc" id="toc-section-d-latent-gp-for-binary-classification-pymc" class="nav-link" data-scroll-target="#section-d-latent-gp-for-binary-classification-pymc"><span class="header-section-number">6.4</span> Section D — Latent GP for binary classification (PyMC)</a></li>
  </ul></li>
  <li><a href="#실전-체크리스트-21.121.3" id="toc-실전-체크리스트-21.121.3" class="nav-link" data-scroll-target="#실전-체크리스트-21.121.3"><span class="header-section-number">7</span> 실전 체크리스트 — § 21.1~21.3</a></li>
  <li><a href="#관련-주제" id="toc-관련-주제" class="nav-link" data-scroll-target="#관련-주제"><span class="header-section-number">8</span> 관련 주제</a></li>
  <li><a href="#참고문헌" id="toc-참고문헌" class="nav-link" data-scroll-target="#참고문헌"><span class="header-section-number">9</span> 참고문헌</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="들어가며-왜-21.121.3-을-한-묶음으로" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="들어가며-왜-21.121.3-을-한-묶음으로"><span class="header-section-number">1</span> 들어가며 — 왜 § 21.1~21.3 을 한 묶음으로</h2>
<p><a href="../../../../../docs/blog/posts/Statistics/bayesian/04-21-0-gaussian-process-overview.html">Ch.21 Overview</a> 에서 GP 의 큰 그림을 정리했다. 본 편은 그중 <strong>함수 추정의 핵심 세 절</strong> 을 깊게 다룬다.</p>
<table class="table">
<colgroup>
<col style="width: 26%">
<col style="width: 36%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">절</th>
<th style="text-align: left;">역할</th>
<th style="text-align: left;">핵심 수학</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">§ 21.1</td>
<td style="text-align: left;"><strong>GP regression 의 모든 것</strong></td>
<td style="text-align: left;">다변량 정규 조건부 공식 → 사후 평균·분산, 식 (21.1) marginal likelihood, Cholesky</td>
</tr>
<tr class="even">
<td style="text-align: center;">§ 21.2</td>
<td style="text-align: left;"><strong>GP 가 큰 모델의 부품으로 어떻게 쓰이는가</strong></td>
<td style="text-align: left;">Kernel 합·곱, periodic kernel, component-wise prediction (식 21.2)</td>
</tr>
<tr class="odd">
<td style="text-align: center;">§ 21.3</td>
<td style="text-align: left;"><strong>비가우시안 우도로의 확장</strong></td>
<td style="text-align: left;">Latent function, Laplace 식 (21.3), EP·VI</td>
</tr>
</tbody>
</table>
<p>§ 21.4 (FDA), § 21.5 (LGP density), § 21.6~21.7 (문헌·연습) 은 별도 편 <a href="./04-21-2-fda-density-exercises.qmd">§ 21.4~21.7</a> 에서 다룬다.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
본 편이 답하는 다섯 가지 질문
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>“함수에 사전분포” 를 수학적으로 어떻게 정의해야 모순이 없는가? (Kolmogorov consistency)</li>
<li>가우시안 우도에서 사후 평균·분산이 닫힌 형태로 나오는 <strong>이유</strong> 는 무엇인가? (다변량 정규의 조건부 공식)</li>
<li>식 (21.1) 의 세 항 — 데이터 적합·Occam·정규화 — 은 어떻게 유도되며 무엇을 균형 맞추는가?</li>
<li>Birthday 데이터의 주간·계절 패턴이 <strong>단순 sin 함수가 아닌 GP</strong> 로 표현될 때 무엇이 더 잡히는가?</li>
<li>비가우시안 우도에서 <span class="math inline">\(\mu\)</span> 적분 소거가 안 될 때 Laplace 가 무엇을 근사하며 그 정확도는 어떤 조건에서 좋은가?</li>
</ol>
</div>
</div>
</section>
<section id="gaussian-process-regression-완전-유도" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="gaussian-process-regression-완전-유도"><span class="header-section-number">2</span> § 21.1 Gaussian Process Regression — 완전 유도</h2>
<section id="kolmogorov-consistency-함수의-분포-를-정당화하기" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="kolmogorov-consistency-함수의-분포-를-정당화하기"><span class="header-section-number">2.1</span> Kolmogorov Consistency — “함수의 분포” 를 정당화하기</h3>
<p>GP 정의를 다시 보자.</p>
<p><span class="math display">\[
\mu \sim \text{GP}(m, k) \iff \forall n,\ \forall x_1, \ldots, x_n \in \mathcal{X},\ \bigl(\mu(x_i)\bigr)_{i=1}^n \sim N\bigl(\mathbf{m}, \mathbf{K}\bigr)
\]</span></p>
<p>여기서 <span class="math inline">\(\mathbf{m}_i = m(x_i)\)</span>, <span class="math inline">\(\mathbf{K}_{ij} = k(x_i, x_j)\)</span>.</p>
<p><strong>문제</strong>: 임의의 <span class="math inline">\(n\)</span> 차원 marginal 만 정의했는데, 이로부터 <strong>함수 공간 전체</strong> 의 확률 분포가 일관되게 존재하는가?</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Kolmogorov 확장 정리
</div>
</div>
<div class="callout-body-container callout-body">
<p>다음 두 조건만 만족하면 <span class="math inline">\(\{x_1, \ldots, x_n\}\)</span> marginal 의 모임으로부터 <strong>유일한</strong> 확률 분포가 함수 공간에 존재한다.</p>
<ol type="1">
<li><strong>순열 불변성</strong>: <span class="math inline">\(\bigl(\mu(x_{\pi(1)}), \ldots, \mu(x_{\pi(n)})\bigr)\)</span> 의 분포가 <span class="math inline">\(\mu(x_1), \ldots, \mu(x_n)\)</span> 의 분포의 순열.</li>
<li><strong>마진화 일관성</strong>: <span class="math inline">\(\bigl(\mu(x_1), \ldots, \mu(x_n), \mu(x_{n+1})\bigr)\)</span> 에서 <span class="math inline">\(\mu(x_{n+1})\)</span> 을 적분 소거하면 <span class="math inline">\(\bigl(\mu(x_1), \ldots, \mu(x_n)\bigr)\)</span>.</li>
</ol>
<p><strong>다변량 정규는 이 두 조건을 자동으로 만족한다</strong>:</p>
<ul>
<li>순열은 평균·공분산을 같이 순열한 정규.</li>
<li>마진화는 정규의 부분집합 분포 = 다시 정규.</li>
</ul>
<p>따라서 mean function <span class="math inline">\(m\)</span> + <strong>positive semi-definite (PSD)</strong> covariance function <span class="math inline">\(k\)</span> 만 정해지면, GP 가 함수 공간 위의 확률 측도로 잘 정의된다.</p>
</div>
</div>
</section>
<section id="kernel-의-psd-요구" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="kernel-의-psd-요구"><span class="header-section-number">2.2</span> Kernel 의 PSD 요구</h3>
<p><span class="math inline">\(k\)</span> 가 covariance function 이려면 임의의 <span class="math inline">\(n\)</span>, 임의의 <span class="math inline">\(x_1, \ldots, x_n\)</span> 에서 <span class="math inline">\(\mathbf{K}\)</span> 가 PSD 여야 한다.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — PSD 가 의미하는 것
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(\mathbf{K}\)</span> 가 PSD 라는 말은 임의의 벡터 <span class="math inline">\(\mathbf{a} \in \mathbb{R}^n\)</span> 에 대해 <span class="math inline">\(\mathbf{a}^T \mathbf{K} \mathbf{a} \geq 0\)</span>. 의미는:</p>
<p><span class="math display">\[
\mathrm{Var}\Bigl(\sum_i a_i \mu(x_i)\Bigr) = \mathbf{a}^T \mathbf{K} \mathbf{a} \geq 0
\]</span></p>
<p>함수 값들의 임의의 선형결합의 분산이 음수일 수 없다는 당연한 요구. <strong>PSD 가 GP 정의의 본질적 제약</strong> 이다.</p>
<p>흔한 PSD kernel:</p>
<ul>
<li>Squared exponential — Bochner 정리로 증명 (Fourier transform 이 양의 측도).</li>
<li>Matern — 마찬가지로 Bochner.</li>
<li>Periodic — sine warping 후 squared exponential.</li>
<li>Linear <span class="math inline">\(k(x, x') = \sigma^2 (x \cdot x' + c)\)</span> — 직접 확인.</li>
</ul>
<p>새로운 kernel 을 만들 때 PSD 위반이 자주 일어나므로, <strong>검증된 kernel 의 합·곱·합성</strong> 으로만 만드는 것이 안전.</p>
</div>
</div>
</section>
<section id="kernel-대수-합곱warping" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="kernel-대수-합곱warping"><span class="header-section-number">2.3</span> Kernel 대수 — 합·곱·warping</h3>
<p>다음 연산은 PSD 를 보존한다.</p>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">연산</th>
<th style="text-align: left;">결과</th>
<th style="text-align: left;">의미</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(k_1 + k_2\)</span></td>
<td style="text-align: left;">PSD</td>
<td style="text-align: left;">“또는” — 두 패턴 중 하나만 비슷해도 함수 값 비슷</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(k_1 \cdot k_2\)</span></td>
<td style="text-align: left;">PSD</td>
<td style="text-align: left;">“그리고” — 두 패턴 모두 비슷해야 함수 값 비슷</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(k(x, x') \cdot c\)</span>, <span class="math inline">\(c &gt; 0\)</span></td>
<td style="text-align: left;">PSD</td>
<td style="text-align: left;">진폭 조정</td>
</tr>
<tr class="even">
<td style="text-align: left;"><span class="math inline">\(k(\phi(x), \phi(x'))\)</span></td>
<td style="text-align: left;">PSD</td>
<td style="text-align: left;">input warping (예: log 변환 후 squared exp)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><span class="math inline">\(f(x) k(x, x') f(x')\)</span></td>
<td style="text-align: left;">PSD</td>
<td style="text-align: left;">“amplitude modulation” — <span class="math inline">\(f\)</span> 가 양수 함수</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — kernel 대수가 모형 빌딩 언어
</div>
</div>
<div class="callout-body-container callout-body">
<p>복잡한 함수 구조는 simple kernel 의 조합으로 표현된다.</p>
<ul>
<li><strong>시간 추세 + 주기</strong>: <span class="math inline">\(k_{\text{trend}}(t, t') + k_{\text{periodic}}(t, t')\)</span>.</li>
<li><strong>시간 따라 진화하는 주기</strong>: <span class="math inline">\(k_{\text{periodic}} \cdot k_{\text{trend}}\)</span>.</li>
<li><strong>공간 × 시간</strong>: <span class="math inline">\(k_{\text{spatial}}(x, x') \cdot k_{\text{time}}(t, t')\)</span> (separable).</li>
<li><strong>국소 진폭 변화</strong>: <span class="math inline">\(\sigma(x) \sigma(x') k(x, x')\)</span>.</li>
</ul>
<p>Birthday 모델 (§ 21.2) 의 5-component 가법 구조가 이 언어로 표현된다.</p>
</div>
</div>
</section>
<section id="대표-kernel-비교표" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="대표-kernel-비교표"><span class="header-section-number">2.4</span> 대표 Kernel 비교표</h3>
<table class="table">
<colgroup>
<col style="width: 26%">
<col style="width: 23%">
<col style="width: 26%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Kernel</th>
<th style="text-align: left;">수식</th>
<th style="text-align: left;">smoothness</th>
<th style="text-align: left;">응용</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Squared exponential</td>
<td style="text-align: left;"><span class="math inline">\(\tau^2 \exp(-\|x-x'\|^2 / 2\ell^2)\)</span></td>
<td style="text-align: left;"><span class="math inline">\(C^\infty\)</span></td>
<td style="text-align: left;">매우 부드러운 함수</td>
</tr>
<tr class="even">
<td style="text-align: left;">Matern <span class="math inline">\(\nu = 5/2\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\tau^2 (1 + \sqrt{5} d/\ell + 5 d^2 / 3\ell^2) \exp(-\sqrt{5} d/\ell)\)</span></td>
<td style="text-align: left;"><span class="math inline">\(C^2\)</span></td>
<td style="text-align: left;">물리적 함수</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Matern <span class="math inline">\(\nu = 3/2\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\tau^2 (1 + \sqrt{3} d/\ell) \exp(-\sqrt{3} d/\ell)\)</span></td>
<td style="text-align: left;"><span class="math inline">\(C^1\)</span></td>
<td style="text-align: left;">거친 함수</td>
</tr>
<tr class="even">
<td style="text-align: left;">Exponential (<span class="math inline">\(\nu = 1/2\)</span>)</td>
<td style="text-align: left;"><span class="math inline">\(\tau^2 \exp(-d/\ell)\)</span></td>
<td style="text-align: left;"><span class="math inline">\(C^0\)</span></td>
<td style="text-align: left;">Wiener-like</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Linear</td>
<td style="text-align: left;"><span class="math inline">\(\sigma_0^2 + \sigma_1^2 (x \cdot x')\)</span></td>
<td style="text-align: left;">analytic</td>
<td style="text-align: left;">사실상 Bayesian linear regression</td>
</tr>
<tr class="even">
<td style="text-align: left;">Periodic</td>
<td style="text-align: left;"><span class="math inline">\(\tau^2 \exp(-2\sin^2(\pi(x-x')/p)/\ell^2)\)</span></td>
<td style="text-align: left;"><span class="math inline">\(C^\infty\)</span></td>
<td style="text-align: left;">주기 신호</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rational quadratic</td>
<td style="text-align: left;"><span class="math inline">\(\tau^2 (1 + d^2 / 2\alpha\ell^2)^{-\alpha}\)</span></td>
<td style="text-align: left;">varies with <span class="math inline">\(\alpha\)</span></td>
<td style="text-align: left;">mixture of length scales</td>
</tr>
</tbody>
</table>
<p>여기서 <span class="math inline">\(d = \|x - x'\|\)</span>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
실무 권장: Squared exp 보다 Matern <span class="math inline">\(\nu = 5/2\)</span>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Squared exponential 은 너무 부드러워 (모든 차수 미분 가능) 실제 데이터의 거칠음을 과소평가하기 쉽다. <strong>Matern <span class="math inline">\(5/2\)</span> 는 두 번 미분 가능 + 충분히 유연</strong> 으로 실무 default 가 되어가고 있다 (Stan·GPyTorch 의 권장).</p>
<p>squared exponential 사용 시: 함수 진폭 추정이 과도하게 작아질 위험. 데이터에 약간의 noise 가 있다면 그 noise 까지 GP 가 흡수하려는 경향.</p>
</div>
</div>
</section>
<section id="mean-function-설계-0-vs-선형-vs-parametric" class="level3" data-number="2.5">
<h3 data-number="2.5" class="anchored" data-anchor-id="mean-function-설계-0-vs-선형-vs-parametric"><span class="header-section-number">2.5</span> Mean Function 설계 — 0 vs 선형 vs parametric</h3>
<p>기본 선택은 <span class="math inline">\(m(x) = 0\)</span>. 이 경우 데이터 외삽 영역에서 <span class="math inline">\(\widetilde\mu \to 0\)</span>.</p>
<p><strong>개선</strong>: <span class="math inline">\(m(x) = X\beta\)</span> — 선형 mean.</p>
<p><span class="math display">\[
\mu(x) = X\beta + g(x), \qquad g \sim \text{GP}(0, k)
\]</span></p>
<p><span class="math inline">\(\beta\)</span> 에 prior 부여 (예: <span class="math inline">\(\beta \sim N(0, \tau_\beta^2 I)\)</span>). 적분 소거 후 다음과 같은 GP 가 유도된다.</p>
<p><span class="math display">\[
\mu \sim \text{GP}(0, k_{\text{eff}}), \qquad k_{\text{eff}}(x, x') = k(x, x') + \tau_\beta^2 X^T X
\]</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — 선형 mean 이 외삽을 구한다
</div>
</div>
<div class="callout-body-container callout-body">
<p>데이터 영역 밖 (예: 새로운 <span class="math inline">\(x^*\)</span> 가 학습 데이터 모든 <span class="math inline">\(x_i\)</span> 에서 멀리 떨어진 경우) 에서 squared exponential 로는 <span class="math inline">\(K(x^*, x) \to 0\)</span>. 따라서 <span class="math inline">\(E(\widetilde\mu) \to 0\)</span> — <strong>0 으로 회귀</strong> 한다.</p>
<p>선형 mean 을 두면 <span class="math inline">\(E(\widetilde\mu) \to X^* \beta\)</span> — <strong>선형 추세로 회귀</strong> 한다. Domain 지식이 “장기적으로 선형 증가” 라면 후자가 훨씬 합리적.</p>
<p>따라서 <strong>시계열·spatial 외삽 문제에서는 zero mean 회피 권장</strong>.</p>
</div>
</div>
</section>
<section id="사후-추론-다변량-정규의-조건부-공식-적용" class="level3" data-number="2.6">
<h3 data-number="2.6" class="anchored" data-anchor-id="사후-추론-다변량-정규의-조건부-공식-적용"><span class="header-section-number">2.6</span> 사후 추론 — 다변량 정규의 조건부 공식 적용</h3>
<p>데이터 모델</p>
<p><span class="math display">\[
y_i = \mu(x_i) + \epsilon_i, \quad \epsilon_i \sim N(0, \sigma^2)
\]</span></p>
<p>새 입력 <span class="math inline">\(\widetilde{x}\)</span> 에서 함수 값 <span class="math inline">\(\widetilde\mu = \mu(\widetilde x)\)</span> 를 예측하고 싶다. <strong>Joint distribution of <span class="math inline">\((y, \widetilde\mu)\)</span></strong>:</p>
<p><span class="math display">\[
\begin{pmatrix} y \\ \widetilde\mu \end{pmatrix} \sim N\left( \begin{pmatrix} \mathbf{0} \\ \mathbf{0} \end{pmatrix},\ \begin{pmatrix} K(x, x) + \sigma^2 I &amp; K(x, \widetilde x) \\ K(\widetilde x, x) &amp; K(\widetilde x, \widetilde x) \end{pmatrix} \right)
\]</span></p>
<p>(zero-mean GP 가정. 일반은 mean 항 이동.)</p>
<p><strong>다변량 정규 조건부 공식 (Casella-Berger, 식 4.6.6 또는 Ch.3 § 3.5 의 BDA)</strong>:</p>
<p><span class="math display">\[
\begin{pmatrix} U \\ V \end{pmatrix} \sim N\left( \begin{pmatrix} \mu_U \\ \mu_V \end{pmatrix}, \begin{pmatrix} \Sigma_{UU} &amp; \Sigma_{UV} \\ \Sigma_{VU} &amp; \Sigma_{VV} \end{pmatrix} \right) \implies V \mid U \sim N(\mu_{V|U}, \Sigma_{V|U})
\]</span></p>
<p><span class="math display">\[
\mu_{V|U} = \mu_V + \Sigma_{VU} \Sigma_{UU}^{-1} (U - \mu_U), \qquad \Sigma_{V|U} = \Sigma_{VV} - \Sigma_{VU} \Sigma_{UU}^{-1} \Sigma_{UV}
\]</span></p>
<p><strong>대입</strong> (<span class="math inline">\(V = \widetilde\mu\)</span>, <span class="math inline">\(U = y\)</span>, <span class="math inline">\(\mu_V = \mu_U = 0\)</span>):</p>
<p><span class="math display">\[
E(\widetilde\mu \mid y) = K(\widetilde x, x) \bigl(K(x, x) + \sigma^2 I\bigr)^{-1} y
\]</span></p>
<p><span class="math display">\[
\text{cov}(\widetilde\mu \mid y) = K(\widetilde x, \widetilde x) - K(\widetilde x, x) \bigl(K(x, x) + \sigma^2 I\bigr)^{-1} K(x, \widetilde x)
\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — 사후 평균·분산이 말하는 것
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>사후 평균 <span class="math inline">\(E(\widetilde\mu \mid y)\)</span></strong>:
<ul>
<li><span class="math inline">\(K(\widetilde x, x)\)</span> = 새 점이 학습 점들과 얼마나 가까운가.</li>
<li><span class="math inline">\(\bigl(K(x, x) + \sigma^2 I\bigr)^{-1} y\)</span> = 학습 데이터를 noise-corrected 가중치로 변환.</li>
<li>둘의 곱 = “학습 데이터에 가중 평균을 매기되, <strong>kernel 거리 가까울수록 큰 가중치</strong>”.</li>
</ul></li>
<li><strong>사후 분산 <span class="math inline">\(\text{cov}(\widetilde\mu \mid y)\)</span></strong>:
<ul>
<li><span class="math inline">\(K(\widetilde x, \widetilde x)\)</span> = prior 분산 (학습 데이터 무시).</li>
<li>그 뒤 항 = 학습 데이터로부터 <strong>얻은 정보</strong> (분산 감소).</li>
<li>학습 점 근처면 “감소” 가 크다 → 사후 분산 작다.</li>
<li>멀리 외삽 영역이면 “감소” 가 작다 → prior 분산으로 회귀.</li>
</ul></li>
</ul>
<p>요약: <strong>사후는 학습 데이터를 통과하는 매끄러운 곡선이며, 학습 점에서 멀어질수록 불확실성이 커진다</strong>. 이것이 GP 가 cross-validation 없이 바로 신뢰 구간을 주는 이유.</p>
</div>
</div>
</section>
<section id="식-21.1-marginal-likelihood-단계별-유도" class="level3" data-number="2.7">
<h3 data-number="2.7" class="anchored" data-anchor-id="식-21.1-marginal-likelihood-단계별-유도"><span class="header-section-number">2.7</span> 식 (21.1) Marginal Likelihood — 단계별 유도</h3>
<p>가우시안 우도에서 <span class="math inline">\(\mu\)</span> 의 적분 소거가 가능하다. <span class="math inline">\(y \sim N(\mu, \sigma^2 I)\)</span>, <span class="math inline">\(\mu \sim \text{GP}(0, k)\)</span> 에서 <span class="math inline">\(\mu(x_1), \ldots, \mu(x_n)\)</span> 를 합치면 <span class="math inline">\(\boldsymbol\mu \sim N(0, K)\)</span>.</p>
<p><span class="math display">\[
y = \boldsymbol\mu + \boldsymbol\epsilon, \quad \boldsymbol\epsilon \sim N(0, \sigma^2 I)
\]</span></p>
<p>두 정규의 합이므로</p>
<p><span class="math display">\[
y \sim N(0, K + \sigma^2 I)
\]</span></p>
<p>따라서 marginal likelihood 는 다변량 정규 PDF 그 자체.</p>
<p><span class="math display">\[
p(y \mid \tau, \ell, \sigma^2) = \frac{1}{(2\pi)^{n/2} |K + \sigma^2 I|^{1/2}} \exp\left( -\frac{1}{2} y^T (K + \sigma^2 I)^{-1} y \right)
\]</span></p>
<p>로그 취하면 식 (21.1):</p>
<p><span class="math display">\[
\log p(y \mid \tau, \ell, \sigma^2) = -\frac{n}{2} \log(2\pi) -\frac{1}{2} \log|K(x, x) + \sigma^2 I| -\frac{1}{2} y^T \bigl(K(x, x) + \sigma^2 I\bigr)^{-1} y \quad (21.1)
\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
세 항의 trade-off — Bayesian Occam
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>상수항</strong> <span class="math inline">\(-\frac{n}{2} \log(2\pi)\)</span>: hyperparameter 무관, 비교에서 무시.</li>
<li><strong>데이터 적합도</strong> <span class="math inline">\(-\frac{1}{2} y^T (K + \sigma^2 I)^{-1} y\)</span>: <span class="math inline">\(y\)</span> 가 모형의 covariance 로 설명되는 정도. <span class="math inline">\(y\)</span> 가 학습 데이터의 자연스러운 GP 표본이면 작은 absolute value.</li>
<li><strong>복잡도 페널티</strong> <span class="math inline">\(-\frac{1}{2} \log|K + \sigma^2 I|\)</span>: <span class="math inline">\(K\)</span> 의 eigenvalue 가 클수록 (= 함수가 큰 진폭 영역을 커버할수록) 페널티 증가.</li>
</ul>
<p><span class="math inline">\(\ell\)</span> 매우 큼 → <span class="math inline">\(K\)</span> 가 거의 상수 행렬 → 적합도는 데이터 평균만 적합 → 적합도 항이 큰 음수 (벌점). <span class="math inline">\(\ell\)</span> 매우 작음 → <span class="math inline">\(K \approx \tau^2 I\)</span> → 적합도 좋지만 복잡도 페널티 큼.</p>
<p><strong>최적 <span class="math inline">\(\ell\)</span> 은 두 항의 trade-off</strong>. Marginal likelihood 최대화가 자동으로 model selection 을 한다 — Bayesian Occam’s razor 의 작동 원리.</p>
</div>
</div>
</section>
<section id="cholesky-기반-수치-안정-구현" class="level3" data-number="2.8">
<h3 data-number="2.8" class="anchored" data-anchor-id="cholesky-기반-수치-안정-구현"><span class="header-section-number">2.8</span> Cholesky 기반 수치 안정 구현</h3>
<p>식 (21.1) 을 직접 계산할 때 <span class="math inline">\(\det\)</span> 와 <span class="math inline">\((\cdot)^{-1}\)</span> 를 따로 구하면 수치 불안정.</p>
<p><strong>Cholesky 분해</strong>: <span class="math inline">\(K + \sigma^2 I = L L^T\)</span>, <span class="math inline">\(L\)</span> 은 하삼각.</p>
<ul>
<li><span class="math inline">\(\log |K + \sigma^2 I| = 2 \sum_i \log L_{ii}\)</span>.</li>
<li><span class="math inline">\(\alpha = (K + \sigma^2 I)^{-1} y\)</span> 는 두 번의 삼각 시스템 풀이로 얻는다 (<span class="math inline">\(L z = y\)</span>, <span class="math inline">\(L^T \alpha = z\)</span>). <span class="math inline">\(O(n^2)\)</span>.</li>
<li><span class="math inline">\(y^T (K + \sigma^2 I)^{-1} y = y^T \alpha\)</span>.</li>
</ul>
<p><strong>Jitter</strong>: <span class="math inline">\(K\)</span> 가 numerically singular 하지 않도록 대각에 <span class="math inline">\(\epsilon I\)</span> (<span class="math inline">\(\epsilon \approx 10^{-6}\)</span>) 를 더한다.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1"></a>L <span class="op">=</span> np.linalg.cholesky(K <span class="op">+</span> sigma2 <span class="op">*</span> np.eye(n) <span class="op">+</span> jitter <span class="op">*</span> np.eye(n))</span>
<span id="cb1-2"><a href="#cb1-2"></a>alpha <span class="op">=</span> np.linalg.solve(L.T, np.linalg.solve(L, y))</span>
<span id="cb1-3"><a href="#cb1-3"></a>log_ml <span class="op">=</span> <span class="op">-</span><span class="fl">0.5</span> <span class="op">*</span> y <span class="op">@</span> alpha <span class="op">-</span> np.<span class="bu">sum</span>(np.log(np.diag(L))) <span class="op">-</span> <span class="fl">0.5</span> <span class="op">*</span> n <span class="op">*</span> np.log(<span class="dv">2</span> <span class="op">*</span> np.pi)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="on3-의-본질과-근사-기법" class="level3" data-number="2.9">
<h3 data-number="2.9" class="anchored" data-anchor-id="on3-의-본질과-근사-기법"><span class="header-section-number">2.9</span> <span class="math inline">\(O(n^3)\)</span> 의 본질과 근사 기법</h3>
<p><span class="math inline">\(K\)</span> 행렬의 사이즈는 <span class="math inline">\(n \times n\)</span>. Cholesky 가 <span class="math inline">\(O(n^3)\)</span>, 메모리는 <span class="math inline">\(O(n^2)\)</span>. <span class="math inline">\(n = 10^4\)</span> 이면 <span class="math inline">\(K\)</span> 만 800MB (double). 이것이 GP 의 본질적 한계.</p>
<p><strong>근사 1 — Inducing Points (Sparse GP)</strong></p>
<p><span class="math inline">\(m \ll n\)</span> 개 가상 점 <span class="math inline">\(z_1, \ldots, z_m\)</span> (inducing locations) 을 도입. <span class="math inline">\(\mu\)</span> 의 분포를 <span class="math inline">\(\mu(z)\)</span> 로 매개변수화하고, 학습 점 <span class="math inline">\(\mu(x)\)</span> 를 <span class="math inline">\(\mu(z)\)</span> 의 조건부로 표현.</p>
<ul>
<li>SOR (Subset of Regressors): <span class="math inline">\(\mu(x) \mid \mu(z)\)</span> 의 평균만 사용.</li>
<li>DTC (Deterministic Training Conditional): SOR + <span class="math inline">\(\mu(z)\)</span> 의 prior 분산.</li>
<li>FITC (Fully Independent Training Conditional): <span class="math inline">\(\mu(x) \mid \mu(z)\)</span> 의 분산도 추가, diagonal.</li>
<li>VFE (Variational Free Energy, Titsias 2009): variational lower bound 로 <span class="math inline">\(z\)</span> 와 hyperparameter 동시 학습.</li>
</ul>
<p>계산 비용 <span class="math inline">\(O(nm^2)\)</span>, 메모리 <span class="math inline">\(O(nm)\)</span>.</p>
<p><strong>근사 2 — Markov Random Field (Lindgren et al.&nbsp;2011)</strong></p>
<p>특정 Matern kernel 은 SPDE (stochastic PDE) 의 해. SPDE 를 finite element 로 이산화하면 sparse precision matrix → <span class="math inline">\(O(n^{3/2})\)</span> for spatial.</p>
<p><strong>근사 3 — KISS-GP / SKI (Wilson, Nickisch 2015)</strong></p>
<p><span class="math inline">\(K\)</span> 를 grid 위에서 평가 후 Toeplitz 구조 활용. <span class="math inline">\(O(n)\)</span> 메모리 + 선형 시간 행렬-벡터 곱.</p>
<p><strong>근사 4 — Reduced rank</strong></p>
<p>Squared exponential kernel 의 Mercer 분해를 <span class="math inline">\(m\)</span> 항에서 truncate. <span class="math inline">\(O(nm^2)\)</span>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
어떤 근사를 언제 쓰는가
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><span class="math inline">\(n \leq 1000\)</span>: 풀 GP, 수치 안정성만 신경.</li>
<li><span class="math inline">\(1000 &lt; n \leq 10000\)</span>: Sparse GP (inducing points). PyMC, GPyTorch.</li>
<li><span class="math inline">\(10000 &lt; n\)</span> + 1-3D 입력: KISS-GP, MRF.</li>
<li><span class="math inline">\(10000 &lt; n\)</span> + 고차원: Variational SGP (Hensman et al.&nbsp;2013) — stochastic gradient.</li>
<li>시계열 1D: state-space GP (Sarkka et al.&nbsp;2013) — <span class="math inline">\(O(n)\)</span>.</li>
</ul>
</div>
</div>
</section>
<section id="anisotropic-ard-의-변수-선택" class="level3" data-number="2.10">
<h3 data-number="2.10" class="anchored" data-anchor-id="anisotropic-ard-의-변수-선택"><span class="header-section-number">2.10</span> Anisotropic ARD 의 변수 선택</h3>
<p>다변량 입력의 anisotropic squared exponential:</p>
<p><span class="math display">\[
k(x, x') = \tau^2 \exp\left( -\sum_{j=1}^p \frac{(x_j - x_j')^2}{2\ell_j^2} \right)
\]</span></p>
<p>각 <span class="math inline">\(\ell_j\)</span> 가 hyperparameter. 로그-스케일에서 <span class="math inline">\(\log \ell_j\)</span> 의 marginal posterior 가 큰 양수에 집중되면 <span class="math inline">\(j\)</span> 번째 변수의 영향이 미미하다고 판단.</p>
<p><strong>Hyperprior</strong>: half-Cauchy(0, 1) 또는 half-<span class="math inline">\(t_4\)</span>(0, 1) 이 robust 한 선택. Inverse Gamma 는 아래쪽 꼬리가 너무 가벼워 <span class="math inline">\(\ell_j \to 0\)</span> 발산을 잘 막지 못한다.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — ARD 가 spike-and-slab 의 연속 대안인 이유
</div>
</div>
<div class="callout-body-container callout-body">
<p>Ch.20 의 spike-and-slab 은 변수를 정확히 0 으로 보내는 0-1 결정. ARD 는 <strong>연속적인 length scale 로 변수의 “유효성”</strong> 을 표현한다.</p>
<ul>
<li><span class="math inline">\(\ell_j \approx 1\)</span> (입력 표준화 후): 적극적으로 사용.</li>
<li><span class="math inline">\(\ell_j \gg 1\)</span>: 거의 사용 안 함.</li>
<li><span class="math inline">\(\ell_j \to \infty\)</span>: 완전 탈락.</li>
</ul>
<p>장점: posterior 가 연속이므로 mixing 좋음. 단점: 정확히 0 이 되는 모형 비교 (Bayes factor) 는 어렵다.</p>
</div>
</div>
</section>
</section>
<section id="birthday-데이터-component-가법-분해-완전-분석" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="birthday-데이터-component-가법-분해-완전-분석"><span class="header-section-number">3</span> § 21.2 Birthday 데이터 — Component 가법 분해 완전 분석</h2>
<section id="데이터와-모델링-철학" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="데이터와-모델링-철학"><span class="header-section-number">3.1</span> 데이터와 모델링 철학</h3>
<ul>
<li><strong>데이터</strong>: 1969-01-01 ~ 1988-12-31, 7305 일 (4 윤년 포함). 일별 출생 수 <span class="math inline">\(y_t\)</span>.</li>
<li><strong>목표</strong>: 발렌타인 데이 (예상 과다)·할로윈 (예상 부족) 같은 특별일 효과 + 주간·계절·장기 패턴 분리.</li>
<li><strong>방법</strong>: 각 패턴을 별도 GP component 로 모델링하고 합산.</li>
</ul>
</section>
<section id="component-가법-모델" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="component-가법-모델"><span class="header-section-number">3.2</span> 5-Component 가법 모델</h3>
<p><span class="math display">\[
y_t = f_1(t) + f_2(t) + f_3(t) + f_4(t) + f_5(t) + \epsilon_t
\]</span></p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">component</th>
<th style="text-align: left;">의미</th>
<th style="text-align: left;">Time scale</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(f_1\)</span></td>
<td style="text-align: left;">장기 추세</td>
<td style="text-align: left;">~10 년</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(f_2\)</span></td>
<td style="text-align: left;">단기 비주기 변동</td>
<td style="text-align: left;">~수 개월</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(f_3\)</span></td>
<td style="text-align: left;">주간 패턴 (시간 따라 진화)</td>
<td style="text-align: left;">7 일</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(f_4\)</span></td>
<td style="text-align: left;">연간 계절 (시간 따라 진화)</td>
<td style="text-align: left;">365.25 일</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(f_5\)</span></td>
<td style="text-align: left;">특별일 효과 (Indicator × <span class="math inline">\(\beta\)</span>)</td>
<td style="text-align: left;">점</td>
</tr>
</tbody>
</table>
</section>
<section id="component-1-2-장단기-추세" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="component-1-2-장단기-추세"><span class="header-section-number">3.3</span> Component 1, 2 — 장단기 추세</h3>
<p><strong>장기</strong>:</p>
<p><span class="math display">\[
f_1(t) \sim \text{GP}(0, k_1), \quad k_1(t, t') = \sigma_1^2 \exp\left( -\frac{|t - t'|^2}{2 \ell_1^2} \right), \quad \ell_1 \gg \ell_2
\]</span></p>
<p><strong>단기</strong>:</p>
<p><span class="math display">\[
f_2(t) \sim \text{GP}(0, k_2), \quad k_2(t, t') = \sigma_2^2 \exp\left( -\frac{|t - t'|^2}{2 \ell_2^2} \right), \quad \ell_2 \approx \text{수 개월}
\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — 두 squared exponential 의 분리
</div>
</div>
<div class="callout-body-container callout-body">
<p>같은 형태의 kernel 을 <strong>다른 length scale 로 두 개</strong> 두는 이유: GP 는 scale 정보를 자동 분리한다.</p>
<p>데이터에 “10 년 단위 추세 + 분기 단위 변동” 이 모두 있으면, <span class="math inline">\(\ell_1 \approx 10\)</span> 년·<span class="math inline">\(\ell_2 \approx 1\)</span> 분기 hyperprior 를 주면 적합 결과에서 <span class="math inline">\(f_1\)</span> 은 부드러운 곡선·<span class="math inline">\(f_2\)</span> 는 거친 변동으로 자연 분리.</p>
<p><strong>핵심</strong>: 사후 분리는 hyperprior 가 두 length scale 을 충분히 떨어뜨려 둔 덕분. Identifiability 위해 hyperprior 가 중요.</p>
</div>
</div>
</section>
<section id="component-3-주간-quasi-periodic-kernel" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="component-3-주간-quasi-periodic-kernel"><span class="header-section-number">3.4</span> Component 3 — 주간 quasi-periodic kernel</h3>
<p><span class="math display">\[
f_3(t) \sim \text{GP}(0, k_3), \quad k_3(t, t') = \sigma_3^2 \underbrace{\exp\left( -\frac{2\sin^2\bigl(\pi(t-t')/7\bigr)}{\ell_{3,1}^2} \right)}_{\text{periodic}} \cdot \underbrace{\exp\left( -\frac{|t-t'|^2}{2\ell_{3,2}^2} \right)}_{\text{evolution}}
\]</span></p>
<section id="periodic-kernel-의-사상-유도" class="level4" data-number="3.4.1">
<h4 data-number="3.4.1" class="anchored" data-anchor-id="periodic-kernel-의-사상-유도"><span class="header-section-number">3.4.1</span> Periodic Kernel 의 사상 유도</h4>
<p>원래의 squared exponential 은 1D 입력 <span class="math inline">\(t\)</span> 의 거리 <span class="math inline">\(|t - t'|^2\)</span> 에 의존. 이를 <strong>원형 위의 거리</strong> 로 바꾸면 주기성 표현.</p>
<p>원형 위의 두 점을 <span class="math inline">\(\bigl(\cos(2\pi t/p), \sin(2\pi t/p)\bigr)\)</span> 로 사상. 이 두 점 사이 chord 거리:</p>
<p><span class="math display">\[
\bigl\| \bigl(\cos(2\pi t/p) - \cos(2\pi t'/p),\ \sin(2\pi t/p) - \sin(2\pi t'/p)\bigr) \bigr\|^2 = 2 - 2\cos\bigl(2\pi(t-t')/p\bigr) = 4\sin^2\bigl(\pi(t-t')/p\bigr)
\]</span></p>
<p>이 chord 거리를 squared exponential 에 대입:</p>
<p><span class="math display">\[
k_{\text{periodic}}(t, t') = \sigma^2 \exp\left( -\frac{4\sin^2\bigl(\pi(t-t')/p\bigr)}{2\ell^2} \right) = \sigma^2 \exp\left( -\frac{2\sin^2\bigl(\pi(t-t')/p\bigr)}{\ell^2} \right)
\]</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — 원형 사상이 한 일
</div>
</div>
<div class="callout-body-container callout-body">
<p>1D 시간을 <strong>원형으로 감싸</strong> 같은 요일 (월요일끼리, 일요일끼리) 이 원형에서 같은 점에 위치하도록 한다. 그 후 squared exponential 적용하면 같은 요일 끼리는 거리 0 → 같은 함수 값.</p>
<p><span class="math inline">\(\ell\)</span> 은 <strong>한 주 안에서의 smoothness</strong>: 작으면 요일별 효과가 sharp 하게 다름, 크면 인접 요일 비슷.</p>
</div>
</div>
</section>
<section id="quasi-periodic-곱-시간에-따른-진화" class="level4" data-number="3.4.2">
<h4 data-number="3.4.2" class="anchored" data-anchor-id="quasi-periodic-곱-시간에-따른-진화"><span class="header-section-number">3.4.2</span> Quasi-periodic 곱 — 시간에 따른 진화</h4>
<p><span class="math inline">\(k_3 = k_{\text{periodic}} \cdot k_{\text{evolution}}\)</span> 의 의미: 두 시점의 함수 값이 비슷하려면</p>
<ul>
<li>같은 요일이고 (periodic 조건),</li>
<li>시점이 가까워야 한다 (evolution 조건).</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Birthday 데이터에서 quasi-periodic 가 잡는 것
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>순수 periodic kernel</strong>: 1969 년 월요일과 1988 년 월요일을 같은 효과로 본다.</p>
<p><strong>Quasi-periodic</strong> (<span class="math inline">\(k_{\text{periodic}} \cdot k_{\text{evolution}}\)</span>): 1969 년 월요일과 1969 년 화요일은 다른 요일이지만 시점이 가까워 약간 비슷. 1969 년 월요일과 1988 년 월요일은 같은 요일이지만 시점이 멀어 다를 수 있음.</p>
<p>→ <strong>시간에 따른 요일 효과의 변화</strong> 를 잡는다 (예: c-section 비율 증가로 평일/주말 차이 커짐).</p>
</div>
</div>
</section>
</section>
<section id="component-4-연간-계절" class="level3" data-number="3.5">
<h3 data-number="3.5" class="anchored" data-anchor-id="component-4-연간-계절"><span class="header-section-number">3.5</span> Component 4 — 연간 계절</h3>
<p><span class="math display">\[
f_4(t) \sim \text{GP}(0, k_4), \quad k_4(t, t') = \sigma_4^2 \exp\left( -\frac{2\sin^2\bigl(\pi(s-s')/365.25\bigr)}{\ell_{4,1}^2} \right) \exp\left( -\frac{|s-s'|^2}{2\ell_{4,2}^2} \right)
\]</span></p>
<p><span class="math inline">\(s = s(t) = t \bmod 365.25\)</span>. 4 년마다 윤년 보정을 위해 365.25.</p>
<p>같은 quasi-periodic 구조, 다른 주기. <strong>여름의 출생률 vs 겨울의 출생률</strong> 같은 패턴이 시간에 따라 진화하는 것을 잡는다.</p>
</section>
<section id="component-5-특별일" class="level3" data-number="3.6">
<h3 data-number="3.6" class="anchored" data-anchor-id="component-5-특별일"><span class="header-section-number">3.6</span> Component 5 — 특별일</h3>
<p><span class="math display">\[
f_5(t) = I_{\text{special day}}(t) \beta_a + I_{\text{weekend}}(t) I_{\text{special day}}(t) \beta_b
\]</span></p>
<ul>
<li><span class="math inline">\(I_{\text{special day}}(t)\)</span> = 13 개 특별일 (New Year’s, Valentine’s, Leap Day, April Fool’s, Independence, Halloween, Christmas, Christmas-NewYear 사이) 의 indicator vector.</li>
<li><span class="math inline">\(\beta_a\)</span> = 평일 효과, <span class="math inline">\(\beta_b\)</span> = 주말 추가 효과.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — 왜 GP 가 아닌 indicator 인가
</div>
</div>
<div class="callout-body-container callout-body">
<p>특별일은 시간 구조가 아닌 <strong>이산 점 사건</strong>. GP 의 매끄러움 가정이 맞지 않는다. 따라서 별도 indicator + linear 모형으로 분리.</p>
<p>이 component 는 <strong>GP 가법 모델이 GP 만으로 구성될 필요가 없음</strong> 을 보여준다. 도메인에 맞는 component 구조를 자유롭게 결합.</p>
</div>
</div>
</section>
<section id="식-21.2-component-wise-prediction" class="level3" data-number="3.7">
<h3 data-number="3.7" class="anchored" data-anchor-id="식-21.2-component-wise-prediction"><span class="header-section-number">3.7</span> 식 (21.2) — Component-wise Prediction</h3>
<p>훈련 후, 한 component 만 떼어 그 부분의 사후 평균을 계산할 수 있다.</p>
<p><span class="math display">\[
E(\widetilde f_1) = K_1(\widetilde x, x) \bigl(K(x, x) + \sigma^2 I\bigr)^{-1} y \quad (21.2)
\]</span></p>
<p>핵심: <span class="math inline">\(K_1\)</span> 만 사용하지만 inverse 는 <strong>전체 <span class="math inline">\(K = K_1 + \cdots + K_5\)</span></strong> 사용.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
왜 이렇게 동작하는가
</div>
</div>
<div class="callout-body-container callout-body">
<p>GP 합 <span class="math inline">\(\mu = f_1 + f_2 + \cdots + f_5\)</span> 에서 <span class="math inline">\(f_1\)</span> 의 사후 평균은:</p>
<p><span class="math display">\[
E(f_1 \mid y) = \text{cov}(f_1, y) \text{Var}(y)^{-1} y = K_1 (K + \sigma^2 I)^{-1} y
\]</span></p>
<ul>
<li><span class="math inline">\(\text{cov}(f_1, y) = \text{cov}(f_1, f_1 + f_2 + \cdots + \epsilon) = \text{Var}(f_1) = K_1\)</span> (component 들이 독립).</li>
<li><span class="math inline">\(\text{Var}(y) = K_1 + K_2 + \cdots + \sigma^2 I = K + \sigma^2 I\)</span>.</li>
</ul>
<p>→ <strong>Component-wise 분해는 multivariate Gaussian 의 직접 결과</strong>.</p>
</div>
</div>
</section>
<section id="improved-8-component-모델" class="level3" data-number="3.8">
<h3 data-number="3.8" class="anchored" data-anchor-id="improved-8-component-모델"><span class="header-section-number">3.8</span> Improved 8-Component 모델</h3>
<p>저자들은 5-component 모델 결과를 보고 잔차의 자기상관 + 특별일 외의 day-of-year 효과 발견. 8-component 로 확장:</p>
<table class="table">
<colgroup>
<col style="width: 41%">
<col style="width: 58%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">component</th>
<th style="text-align: left;">추가/변경</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(f_5\)</span> → 평일 day-of-year periodic</td>
<td style="text-align: left;">모든 day 에 효과 허용</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(f_6\)</span> → 주말 day-of-year periodic</td>
<td style="text-align: left;">평일과 분리</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(f_7\)</span> → 4 개 floating holiday (Memorial, Labor, Thanksgiving 등) indicator</td>
<td style="text-align: left;">이동 휴일</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(f_8\)</span> → 매우 짧은 length scale 비주기</td>
<td style="text-align: left;">잔차 자기상관 흡수</td>
</tr>
</tbody>
</table>
<p><strong>LOO-CV lppd</strong>: 5-component <span class="math inline">\(= 2074\)</span> → 8-component <span class="math inline">\(= 2477\)</span>. <strong>명백한 개선</strong>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — GP 모델 빌딩의 일반 원칙
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><strong>단순한 component 부터 시작</strong>: 추세 + 노이즈.</li>
<li><strong>잔차 점검</strong>: 자기상관·주기·outlier?</li>
<li><strong>Component 추가</strong>: 잡지 못한 패턴마다 별도 GP component.</li>
<li><strong>LOO-CV lppd 비교</strong>: 추가 효과 정량화.</li>
<li><strong>반복</strong>.</li>
</ol>
<p>핵심: GP 는 <strong>선형 추가 (additive)</strong> 이 자연스러우므로 lego 처럼 부품을 조립할 수 있다. 각 부품의 hyperprior 가 time scale 을 잘 분리해 두면 mixing 도 좋다.</p>
</div>
</div>
</section>
</section>
<section id="latent-gaussian-process-models" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="latent-gaussian-process-models"><span class="header-section-number">4</span> § 21.3 Latent Gaussian Process Models</h2>
<section id="동기-비가우시안-우도" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="동기-비가우시안-우도"><span class="header-section-number">4.1</span> 동기 — 비가우시안 우도</h3>
<p>GP 는 함수 <span class="math inline">\(\mu\)</span> 의 사전분포. 그러나 데이터가 항상 <span class="math inline">\(y \sim N(\mu, \sigma^2)\)</span> 형태는 아니다.</p>
<table class="table">
<colgroup>
<col style="width: 31%">
<col style="width: 36%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">데이터 유형</th>
<th style="text-align: left;">우도</th>
<th style="text-align: left;">Link</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Binary</td>
<td style="text-align: left;"><span class="math inline">\(y \sim \text{Bernoulli}(p)\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\text{logit}(p) = f\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">Count</td>
<td style="text-align: left;"><span class="math inline">\(y \sim \text{Poisson}(\lambda)\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\log \lambda = f\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;">생존 시간</td>
<td style="text-align: left;"><span class="math inline">\(y \sim \text{Weibull}/\text{log-logistic}\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\log(\text{scale}) = f\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">Multi-class</td>
<td style="text-align: left;"><span class="math inline">\(y \sim \text{Categorical}(\pi)\)</span></td>
<td style="text-align: left;">softmax of <span class="math inline">\(f_k\)</span></td>
</tr>
</tbody>
</table>
<p>이 경우 <strong>latent function <span class="math inline">\(f\)</span></strong> 에 GP prior 를 두고, 우도를 link 로 결정.</p>
</section>
<section id="latent-gp-모델-구조" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="latent-gp-모델-구조"><span class="header-section-number">4.2</span> Latent GP 모델 구조</h3>
<p><span class="math display">\[
\begin{aligned}
f &amp;\sim \text{GP}(0, k) \\
y_i \mid f, \phi &amp;\sim p(y_i \mid f(x_i), \phi)
\end{aligned}
\]</span></p>
<p><span class="math inline">\(\phi\)</span> = 추가 우도 parameter (예: Weibull shape).</p>
<p>조건부 사후:</p>
<p><span class="math display">\[
p(f \mid x, y, \theta, \phi) \propto p(y \mid f, \phi) \cdot p(f \mid x, \theta)
\]</span></p>
<ul>
<li><span class="math inline">\(p(f \mid x, \theta) = N(0, K(x, x))\)</span> — GP prior.</li>
<li><span class="math inline">\(p(y \mid f, \phi)\)</span> — 비가우시안 우도.</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
핵심 어려움
</div>
</div>
<div class="callout-body-container callout-body">
<p>가우시안 우도에서는 적합도 = 정규 (식 21.1). 비가우시안에서는 <strong>곱이 정규가 아님</strong> → <span class="math inline">\(f\)</span> 적분 소거 불가능 → marginal likelihood 가 닫힌 형태로 안 나옴.</p>
<p>해결: <strong>근사</strong>. (1) Laplace, (2) EP, (3) VI, (4) MCMC.</p>
</div>
</div>
</section>
<section id="laplace-근사-식-21.3-유도" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="laplace-근사-식-21.3-유도"><span class="header-section-number">4.3</span> Laplace 근사 — 식 (21.3) 유도</h3>
<section id="step-1-사후를-mode-중심-정규로-근사" class="level4" data-number="4.3.1">
<h4 data-number="4.3.1" class="anchored" data-anchor-id="step-1-사후를-mode-중심-정규로-근사"><span class="header-section-number">4.3.1</span> Step 1 — 사후를 mode 중심 정규로 근사</h4>
<p><span class="math display">\[
p(f \mid x, y, \theta, \phi) \approx N(f \mid \widehat f, \Sigma)
\]</span></p>
<p><span class="math inline">\(\widehat f\)</span> = 사후 mode = <span class="math inline">\(\arg\max_f \log p(f \mid x, y, \theta, \phi)\)</span>.</p>
<p><span class="math inline">\(\Sigma\)</span> = log posterior 의 mode 에서 음의 Hessian 의 inverse.</p>
</section>
<section id="step-2-hessian-계산" class="level4" data-number="4.3.2">
<h4 data-number="4.3.2" class="anchored" data-anchor-id="step-2-hessian-계산"><span class="header-section-number">4.3.2</span> Step 2 — Hessian 계산</h4>
<p>Log posterior:</p>
<p><span class="math display">\[
\log p(f \mid \cdot) = \log p(y \mid f, \phi) - \frac{1}{2} f^T K^{-1} f + \text{const}
\]</span></p>
<p>미분:</p>
<p><span class="math display">\[
\nabla_f \log p = \nabla_f \log p(y \mid f, \phi) - K^{-1} f
\]</span></p>
<p>Hessian:</p>
<p><span class="math display">\[
\nabla^2_f \log p = \nabla^2_f \log p(y \mid f, \phi) - K^{-1} = -W - K^{-1}
\]</span></p>
<p>where <span class="math inline">\(W\)</span> = diagonal matrix with <span class="math inline">\(W_{ii} = -\partial^2 \log p(y_i \mid f_i, \phi) / \partial f_i^2 \mid_{f_i = \widehat f_i}\)</span>.</p>
<p>(우도가 <span class="math inline">\(f_i\)</span> 들에 대해 conditional independent 이므로 <span class="math inline">\(W\)</span> 가 diagonal — 일반적인 GLM 조건.)</p>
<p>따라서</p>
<p><span class="math display">\[
\Sigma^{-1} = K^{-1} + W
\]</span></p>
<p>이 식이 본문의 <span class="math inline">\(\Sigma^{-1} = K(x, x) + W\)</span> 와 다르게 보이지만, 사실 같다 — 문헌 표기 차이로, 식 (21.3) 의 <span class="math inline">\(K(x, x)\)</span> 자리에 <span class="math inline">\(K^{-1}\)</span> 이 들어가야 한다 (혼동 주의).</p>
</section>
<section id="step-3-marginal-likelihood-laplace-근사" class="level4" data-number="4.3.3">
<h4 data-number="4.3.3" class="anchored" data-anchor-id="step-3-marginal-likelihood-laplace-근사"><span class="header-section-number">4.3.3</span> Step 3 — Marginal likelihood Laplace 근사</h4>
<p><span class="math inline">\(\log p(y \mid x, \theta, \phi) = \log \int p(y \mid f, \phi) p(f \mid x, \theta) df\)</span></p>
<p>Laplace’s method (Section 13.3 of BDA):</p>
<p><span class="math display">\[
\log p(y \mid x, \theta, \phi) \approx \log p(y \mid \widehat f, \phi) + \log p(\widehat f \mid x, \theta) + \frac{n}{2} \log(2\pi) - \frac{1}{2} \log |\Sigma^{-1}|
\]</span></p>
<p>대입:</p>
<p><span class="math display">\[
\log p(\widehat f \mid x, \theta) = -\frac{n}{2} \log(2\pi) - \frac{1}{2} \log |K| - \frac{1}{2} \widehat f^T K^{-1} \widehat f
\]</span></p>
<p><span class="math display">\[
\log |\Sigma^{-1}| = \log |K^{-1} + W| = \log |K^{-1}| + \log |I + K W| = -\log|K| + \log|I + W^{1/2} K W^{1/2}|
\]</span></p>
<p>(둘째 등호는 <span class="math inline">\(\det(A + B) / \det(A) = \det(I + A^{-1}B)\)</span>, 셋째는 <span class="math inline">\(W^{1/2}\)</span> 를 양옆에 곱해 sym 형태로.)</p>
<p>조합:</p>
<p><span class="math display">\[
\log p(y \mid x, \theta, \phi) \approx \log p(y \mid \widehat f, \phi) - \frac{1}{2} \widehat f^T K^{-1} \widehat f - \frac{1}{2} \log |B| \quad (21.3)
\]</span></p>
<p>where <span class="math inline">\(|B| = |I + W^{1/2} K(x, x) W^{1/2}|\)</span>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
식 (21.3) 의 세 항 — 가우시안 (21.1) 과 평행
</div>
</div>
<div class="callout-body-container callout-body">
<table class="table">
<colgroup>
<col style="width: 22%">
<col style="width: 38%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">항</th>
<th style="text-align: left;">식 (21.1) (가우시안)</th>
<th style="text-align: left;">식 (21.3) (latent GP)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">데이터 적합도</td>
<td style="text-align: left;"><span class="math inline">\(-\frac{1}{2} y^T (K + \sigma^2 I)^{-1} y\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\log p(y \mid \widehat f, \phi)\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Prior penalty</td>
<td style="text-align: left;">(covariance 안에 흡수)</td>
<td style="text-align: left;"><span class="math inline">\(-\frac{1}{2} \widehat f^T K^{-1} \widehat f\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">복잡도</td>
<td style="text-align: left;"><span class="math inline">\(-\frac{1}{2} \log|K + \sigma^2 I|\)</span></td>
<td style="text-align: left;"><span class="math inline">\(-\frac{1}{2} \log|B|\)</span></td>
</tr>
</tbody>
</table>
<p>평행 구조가 명확하다. <strong>Laplace 가 비가우시안 우도를 가우시안화 했을 때 식 (21.1) 의 형태로 회귀</strong>.</p>
<p>근사 정확도:</p>
<ul>
<li>우도가 거의 정규 (예: Poisson with large counts) → Laplace 매우 정확.</li>
<li>우도가 매우 비대칭 (예: Bernoulli with small <span class="math inline">\(p\)</span>) → Laplace 부정확, EP 권장.</li>
</ul>
</div>
</div>
</section>
</section>
<section id="ep-와-vi-laplace-가-부족할-때" class="level3" data-number="4.4">
<h3 data-number="4.4" class="anchored" data-anchor-id="ep-와-vi-laplace-가-부족할-때"><span class="header-section-number">4.4</span> EP 와 VI — Laplace 가 부족할 때</h3>
<p><strong>Expectation Propagation</strong> (Minka 2001):</p>
<p>각 사이트 <span class="math inline">\(i\)</span> 의 우도를 normal 로 근사 (<span class="math inline">\(\widetilde p_i(f_i) = N(f_i \mid \widetilde m_i, \widetilde s_i^2)\)</span>). EP 는 KL projection 을 통해 이 근사를 반복 갱신.</p>
<ul>
<li>장점: Laplace 보다 정확 (특히 logistic).</li>
<li>단점: 발산 가능, 느림.</li>
</ul>
<p><strong>Variational Inference</strong> (Section 13.7 of BDA):</p>
<p><span class="math inline">\(q(f) = N(f \mid m, S)\)</span> 또는 <span class="math inline">\(q(f) = \prod_i q_i(f_i)\)</span> (mean-field). KL<span class="math inline">\((q \| p)\)</span> 최소화.</p>
<ul>
<li>장점: 빠름, 발산 없음.</li>
<li>단점: 사후 분산 underestimate (mean-field 의 일반 한계).</li>
</ul>
</section>
<section id="leukemia-생존-분석-latent-gp-의-위력" class="level3" data-number="4.5">
<h3 data-number="4.5" class="anchored" data-anchor-id="leukemia-생존-분석-latent-gp-의-위력"><span class="header-section-number">4.5</span> Leukemia 생존 분석 — Latent GP 의 위력</h3>
<section id="데이터" class="level4" data-number="4.5.1">
<h4 data-number="4.5.1" class="anchored" data-anchor-id="데이터"><span class="header-section-number">4.5.1</span> 데이터</h4>
<ul>
<li>1043 명 AML (acute myeloid leukemia) 환자, 1982~1998 영국 North West Leukemia Register.</li>
<li>우측 절단 (right censoring) 16%.</li>
<li>Predictor 4: age, sex, log WBC (white blood cell count), Townsend deprivation index (TDI).</li>
</ul>
</section>
<section id="모델" class="level4" data-number="4.5.2">
<h4 data-number="4.5.2" class="anchored" data-anchor-id="모델"><span class="header-section-number">4.5.2</span> 모델</h4>
<p><span class="math display">\[
y_i \mid f_i, r \sim p(y_i \mid f_i, r)_{\text{log-logistic}}
\]</span></p>
<p>Log-logistic 우도 (right censoring 포함):</p>
<p><span class="math display">\[
p(y \mid \cdot) = \prod_{i=1}^n \left( \frac{r y^{r-1}}{\exp(f(X_i))^r} \right)^{1 - z_i} \left( 1 + \left(\frac{y}{\exp(f(X_i))}\right)^r \right)^{z_i - 2}
\]</span></p>
<p><span class="math inline">\(z_i \in \{0, 1\}\)</span> = censoring indicator. <span class="math inline">\(r\)</span> = shape parameter.</p>
<p><strong>Latent function</strong>:</p>
<p><span class="math display">\[
f(X_i) = \alpha + X_i \beta + \mu(X_i), \qquad \mu \sim \text{GP}(0, k_{\text{aniso}})
\]</span></p>
<p>선형 mean 베이스 + GP 비선형 보정. ARD anisotropic kernel.</p>
<p><strong>Hyperpriors</strong>:</p>
<ul>
<li><span class="math inline">\(\alpha \sim N(0, \sigma_\alpha^2)\)</span>, <span class="math inline">\(\beta \sim N(0, \sigma_\beta^2)\)</span>.</li>
<li><span class="math inline">\(\sigma_\alpha^2, \sigma_\beta^2, \sigma_g^2 \sim \text{Inv-}\chi^2(1, 1)\)</span>.</li>
<li><span class="math inline">\(\ell_j \sim \text{Cauchy}^+(0, 1)\)</span>.</li>
<li><span class="math inline">\(\log r\)</span> uniform.</li>
</ul>
</section>
<section id="추론" class="level4" data-number="4.5.3">
<h4 data-number="4.5.3" class="anchored" data-anchor-id="추론"><span class="header-section-number">4.5.3</span> 추론</h4>
<ul>
<li>Laplace 로 latent 적분 소거.</li>
<li>CCD integration 으로 hyperparameter 적분 소거.</li>
<li>EP 도 시도했으나 약 10 배 느림, 결과 유사.</li>
</ul>
</section>
<section id="결과" class="level4" data-number="4.5.4">
<h4 data-number="4.5.4" class="anchored" data-anchor-id="결과"><span class="header-section-number">4.5.4</span> 결과</h4>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">모델</th>
<th style="text-align: center;">LOO-CV lppd</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Linear 만 (상수 + <span class="math inline">\(X_i \beta\)</span>)</td>
<td style="text-align: center;"><span class="math inline">\(-1662\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">+ GP 비선형</td>
<td style="text-align: center;"><span class="math inline">\(-1629\)</span></td>
</tr>
</tbody>
</table>
<p><strong>33 단위 개선</strong>. 절대값으로는 작아 보이지만, 데이터 1043 점이므로 점당 0.03 단위 개선 — 통계적으로 명확.</p>
</section>
<section id="발견된-패턴-figure-21.6" class="level4" data-number="4.5.5">
<h4 data-number="4.5.5" class="anchored" data-anchor-id="발견된-패턴-figure-21.6"><span class="header-section-number">4.5.5</span> 발견된 패턴 (Figure 21.6)</h4>
<ul>
<li><strong>Age</strong>: 매우 어린 (소수의 청소년 백혈병) 과 노년에서 위험 증가, 30~50 대에 평탄 — 비선형.</li>
<li><strong>WBC</strong>: 매우 낮은 WBC 에서도 위험 증가 — 이전 (log 변환 안 한) 분석에서는 못 잡음.</li>
<li><strong>TDI</strong>: 단조 증가 (deprivation 클수록 위험 큼).</li>
<li><strong>WBC × TDI 상호작용</strong>: TDI 높은 그룹에서 WBC 효과가 다름.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — GP latent 가 발견을 만든다
</div>
</div>
<div class="callout-body-container callout-body">
<p>전통 Cox + linear: WBC 와 TDI 의 추가 항 + (필요시) <span class="math inline">\(X_{\text{WBC}} \times X_{\text{TDI}}\)</span> 명시적 상호작용 항. 그러나 도메인 지식 없이 어떤 상호작용을 넣을지 미리 결정하기 어렵다.</p>
<p>GP latent + ARD: <strong>자동으로 모든 상호작용을 표현</strong> (kernel 이 결합 입력 함수). Length scale 이 데이터로부터 학습 → 어떤 변수 조합이 중요한지 자동 발견.</p>
<p>단, “자동 발견” 의 대가는 (1) 해석이 어려움 (단일 효과·상호작용 분리가 plot 으로만), (2) 외삽 위험.</p>
</div>
</div>
</section>
</section>
</section>
<section id="핵심-수식-유도-부록" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="핵심-수식-유도-부록"><span class="header-section-number">5</span> 핵심 수식 유도 부록</h2>
<section id="다변량-정규-조건부-공식-schur-complement" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="다변량-정규-조건부-공식-schur-complement"><span class="header-section-number">5.1</span> 다변량 정규 조건부 공식 — Schur Complement</h3>
<p><span class="math display">\[
\Sigma = \begin{pmatrix} \Sigma_{UU} &amp; \Sigma_{UV} \\ \Sigma_{VU} &amp; \Sigma_{VV} \end{pmatrix}, \qquad \Sigma^{-1} = \begin{pmatrix} A &amp; B \\ C &amp; D \end{pmatrix}
\]</span></p>
<p>Block matrix inversion (Schur complement 정리):</p>
<p><span class="math display">\[
A = (\Sigma_{UU} - \Sigma_{UV} \Sigma_{VV}^{-1} \Sigma_{VU})^{-1}, \qquad D = (\Sigma_{VV} - \Sigma_{VU} \Sigma_{UU}^{-1} \Sigma_{UV})^{-1}
\]</span></p>
<p><span class="math inline">\(D^{-1} = \Sigma_{VV} - \Sigma_{VU} \Sigma_{UU}^{-1} \Sigma_{UV}\)</span> 이 바로 <strong>사후 분산</strong>.</p>
<p>조건부 평균은 정규의 quadratic form 을 <span class="math inline">\(V\)</span> 에 대해 최소화하면 얻어진다 (BDA Ch.3 § 3.5 유도).</p>
</section>
<section id="marginal-likelihood-의-또다른-형태" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="marginal-likelihood-의-또다른-형태"><span class="header-section-number">5.2</span> Marginal Likelihood 의 또다른 형태</h3>
<p><span class="math inline">\(\alpha = (K + \sigma^2 I)^{-1} y\)</span> 로 두면</p>
<p><span class="math display">\[
y^T (K + \sigma^2 I)^{-1} y = y^T \alpha
\]</span></p>
<p>Cholesky <span class="math inline">\(K + \sigma^2 I = LL^T\)</span> 후</p>
<p><span class="math display">\[
\log |K + \sigma^2 I| = 2 \sum_i \log L_{ii}
\]</span></p>
<p>따라서 식 (21.1):</p>
<p><span class="math display">\[
\log p(y) = -\frac{1}{2} y^T \alpha - \sum_i \log L_{ii} - \frac{n}{2} \log(2\pi)
\]</span></p>
<p>이것이 실무 코드에 직접 들어가는 형태.</p>
</section>
<section id="periodic-kernel-의-mercer-분해" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="periodic-kernel-의-mercer-분해"><span class="header-section-number">5.3</span> Periodic Kernel 의 Mercer 분해</h3>
<p><span class="math inline">\(k_{\text{periodic}}(t, t')\)</span> 는 Fourier basis 의 무한 합으로 표현된다.</p>
<p><span class="math display">\[
k_{\text{periodic}}(t, t') = \sum_{k=0}^\infty \lambda_k \cos(2\pi k(t - t')/p)
\]</span></p>
<p><span class="math inline">\(\lambda_k\)</span> = exponentially decaying weights determined by <span class="math inline">\(\ell\)</span>. 이 분해가 <strong>periodic kernel = “Fourier basis 가중합”</strong> 의 정확한 의미.</p>
</section>
</section>
<section id="코드-풀-구현-numpy-pymc-scikit-learn" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="코드-풀-구현-numpy-pymc-scikit-learn"><span class="header-section-number">6</span> 코드 — 풀 구현 (NumPy + PyMC + scikit-learn)</h2>
<section id="section-a-1d-gp-regression-with-marginal-likelihood" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="section-a-1d-gp-regression-with-marginal-likelihood"><span class="header-section-number">6.1</span> Section A — 1D GP regression with marginal likelihood</h3>
<div class="sourceCode" id="cb2"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb2-2"><a href="#cb2-2"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb2-3"><a href="#cb2-3"></a></span>
<span id="cb2-4"><a href="#cb2-4"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">0</span>)</span>
<span id="cb2-5"><a href="#cb2-5"></a></span>
<span id="cb2-6"><a href="#cb2-6"></a><span class="kw">def</span> squared_exp(x1, x2, tau<span class="op">=</span><span class="fl">1.0</span>, ell<span class="op">=</span><span class="fl">1.0</span>):</span>
<span id="cb2-7"><a href="#cb2-7"></a>    d2 <span class="op">=</span> (x1[:, <span class="va">None</span>] <span class="op">-</span> x2[<span class="va">None</span>, :]) <span class="op">**</span> <span class="dv">2</span></span>
<span id="cb2-8"><a href="#cb2-8"></a>    <span class="cf">return</span> tau <span class="op">**</span> <span class="dv">2</span> <span class="op">*</span> np.exp(<span class="op">-</span>d2 <span class="op">/</span> (<span class="dv">2</span> <span class="op">*</span> ell <span class="op">**</span> <span class="dv">2</span>))</span>
<span id="cb2-9"><a href="#cb2-9"></a></span>
<span id="cb2-10"><a href="#cb2-10"></a></span>
<span id="cb2-11"><a href="#cb2-11"></a><span class="co"># simulate data</span></span>
<span id="cb2-12"><a href="#cb2-12"></a>n <span class="op">=</span> <span class="dv">30</span></span>
<span id="cb2-13"><a href="#cb2-13"></a>x <span class="op">=</span> np.sort(rng.uniform(<span class="op">-</span><span class="dv">3</span>, <span class="dv">3</span>, n))</span>
<span id="cb2-14"><a href="#cb2-14"></a>y_true <span class="op">=</span> np.sin(x) <span class="op">+</span> <span class="fl">0.3</span> <span class="op">*</span> np.cos(<span class="dv">3</span> <span class="op">*</span> x)</span>
<span id="cb2-15"><a href="#cb2-15"></a>sigma <span class="op">=</span> <span class="fl">0.15</span></span>
<span id="cb2-16"><a href="#cb2-16"></a>y <span class="op">=</span> y_true <span class="op">+</span> rng.normal(<span class="dv">0</span>, sigma, n)</span>
<span id="cb2-17"><a href="#cb2-17"></a></span>
<span id="cb2-18"><a href="#cb2-18"></a><span class="co"># Cholesky-based posterior + marginal likelihood</span></span>
<span id="cb2-19"><a href="#cb2-19"></a><span class="kw">def</span> gp_posterior(x_train, y_train, x_test, tau, ell, sigma2, jitter<span class="op">=</span><span class="fl">1e-6</span>):</span>
<span id="cb2-20"><a href="#cb2-20"></a>    n <span class="op">=</span> <span class="bu">len</span>(x_train)</span>
<span id="cb2-21"><a href="#cb2-21"></a>    K <span class="op">=</span> squared_exp(x_train, x_train, tau, ell)</span>
<span id="cb2-22"><a href="#cb2-22"></a>    K_s <span class="op">=</span> squared_exp(x_test, x_train, tau, ell)</span>
<span id="cb2-23"><a href="#cb2-23"></a>    K_ss <span class="op">=</span> squared_exp(x_test, x_test, tau, ell)</span>
<span id="cb2-24"><a href="#cb2-24"></a>    L <span class="op">=</span> np.linalg.cholesky(K <span class="op">+</span> (sigma2 <span class="op">+</span> jitter) <span class="op">*</span> np.eye(n))</span>
<span id="cb2-25"><a href="#cb2-25"></a>    alpha <span class="op">=</span> np.linalg.solve(L.T, np.linalg.solve(L, y_train))</span>
<span id="cb2-26"><a href="#cb2-26"></a>    mu_post <span class="op">=</span> K_s <span class="op">@</span> alpha</span>
<span id="cb2-27"><a href="#cb2-27"></a>    v <span class="op">=</span> np.linalg.solve(L, K_s.T)</span>
<span id="cb2-28"><a href="#cb2-28"></a>    cov_post <span class="op">=</span> K_ss <span class="op">-</span> v.T <span class="op">@</span> v</span>
<span id="cb2-29"><a href="#cb2-29"></a>    log_ml <span class="op">=</span> (</span>
<span id="cb2-30"><a href="#cb2-30"></a>        <span class="op">-</span><span class="fl">0.5</span> <span class="op">*</span> y_train <span class="op">@</span> alpha</span>
<span id="cb2-31"><a href="#cb2-31"></a>        <span class="op">-</span> np.<span class="bu">sum</span>(np.log(np.diag(L)))</span>
<span id="cb2-32"><a href="#cb2-32"></a>        <span class="op">-</span> <span class="fl">0.5</span> <span class="op">*</span> n <span class="op">*</span> np.log(<span class="dv">2</span> <span class="op">*</span> np.pi)</span>
<span id="cb2-33"><a href="#cb2-33"></a>    )</span>
<span id="cb2-34"><a href="#cb2-34"></a>    <span class="cf">return</span> mu_post, cov_post, log_ml</span>
<span id="cb2-35"><a href="#cb2-35"></a></span>
<span id="cb2-36"><a href="#cb2-36"></a></span>
<span id="cb2-37"><a href="#cb2-37"></a>x_test <span class="op">=</span> np.linspace(<span class="op">-</span><span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">200</span>)</span>
<span id="cb2-38"><a href="#cb2-38"></a>mu_post, cov_post, log_ml <span class="op">=</span> gp_posterior(x, y, x_test, tau<span class="op">=</span><span class="fl">1.0</span>, ell<span class="op">=</span><span class="fl">1.0</span>, sigma2<span class="op">=</span><span class="fl">0.04</span>)</span>
<span id="cb2-39"><a href="#cb2-39"></a><span class="bu">print</span>(<span class="ss">f"log marginal likelihood: </span><span class="sc">{</span>log_ml<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="section-b-hyperparameter-optimization-type-ii-mle" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="section-b-hyperparameter-optimization-type-ii-mle"><span class="header-section-number">6.2</span> Section B — Hyperparameter optimization (Type-II MLE)</h3>
<div class="sourceCode" id="cb3"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1"></a><span class="im">from</span> scipy.optimize <span class="im">import</span> minimize</span>
<span id="cb3-2"><a href="#cb3-2"></a></span>
<span id="cb3-3"><a href="#cb3-3"></a><span class="kw">def</span> neg_log_ml(params, x_train, y_train):</span>
<span id="cb3-4"><a href="#cb3-4"></a>    log_tau, log_ell, log_sigma <span class="op">=</span> params</span>
<span id="cb3-5"><a href="#cb3-5"></a>    tau, ell, sigma2 <span class="op">=</span> np.exp(log_tau), np.exp(log_ell), np.exp(<span class="dv">2</span> <span class="op">*</span> log_sigma)</span>
<span id="cb3-6"><a href="#cb3-6"></a>    n <span class="op">=</span> <span class="bu">len</span>(x_train)</span>
<span id="cb3-7"><a href="#cb3-7"></a>    K <span class="op">=</span> squared_exp(x_train, x_train, tau, ell)</span>
<span id="cb3-8"><a href="#cb3-8"></a>    <span class="cf">try</span>:</span>
<span id="cb3-9"><a href="#cb3-9"></a>        L <span class="op">=</span> np.linalg.cholesky(K <span class="op">+</span> sigma2 <span class="op">*</span> np.eye(n) <span class="op">+</span> <span class="fl">1e-6</span> <span class="op">*</span> np.eye(n))</span>
<span id="cb3-10"><a href="#cb3-10"></a>    <span class="cf">except</span> np.linalg.LinAlgError:</span>
<span id="cb3-11"><a href="#cb3-11"></a>        <span class="cf">return</span> <span class="fl">1e10</span></span>
<span id="cb3-12"><a href="#cb3-12"></a>    alpha <span class="op">=</span> np.linalg.solve(L.T, np.linalg.solve(L, y_train))</span>
<span id="cb3-13"><a href="#cb3-13"></a>    <span class="cf">return</span> <span class="fl">0.5</span> <span class="op">*</span> y_train <span class="op">@</span> alpha <span class="op">+</span> np.<span class="bu">sum</span>(np.log(np.diag(L))) <span class="op">+</span> <span class="fl">0.5</span> <span class="op">*</span> n <span class="op">*</span> np.log(<span class="dv">2</span> <span class="op">*</span> np.pi)</span>
<span id="cb3-14"><a href="#cb3-14"></a></span>
<span id="cb3-15"><a href="#cb3-15"></a></span>
<span id="cb3-16"><a href="#cb3-16"></a><span class="co"># optimize starting from log(1), log(1), log(0.5)</span></span>
<span id="cb3-17"><a href="#cb3-17"></a>res <span class="op">=</span> minimize(neg_log_ml, [<span class="dv">0</span>, <span class="dv">0</span>, <span class="op">-</span><span class="fl">0.7</span>], args<span class="op">=</span>(x, y), method<span class="op">=</span><span class="st">"L-BFGS-B"</span>)</span>
<span id="cb3-18"><a href="#cb3-18"></a>tau_hat, ell_hat, sigma_hat <span class="op">=</span> np.exp(res.x[<span class="dv">0</span>]), np.exp(res.x[<span class="dv">1</span>]), np.exp(res.x[<span class="dv">2</span>])</span>
<span id="cb3-19"><a href="#cb3-19"></a><span class="bu">print</span>(<span class="ss">f"learned: tau=</span><span class="sc">{</span>tau_hat<span class="sc">:.3f}</span><span class="ss">, ell=</span><span class="sc">{</span>ell_hat<span class="sc">:.3f}</span><span class="ss">, sigma=</span><span class="sc">{</span>sigma_hat<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb3-20"><a href="#cb3-20"></a><span class="bu">print</span>(<span class="ss">f"true sigma was: </span><span class="sc">{</span>sigma<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="section-c-birthday-style-additive-model-toy" class="level3" data-number="6.3">
<h3 data-number="6.3" class="anchored" data-anchor-id="section-c-birthday-style-additive-model-toy"><span class="header-section-number">6.3</span> Section C — Birthday-style additive model (toy)</h3>
<p>실제 birthday 데이터는 너무 크므로 (n=7305) toy 데이터로 5-component 분해 시연.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1"></a><span class="co"># simulate trend + seasonal + weekly + noise</span></span>
<span id="cb4-2"><a href="#cb4-2"></a>T <span class="op">=</span> <span class="dv">365</span> <span class="op">*</span> <span class="dv">5</span>  <span class="co"># 5 years daily</span></span>
<span id="cb4-3"><a href="#cb4-3"></a>t <span class="op">=</span> np.arange(T)</span>
<span id="cb4-4"><a href="#cb4-4"></a>trend <span class="op">=</span> <span class="fl">0.001</span> <span class="op">*</span> t</span>
<span id="cb4-5"><a href="#cb4-5"></a>seasonal <span class="op">=</span> <span class="fl">0.5</span> <span class="op">*</span> np.sin(<span class="dv">2</span> <span class="op">*</span> np.pi <span class="op">*</span> t <span class="op">/</span> <span class="dv">365</span>)</span>
<span id="cb4-6"><a href="#cb4-6"></a>weekly <span class="op">=</span> <span class="fl">0.3</span> <span class="op">*</span> np.sin(<span class="dv">2</span> <span class="op">*</span> np.pi <span class="op">*</span> t <span class="op">/</span> <span class="dv">7</span>) <span class="op">+</span> <span class="fl">0.2</span> <span class="op">*</span> np.cos(<span class="dv">2</span> <span class="op">*</span> np.pi <span class="op">*</span> t <span class="op">/</span> <span class="dv">7</span>)</span>
<span id="cb4-7"><a href="#cb4-7"></a>noise <span class="op">=</span> rng.normal(<span class="dv">0</span>, <span class="fl">0.1</span>, T)</span>
<span id="cb4-8"><a href="#cb4-8"></a>y_birth <span class="op">=</span> <span class="dv">100</span> <span class="op">+</span> trend <span class="op">+</span> seasonal <span class="op">+</span> weekly <span class="op">+</span> noise</span>
<span id="cb4-9"><a href="#cb4-9"></a></span>
<span id="cb4-10"><a href="#cb4-10"></a><span class="co"># subsample for tractable GP</span></span>
<span id="cb4-11"><a href="#cb4-11"></a>idx <span class="op">=</span> rng.choice(T, <span class="dv">200</span>, replace<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb4-12"><a href="#cb4-12"></a>idx <span class="op">=</span> np.sort(idx)</span>
<span id="cb4-13"><a href="#cb4-13"></a>x_b <span class="op">=</span> t[idx].astype(<span class="bu">float</span>)</span>
<span id="cb4-14"><a href="#cb4-14"></a>y_b <span class="op">=</span> y_birth[idx]</span>
<span id="cb4-15"><a href="#cb4-15"></a></span>
<span id="cb4-16"><a href="#cb4-16"></a><span class="kw">def</span> periodic_kernel(x1, x2, sigma<span class="op">=</span><span class="fl">1.0</span>, ell<span class="op">=</span><span class="fl">1.0</span>, period<span class="op">=</span><span class="dv">7</span>):</span>
<span id="cb4-17"><a href="#cb4-17"></a>    d <span class="op">=</span> x1[:, <span class="va">None</span>] <span class="op">-</span> x2[<span class="va">None</span>, :]</span>
<span id="cb4-18"><a href="#cb4-18"></a>    <span class="cf">return</span> sigma <span class="op">**</span> <span class="dv">2</span> <span class="op">*</span> np.exp(<span class="op">-</span><span class="dv">2</span> <span class="op">*</span> np.sin(np.pi <span class="op">*</span> d <span class="op">/</span> period) <span class="op">**</span> <span class="dv">2</span> <span class="op">/</span> ell <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="cb4-19"><a href="#cb4-19"></a></span>
<span id="cb4-20"><a href="#cb4-20"></a></span>
<span id="cb4-21"><a href="#cb4-21"></a><span class="co"># combined kernel: trend (squared exp, large ell) + seasonal (periodic 365) + weekly (periodic 7)</span></span>
<span id="cb4-22"><a href="#cb4-22"></a><span class="kw">def</span> combined_kernel(x1, x2):</span>
<span id="cb4-23"><a href="#cb4-23"></a>    K_trend <span class="op">=</span> squared_exp(x1, x2, tau<span class="op">=</span><span class="fl">1.0</span>, ell<span class="op">=</span><span class="dv">500</span>)</span>
<span id="cb4-24"><a href="#cb4-24"></a>    K_seasonal <span class="op">=</span> periodic_kernel(x1, x2, sigma<span class="op">=</span><span class="fl">0.7</span>, ell<span class="op">=</span><span class="fl">1.0</span>, period<span class="op">=</span><span class="dv">365</span>)</span>
<span id="cb4-25"><a href="#cb4-25"></a>    K_weekly <span class="op">=</span> periodic_kernel(x1, x2, sigma<span class="op">=</span><span class="fl">0.4</span>, ell<span class="op">=</span><span class="fl">1.0</span>, period<span class="op">=</span><span class="dv">7</span>)</span>
<span id="cb4-26"><a href="#cb4-26"></a>    <span class="cf">return</span> K_trend <span class="op">+</span> K_seasonal <span class="op">+</span> K_weekly</span>
<span id="cb4-27"><a href="#cb4-27"></a></span>
<span id="cb4-28"><a href="#cb4-28"></a></span>
<span id="cb4-29"><a href="#cb4-29"></a>x_b_norm <span class="op">=</span> (x_b <span class="op">-</span> x_b.mean()) <span class="op">/</span> x_b.std()</span>
<span id="cb4-30"><a href="#cb4-30"></a>y_b_norm <span class="op">=</span> (y_b <span class="op">-</span> y_b.mean()) <span class="op">/</span> y_b.std()</span>
<span id="cb4-31"><a href="#cb4-31"></a></span>
<span id="cb4-32"><a href="#cb4-32"></a>K_full <span class="op">=</span> combined_kernel(x_b, x_b)</span>
<span id="cb4-33"><a href="#cb4-33"></a>L <span class="op">=</span> np.linalg.cholesky(K_full <span class="op">+</span> <span class="fl">0.01</span> <span class="op">*</span> np.eye(<span class="bu">len</span>(x_b)) <span class="op">+</span> <span class="fl">1e-6</span> <span class="op">*</span> np.eye(<span class="bu">len</span>(x_b)))</span>
<span id="cb4-34"><a href="#cb4-34"></a>alpha_b <span class="op">=</span> np.linalg.solve(L.T, np.linalg.solve(L, y_b_norm))</span>
<span id="cb4-35"><a href="#cb4-35"></a></span>
<span id="cb4-36"><a href="#cb4-36"></a><span class="co"># component-wise prediction (eq. 21.2)</span></span>
<span id="cb4-37"><a href="#cb4-37"></a>x_pred <span class="op">=</span> np.linspace(<span class="dv">0</span>, T, <span class="dv">500</span>)</span>
<span id="cb4-38"><a href="#cb4-38"></a>K_seasonal_s <span class="op">=</span> periodic_kernel(x_pred, x_b, sigma<span class="op">=</span><span class="fl">0.7</span>, ell<span class="op">=</span><span class="fl">1.0</span>, period<span class="op">=</span><span class="dv">365</span>)</span>
<span id="cb4-39"><a href="#cb4-39"></a>K_weekly_s <span class="op">=</span> periodic_kernel(x_pred, x_b, sigma<span class="op">=</span><span class="fl">0.4</span>, ell<span class="op">=</span><span class="fl">1.0</span>, period<span class="op">=</span><span class="dv">7</span>)</span>
<span id="cb4-40"><a href="#cb4-40"></a>K_trend_s <span class="op">=</span> squared_exp(x_pred, x_b, tau<span class="op">=</span><span class="fl">1.0</span>, ell<span class="op">=</span><span class="dv">500</span>)</span>
<span id="cb4-41"><a href="#cb4-41"></a></span>
<span id="cb4-42"><a href="#cb4-42"></a>mu_seasonal <span class="op">=</span> K_seasonal_s <span class="op">@</span> alpha_b</span>
<span id="cb4-43"><a href="#cb4-43"></a>mu_weekly <span class="op">=</span> K_weekly_s <span class="op">@</span> alpha_b</span>
<span id="cb4-44"><a href="#cb4-44"></a>mu_trend <span class="op">=</span> K_trend_s <span class="op">@</span> alpha_b</span>
<span id="cb4-45"><a href="#cb4-45"></a></span>
<span id="cb4-46"><a href="#cb4-46"></a><span class="bu">print</span>(<span class="ss">f"trend range: [</span><span class="sc">{</span>mu_trend<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.3f}</span><span class="ss">, </span><span class="sc">{</span>mu_trend<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.3f}</span><span class="ss">]"</span>)</span>
<span id="cb4-47"><a href="#cb4-47"></a><span class="bu">print</span>(<span class="ss">f"seasonal range: [</span><span class="sc">{</span>mu_seasonal<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.3f}</span><span class="ss">, </span><span class="sc">{</span>mu_seasonal<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.3f}</span><span class="ss">]"</span>)</span>
<span id="cb4-48"><a href="#cb4-48"></a><span class="bu">print</span>(<span class="ss">f"weekly range: [</span><span class="sc">{</span>mu_weekly<span class="sc">.</span><span class="bu">min</span>()<span class="sc">:.3f}</span><span class="ss">, </span><span class="sc">{</span>mu_weekly<span class="sc">.</span><span class="bu">max</span>()<span class="sc">:.3f}</span><span class="ss">]"</span>)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="section-d-latent-gp-for-binary-classification-pymc" class="level3" data-number="6.4">
<h3 data-number="6.4" class="anchored" data-anchor-id="section-d-latent-gp-for-binary-classification-pymc"><span class="header-section-number">6.4</span> Section D — Latent GP for binary classification (PyMC)</h3>
<div class="sourceCode" id="cb5"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1"></a><span class="im">import</span> pymc <span class="im">as</span> pm</span>
<span id="cb5-2"><a href="#cb5-2"></a></span>
<span id="cb5-3"><a href="#cb5-3"></a><span class="co"># simulate binary data with nonlinear decision function</span></span>
<span id="cb5-4"><a href="#cb5-4"></a>n_bin <span class="op">=</span> <span class="dv">100</span></span>
<span id="cb5-5"><a href="#cb5-5"></a>x_bin <span class="op">=</span> rng.uniform(<span class="op">-</span><span class="dv">3</span>, <span class="dv">3</span>, n_bin).reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb5-6"><a href="#cb5-6"></a>f_true <span class="op">=</span> np.sin(x_bin.ravel()) <span class="op">+</span> <span class="fl">0.5</span> <span class="op">*</span> x_bin.ravel()</span>
<span id="cb5-7"><a href="#cb5-7"></a>p_true <span class="op">=</span> <span class="dv">1</span> <span class="op">/</span> (<span class="dv">1</span> <span class="op">+</span> np.exp(<span class="op">-</span>f_true))</span>
<span id="cb5-8"><a href="#cb5-8"></a>y_bin <span class="op">=</span> rng.binomial(<span class="dv">1</span>, p_true)</span>
<span id="cb5-9"><a href="#cb5-9"></a></span>
<span id="cb5-10"><a href="#cb5-10"></a><span class="cf">with</span> pm.Model() <span class="im">as</span> latent_gp:</span>
<span id="cb5-11"><a href="#cb5-11"></a>    ell <span class="op">=</span> pm.HalfNormal(<span class="st">"ell"</span>, <span class="fl">1.0</span>)</span>
<span id="cb5-12"><a href="#cb5-12"></a>    tau <span class="op">=</span> pm.HalfNormal(<span class="st">"tau"</span>, <span class="fl">1.0</span>)</span>
<span id="cb5-13"><a href="#cb5-13"></a>    cov <span class="op">=</span> tau <span class="op">**</span> <span class="dv">2</span> <span class="op">*</span> pm.gp.cov.ExpQuad(input_dim<span class="op">=</span><span class="dv">1</span>, ls<span class="op">=</span>ell)</span>
<span id="cb5-14"><a href="#cb5-14"></a>    gp <span class="op">=</span> pm.gp.Latent(cov_func<span class="op">=</span>cov)</span>
<span id="cb5-15"><a href="#cb5-15"></a>    f <span class="op">=</span> gp.prior(<span class="st">"f"</span>, X<span class="op">=</span>x_bin)</span>
<span id="cb5-16"><a href="#cb5-16"></a>    p <span class="op">=</span> pm.Deterministic(<span class="st">"p"</span>, pm.math.sigmoid(f))</span>
<span id="cb5-17"><a href="#cb5-17"></a>    pm.Bernoulli(<span class="st">"y"</span>, p<span class="op">=</span>p, observed<span class="op">=</span>y_bin)</span>
<span id="cb5-18"><a href="#cb5-18"></a>    trace <span class="op">=</span> pm.sample(<span class="dv">800</span>, tune<span class="op">=</span><span class="dv">800</span>, target_accept<span class="op">=</span><span class="fl">0.95</span>, chains<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb5-19"><a href="#cb5-19"></a></span>
<span id="cb5-20"><a href="#cb5-20"></a><span class="bu">print</span>(trace.posterior[[<span class="st">"tau"</span>, <span class="st">"ell"</span>]].mean(dim<span class="op">=</span>(<span class="st">"chain"</span>, <span class="st">"draw"</span>)))</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
코드 가이드
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Section A</strong>: GP 사후의 모든 핵심 식을 NumPy 로 직접 구현. Cholesky · alpha · log marginal likelihood 가 한 함수에 정리됨.</li>
<li><strong>Section B</strong>: Hyperparameter 의 Type-II MLE. scipy.optimize 로 negative log marginal likelihood 최소화. Log-scale 로 hyperparameter 를 두면 양수 제약이 자동.</li>
<li><strong>Section C</strong>: Birthday 모델의 toy 버전. Component-wise prediction 식 (21.2) 가 어떻게 작동하는지 확인 (<code>mu_seasonal</code>, <code>mu_weekly</code>, <code>mu_trend</code> 분리).</li>
<li><strong>Section D</strong>: Bernoulli 우도 + GP latent. PyMC 의 <code>gp.Latent</code> 가 sampling 으로 inference (Laplace 도 <code>pm.find_MAP</code> 로 가능).</li>
</ul>
</div>
</div>
</section>
</section>
<section id="실전-체크리스트-21.121.3" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="실전-체크리스트-21.121.3"><span class="header-section-number">7</span> 실전 체크리스트 — § 21.1~21.3</h2>
<p><strong>§ 21.1 GP regression</strong></p>
<ol type="1">
<li><strong>Mean function</strong>: zero vs linear 결정. 외삽 영역이 있다면 linear 권장.</li>
<li><strong>Kernel</strong>: Matern <span class="math inline">\(\nu = 5/2\)</span> default, squared exp 은 매우 부드러운 함수만.</li>
<li><strong>Anisotropic</strong>: 다변량이면 항상 ARD.</li>
<li><strong>Hyperprior</strong>: half-Cauchy / half-<span class="math inline">\(t_4\)</span> for <span class="math inline">\(\ell\)</span>, half-Normal for <span class="math inline">\(\tau\)</span>, <span class="math inline">\(\sigma\)</span>.</li>
<li><strong>계산</strong>: Cholesky + jitter <span class="math inline">\(10^{-6}\)</span>. 직접 inverse 절대 금지.</li>
<li><strong><span class="math inline">\(n\)</span> 따라</strong>: &lt; 1000 풀 GP, <span class="math inline">\(\geq 1000\)</span> sparse / inducing.</li>
</ol>
<p><strong>§ 21.2 Component 가법 모델</strong></p>
<ol start="7" type="1">
<li><strong>시작은 단순하게</strong>: trend + noise 부터.</li>
<li><strong>잔차 점검 후 component 추가</strong>: 자기상관·주기 발견되면 해당 kernel 추가.</li>
<li><strong>Length scale 분리</strong>: 각 component 의 <span class="math inline">\(\ell\)</span> hyperprior 가 충분히 다를 것.</li>
<li><strong>LOO-CV lppd 비교</strong> 로 component 추가 효과 정량화.</li>
<li><strong>Component-wise prediction 식 (21.2)</strong> 으로 사후 시각화.</li>
<li><strong>Periodic + squared exp 곱</strong> 으로 시간에 따라 진화하는 패턴 표현.</li>
</ol>
<p><strong>§ 21.3 Latent GP</strong></p>
<ol start="13" type="1">
<li><strong>우도 결정</strong>: binary → logistic, count → Poisson, 생존 → log-logistic / Weibull.</li>
<li><strong>Latent mean 베이스</strong>: <span class="math inline">\(\alpha + X\beta\)</span> 로 GP 외삽 위험 완화.</li>
<li><strong>추론 방법 선택</strong>:
<ul>
<li>우도가 거의 정규: Laplace.</li>
<li>우도가 비대칭 (small <span class="math inline">\(p\)</span> logistic): EP.</li>
<li>빠른 결과 필요: VI.</li>
<li>정확도 최우선: MCMC + GP-specific samplers (elliptic slice).</li>
</ul></li>
<li><strong>Hyperparameter 적분 소거</strong>: marginal mode + Gaussian 또는 CCD integration.</li>
<li><strong>상호작용 발견 시</strong>: ARD length scales 와 plot 으로 해석. 단일 효과·상호작용을 추가 plot 으로 분리.</li>
</ol>
</section>
<section id="관련-주제" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="관련-주제"><span class="header-section-number">8</span> 관련 주제</h2>
<p><strong>선행 지식</strong></p>
<ul>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/04-21-0-gaussian-process-overview.html">Ch.21 Overview</a></li>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/04-20-0-basis-function-models-overview.html">Ch.20 Overview — Basis Function Models</a></li>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/04-20-1-splines-basis-shrinkage.html">Ch.20 § 20.1~20.2 — Splines·Basis Selection·Shrinkage</a></li>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/03-16-0-generalized-linear-models-overview.html">Ch.16 Generalized Linear Models</a></li>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/02-13-3-variational-inference-expectation-propagation.html">Ch.13 § 13.7~13.8 — Variational Inference·EP</a></li>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/00-4-1-normal-approx-asymptotics.html">Ch.4 § 4.1 — Normal Approximation (Laplace 기초)</a></li>
</ul>
<p><strong>후속 주제</strong></p>
<ul>
<li><a href="./04-21-2-fda-density-exercises.qmd">Ch.21 § 21.4~21.7 — FDA·LGP density·Exercises</a> (예정)</li>
<li><a href="./04-22-0-finite-mixture-overview.qmd">Ch.22 Finite Mixture Models Overview</a> (예정)</li>
<li><a href="./04-23-0-dirichlet-process-overview.qmd">Ch.23 Dirichlet Process Models Overview</a> (예정)</li>
</ul>
<p><strong>관련 개념 (cross-category)</strong></p>
<ul>
<li><a href="../00-3-2-multinomial-multivariate.qmd">Multivariate Normal Distribution</a> — 조건부 공식의 기반</li>
<li><a href="../../Math/cholesky.qmd">Cholesky Decomposition</a></li>
<li><a href="../../Math/kernel-methods-rkhs.qmd">Kernel Methods and RKHS</a></li>
<li><a href="../survival/survival-overview.qmd">Survival Analysis Overview</a></li>
<li><a href="../../Machine_Learning/bayesian-optimization.qmd">Bayesian Optimization with GP</a></li>
<li><a href="../../Deep_Learning/nngp-ntk.qmd">Neural Network Gaussian Process (NNGP)</a></li>
</ul>
</section>
<section id="참고문헌" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="참고문헌"><span class="header-section-number">9</span> 참고문헌</h2>
<ul>
<li>Gelman, A., Carlin, J. B., Stern, H. S., Dunson, D. B., Vehtari, A., &amp; Rubin, D. B. (2013). <em>Bayesian Data Analysis</em> (3rd ed.), Ch.21 § 21.1~21.3. CRC Press.</li>
<li>Rasmussen, C. E., &amp; Williams, C. K. I. (2006). <em>Gaussian Processes for Machine Learning</em>. MIT Press. (특히 Ch.2 GP regression, Ch.3 classification, Ch.5 model selection)</li>
<li>Neal, R. M. (1998). Regression and Classification Using Gaussian Process Priors. <em>Bayesian Statistics</em>, 6, 475-501. (ARD 도입)</li>
<li>Williams, C. K. I., &amp; Barber, D. (1998). Bayesian Classification with Gaussian Processes. <em>IEEE PAMI</em>, 20(12), 1342-1351. (Laplace approximation for GP classification)</li>
<li>Minka, T. (2001). Expectation Propagation for Approximate Bayesian Inference. <em>UAI</em>. (EP)</li>
<li>Titsias, M. (2009). Variational Learning of Inducing Variables in Sparse Gaussian Processes. <em>AISTATS</em>. (VFE inducing points)</li>
<li>Hensman, J., Fusi, N., &amp; Lawrence, N. D. (2013). Gaussian Processes for Big Data. <em>UAI</em>. (Stochastic VI for GP)</li>
<li>Wilson, A. G., &amp; Nickisch, H. (2015). Kernel Interpolation for Scalable Structured Gaussian Processes (KISS-GP). <em>ICML</em>.</li>
<li>Lindgren, F., Rue, H., &amp; Lindstrom, J. (2011). An Explicit Link between Gaussian Fields and Gaussian Markov Random Fields: The SPDE Approach. <em>JRSS B</em>, 73, 423-498.</li>
<li>Sarkka, S., Solin, A., &amp; Hartikainen, J. (2013). Spatiotemporal Learning via Infinite-Dimensional Bayesian Filtering and Smoothing. <em>IEEE Signal Processing Magazine</em>, 30(4), 51-61.</li>
<li>Henderson, R., Shimakura, S., &amp; Gorst, D. (2002). Modeling Spatial Variation in Leukemia Survival Data. <em>JASA</em>, 97, 965-972. (Leukemia 데이터 출처)</li>
<li>Vanhatalo, J., Pietilainen, V., &amp; Vehtari, A. (2010). Approximate Inference for Disease Mapping with Sparse Gaussian Processes. <em>Statistics in Medicine</em>, 29(15), 1580-1607.</li>
</ul>


</section>

</main> <!-- /main -->
<script type="text/javascript">

// replace cmd keyboard shortcut w/ control on non-Mac platforms
const kPlatformMac = typeof navigator !== 'undefined' ? /Mac/.test(navigator.platform) : false;
if (!kPlatformMac) {
   var kbds = document.querySelectorAll("kbd")
   kbds.forEach(function(kbd) {
      kbd.innerHTML = kbd.innerHTML.replace(/⌘/g, '⌃');
   });
}

// tweak headings in pymd
document.querySelectorAll(".pymd span.co").forEach(el => {
   if (!el.innerText.startsWith("#|")) {
      el.style.fontWeight = 1000;
   }
});

</script>
<!-- Begin Mailchimp Signup Form -->
<div id="mc_embed_signup" style="padding-bottom: 1em; max-width: 400px;" class="ms-auto me-auto">
  <p style="font-weight: 600; margin-bottom: 0;">Subscribe</p>
  <span style="font-size: 0.9em;">Enjoy this blog? Get notified of new posts by email:</span>
<form action="https://quarto.us14.list-manage.com/subscribe/post?u=c79fb56a311ae347fbe916740&amp;id=ec05dfca03" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate="">
    <div id="mc_embed_signup_scroll">
	
        <div class="input-group mt-1 mb-2">
        <input type="email" class="form-control" placeholder="Email Address" aria-label="Email Address" name="EMAIL" style="font-size: 0.8em; padding: .2em;">
        </div>              

	<div id="mce-responses" class="clear foot">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_c79fb56a311ae347fbe916740_ec05dfca03" tabindex="-1" value=""></div>
        <div class="optionalParent">
            <div class="clear foot" style="display: flex; align-items: center; justify-content: center;">
              
              
                <input type="submit" value="Subscribe" name="subscribe" style="min-width: 150px; font-size: 0.8em;" id="mc-embedded-subscribe" class="button btn btn-light btn-sm ms-auto me-auto">
            </div>
        </div>
    </div>
</form>
</div>

<!--End mc_embed_signup-->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "복사완료!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "복사완료!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="kmink3225/blog" data-repo-id="R_kgDOLCZyDg" data-category="Blog" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script>
<input type="hidden" id="giscus-base-theme" value="light">
<input type="hidden" id="giscus-alt-theme" value="dark">
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Kwangmin Kim</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="../../../../../about.html">
<p>About</p>
</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/kmink3225/blog">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>