<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ko" xml:lang="ko"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.543">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kwangmin Kim">
<meta name="description" content="Gelman BDA Ch.22 의 § 22.1~22.3 을 한 편으로 깊게 다룬다. § 22.1 식 (22.1) finite mixture 의 완전 정의, 식 (22.2) latent indicator joint 의 적분 vs 계산 두 표현, 연속 혼합 (t = scale mixture·negative binomial = Poisson-Gamma·beta-binomial = binomial-Beta) 의 marginalization 유도, identifiability 의 label ambiguity, Dirichlet prior 의 conjugate 갱신, posterior properness 함정, H 결정의 4 가지 접근, 두 학파 (진짜 부분모집단 vs 유연한 근사). § 22.2 17 명 (정상 11 + 조현병 6) × 30 trials 데이터의 motor retardation \beta + attentional delay (\lambda, \tau) 모델 완전 유도, ECM 알고리즘의 식 (22.5) E-step 베이즈 룰 적용, 식 (22.6) M-step conjugate weighted average, 식 (22.7) variance 갱신, 100 random starting points 로 multimodality 점검, t_4 approximation + importance resampling 으로 Gibbs 시작점, Gibbs 의 6 단계 conditional sampling, T_{\min}/T_{\max} 사후 예측 검정의 lack of fit 발견, \omega + \sigma_{y2}^2 추가의 확장 모델. § 22.3 식 (22.10) exchangeable prior 와 사후 marginal 동일성, 식 (22.11)~(22.12) location-scale Gaussian mixture 의 3 단계 conjugate Gibbs, label switching 의 두 처리 — Stephens (2000) KL loss postprocessing 알고리즘 vs order constraint 의 다변량 한계, density estimation 시 switching 무시 가능 이유.">

<title>Kwangmin Kim - Ch.22 § 22.1~22.3 심화 — Setup · Schizophrenia · Label Switching</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../../../">
<script src="../../../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../../../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../../../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": true,
  "language": {
    "search-no-results-text": "일치 없음",
    "search-matching-documents-text": "일치된 문서",
    "search-copy-link-title": "검색 링크 복사",
    "search-hide-matches-text": "추가 검색 결과 숨기기",
    "search-more-match-text": "추가 검색결과",
    "search-more-matches-text": "추가 검색결과",
    "search-clear-button-title": "제거",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "취소",
    "search-submit-button-title": "검색",
    "search-label": "검색"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-6W0EKFMWBN"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-6W0EKFMWBN', { 'anonymize_ip': true});
</script>
<style>

      .quarto-title-block .quarto-title-banner h1,
      .quarto-title-block .quarto-title-banner h2,
      .quarto-title-block .quarto-title-banner h3,
      .quarto-title-block .quarto-title-banner h4,
      .quarto-title-block .quarto-title-banner h5,
      .quarto-title-block .quarto-title-banner h6
      {
        color: black;
      }

      .quarto-title-block .quarto-title-banner {
        color: black;
background: #EDF3F9;
      }
</style>
<style>
.custom-footer { 
  text-align: center; 
  font-size: 0.8em; 
  color: #666; 
  margin-top: 2rem; 
}
</style>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../../../styles.css">
<meta property="og:title" content="Kwangmin Kim - Ch.22 § 22.1~22.3 심화 — Setup · Schizophrenia · Label Switching">
<meta property="og:description" content="Gelman BDA Ch.22 의 § 22.1~22.3 을 한 편으로 깊게 다룬다. § 22.1 식 (22.1) finite mixture 의 완전 정의, 식 (22.2) latent indicator joint 의 적분 vs 계산 두 표현, 연속 혼합 (\(t\) = scale mixture·negative binomial = Poisson-Gamma·beta-binomial = binomial-Beta) 의 marginalization 유도, identifiability 의 label ambiguity, Dirichlet prior 의 conjugate 갱신, posterior properness 함정, \(H\) 결정의 4 가지 접근, 두 학파 (진짜 부분모집단 vs 유연한 근사). § 22.2 17 명 (정상 11 + 조현병 6) × 30 trials 데이터의 motor retardation \(\beta\) + attentional delay (\(\lambda, \tau\)) 모델 완전 유도, ECM 알고리즘의 식 (22.5) E-step 베이즈 룰 적용, 식 (22.6) M-step conjugate weighted average, 식 (22.7) variance 갱신, 100 random starting points 로 multimodality 점검, \(t_4\) approximation + importance resampling 으로 Gibbs 시작점, Gibbs 의 6 단계 conditional sampling, \(T_{\min}/T_{\max}\) 사후 예측 검정의 lack of fit 발견, \(\omega + \sigma_{y2}^2\) 추가의 확장 모델. § 22.3 식 (22.10) exchangeable prior 와 사후 marginal 동일성, 식 (22.11)~(22.12) location-scale Gaussian mixture 의 3 단계 conjugate Gibbs, label switching 의 두 처리 — Stephens (2000) KL loss postprocessing 알고리즘 vs order constraint 의 다변량 한계, density estimation 시 switching 무시 가능 이유.">
<meta property="og:site_name" content="Kwangmin Kim">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../../../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../../../.././images/logo.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../../../../index.html">
    <span class="navbar-title">Kwangmin Kim</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="검색"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="탐색 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../../docs/blog/index.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../../../about.html"> 
<span class="menu-text">Me</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/kmink3225"> <i class="bi bi-github" role="img" aria-label="Github">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/kwangmin-kim-a5241b200/"> <i class="bi bi-linkedin" role="img" aria-label="Linkedin">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../../../../docs/blog/index.xml"> <i class="bi bi-rss" role="img" aria-label="RSS">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="다크 모드 전환"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Ch.22 § 22.1~22.3 심화 — Setup · Schizophrenia · Label Switching</h1>
            <p class="subtitle lead">식 (22.1) 가중합·식 (22.2) latent indicator·continuous mixture 유도·17명 reaction time ECM 식 (22.5)~(22.7) 완전 유도·Gibbs sampler 모든 단계·posterior predictive checks·식 (22.10) exchangeable prior·식 (22.11)~(22.12) conjugate Gibbs·KL loss postprocessing</p>
                  <div>
        <div class="description">
          <p>Gelman BDA Ch.22 의 § 22.1~22.3 을 한 편으로 깊게 다룬다. § 22.1 식 (22.1) finite mixture 의 완전 정의, 식 (22.2) latent indicator joint 의 적분 vs 계산 두 표현, 연속 혼합 (<span class="math inline">\(t\)</span> = scale mixture·negative binomial = Poisson-Gamma·beta-binomial = binomial-Beta) 의 marginalization 유도, identifiability 의 label ambiguity, Dirichlet prior 의 conjugate 갱신, posterior properness 함정, <span class="math inline">\(H\)</span> 결정의 4 가지 접근, 두 학파 (진짜 부분모집단 vs 유연한 근사). § 22.2 17 명 (정상 11 + 조현병 6) × 30 trials 데이터의 motor retardation <span class="math inline">\(\beta\)</span> + attentional delay (<span class="math inline">\(\lambda, \tau\)</span>) 모델 완전 유도, ECM 알고리즘의 식 (22.5) E-step 베이즈 룰 적용, 식 (22.6) M-step conjugate weighted average, 식 (22.7) variance 갱신, 100 random starting points 로 multimodality 점검, <span class="math inline">\(t_4\)</span> approximation + importance resampling 으로 Gibbs 시작점, Gibbs 의 6 단계 conditional sampling, <span class="math inline">\(T_{\min}/T_{\max}\)</span> 사후 예측 검정의 lack of fit 발견, <span class="math inline">\(\omega + \sigma_{y2}^2\)</span> 추가의 확장 모델. § 22.3 식 (22.10) exchangeable prior 와 사후 marginal 동일성, 식 (22.11)~(22.12) location-scale Gaussian mixture 의 3 단계 conjugate Gibbs, label switching 의 두 처리 — Stephens (2000) KL loss postprocessing 알고리즘 vs order constraint 의 다변량 한계, density estimation 시 switching 무시 가능 이유.</p>
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">Statistics</div>
                <div class="quarto-category">Bayesian</div>
                <div class="quarto-category">Mixture-Models</div>
                <div class="quarto-category">EM-Algorithm</div>
                <div class="quarto-category">Gibbs-Sampler</div>
                <div class="quarto-category">Latent-Variable</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">저자</div>
      <div class="quarto-title-meta-contents">
               <p>Kwangmin Kim </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">공개</div>
      <div class="quarto-title-meta-contents">
        <p class="date">2026년 04월 27일</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">목차</h2>
   
  <ul>
  <li><a href="#들어가며-본-편의-자리" id="toc-들어가며-본-편의-자리" class="nav-link active" data-scroll-target="#들어가며-본-편의-자리"><span class="header-section-number">1</span> 들어가며 — 본 편의 자리</a></li>
  <li><a href="#setting-up-mixture-models-정의와-정당화" id="toc-setting-up-mixture-models-정의와-정당화" class="nav-link" data-scroll-target="#setting-up-mixture-models-정의와-정당화"><span class="header-section-number">2</span> § 22.1 Setting Up Mixture Models — 정의와 정당화</a>
  <ul class="collapse">
  <li><a href="#식-22.1-finite-mixture-의-완전-정의" id="toc-식-22.1-finite-mixture-의-완전-정의" class="nav-link" data-scroll-target="#식-22.1-finite-mixture-의-완전-정의"><span class="header-section-number">2.1</span> 식 (22.1) Finite Mixture 의 완전 정의</a></li>
  <li><a href="#식-22.2-latent-indicator-joint" id="toc-식-22.2-latent-indicator-joint" class="nav-link" data-scroll-target="#식-22.2-latent-indicator-joint"><span class="header-section-number">2.2</span> 식 (22.2) Latent Indicator Joint</a></li>
  <li><a href="#continuous-mixtures-일반화" id="toc-continuous-mixtures-일반화" class="nav-link" data-scroll-target="#continuous-mixtures-일반화"><span class="header-section-number">2.3</span> Continuous Mixtures — 일반화</a></li>
  <li><a href="#identifiability-label-ambiguity" id="toc-identifiability-label-ambiguity" class="nav-link" data-scroll-target="#identifiability-label-ambiguity"><span class="header-section-number">2.4</span> Identifiability — Label Ambiguity</a></li>
  <li><a href="#posterior-properness-함정" id="toc-posterior-properness-함정" class="nav-link" data-scroll-target="#posterior-properness-함정"><span class="header-section-number">2.5</span> Posterior Properness — 함정</a></li>
  <li><a href="#h-결정-4-가지-접근" id="toc-h-결정-4-가지-접근" class="nav-link" data-scroll-target="#h-결정-4-가지-접근"><span class="header-section-number">2.6</span> <span class="math inline">\(H\)</span> 결정 — 4 가지 접근</a></li>
  <li><a href="#dirichlet-conjugate-갱신" id="toc-dirichlet-conjugate-갱신" class="nav-link" data-scroll-target="#dirichlet-conjugate-갱신"><span class="header-section-number">2.7</span> Dirichlet Conjugate 갱신</a></li>
  </ul></li>
  <li><a href="#schizophrenia-reaction-times-ecm-과-gibbs-의-완전-유도" id="toc-schizophrenia-reaction-times-ecm-과-gibbs-의-완전-유도" class="nav-link" data-scroll-target="#schizophrenia-reaction-times-ecm-과-gibbs-의-완전-유도"><span class="header-section-number">3</span> § 22.2 Schizophrenia Reaction Times — ECM 과 Gibbs 의 완전 유도</a>
  <ul class="collapse">
  <li><a href="#데이터와-과학적-가설" id="toc-데이터와-과학적-가설" class="nav-link" data-scroll-target="#데이터와-과학적-가설"><span class="header-section-number">3.1</span> 데이터와 과학적 가설</a></li>
  <li><a href="#모델-식-표현" id="toc-모델-식-표현" class="nav-link" data-scroll-target="#모델-식-표현"><span class="header-section-number">3.2</span> 모델 — 식 표현</a></li>
  <li><a href="#hyperprior-와-식별성" id="toc-hyperprior-와-식별성" class="nav-link" data-scroll-target="#hyperprior-와-식별성"><span class="header-section-number">3.3</span> Hyperprior 와 식별성</a></li>
  <li><a href="#crude-estimate-시작점" id="toc-crude-estimate-시작점" class="nav-link" data-scroll-target="#crude-estimate-시작점"><span class="header-section-number">3.4</span> Crude Estimate (시작점)</a></li>
  <li><a href="#ecm-e-step-식-22.5" id="toc-ecm-e-step-식-22.5" class="nav-link" data-scroll-target="#ecm-e-step-식-22.5"><span class="header-section-number">3.5</span> ECM E-step — 식 (22.5)</a></li>
  <li><a href="#ecm-m-step-식-22.622.7" id="toc-ecm-m-step-식-22.622.7" class="nav-link" data-scroll-target="#ecm-m-step-식-22.622.7"><span class="header-section-number">3.6</span> ECM M-step — 식 (22.6)~(22.7)</a></li>
  <li><a href="#gibbs-sampler-6-단계" id="toc-gibbs-sampler-6-단계" class="nav-link" data-scroll-target="#gibbs-sampler-6-단계"><span class="header-section-number">3.7</span> Gibbs Sampler — 6 단계</a></li>
  <li><a href="#degenerate-point-의-위험" id="toc-degenerate-point-의-위험" class="nav-link" data-scroll-target="#degenerate-point-의-위험"><span class="header-section-number">3.8</span> Degenerate Point 의 위험</a></li>
  <li><a href="#posterior-predictive-checks" id="toc-posterior-predictive-checks" class="nav-link" data-scroll-target="#posterior-predictive-checks"><span class="header-section-number">3.9</span> Posterior Predictive Checks</a></li>
  <li><a href="#expanded-model-omega-와-sigma_y22" id="toc-expanded-model-omega-와-sigma_y22" class="nav-link" data-scroll-target="#expanded-model-omega-와-sigma_y22"><span class="header-section-number">3.10</span> Expanded Model — <span class="math inline">\(\omega\)</span> 와 <span class="math inline">\(\sigma_{y2}^2\)</span></a></li>
  </ul></li>
  <li><a href="#label-switching-and-posterior-computation" id="toc-label-switching-and-posterior-computation" class="nav-link" data-scroll-target="#label-switching-and-posterior-computation"><span class="header-section-number">4</span> § 22.3 Label Switching and Posterior Computation</a>
  <ul class="collapse">
  <li><a href="#식-22.10-exchangeable-prior" id="toc-식-22.10-exchangeable-prior" class="nav-link" data-scroll-target="#식-22.10-exchangeable-prior"><span class="header-section-number">4.1</span> 식 (22.10) Exchangeable Prior</a></li>
  <li><a href="#식-22.1122.12-conjugate-gibbs" id="toc-식-22.1122.12-conjugate-gibbs" class="nav-link" data-scroll-target="#식-22.1122.12-conjugate-gibbs"><span class="header-section-number">4.2</span> 식 (22.11)~(22.12) Conjugate Gibbs</a></li>
  <li><a href="#default-hyperparameters" id="toc-default-hyperparameters" class="nav-link" data-scroll-target="#default-hyperparameters"><span class="header-section-number">4.3</span> Default Hyperparameters</a></li>
  <li><a href="#label-switching-의-발생-메커니즘" id="toc-label-switching-의-발생-메커니즘" class="nav-link" data-scroll-target="#label-switching-의-발생-메커니즘"><span class="header-section-number">4.4</span> Label Switching 의 발생 메커니즘</a></li>
  <li><a href="#postprocessing-stephens-2000-kl-loss" id="toc-postprocessing-stephens-2000-kl-loss" class="nav-link" data-scroll-target="#postprocessing-stephens-2000-kl-loss"><span class="header-section-number">4.5</span> Postprocessing — Stephens (2000) KL Loss</a></li>
  <li><a href="#order-constraint-한계" id="toc-order-constraint-한계" class="nav-link" data-scroll-target="#order-constraint-한계"><span class="header-section-number">4.6</span> Order Constraint — 한계</a></li>
  </ul></li>
  <li><a href="#핵심-수식-통합" id="toc-핵심-수식-통합" class="nav-link" data-scroll-target="#핵심-수식-통합"><span class="header-section-number">5</span> 핵심 수식 통합</a></li>
  <li><a href="#실행-예제-schizophrenia-모델-단순화-gibbs-pymc" id="toc-실행-예제-schizophrenia-모델-단순화-gibbs-pymc" class="nav-link" data-scroll-target="#실행-예제-schizophrenia-모델-단순화-gibbs-pymc"><span class="header-section-number">6</span> 실행 예제 — Schizophrenia 모델 단순화 + Gibbs (PyMC)</a></li>
  <li><a href="#실전-체크리스트-22.122.3" id="toc-실전-체크리스트-22.122.3" class="nav-link" data-scroll-target="#실전-체크리스트-22.122.3"><span class="header-section-number">7</span> 실전 체크리스트 — § 22.1~22.3</a></li>
  <li><a href="#관련-주제" id="toc-관련-주제" class="nav-link" data-scroll-target="#관련-주제"><span class="header-section-number">8</span> 관련 주제</a></li>
  <li><a href="#참고문헌" id="toc-참고문헌" class="nav-link" data-scroll-target="#참고문헌"><span class="header-section-number">9</span> 참고문헌</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="들어가며-본-편의-자리" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="들어가며-본-편의-자리"><span class="header-section-number">1</span> 들어가며 — 본 편의 자리</h2>
<p>Ch.22 의 사다리:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">편</th>
<th style="text-align: left;">주제</th>
<th style="text-align: left;">핵심</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><a href="../../../../../docs/blog/posts/Statistics/bayesian/04-22-0-finite-mixture-overview.html">Overview (04-22-0)</a></td>
<td style="text-align: left;">Ch.22 의 큰 그림</td>
<td style="text-align: left;">5 절 조망 + 핵심 수식</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>§ 22.1~22.3 (본 편)</strong></td>
<td style="text-align: left;"><strong>혼합 모델 정의·적합·식별</strong></td>
<td style="text-align: left;">식 (22.1)~(22.2)·ECM 식 (22.5)~(22.7)·Gibbs·식 (22.10)~(22.12)·label switching</td>
</tr>
<tr class="odd">
<td style="text-align: left;">§ 22.4~22.6</td>
<td style="text-align: left;">알려지지 않은 <span class="math inline">\(H\)</span> + 분류·회귀 + 연습</td>
<td style="text-align: left;">Truncated upper bound·<span class="math inline">\(a = n_0/H\)</span>·classification·exercises</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
본 편이 답하는 다섯 가지 질문
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li>식 (22.1) 가중합과 식 (22.2) latent indicator joint 가 <strong>같은 모델의 두 표현</strong> 인 이유는 무엇인가?</li>
<li>연속 혼합 (continuous mixture) 이 hierarchical model + robust 통계 + over-dispersion 분포 (negative binomial, beta-binomial) 를 통일하는 이유는?</li>
<li>ECM 의 E-step (식 22.5) 과 M-step (식 22.6, 22.7) 이 각각 <strong>베이즈 룰의 어느 단계</strong> 를 자동화하는가?</li>
<li>Gibbs sampler 의 6 단계가 ECM 의 stochastic counterpart 임을 어떻게 보일 수 있는가?</li>
<li>Label switching 이 발생할 때 <strong>density estimation 에는 무해</strong> 하지만 cluster-specific 추론에는 치명적인 이유는?</li>
</ol>
</div>
</div>
</section>
<section id="setting-up-mixture-models-정의와-정당화" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="setting-up-mixture-models-정의와-정당화"><span class="header-section-number">2</span> § 22.1 Setting Up Mixture Models — 정의와 정당화</h2>
<section id="식-22.1-finite-mixture-의-완전-정의" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="식-22.1-finite-mixture-의-완전-정의"><span class="header-section-number">2.1</span> 식 (22.1) Finite Mixture 의 완전 정의</h3>
<p>데이터 <span class="math inline">\(y_i\)</span> 가 <span class="math inline">\(H\)</span> 개 하위 모집단 중 하나에서 추출:</p>
<p><span class="math display">\[
p(y_i \mid \theta, \lambda) = \sum_{h=1}^H \lambda_h f(y_i \mid \theta_h) \quad (22.1)
\]</span></p>
<ul>
<li><span class="math inline">\(f(\cdot \mid \theta_h)\)</span> = <span class="math inline">\(h\)</span> 번째 성분 분포 (보통 모든 <span class="math inline">\(h\)</span> 가 같은 가족, 다른 모수).</li>
<li><span class="math inline">\(\theta = (\theta_1, \ldots, \theta_H)\)</span> — 성분별 모수 벡터.</li>
<li><span class="math inline">\(\lambda = (\lambda_1, \ldots, \lambda_H)\)</span> — 혼합 비율, <span class="math inline">\(\lambda_h \geq 0\)</span>, <span class="math inline">\(\sum_h \lambda_h = 1\)</span>.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — Mixture 가 conditioning 의 자연스러운 역방향
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="../../../../../docs/blog/posts/Statistics/bayesian/00-5-0-hierarchical.html">Ch.5 hierarchical models</a> 의 원칙: <strong>conditioning 을 통해 현실적 확률 모델 구성</strong>.</p>
<ul>
<li>키 = (성별, 인종) 별로 정규 → 정상적 hierarchical 모델.</li>
<li>성별·인종 미관측 → 이 정보를 적분 소거하면 mixture.</li>
</ul>
<p>따라서 <strong>mixture = “관측 안 된 conditioning 변수를 marginalize 한 결과”</strong>. Latent indicator <span class="math inline">\(z_i\)</span> 는 그 미관측 변수를 명시적으로 변수화한 것.</p>
<p>핵심 함의: 가능하면 conditioning 정보를 직접 사용 (mixture 가 필요 없음). 정말 모를 때만 mixture.</p>
</div>
</div>
</section>
<section id="식-22.2-latent-indicator-joint" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="식-22.2-latent-indicator-joint"><span class="header-section-number">2.2</span> 식 (22.2) Latent Indicator Joint</h3>
<p><span class="math display">\[
z_i = (z_{i1}, \ldots, z_{iH}) \in \{0, 1\}^H, \qquad \sum_h z_{ih} = 1
\]</span></p>
<p><span class="math inline">\(z_i \mid \lambda \sim \text{Multinomial}(1; \lambda_1, \ldots, \lambda_H)\)</span>. Joint distribution:</p>
<p><span class="math display">\[
p(y, z \mid \theta, \lambda) = p(z \mid \lambda) p(y \mid z, \theta) = \prod_{i=1}^n \prod_{h=1}^H \bigl(\lambda_h f(y_i \mid \theta_h)\bigr)^{z_{ih}} \quad (22.2)
\]</span></p>
<p>각 <span class="math inline">\(i\)</span> 에 대해 정확히 하나의 <span class="math inline">\(z_{ih}\)</span> 가 1이고 나머지 0 — <strong>곱의 대부분이 <span class="math inline">\(1\)</span> 이고 단 하나가 <span class="math inline">\(\lambda_h f(y_i \mid \theta_h)\)</span></strong>.</p>
<section id="식-22.1-식-22.2-의-동치" class="level4" data-number="2.2.1">
<h4 data-number="2.2.1" class="anchored" data-anchor-id="식-22.1-식-22.2-의-동치"><span class="header-section-number">2.2.1</span> 식 (22.1) ↔︎ 식 (22.2) 의 동치</h4>
<p><span class="math inline">\(z\)</span> 를 marginalize:</p>
<p><span class="math display">\[
p(y_i \mid \theta, \lambda) = \sum_{z_i} p(y_i, z_i \mid \theta, \lambda) = \sum_{h=1}^H \lambda_h f(y_i \mid \theta_h)
\]</span></p>
<p>→ 식 (22.1) 복원.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — 두 표현의 역할 분담
</div>
</div>
<div class="callout-body-container callout-body">
<table class="table">
<colgroup>
<col style="width: 23%">
<col style="width: 41%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">표현</th>
<th style="text-align: left;">강점</th>
<th style="text-align: left;">사용처</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">식 (22.1) 가중합</td>
<td style="text-align: left;">likelihood 의 직접 표현</td>
<td style="text-align: left;">모델 정의·marginal likelihood</td>
</tr>
<tr class="even">
<td style="text-align: left;">식 (22.2) joint</td>
<td style="text-align: left;">conditional 이 표준 형태</td>
<td style="text-align: left;">EM·ECM·Gibbs 계산</td>
</tr>
</tbody>
</table>
<p>Conditional on <span class="math inline">\(z\)</span> 면 <strong>mixture 가 사라지고</strong> <span class="math inline">\(H\)</span> 개의 표준 모델로 분해. 이것이 latent variable augmentation 이 mixture 추정을 단순화하는 핵심.</p>
<p>만약 <span class="math inline">\(z\)</span> 가 알려진 ground truth 라면 (예: 키 + 성별 데이터), mixture 가 아니고 <span class="math inline">\(H\)</span> 개의 conditional model. 식 (22.2) 의 product term 이 그대로 likelihood.</p>
</div>
</div>
</section>
</section>
<section id="continuous-mixtures-일반화" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="continuous-mixtures-일반화"><span class="header-section-number">2.3</span> Continuous Mixtures — 일반화</h3>
<p>식 (22.1) 의 자연스러운 확장:</p>
<p><span class="math display">\[
p(y_i) = \int p(y_i \mid \theta) \lambda(\theta) d\theta
\]</span></p>
<p><span class="math inline">\(\lambda(\theta)\)</span> = mixing distribution (parameter space 위의 분포).</p>
<section id="사례-1-t-분포-scale-mixture-of-normals" class="level4" data-number="2.3.1">
<h4 data-number="2.3.1" class="anchored" data-anchor-id="사례-1-t-분포-scale-mixture-of-normals"><span class="header-section-number">2.3.1</span> 사례 1 — <span class="math inline">\(t\)</span> 분포 (scale mixture of normals)</h4>
<p><span class="math display">\[
y_i \mid \mu, \sigma^2, z_i \sim N(\mu, \sigma^2 z_i), \qquad z_i \sim \text{Inv-}\chi^2(\nu, 1)
\]</span></p>
<p><span class="math inline">\(z_i\)</span> 적분 소거:</p>
<p><span class="math display">\[
p(y_i \mid \mu, \sigma^2, \nu) = \int N(y_i \mid \mu, \sigma^2 z) \cdot \text{Inv-}\chi^2(z \mid \nu, 1) dz = t_\nu(y_i \mid \mu, \sigma^2)
\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — Robust 통계학이 왜 mixture 인가
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(t_\nu\)</span> 의 heavy tail = “분산이 큰 normal component 가 가끔 등장” 의 marginal.</p>
<p>Outlier 가 도착하면 <span class="math inline">\(z_i\)</span> 사후가 큰 값으로 → 그 관측치는 “큰 분산 component” 로 분류 → <strong>다른 데이터의 추정에 영향 거의 없음</strong>.</p>
<p>이것이 <a href="../../../../../docs/blog/posts/Statistics/bayesian/03-17-0-robust-inference-overview.html">Ch.17 robust inference</a> 의 핵심 메커니즘. <strong>Mixture indicator 가 outlier 를 자동 격리</strong>.</p>
</div>
</div>
</section>
<section id="사례-2-negative-binomial-poisson-gamma-mixture" class="level4" data-number="2.3.2">
<h4 data-number="2.3.2" class="anchored" data-anchor-id="사례-2-negative-binomial-poisson-gamma-mixture"><span class="header-section-number">2.3.2</span> 사례 2 — Negative binomial (Poisson-Gamma mixture)</h4>
<p><span class="math display">\[
y_i \mid \lambda_i \sim \text{Poisson}(\lambda_i), \qquad \lambda_i \sim \text{Gamma}(r, p/(1-p))
\]</span></p>
<p>Marginal: <span class="math inline">\(y_i \sim \text{NegBin}(r, p)\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — Over-dispersion 의 정체
</div>
</div>
<div class="callout-body-container callout-body">
<p>Poisson 의 약점: 평균 = 분산 강제. 실제 count data 는 더 큰 분산 (over-dispersion).</p>
<p>해법: <span class="math inline">\(\lambda_i\)</span> 가 개체별로 다른 값 (Gamma 에서 추출) → <strong>개체간 변동</strong> 이 추가 분산 기여 → over-dispersion.</p>
<p>같은 정신: <strong>beta-binomial = binomial 의 Beta-mixture</strong>.</p>
</div>
</div>
</section>
<section id="사례-3-hierarchical-models-continuous-mixture" class="level4" data-number="2.3.3">
<h4 data-number="2.3.3" class="anchored" data-anchor-id="사례-3-hierarchical-models-continuous-mixture"><span class="header-section-number">2.3.3</span> 사례 3 — Hierarchical models = continuous mixture</h4>
<p><a href="../../../../../docs/blog/posts/Statistics/bayesian/00-5-0-hierarchical.html">Ch.5 hierarchical model</a> 의 일반 구조:</p>
<p><span class="math display">\[
y_i \mid \theta_i \sim p(y_i \mid \theta_i), \qquad \theta_i \mid \phi \sim p(\theta_i \mid \phi)
\]</span></p>
<p><span class="math inline">\(\theta_i\)</span> 가 <strong>개체별 latent</strong>, <span class="math inline">\(\phi\)</span> 가 <strong>mixing distribution 의 hyperparameter</strong>. 이것이 정확히 continuous mixture.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Mixture 의 통일 관점
</div>
</div>
<div class="callout-body-container callout-body">
<pre><code>Hierarchical model = continuous mixture (개체별 다른 θ)
        ↓ θ_i 가 H 개 이산값만 가질 수 있음
Finite mixture = 식 (22.1) (H 개 cluster)
        ↓ θ 가 무한 차원 분포에서 추출
Dirichlet Process mixture = Ch.23</code></pre>
<p>세 가지가 같은 framework — <strong>latent variable 의 차원이 다를 뿐</strong>.</p>
</div>
</div>
</section>
</section>
<section id="identifiability-label-ambiguity" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="identifiability-label-ambiguity"><span class="header-section-number">2.4</span> Identifiability — Label Ambiguity</h3>
<p><strong>문제</strong>: 식 (22.1) 의 우도가 <span class="math inline">\(\theta_h\)</span> 의 라벨 순열 (permutation) 에 불변.</p>
<p><span class="math display">\[
p(y \mid (\lambda_1, \theta_1, \lambda_2, \theta_2)) = p(y \mid (\lambda_2, \theta_2, \lambda_1, \theta_1))
\]</span></p>
<p>→ 사후가 <span class="math inline">\(H!\)</span> 개 동등 mode. 이것이 <strong>label switching</strong> 의 근원 (§ 22.3 에서 상세).</p>
</section>
<section id="posterior-properness-함정" class="level3" data-number="2.5">
<h3 data-number="2.5" class="anchored" data-anchor-id="posterior-properness-함정"><span class="header-section-number">2.5</span> Posterior Properness — 함정</h3>
<p><strong>Improper prior 가 위험한 이유</strong>:</p>
<ul>
<li>정규 mixture 에서 한 component 의 분산 <span class="math inline">\(\sigma_h^2 \to 0\)</span> 이면, 그 component 가 single observation 에 정확히 맞춰지면서 likelihood <span class="math inline">\(\to \infty\)</span>.</li>
<li>Improper prior <span class="math inline">\(p(\sigma_h^2) \propto 1/\sigma_h^2\)</span> + 위 degenerate mode → <strong>사후 밀도 적분이 발산</strong> → improper posterior.</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
정규 혼합의 prior 권장
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>공통 분산</strong> (<span class="math inline">\(\sigma_1 = \sigma_2 = \cdots = \sigma_H\)</span>): improper prior OK (단일 분산).</li>
<li><strong>분산 비율 고정</strong> (<span class="math inline">\(\sigma_2/\sigma_1\)</span> 알려짐): improper OK.</li>
<li><strong>분산 자유</strong>: <strong>반드시 proper prior</strong> (Inverse Gamma 등).</li>
</ul>
<p>이는 Ch.5 § 5.7 의 hierarchical variance prior 권장 사항과 같은 정신.</p>
</div>
</div>
</section>
<section id="h-결정-4-가지-접근" class="level3" data-number="2.6">
<h3 data-number="2.6" class="anchored" data-anchor-id="h-결정-4-가지-접근"><span class="header-section-number">2.6</span> <span class="math inline">\(H\)</span> 결정 — 4 가지 접근</h3>
<table class="table">
<colgroup>
<col style="width: 36%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">접근</th>
<th style="text-align: left;">장단점</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">도메인 지식 고정</td>
<td style="text-align: left;">가장 확실하지만 가능한 경우만</td>
</tr>
<tr class="even">
<td style="text-align: left;">여러 <span class="math inline">\(H\)</span> 비교 (WAIC, LOO-CV)</td>
<td style="text-align: left;">표준적, 단 <span class="math inline">\(H\)</span> 불확실성 무시</td>
</tr>
<tr class="odd">
<td style="text-align: left;">계층적 (<span class="math inline">\(H\)</span> 자체에 prior + RJMCMC)</td>
<td style="text-align: left;">통합적이지만 계산 복잡</td>
</tr>
<tr class="even">
<td style="text-align: left;">Truncated upper bound + sparse Dirichlet</td>
<td style="text-align: left;">§ 22.4 에서 — 단순하면서 효과적</td>
</tr>
</tbody>
</table>
</section>
<section id="dirichlet-conjugate-갱신" class="level3" data-number="2.7">
<h3 data-number="2.7" class="anchored" data-anchor-id="dirichlet-conjugate-갱신"><span class="header-section-number">2.7</span> Dirichlet Conjugate 갱신</h3>
<p><span class="math inline">\(\lambda \sim \text{Dirichlet}(\alpha_1, \ldots, \alpha_H)\)</span> + multinomial <span class="math inline">\(z_i\)</span> 데이터.</p>
<p><span class="math inline">\(n_h = \sum_i z_{ih}\)</span> = component <span class="math inline">\(h\)</span> 에 속한 관측치 수.</p>
<p><strong>사후</strong>:</p>
<p><span class="math display">\[
\lambda \mid z \sim \text{Dirichlet}(\alpha_1 + n_1, \ldots, \alpha_H + n_H)
\]</span></p>
<p>이것이 Gibbs sampler 의 <span class="math inline">\(\lambda\)</span> 단계.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — Dirichlet 의 stick-breaking 표현
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(\lambda\)</span> 를 차례로 결정:</p>
<p><span class="math display">\[
V_h \sim \text{Beta}\Bigl(\alpha_h, \sum_{l &gt; h} \alpha_l\Bigr), \quad \lambda_1 = V_1, \quad \lambda_h = V_h \prod_{l &lt; h}(1 - V_l)
\]</span></p>
<p>“길이 1 의 막대를 첫 component 에 <span class="math inline">\(V_1\)</span> 만큼 자르고, 남은 <span class="math inline">\(1 - V_1\)</span> 를 다음에 <span class="math inline">\(V_2\)</span> 만큼…”.</p>
<p><span class="math inline">\(\alpha_h = a\)</span> (균등) 로 두면 흔한 Dirichlet. <span class="math inline">\(\alpha_h = a/H\)</span> 로 두면 sparse — 이것이 Ch.23 DP 의 finite approximation (§ 22.4).</p>
</div>
</div>
</section>
</section>
<section id="schizophrenia-reaction-times-ecm-과-gibbs-의-완전-유도" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="schizophrenia-reaction-times-ecm-과-gibbs-의-완전-유도"><span class="header-section-number">3</span> § 22.2 Schizophrenia Reaction Times — ECM 과 Gibbs 의 완전 유도</h2>
<section id="데이터와-과학적-가설" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="데이터와-과학적-가설"><span class="header-section-number">3.1</span> 데이터와 과학적 가설</h3>
<p><strong>데이터</strong> (Belin &amp; Rubin 1990): 17 명 (정상 11 + 조현병 6) × 30 trials. <span class="math inline">\(y_{ij}\)</span> = 개인 <span class="math inline">\(j\)</span> 의 <span class="math inline">\(i\)</span> 번째 시도 반응시간 (log scale).</p>
<p><strong>가설 (psychology theory)</strong>:</p>
<ul>
<li><strong>Motor retardation</strong>: 조현병의 평균 반응시간이 길다 (모든 trial).</li>
<li><strong>Attentional deficit</strong>: 일부 trial 에서만 추가 지연 (mixture component).</li>
</ul>
<p>→ 조현병 환자에서만 두 성분 정규 mixture.</p>
</section>
<section id="모델-식-표현" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="모델-식-표현"><span class="header-section-number">3.2</span> 모델 — 식 표현</h3>
<p><span class="math display">\[
\begin{aligned}
y_{ij} \mid \alpha_j, z_{ij}, \phi &amp;\sim N(\alpha_j + \tau z_{ij},\ \sigma_y^2) \\
\alpha_j \mid z, \phi &amp;\sim N(\mu + \beta S_j,\ \sigma_\alpha^2) \\
z_{ij} \mid \phi &amp;\sim \text{Bernoulli}(\lambda S_j)
\end{aligned}
\]</span></p>
<ul>
<li><span class="math inline">\(S_j \in \{0, 1\}\)</span> — 조현병 indicator (관측).</li>
<li><span class="math inline">\(z_{ij}\)</span> — attentional delay indicator (latent), 정상은 강제 0.</li>
<li>Parameter: <span class="math inline">\(\alpha = (\alpha_1, \ldots, \alpha_{17})\)</span>, <span class="math inline">\(\phi = (\sigma_\alpha^2, \beta, \lambda, \tau, \mu, \sigma_y^2)\)</span>.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — 모델의 3 층 구조
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Layer 1 (관측)</strong>: <span class="math inline">\(y_{ij}\)</span> — 측정치.</li>
<li><strong>Layer 2 (개체)</strong>: <span class="math inline">\(\alpha_j\)</span> — 개인별 평균 (random effect).</li>
<li><strong>Layer 3 (모집단)</strong>: <span class="math inline">\(\mu, \beta\)</span> (그룹 차이), <span class="math inline">\(\tau, \lambda\)</span> (mixture 모수), <span class="math inline">\(\sigma_\alpha, \sigma_y\)</span> (분산).</li>
</ul>
<p>Latent <span class="math inline">\(z_{ij}\)</span> 는 layer 1 의 mixture, <span class="math inline">\(\alpha_j\)</span> 는 layer 2 의 hierarchy. <strong>두 latent structure</strong> 가 동시에.</p>
</div>
</div>
</section>
<section id="hyperprior-와-식별성" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="hyperprior-와-식별성"><span class="header-section-number">3.3</span> Hyperprior 와 식별성</h3>
<ul>
<li><span class="math inline">\(\tau &gt; 0\)</span> — <strong>delay 가 양수</strong> (모델 식별성 보장; 부호 반전 mode 회피).</li>
<li><span class="math inline">\(\lambda \in [0.001, 0.999]\)</span> — boundary 회피.</li>
<li><span class="math inline">\(\sigma_\alpha, \sigma_y &gt; 0\)</span> — 표준 양수 제약.</li>
<li>그 외 uniform on log scale.</li>
</ul>
</section>
<section id="crude-estimate-시작점" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="crude-estimate-시작점"><span class="header-section-number">3.4</span> Crude Estimate (시작점)</h3>
<ul>
<li><span class="math inline">\(\widehat\alpha_j\)</span> = 개인 <span class="math inline">\(j\)</span> 의 데이터 평균.</li>
<li><span class="math inline">\(\widehat\sigma_y^2\)</span> = 정상인 within-person 분산 평균.</li>
<li><span class="math inline">\(\widehat\mu\)</span> = 정상인 <span class="math inline">\(\widehat\alpha_j\)</span> 평균.</li>
<li><span class="math inline">\(\widehat\beta\)</span> = 조현병 - 정상 평균 차이.</li>
<li><span class="math inline">\(\widehat\sigma_\alpha^2\)</span> = 그룹 내 <span class="math inline">\(\widehat\alpha_j\)</span> 분산.</li>
<li><span class="math inline">\(\widehat\lambda = 1/3\)</span>, <span class="math inline">\(\widehat\tau = 1.0\)</span> — 시각 inspection (Figure 22.1).</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — Crude estimate 의 역할
</div>
</div>
<div class="callout-body-container callout-body">
<p>Crude = “분포 무시하고 점 추정”. 두 역할:</p>
<ol type="1">
<li>ECM/Gibbs 의 시작점 (수렴 안정).</li>
<li>Multimodal posterior 탐지 — crude 를 100 회 randomly perturb (각 모수를 <span class="math inline">\(\chi_1^2\)</span> 로 나눔) 하여 100 starting points → ECM 으로 모든 mode 찾기.</li>
</ol>
<p><strong>Multimodal 인 mixture 모델에서 single starting point 는 위험</strong>. 100 starting 권장.</p>
</div>
</div>
</section>
<section id="ecm-e-step-식-22.5" class="level3" data-number="3.5">
<h3 data-number="3.5" class="anchored" data-anchor-id="ecm-e-step-식-22.5"><span class="header-section-number">3.5</span> ECM E-step — 식 (22.5)</h3>
<p>조현병 trial <span class="math inline">\((i, j)\)</span> 가 delayed 였을 사후 확률:</p>
<p><span class="math display">\[
\zeta_{ij} = \Pr(z_{ij} = 1 \mid \theta^{\text{old}}, y) = \frac{\lambda^{\text{old}} N(y_{ij} \mid \alpha_j^{\text{old}} + \tau^{\text{old}}, (\sigma_y^{\text{old}})^2)}{(1 - \lambda^{\text{old}}) N(y_{ij} \mid \alpha_j^{\text{old}}, (\sigma_y^{\text{old}})^2) + \lambda^{\text{old}} N(y_{ij} \mid \alpha_j^{\text{old}} + \tau^{\text{old}}, (\sigma_y^{\text{old}})^2)} \quad (22.5)
\]</span></p>
<section id="베이즈-룰의-직접-적용" class="level4" data-number="3.5.1">
<h4 data-number="3.5.1" class="anchored" data-anchor-id="베이즈-룰의-직접-적용"><span class="header-section-number">3.5.1</span> 베이즈 룰의 직접 적용</h4>
<p><span class="math display">\[
\Pr(z_{ij} = 1 \mid y_{ij}) = \frac{\Pr(y_{ij} \mid z_{ij} = 1) \Pr(z_{ij} = 1)}{\Pr(y_{ij} \mid z_{ij} = 1) \Pr(z_{ij} = 1) + \Pr(y_{ij} \mid z_{ij} = 0) \Pr(z_{ij} = 0)}
\]</span></p>
<p>대입하면 정확히 (22.5). <span class="math inline">\(\Pr(z_{ij} = 1) = \lambda\)</span> (조현병이면).</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — <span class="math inline">\(\zeta_{ij}\)</span> 가 의미하는 것
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><span class="math inline">\(y_{ij}\)</span> 매우 큼 → “delayed component” 의 likelihood 가 크고 → <span class="math inline">\(\zeta_{ij} \to 1\)</span>.</li>
<li><span class="math inline">\(y_{ij}\)</span> 보통 → 두 component likelihood 비슷, <span class="math inline">\(\lambda\)</span> 가 결정.</li>
<li><span class="math inline">\(\zeta_{ij}\)</span> 가 0 또는 1 에 가까울수록 <strong>각 trial 의 attribution 이 명확</strong>.</li>
</ul>
<p>ECM 의 E-step 은 “모든 trial 에 대해 attribution 의 사후 기댓값 계산” 을 의미. <strong>Soft assignment</strong> (확률) 이지 hard 가 아님.</p>
</div>
</div>
</section>
</section>
<section id="ecm-m-step-식-22.622.7" class="level3" data-number="3.6">
<h3 data-number="3.6" class="anchored" data-anchor-id="ecm-m-step-식-22.622.7"><span class="header-section-number">3.6</span> ECM M-step — 식 (22.6)~(22.7)</h3>
<p>조건부 기댓값을 가지고 <span class="math inline">\(\theta\)</span> 를 한 block 씩 갱신.</p>
<section id="step-1-lambda-갱신" class="level4" data-number="3.6.1">
<h4 data-number="3.6.1" class="anchored" data-anchor-id="step-1-lambda-갱신"><span class="header-section-number">3.6.1</span> Step 1 — <span class="math inline">\(\lambda\)</span> 갱신</h4>
<p><span class="math display">\[
\lambda^{\text{new}} = \frac{1}{6 \times 30} \sum_{j=12}^{17} \sum_{i=1}^{30} \zeta_{ij}
\]</span></p>
<p><span class="math inline">\(\sum \zeta_{ij}\)</span> = “delay 였을 것” 의 기댓값 합. 6 환자 × 30 trial = 180 으로 나눈다.</p>
</section>
<section id="step-2-alpha_j-갱신-식-22.6" class="level4" data-number="3.6.2">
<h4 data-number="3.6.2" class="anchored" data-anchor-id="step-2-alpha_j-갱신-식-22.6"><span class="header-section-number">3.6.2</span> Step 2 — <span class="math inline">\(\alpha_j\)</span> 갱신 (식 22.6)</h4>
<p><span class="math inline">\(\alpha_j\)</span> 의 likelihood + prior 의 conjugate 결합:</p>
<p><span class="math display">\[
\alpha_j^{\text{new}} = \frac{\frac{1}{\sigma_\alpha^2}(\mu + \beta S_j) + \sum_{i=1}^{30} \frac{1}{\sigma_y^2}(y_{ij} - \zeta_{ij} \tau)}{\frac{1}{\sigma_\alpha^2} + \sum_{i=1}^{30} \frac{1}{\sigma_y^2}} \quad (22.6)
\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — Conjugate normal weighted average
</div>
</div>
<div class="callout-body-container callout-body">
<p>표준 conjugate normal posterior 의 형태:</p>
<p><span class="math display">\[
\text{posterior mean} = \frac{\text{prior precision} \cdot \text{prior mean} + \text{data precision} \cdot \text{data}}{\text{prior precision} + \text{data precision}}
\]</span></p>
<p>식 (22.6) 에서:</p>
<ul>
<li>Prior mean = <span class="math inline">\(\mu + \beta S_j\)</span> (그룹 평균).</li>
<li>Prior precision = <span class="math inline">\(1/\sigma_\alpha^2\)</span>.</li>
<li>Data = “<span class="math inline">\(\zeta\)</span>-corrected” <span class="math inline">\(y_{ij} - \zeta_{ij} \tau\)</span> (delay 가능성을 제거한 평균).</li>
<li>Data precision = <span class="math inline">\(1/\sigma_y^2\)</span> × 30.</li>
</ul>
<p><strong><span class="math inline">\(\zeta\)</span>-correction 의 의미</strong>: trial <span class="math inline">\((i, j)\)</span> 가 delay 였을 확률 <span class="math inline">\(\zeta_{ij}\)</span> 만큼 <span class="math inline">\(\tau\)</span> 빼기 → “<span class="math inline">\(\alpha_j\)</span> 의 평균” 에 대한 corrected estimate.</p>
</div>
</div>
</section>
<section id="step-3-tau-sigma_y2-갱신" class="level4" data-number="3.6.3">
<h4 data-number="3.6.3" class="anchored" data-anchor-id="step-3-tau-sigma_y2-갱신"><span class="header-section-number">3.6.3</span> Step 3 — <span class="math inline">\(\tau, \sigma_y^2\)</span> 갱신</h4>
<p><span class="math display">\[
\tau^{\text{new}} = \frac{\sum_{j,i} \zeta_{ij}(y_{ij} - \alpha_j)}{\sum_{j,i} \zeta_{ij}}
\]</span></p>
<p><span class="math display">\[
(\sigma_y^{\text{new}})^2 = \frac{1}{17 \times 30} \sum_{j,i} (y_{ij} - \alpha_j - \zeta_{ij} \tau^{\text{new}})^2
\]</span></p>
<p><span class="math inline">\(\tau\)</span> = “delay 였을 확률 가중 평균 of <span class="math inline">\((y_{ij} - \alpha_j)\)</span>”.</p>
</section>
<section id="step-4-mu-beta-sigma_alpha2-갱신-식-22.7" class="level4" data-number="3.6.4">
<h4 data-number="3.6.4" class="anchored" data-anchor-id="step-4-mu-beta-sigma_alpha2-갱신-식-22.7"><span class="header-section-number">3.6.4</span> Step 4 — <span class="math inline">\(\mu, \beta, \sigma_\alpha^2\)</span> 갱신 (식 22.7)</h4>
<p>조건부 정규 모형:</p>
<p><span class="math display">\[
\mu^{\text{new}} = \frac{1}{11} \sum_{j=1}^{11} \alpha_j, \qquad \beta^{\text{new}} = \frac{1}{6} \sum_{j=12}^{17} \alpha_j - \mu^{\text{new}} \quad (22.7)
\]</span></p>
<p><span class="math inline">\(\mu\)</span> = 정상인 <span class="math inline">\(\alpha_j\)</span> 평균. <span class="math inline">\(\beta\)</span> = 조현병 vs 정상 평균 차이.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — ECM 의 monotone convergence
</div>
</div>
<div class="callout-body-container callout-body">
<p>EM 이론 (Dempster-Laird-Rubin 1977): 매 iteration 마다 marginal likelihood <span class="math inline">\(p(y \mid \theta)\)</span> 가 감소하지 않는다.</p>
<p><strong>ECM</strong> (Meng-Rubin 1993): M-step 을 block 별 conditional max 로 분해해도 monotone 보장. 각 conditional max 가 <span class="math inline">\(\theta\)</span> 의 한 block 에 대해 likelihood 를 증가 (또는 유지).</p>
<p>따라서 100 iteration 정도면 mode 에 거의 도달. 만약 likelihood 가 감소하면 <strong>버그</strong> — 코드 점검 신호.</p>
</div>
</div>
</section>
</section>
<section id="gibbs-sampler-6-단계" class="level3" data-number="3.7">
<h3 data-number="3.7" class="anchored" data-anchor-id="gibbs-sampler-6-단계"><span class="header-section-number">3.7</span> Gibbs Sampler — 6 단계</h3>
<p>ECM 의 mode 대신 stochastic conditional sampling.</p>
<section id="단계-1-z_ij" class="level4" data-number="3.7.1">
<h4 data-number="3.7.1" class="anchored" data-anchor-id="단계-1-z_ij"><span class="header-section-number">3.7.1</span> 단계 1 — <span class="math inline">\(z_{ij}\)</span></h4>
<p><span class="math display">\[
z_{ij} \mid \cdots \sim \text{Bernoulli}(\zeta_{ij})
\]</span></p>
<p>ECM 의 <span class="math inline">\(\zeta_{ij}\)</span> 와 같지만 점이 아닌 표본.</p>
</section>
<section id="단계-2-alpha_j" class="level4" data-number="3.7.2">
<h4 data-number="3.7.2" class="anchored" data-anchor-id="단계-2-alpha_j"><span class="header-section-number">3.7.2</span> 단계 2 — <span class="math inline">\(\alpha_j\)</span></h4>
<p><span class="math display">\[
\alpha_j \mid \cdots \sim N\Bigl(\alpha_j^{\text{new}},\ \frac{1}{\sigma_\alpha^{-2} + 30 \sigma_y^{-2}}\Bigr)
\]</span></p>
<p>식 (22.6) 의 <span class="math inline">\(\alpha_j^{\text{new}}\)</span> 를 평균, denominator 의 inverse 를 분산.</p>
</section>
<section id="단계-3-lambda" class="level4" data-number="3.7.3">
<h4 data-number="3.7.3" class="anchored" data-anchor-id="단계-3-lambda"><span class="header-section-number">3.7.3</span> 단계 3 — <span class="math inline">\(\lambda\)</span></h4>
<p><span class="math display">\[
\lambda \mid \cdots \sim \text{Beta}(h + 1,\ 180 - h + 1)
\]</span></p>
<p><span class="math inline">\(h = \sum_{j,i} z_{ij}\)</span> = 표본에서 delay 된 trial 의 실제 수. Beta-Bernoulli conjugate.</p>
</section>
<section id="단계-4-sigma_y2-sigma_alpha2" class="level4" data-number="3.7.4">
<h4 data-number="3.7.4" class="anchored" data-anchor-id="단계-4-sigma_y2-sigma_alpha2"><span class="header-section-number">3.7.4</span> 단계 4 — <span class="math inline">\(\sigma_y^2, \sigma_\alpha^2\)</span></h4>
<p><span class="math display">\[
\sigma_y^2 \mid \cdots \sim \text{Inv-}\chi^2\Bigl(508,\ \frac{1}{508}\sum_{j,i}(y_{ij} - \alpha_j - z_{ij}\tau)^2\Bigr)
\]</span></p>
<p><span class="math display">\[
\sigma_\alpha^2 \mid \cdots \sim \text{Inv-}\chi^2\Bigl(15,\ \frac{1}{15}\sum_j(\alpha_j - \mu - \beta S_j)^2\Bigr)
\]</span></p>
<p><span class="math inline">\(508 = 17 \times 30 - 17 \cdot \frac{1}{2}\)</span> 형태의 자유도, <span class="math inline">\(15 = 17 - 2\)</span>.</p>
</section>
<section id="단계-5-tau" class="level4" data-number="3.7.5">
<h4 data-number="3.7.5" class="anchored" data-anchor-id="단계-5-tau"><span class="header-section-number">3.7.5</span> 단계 5 — <span class="math inline">\(\tau\)</span></h4>
<p><span class="math display">\[
\tau \mid \cdots \sim N\Bigl(\frac{\sum_{j,i} z_{ij}(y_{ij} - \alpha_j)}{\sum_{j,i} z_{ij}},\ \frac{\sigma_y^2}{\sum_{j,i} z_{ij}}\Bigr)
\]</span></p>
</section>
<section id="단계-6-mu-beta" class="level4" data-number="3.7.6">
<h4 data-number="3.7.6" class="anchored" data-anchor-id="단계-6-mu-beta"><span class="header-section-number">3.7.6</span> 단계 6 — <span class="math inline">\(\mu, \beta\)</span></h4>
<p><span class="math display">\[
\mu \mid \cdots \sim N\Bigl(\frac{1}{17}\sum_j(\alpha_j - \beta S_j),\ \frac{\sigma_\alpha^2}{17}\Bigr)
\]</span></p>
<p><span class="math display">\[
\beta \mid \cdots \sim N\Bigl(\frac{1}{6}\sum_{j=12}^{17}(\alpha_j - \mu),\ \frac{\sigma_\alpha^2}{6}\Bigr) \quad (22.9)
\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — Gibbs 가 ECM 의 stochastic 버전
</div>
</div>
<div class="callout-body-container callout-body">
<table class="table">
<colgroup>
<col style="width: 26%">
<col style="width: 36%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">모수</th>
<th style="text-align: left;">ECM</th>
<th style="text-align: left;">Gibbs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\zeta_{ij}\)</span></td>
<td style="text-align: left;">점 (확률 자체)</td>
<td style="text-align: left;"><span class="math inline">\(\text{Bernoulli}(\zeta_{ij})\)</span> 추출</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\alpha_j\)</span></td>
<td style="text-align: left;">식 (22.6) 의 mean</td>
<td style="text-align: left;">같은 mean, conjugate variance 의 정규</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\sigma^2\)</span></td>
<td style="text-align: left;">sum-of-squares 직접</td>
<td style="text-align: left;">같은 sum-of-squares 의 Inv-<span class="math inline">\(\chi^2\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\lambda\)</span></td>
<td style="text-align: left;"><span class="math inline">\(\zeta\)</span> 평균</td>
<td style="text-align: left;">Beta-Bernoulli 사후</td>
</tr>
</tbody>
</table>
<p><strong>같은 단계, 다른 read</strong>: ECM 은 mode, Gibbs 는 stochastic draw. 따라서 ECM 으로 mode 찾고 → 그 근처 <span class="math inline">\(t_4\)</span> 근사 → importance resampling 으로 Gibbs 시작점 선택, 이 워크플로우가 자연스럽다.</p>
</div>
</div>
</section>
</section>
<section id="degenerate-point-의-위험" class="level3" data-number="3.8">
<h3 data-number="3.8" class="anchored" data-anchor-id="degenerate-point-의-위험"><span class="header-section-number">3.8</span> Degenerate Point 의 위험</h3>
<p><span class="math inline">\(\sum z_{ij} = 0\)</span> 이면 (모든 <span class="math inline">\(z\)</span> 가 0) → <span class="math inline">\(\tau\)</span> 의 conditional 분포 (Step 5) 가 미정의 (분모 0).</p>
<ul>
<li>우연히 발생: 데이터가 mixture 를 강하게 지지하면 unlikely.</li>
<li>발생 가능: 데이터에서 <span class="math inline">\(\sum z = 0\)</span> 이 합리적이면 → <strong><span class="math inline">\(\tau\)</span> 에 informative prior 필수</strong>.</li>
</ul>
<p>이 Schizophrenia 데이터에서는 <span class="math inline">\(\sum z = 0\)</span> 이 사후 확률 <span class="math inline">\(e^{-20}\)</span> 미만이므로 무시 안전.</p>
</section>
<section id="posterior-predictive-checks" class="level3" data-number="3.9">
<h3 data-number="3.9" class="anchored" data-anchor-id="posterior-predictive-checks"><span class="header-section-number">3.9</span> Posterior Predictive Checks</h3>
<p><strong>Test quantities</strong>:</p>
<ul>
<li><span class="math inline">\(T_{\min}, T_{\max}\)</span> = 6 환자의 within-person sd 의 최솟값/최댓값.</li>
</ul>
<section id="원래-모델-결과-figure-22.2" class="level4" data-number="3.9.1">
<h4 data-number="3.9.1" class="anchored" data-anchor-id="원래-모델-결과-figure-22.2"><span class="header-section-number">3.9.1</span> 원래 모델 결과 (Figure 22.2)</h4>
<ul>
<li>Observed <span class="math inline">\(T_{\min} = 0.105\)</span>, sim 의 평균 <span class="math inline">\(\approx 0.20\)</span> → p-value 0.000.</li>
<li>Observed <span class="math inline">\(T_{\max} = 0.55\)</span>, sim 의 평균 <span class="math inline">\(\approx 0.40\)</span> → p-value 1.000.</li>
</ul>
<p>→ <strong>명백한 lack of fit</strong>. 환자별 within-variability 가 모델보다 훨씬 다양.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — 좋은 test quantity 의 원리
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>나쁜</strong>: 평균 <span class="math inline">\(s_j\)</span> — <span class="math inline">\(\sigma_y^2\)</span> 의 sufficient statistic, 모델이 자동 적합.</p>
<p><strong>좋은</strong>: extreme 값 (<span class="math inline">\(T_{\min}, T_{\max}\)</span>) — 분포의 모양에 민감, sufficient statistic 와 직교.</p>
<p>원리: <strong>likelihood 적합에 자동으로 사용된 statistic 의 함수는 검정 의미가 없다</strong>. Posterior predictive p-value 가 항상 0.5 근처 (모델이 자동 잘 맞춤).</p>
<p>따라서 모델이 잡지 못한 <strong>2 차·3 차 모멘트, 극값, tail 형태</strong> 같은 quantity 가 좋은 test.</p>
</div>
</div>
</section>
</section>
<section id="expanded-model-omega-와-sigma_y22" class="level3" data-number="3.10">
<h3 data-number="3.10" class="anchored" data-anchor-id="expanded-model-omega-와-sigma_y22"><span class="header-section-number">3.10</span> Expanded Model — <span class="math inline">\(\omega\)</span> 와 <span class="math inline">\(\sigma_{y2}^2\)</span></h3>
<p>원래 모델 한계: 모든 환자가 같은 <span class="math inline">\(\lambda\)</span>, 같은 <span class="math inline">\(\sigma_y\)</span>.</p>
<p><strong>확장</strong>:</p>
<ul>
<li><span class="math inline">\(\omega\)</span> = 조현병 환자 중 attentional delay 에 취약한 비율.</li>
<li><span class="math inline">\(W_j \in \{0, 1\}\)</span> = 환자 <span class="math inline">\(j\)</span> 가 vulnerable 하면 1.</li>
<li><span class="math inline">\(\sigma_{y2}^2\)</span> = delay 측정의 분산 (별도).</li>
</ul>
<p>수정 모델:</p>
<p><span class="math display">\[
\begin{aligned}
y_{ij} \mid z_{ij}, \theta &amp;\sim N(\alpha_j + \tau z_{ij},\ (1 - z_{ij})\sigma_y^2 + z_{ij} \sigma_{y2}^2) \\
z_{ij} \mid S_j, W_j, \theta &amp;\sim \text{Bernoulli}(\lambda S_j W_j) \\
W_j \mid S_j, \theta &amp;\sim \text{Bernoulli}(\omega S_j)
\end{aligned}
\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — 확장 모델의 패턴
</div>
</div>
<div class="callout-body-container callout-body">
<p>원래 모델 ⊂ 확장 모델 — <strong>nested</strong>.</p>
<ul>
<li><span class="math inline">\(W_j = 1 \forall j\)</span>, <span class="math inline">\(\sigma_{y2}^2 = \sigma_y^2\)</span> 면 원래 모델 복원.</li>
</ul>
<p>확장은 두 가지 source 의 heterogeneity 추가:</p>
<ol type="1">
<li><strong>개체 간</strong> (between-subject): 일부 환자만 vulnerable.</li>
<li><strong>시점 내</strong> (within-trial): delayed trial 의 분산 별도.</li>
</ol>
<p>→ Posterior predictive checks 의 lack of fit 에 <strong>두 새 source 가 직접 대응</strong>.</p>
</div>
</div>
<section id="결과-table-22.1" class="level4" data-number="3.10.1">
<h4 data-number="3.10.1" class="anchored" data-anchor-id="결과-table-22.1"><span class="header-section-number">3.10.1</span> 결과 (Table 22.1)</h4>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">모수</th>
<th style="text-align: left;">원래 [2.5%, median, 97.5%]</th>
<th style="text-align: left;">확장</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\lambda\)</span></td>
<td style="text-align: left;">[0.07, 0.12, 0.18]</td>
<td style="text-align: left;">[0.46, 0.64, 0.88]</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\tau\)</span></td>
<td style="text-align: left;">[0.74, 0.85, 0.96]</td>
<td style="text-align: left;">[0.21, 0.42, 0.60]</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\beta\)</span></td>
<td style="text-align: left;">[0.17, 0.32, 0.48]</td>
<td style="text-align: left;">[0.07, 0.24, 0.43]</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\omega\)</span></td>
<td style="text-align: left;">fixed at 1</td>
<td style="text-align: left;">[0.24, 0.56, 0.84]</td>
</tr>
</tbody>
</table>
<p><strong>해석</strong>:</p>
<ul>
<li><span class="math inline">\(\omega \approx 0.56\)</span>: 조현병 환자의 약 절반만 delay-prone.</li>
<li><span class="math inline">\(\lambda \approx 0.64\)</span>: 그 환자들에서는 더 자주 delay (이전 12% → 64%).</li>
<li><span class="math inline">\(\tau \approx 0.42\)</span>: delay 크기는 더 작음 (이전 0.85 → 0.42).</li>
<li><span class="math inline">\(\beta\)</span> 는 거의 변화 없음 (motor retardation 은 robust).</li>
</ul>
<p><strong>Posterior predictive checks</strong> (Figure 22.3): scale 이 작아짐, p-values <span class="math inline">\(0.97, 0.05\)</span> → 여전히 imperfect 이나 큰 개선.</p>
</section>
</section>
</section>
<section id="label-switching-and-posterior-computation" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="label-switching-and-posterior-computation"><span class="header-section-number">4</span> § 22.3 Label Switching and Posterior Computation</h2>
<section id="식-22.10-exchangeable-prior" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="식-22.10-exchangeable-prior"><span class="header-section-number">4.1</span> 식 (22.10) Exchangeable Prior</h3>
<p>가장 흔한 mixture prior:</p>
<p><span class="math display">\[
(\pi_1, \ldots, \pi_H) \sim \text{Dirichlet}(a, \ldots, a), \qquad \theta_h \sim P_0 \text{ independently} \quad (22.10)
\]</span></p>
<ul>
<li><span class="math inline">\(a\)</span> = symmetric Dirichlet hyperparameter.</li>
<li><span class="math inline">\(P_0\)</span> = component parameter 의 공통 prior (예: normal-inverse-gamma).</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exchangeable prior 의 함의
</div>
</div>
<div class="callout-body-container callout-body">
<p>Prior 가 component label permutation 에 불변 → <strong>사후 marginal of <span class="math inline">\(\theta_h\)</span> 가 모든 <span class="math inline">\(h\)</span> 에서 동일</strong>.</p>
<p>수식으로:</p>
<p><span class="math display">\[
p(\theta_1 \mid y) = p(\theta_2 \mid y) = \cdots = p(\theta_H \mid y)
\]</span></p>
<p>따라서 “component <span class="math inline">\(h\)</span> 의 평균” 의 사후 평균은 모든 <span class="math inline">\(h\)</span> 가 같음 — <strong>무의미</strong>.</p>
<p>이것이 label switching 문제의 본질.</p>
</div>
</div>
</section>
<section id="식-22.1122.12-conjugate-gibbs" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="식-22.1122.12-conjugate-gibbs"><span class="header-section-number">4.2</span> 식 (22.11)~(22.12) Conjugate Gibbs</h3>
<p>일변량 location-scale Gaussian mixture:</p>
<p><span class="math display">\[
y_i \mid z_i \sim N(\mu_{z_i}, \tau_{z_i}^2), \quad \Pr(z_i = h) = \pi_h \quad (22.11)
\]</span></p>
<p><span class="math display">\[
\mu_h, \tau_h^2 \sim N(\mu_h \mid \mu_0, \kappa \tau_h^2) \cdot \text{Inv-Gamma}(\tau_h^2 \mid a_\tau, b_\tau) \quad (22.12)
\]</span></p>
<section id="단계-gibbs" class="level4" data-number="4.2.1">
<h4 data-number="4.2.1" class="anchored" data-anchor-id="단계-gibbs"><span class="header-section-number">4.2.1</span> 3 단계 Gibbs</h4>
<p><strong>Step 1 — <span class="math inline">\(z_i\)</span></strong>:</p>
<p><span class="math display">\[
\Pr(z_i = h \mid \cdots) = \frac{\pi_h N(y_i \mid \mu_h, \tau_h^{-1})}{\sum_l \pi_l N(y_i \mid \mu_l, \tau_l^{-1})}, \quad h = 1, \ldots, H
\]</span></p>
<p><strong>Step 2 — <span class="math inline">\((\mu_h, \tau_h^2)\)</span></strong>:</p>
<p><span class="math display">\[
\widehat\kappa_h = (\kappa^{-1} + n_h)^{-1}, \quad \widehat\mu_h = \widehat\kappa_h(\kappa^{-1}\mu_0 + n_h \bar y_h), \quad \widehat a_{\tau_h} = a_\tau + n_h/2
\]</span></p>
<p><span class="math display">\[
\widehat b_{\tau_h} = b_\tau + \frac{1}{2}\Bigl(\sum_{i: z_i = h}(y_i - \bar y_h)^2 + \frac{n_h}{1 + \kappa n_h}(\bar y_h - \mu_0)^2\Bigr)
\]</span></p>
<p><span class="math display">\[
\mu_h, \tau_h^2 \mid \cdots \sim N(\mu_h \mid \widehat\mu_h, \widehat\kappa_h \tau_h^2) \cdot \text{Inv-Gamma}(\tau_h^2 \mid \widehat a_{\tau_h}, \widehat b_{\tau_h})
\]</span></p>
<p><strong>Step 3 — <span class="math inline">\(\pi\)</span></strong>:</p>
<p><span class="math display">\[
\pi \mid \cdots \sim \text{Dir}(a + n_1, \ldots, a + n_H)
\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — 3 단계 Gibbs 의 분해
</div>
</div>
<div class="callout-body-container callout-body">
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">단계</th>
<th style="text-align: left;">보는 것</th>
<th style="text-align: left;">단순화</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: left;"><span class="math inline">\(z\)</span></td>
<td style="text-align: left;">각 관측치 별 multinomial — <span class="math inline">\(H\)</span> 항만</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: left;"><span class="math inline">\((\mu_h, \tau_h^2)\)</span></td>
<td style="text-align: left;">같은 <span class="math inline">\(z\)</span> 끼리 모은 표준 정규 추정</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: left;"><span class="math inline">\(\pi\)</span></td>
<td style="text-align: left;">Dirichlet conjugate</td>
</tr>
</tbody>
</table>
<p>각 단계가 <strong>표준 conjugate update</strong>. Mixture 의 어려움은 “이 셋을 동시에” — Gibbs 가 conditional 로 분해해 한 번에 한 가지씩.</p>
</div>
</div>
</section>
</section>
<section id="default-hyperparameters" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="default-hyperparameters"><span class="header-section-number">4.3</span> Default Hyperparameters</h3>
<p>데이터 표준화 (<span class="math inline">\(\mu = 0, \text{sd} = 1\)</span>) 후:</p>
<ul>
<li><span class="math inline">\(\mu_0 = 0\)</span> (cluster mean 의 prior 평균).</li>
<li><span class="math inline">\(\kappa = 1\)</span> (cluster mean 의 prior 분산 = <span class="math inline">\(\tau^2\)</span>).</li>
<li><span class="math inline">\(a_\tau = 2, b_\tau = 4\)</span> (분산의 weakly informative).</li>
</ul>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="math inline">\(P_0\)</span> 가 너무 diffuse 하면 나쁜 일
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(P_0\)</span> 가 매우 넓으면 (예: <span class="math inline">\(\kappa = 100\)</span>) → cluster mean 들이 데이터 영역 밖에 무한히 흩어짐 → 데이터가 한 두 cluster 에 모두 집중 → <strong><span class="math inline">\(H_n\)</span> 사후가 부적절히 작아짐</strong>.</p>
<p>따라서 표준화 후 <span class="math inline">\(\mu_0 = 0, \kappa = 1\)</span> 처럼 <strong>데이터 영역과 비슷한 scale</strong> 의 <span class="math inline">\(P_0\)</span> 권장.</p>
</div>
</div>
</section>
<section id="label-switching-의-발생-메커니즘" class="level3" data-number="4.4">
<h3 data-number="4.4" class="anchored" data-anchor-id="label-switching-의-발생-메커니즘"><span class="header-section-number">4.4</span> Label Switching 의 발생 메커니즘</h3>
<p>두 component, <span class="math inline">\(\mu_1 \approx 0\)</span>, <span class="math inline">\(\mu_2 \approx -1\)</span> 의 데이터를 가정.</p>
<p><strong>Well-mixing Gibbs</strong>: <span class="math inline">\(\mu_1\)</span> samples 가 0 과 -1 사이를 빈번히 jump. 사후 marginal <span class="math inline">\(p(\mu_h \mid y)\)</span> 는 두 mode (0 과 -1).</p>
<p><strong>현실의 Gibbs</strong>: 두 mode 사이 low density gap 때문에 <strong>장기간 한 mode 에 머무름</strong> → “5000 sample 동안 <span class="math inline">\(\mu_1 \approx 0\)</span>, 갑자기 switch 후 <span class="math inline">\(\mu_1 \approx -1\)</span>”.</p>
<p>따라서:</p>
<ul>
<li><strong>Density estimate <span class="math inline">\(g(y) = \sum_h \pi_h N(y \mid \mu_h, \tau_h^2)\)</span></strong>: switch 에 불변. 잘 추정.</li>
<li><strong>Component-specific mean <span class="math inline">\(\mu_1\)</span></strong>: 의미 없는 사후 평균.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — 왜 density 는 무관, <span class="math inline">\(\mu_h\)</span> 는 문제인가
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(g(y)\)</span> 는 <strong>합</strong> <span class="math inline">\(\sum_h\)</span> 형태. <span class="math inline">\(h\)</span> 의 라벨이 바뀌어도 합은 같음 — exchangeable.</p>
<p><span class="math inline">\(\mu_h\)</span> 는 <strong>개별 component</strong> — 라벨이 바뀌면 다른 의미.</p>
<p>따라서 mixture 모델의 “유효한 inference” 는 <strong>switching invariant quantity</strong>:</p>
<ul>
<li>Density at any <span class="math inline">\(y\)</span>.</li>
<li><span class="math inline">\(H_n\)</span> (occupied components 수).</li>
<li>“어느 두 관측치가 같은 cluster” 의 확률 (co-clustering matrix).</li>
<li>분류 정확도 (downstream task).</li>
</ul>
<p><strong>무효한</strong>: <span class="math inline">\(\mu_h, \tau_h, \pi_h\)</span> 의 marginal 추정.</p>
</div>
</div>
</section>
<section id="postprocessing-stephens-2000-kl-loss" class="level3" data-number="4.5">
<h3 data-number="4.5" class="anchored" data-anchor-id="postprocessing-stephens-2000-kl-loss"><span class="header-section-number">4.5</span> Postprocessing — Stephens (2000) KL Loss</h3>
<p>라벨 정렬 알고리즘:</p>
<ol type="1">
<li>Gibbs samples <span class="math inline">\(\theta^{(s)} = (\mu^{(s)}, \tau^{(s)}, \pi^{(s)})\)</span>, <span class="math inline">\(s = 1, \ldots, S\)</span>.</li>
<li><strong>Reference</strong> action <span class="math inline">\(a\)</span> (현재 추정치, 예: 평균 <span class="math inline">\(\bar\theta\)</span>).</li>
<li>각 sample 에 permutation <span class="math inline">\(\sigma_s \in S_H\)</span> 적용해 KL loss 최소화: <span class="math display">\[
\sigma_s = \arg\min_\sigma L\bigl(a, \sigma(\theta^{(s)})\bigr)
\]</span></li>
<li><strong>반복</strong>: 새 reference <span class="math inline">\(a\)</span> 를 정렬된 sample 의 평균으로 업데이트, 다시 permutation 갱신, 수렴 시까지.</li>
</ol>
<section id="kl-loss-의-형태" class="level4" data-number="4.5.1">
<h4 data-number="4.5.1" class="anchored" data-anchor-id="kl-loss-의-형태"><span class="header-section-number">4.5.1</span> KL loss 의 형태</h4>
<p><span class="math inline">\(L(a, \theta) = \sum_i \text{KL}\bigl(p_a(z_i = \cdot \mid y_i) \,\|\, p_\theta(z_i = \cdot \mid y_i)\bigr)\)</span>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — KL loss 가 하는 일
</div>
</div>
<div class="callout-body-container callout-body">
<p>각 관측치 <span class="math inline">\(i\)</span> 의 cluster assignment 분포가 reference 와 정렬되도록 라벨을 매김.</p>
<p>즉, “관측치 1 이 cluster A 에 속할 확률, 2 가 B 에 속할 확률…” 가 reference 와 가장 일치하도록.</p>
<p><strong>다변량·차원 무관</strong> — order constraint 처럼 “어느 차원으로 정렬” 을 결정할 필요 없음.</p>
</div>
</div>
</section>
</section>
<section id="order-constraint-한계" class="level3" data-number="4.6">
<h3 data-number="4.6" class="anchored" data-anchor-id="order-constraint-한계"><span class="header-section-number">4.6</span> Order Constraint — 한계</h3>
<p><span class="math inline">\(\mu_1 &lt; \mu_2 &lt; \cdots &lt; \mu_H\)</span> 강제.</p>
<section id="한계-1-다변량" class="level4" data-number="4.6.1">
<h4 data-number="4.6.1" class="anchored" data-anchor-id="한계-1-다변량"><span class="header-section-number">4.6.1</span> 한계 1 — 다변량</h4>
<p><span class="math inline">\(\mu_h\)</span> 가 벡터면 어느 차원으로 정렬? 첫 번째? norm? 어느 것도 자연스럽지 않음.</p>
</section>
<section id="한계-2-평균이-가까울-때" class="level4" data-number="4.6.2">
<h4 data-number="4.6.2" class="anchored" data-anchor-id="한계-2-평균이-가까울-때"><span class="header-section-number">4.6.2</span> 한계 2 — 평균이 가까울 때</h4>
<p><span class="math inline">\(\mu_1 = 0.5, \mu_2 = 0.6\)</span> 에 약간의 noise 가 있으면, sampling 중 순서가 자주 뒤집힘 → constraint 가 작동하지 않음.</p>
</section>
<section id="한계-3-variance-만-다른-component" class="level4" data-number="4.6.3">
<h4 data-number="4.6.3" class="anchored" data-anchor-id="한계-3-variance-만-다른-component"><span class="header-section-number">4.6.3</span> 한계 3 — Variance 만 다른 component</h4>
<p><span class="math inline">\(\mu_1 = \mu_2 = 0\)</span>, <span class="math inline">\(\sigma_1 = 0.1, \sigma_2 = 1.0\)</span> 의 normal mixture (heavy tail 표현) — 평균 정렬로는 식별 불가.</p>
</section>
<section id="한계-4-order-에-의한-bias" class="level4" data-number="4.6.4">
<h4 data-number="4.6.4" class="anchored" data-anchor-id="한계-4-order-에-의한-bias"><span class="header-section-number">4.6.4</span> 한계 4 — Order 에 의한 bias</h4>
<p><span class="math inline">\(\mu_h\)</span> 가 사후적으로 비슷해야 하는데 constraint 가 강제로 분리 → <strong>차이를 부풀림</strong>.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
실무 권장
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Density estimation 만 목적</strong>:</p>
<ul>
<li>Label switching 무시.</li>
<li>사후 평균 density <span class="math inline">\(\hat g(y) = \frac{1}{S} \sum_s \sum_h \pi_h^{(s)} N(y \mid \mu_h^{(s)}, \tau_h^{(s)2})\)</span> 만 보고.</li>
</ul>
<p><strong>Cluster-specific 해석 필요</strong>:</p>
<ul>
<li>Stephens KL loss postprocessing.</li>
<li>또는 informative prior 로 component identification (예: <span class="math inline">\(\mu_h\)</span> 에 데이터-기반 위치 prior).</li>
</ul>
<p><strong>다변량 + cluster 해석</strong>:</p>
<ul>
<li>Postprocessing 만이 실용적. Order constraint 는 거의 불가능.</li>
</ul>
</div>
</div>
</section>
</section>
</section>
<section id="핵심-수식-통합" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="핵심-수식-통합"><span class="header-section-number">5</span> 핵심 수식 통합</h2>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">번호</th>
<th style="text-align: left;">수식</th>
<th style="text-align: left;">의미</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">(22.1)</td>
<td style="text-align: left;"><span class="math inline">\(p(y_i) = \sum_h \lambda_h f(y_i \mid \theta_h)\)</span></td>
<td style="text-align: left;">Finite mixture</td>
</tr>
<tr class="even">
<td style="text-align: center;">(22.2)</td>
<td style="text-align: left;"><span class="math inline">\(p(y, z) = \prod_i \prod_h (\lambda_h f(y_i \mid \theta_h))^{z_{ih}}\)</span></td>
<td style="text-align: left;">Joint with indicator</td>
</tr>
<tr class="odd">
<td style="text-align: center;">(22.5)</td>
<td style="text-align: left;"><span class="math inline">\(\zeta_{ij} = \frac{\lambda N(\cdots, \alpha_j + \tau)}{(1-\lambda)N(\cdots, \alpha_j) + \lambda N(\cdots, \alpha_j + \tau)}\)</span></td>
<td style="text-align: left;">E-step (Bayes rule)</td>
</tr>
<tr class="even">
<td style="text-align: center;">(22.6)</td>
<td style="text-align: left;"><span class="math inline">\(\alpha_j^{\text{new}} = \frac{\sigma_\alpha^{-2}(\mu + \beta S_j) + \sigma_y^{-2}\sum_i (y_{ij} - \zeta_{ij}\tau)}{\sigma_\alpha^{-2} + n_j \sigma_y^{-2}}\)</span></td>
<td style="text-align: left;">M-step normal weighted</td>
</tr>
<tr class="odd">
<td style="text-align: center;">(22.7)</td>
<td style="text-align: left;"><span class="math inline">\(\mu^{\text{new}}, \beta^{\text{new}}\)</span> 의 평균 형태</td>
<td style="text-align: left;">M-step group mean</td>
</tr>
<tr class="even">
<td style="text-align: center;">(22.10)</td>
<td style="text-align: left;"><span class="math inline">\(\pi \sim \text{Dir}(a, \ldots, a),\ \theta_h \sim P_0\)</span></td>
<td style="text-align: left;">Exchangeable prior</td>
</tr>
<tr class="odd">
<td style="text-align: center;">(22.11)</td>
<td style="text-align: left;"><span class="math inline">\(y_i \mid z_i \sim N(\mu_{z_i}, \tau_{z_i}^2)\)</span></td>
<td style="text-align: left;">Location-scale mixture</td>
</tr>
<tr class="even">
<td style="text-align: center;">(22.12)</td>
<td style="text-align: left;"><span class="math inline">\(\mu_h, \tau_h^2 \sim N \cdot \text{Inv-Gamma}\)</span></td>
<td style="text-align: left;">Conjugate prior</td>
</tr>
</tbody>
</table>
</section>
<section id="실행-예제-schizophrenia-모델-단순화-gibbs-pymc" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="실행-예제-schizophrenia-모델-단순화-gibbs-pymc"><span class="header-section-number">6</span> 실행 예제 — Schizophrenia 모델 단순화 + Gibbs (PyMC)</h2>
<div class="sourceCode" id="cb2"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb2-2"><a href="#cb2-2"></a><span class="im">import</span> pymc <span class="im">as</span> pm</span>
<span id="cb2-3"><a href="#cb2-3"></a><span class="im">import</span> arviz <span class="im">as</span> az</span>
<span id="cb2-4"><a href="#cb2-4"></a></span>
<span id="cb2-5"><a href="#cb2-5"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">0</span>)</span>
<span id="cb2-6"><a href="#cb2-6"></a></span>
<span id="cb2-7"><a href="#cb2-7"></a><span class="co"># simulate data similar to Belin-Rubin 1990</span></span>
<span id="cb2-8"><a href="#cb2-8"></a>n_normal <span class="op">=</span> <span class="dv">11</span></span>
<span id="cb2-9"><a href="#cb2-9"></a>n_schizo <span class="op">=</span> <span class="dv">6</span></span>
<span id="cb2-10"><a href="#cb2-10"></a>n_trials <span class="op">=</span> <span class="dv">30</span></span>
<span id="cb2-11"><a href="#cb2-11"></a></span>
<span id="cb2-12"><a href="#cb2-12"></a><span class="co"># true parameters</span></span>
<span id="cb2-13"><a href="#cb2-13"></a>mu_true <span class="op">=</span> <span class="fl">6.0</span>      <span class="co"># baseline log RT</span></span>
<span id="cb2-14"><a href="#cb2-14"></a>beta_true <span class="op">=</span> <span class="fl">0.3</span>    <span class="co"># motor retardation for schizophrenics</span></span>
<span id="cb2-15"><a href="#cb2-15"></a>sigma_alpha <span class="op">=</span> <span class="fl">0.2</span>  <span class="co"># individual variation</span></span>
<span id="cb2-16"><a href="#cb2-16"></a>sigma_y <span class="op">=</span> <span class="fl">0.25</span>     <span class="co"># within-individual variation</span></span>
<span id="cb2-17"><a href="#cb2-17"></a>tau_true <span class="op">=</span> <span class="fl">0.85</span>    <span class="co"># attentional delay magnitude</span></span>
<span id="cb2-18"><a href="#cb2-18"></a>lam_true <span class="op">=</span> <span class="fl">0.12</span>    <span class="co"># attentional delay frequency</span></span>
<span id="cb2-19"><a href="#cb2-19"></a></span>
<span id="cb2-20"><a href="#cb2-20"></a>S <span class="op">=</span> np.array([<span class="dv">0</span>]<span class="op">*</span>n_normal <span class="op">+</span> [<span class="dv">1</span>]<span class="op">*</span>n_schizo)</span>
<span id="cb2-21"><a href="#cb2-21"></a>alpha_true <span class="op">=</span> mu_true <span class="op">+</span> beta_true <span class="op">*</span> S <span class="op">+</span> rng.normal(<span class="dv">0</span>, sigma_alpha, n_normal <span class="op">+</span> n_schizo)</span>
<span id="cb2-22"><a href="#cb2-22"></a></span>
<span id="cb2-23"><a href="#cb2-23"></a>y <span class="op">=</span> np.zeros((n_normal <span class="op">+</span> n_schizo, n_trials))</span>
<span id="cb2-24"><a href="#cb2-24"></a><span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(n_normal <span class="op">+</span> n_schizo):</span>
<span id="cb2-25"><a href="#cb2-25"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(n_trials):</span>
<span id="cb2-26"><a href="#cb2-26"></a>        <span class="cf">if</span> S[j] <span class="op">==</span> <span class="dv">1</span> <span class="kw">and</span> rng.uniform() <span class="op">&lt;</span> lam_true:</span>
<span id="cb2-27"><a href="#cb2-27"></a>            y[j, i] <span class="op">=</span> rng.normal(alpha_true[j] <span class="op">+</span> tau_true, sigma_y)  <span class="co"># delayed</span></span>
<span id="cb2-28"><a href="#cb2-28"></a>        <span class="cf">else</span>:</span>
<span id="cb2-29"><a href="#cb2-29"></a>            y[j, i] <span class="op">=</span> rng.normal(alpha_true[j], sigma_y)</span>
<span id="cb2-30"><a href="#cb2-30"></a></span>
<span id="cb2-31"><a href="#cb2-31"></a><span class="co"># Bayesian mixture model</span></span>
<span id="cb2-32"><a href="#cb2-32"></a><span class="cf">with</span> pm.Model() <span class="im">as</span> schizo_model:</span>
<span id="cb2-33"><a href="#cb2-33"></a>    <span class="co"># population params</span></span>
<span id="cb2-34"><a href="#cb2-34"></a>    mu <span class="op">=</span> pm.Normal(<span class="st">"mu"</span>, <span class="dv">6</span>, <span class="dv">1</span>)</span>
<span id="cb2-35"><a href="#cb2-35"></a>    beta <span class="op">=</span> pm.Normal(<span class="st">"beta"</span>, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb2-36"><a href="#cb2-36"></a>    sigma_alpha <span class="op">=</span> pm.HalfNormal(<span class="st">"sigma_alpha"</span>, <span class="fl">0.5</span>)</span>
<span id="cb2-37"><a href="#cb2-37"></a>    sigma_y_param <span class="op">=</span> pm.HalfNormal(<span class="st">"sigma_y"</span>, <span class="fl">0.5</span>)</span>
<span id="cb2-38"><a href="#cb2-38"></a>    tau <span class="op">=</span> pm.HalfNormal(<span class="st">"tau"</span>, <span class="dv">1</span>)  <span class="co"># positivity for identifiability</span></span>
<span id="cb2-39"><a href="#cb2-39"></a>    lam <span class="op">=</span> pm.Beta(<span class="st">"lambda"</span>, <span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb2-40"><a href="#cb2-40"></a></span>
<span id="cb2-41"><a href="#cb2-41"></a>    <span class="co"># individual random effects</span></span>
<span id="cb2-42"><a href="#cb2-42"></a>    alpha <span class="op">=</span> pm.Normal(<span class="st">"alpha"</span>, mu <span class="op">+</span> beta <span class="op">*</span> S, sigma_alpha,</span>
<span id="cb2-43"><a href="#cb2-43"></a>                      shape<span class="op">=</span>n_normal <span class="op">+</span> n_schizo)</span>
<span id="cb2-44"><a href="#cb2-44"></a></span>
<span id="cb2-45"><a href="#cb2-45"></a>    <span class="co"># likelihood per trial — marginalize z analytically</span></span>
<span id="cb2-46"><a href="#cb2-46"></a>    <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(n_normal <span class="op">+</span> n_schizo):</span>
<span id="cb2-47"><a href="#cb2-47"></a>        <span class="cf">if</span> S[j] <span class="op">==</span> <span class="dv">0</span>:  <span class="co"># normal: no mixture</span></span>
<span id="cb2-48"><a href="#cb2-48"></a>            pm.Normal(<span class="ss">f"y_</span><span class="sc">{</span>j<span class="sc">}</span><span class="ss">"</span>, mu<span class="op">=</span>alpha[j], sigma<span class="op">=</span>sigma_y_param,</span>
<span id="cb2-49"><a href="#cb2-49"></a>                      observed<span class="op">=</span>y[j])</span>
<span id="cb2-50"><a href="#cb2-50"></a>        <span class="cf">else</span>:  <span class="co"># schizophrenic: two-component mixture</span></span>
<span id="cb2-51"><a href="#cb2-51"></a>            comp_undelayed <span class="op">=</span> pm.Normal.dist(mu<span class="op">=</span>alpha[j], sigma<span class="op">=</span>sigma_y_param)</span>
<span id="cb2-52"><a href="#cb2-52"></a>            comp_delayed <span class="op">=</span> pm.Normal.dist(mu<span class="op">=</span>alpha[j] <span class="op">+</span> tau, sigma<span class="op">=</span>sigma_y_param)</span>
<span id="cb2-53"><a href="#cb2-53"></a>            pm.Mixture(<span class="ss">f"y_</span><span class="sc">{</span>j<span class="sc">}</span><span class="ss">"</span>, w<span class="op">=</span>[<span class="dv">1</span> <span class="op">-</span> lam, lam],</span>
<span id="cb2-54"><a href="#cb2-54"></a>                       comp_dists<span class="op">=</span>[comp_undelayed, comp_delayed],</span>
<span id="cb2-55"><a href="#cb2-55"></a>                       observed<span class="op">=</span>y[j])</span>
<span id="cb2-56"><a href="#cb2-56"></a></span>
<span id="cb2-57"><a href="#cb2-57"></a>    trace <span class="op">=</span> pm.sample(<span class="dv">1500</span>, tune<span class="op">=</span><span class="dv">1500</span>, target_accept<span class="op">=</span><span class="fl">0.95</span>, chains<span class="op">=</span><span class="dv">4</span>)</span>
<span id="cb2-58"><a href="#cb2-58"></a></span>
<span id="cb2-59"><a href="#cb2-59"></a><span class="bu">print</span>(az.summary(trace, var_names<span class="op">=</span>[<span class="st">"mu"</span>, <span class="st">"beta"</span>, <span class="st">"tau"</span>, <span class="st">"lambda"</span>,</span>
<span id="cb2-60"><a href="#cb2-60"></a>                                    <span class="st">"sigma_alpha"</span>, <span class="st">"sigma_y"</span>]))</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
코드 가이드
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Identifiability</strong>: <code>tau = HalfNormal</code> 로 양수 강제 — 식별성 보장.</li>
<li><strong>Mixture analytic marginalization</strong>: PyMC 의 <code>pm.Mixture</code> 가 latent <span class="math inline">\(z_{ij}\)</span> 를 자동 적분. ECM 의 명시적 <span class="math inline">\(\zeta_{ij}\)</span> 가 internal 로 처리.</li>
<li><strong>정상은 mixture 아님</strong>: <span class="math inline">\(S_j = 0\)</span> 환자는 단일 정규로 분기. 모델의 <span class="math inline">\(S_j\)</span> 조건부 구조 그대로.</li>
<li><strong>HMC vs Gibbs</strong>: PyMC 의 default 는 NUTS (HMC). Conjugate Gibbs 보다 hyperparameter 처리에 robust. 필요시 <code>pm.sample(step=pm.Slice())</code> 등 변경 가능.</li>
</ul>
</div>
</div>
</section>
<section id="실전-체크리스트-22.122.3" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="실전-체크리스트-22.122.3"><span class="header-section-number">7</span> 실전 체크리스트 — § 22.1~22.3</h2>
<p><strong>§ 22.1 Setup</strong></p>
<ol type="1">
<li><strong>Mixture 가 정말 필요한가</strong>: conditioning 변수 (성별, 그룹) 가 관측 가능하면 그것을 우선.</li>
<li><strong><span class="math inline">\(H\)</span> 결정</strong>: 도메인 지식 ↔︎ WAIC ↔︎ truncated upper bound 중 선택.</li>
<li><strong>Component 가족 <span class="math inline">\(f\)</span></strong>: 정규 default, <span class="math inline">\(t\)</span> robust, 다변량 <span class="math inline">\(\Sigma\)</span> 형태 결정.</li>
<li><strong>Continuous mixture</strong>: hierarchical model, <span class="math inline">\(t\)</span>, neg-binomial 모두 같은 framework.</li>
</ol>
<p><strong>Prior</strong></p>
<ol start="5" type="1">
<li><strong>분산 prior</strong>: 자유 분산이면 <strong>proper 필수</strong>. Inverse-Gamma 권장.</li>
<li><strong>Boundary 회피</strong>: <span class="math inline">\(\lambda \in [0.001, 0.999]\)</span>, $&gt; $ 작은 양수.</li>
<li><strong>식별성 제약</strong>: <span class="math inline">\(\tau &gt; 0\)</span> 같은 부호 제약 또는 <span class="math inline">\(\mu\)</span> 순서 제약.</li>
</ol>
<p><strong>§ 22.2 ECM·Gibbs</strong></p>
<ol start="8" type="1">
<li><strong>Crude estimate</strong> 100 개 (random perturbation) 로 starting points.</li>
<li><strong>ECM 100 회</strong> 로 mode 찾고 multiple mode 점검.</li>
<li><strong>Mode → <span class="math inline">\(t_4\)</span> 근사 → importance resampling</strong> 으로 Gibbs 시작점.</li>
<li><strong>Gibbs 6 단계</strong> 의 각 conditional 표준 형태 확인.</li>
<li>Likelihood 가 ECM 매 iteration 에서 monotone increase 인지 검증.</li>
</ol>
<p><strong>Posterior Predictive</strong></p>
<ol start="13" type="1">
<li><strong>Sufficient statistic 외 quantity</strong> 를 test 로 (예: 극값, 분위수).</li>
<li>p-value 가 0 또는 1 에 가까우면 lack of fit → 모델 확장.</li>
<li><strong>확장</strong> 은 nested 형태로 (원래 모델이 special case) — 비교 가능.</li>
</ol>
<p><strong>§ 22.3 Label Switching</strong></p>
<ol start="16" type="1">
<li><strong>Density estimation 만</strong>: switching 무시, 사후 평균 density 계산.</li>
<li><strong>Cluster-specific 추론</strong>: Stephens KL loss postprocessing.</li>
<li><strong>Order constraint 권장 안 함</strong>: 다변량에서는 사실상 불가능.</li>
<li><strong>수렴 진단</strong>: <span class="math inline">\(\widehat R\)</span> 은 density 또는 switching-invariant quantity 에 대해.</li>
</ol>
</section>
<section id="관련-주제" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="관련-주제"><span class="header-section-number">8</span> 관련 주제</h2>
<p><strong>Ch.22 시리즈</strong></p>
<ul>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/04-22-0-finite-mixture-overview.html">Ch.22 Overview</a></li>
</ul>
<p><strong>선행 지식</strong></p>
<ul>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/00-5-0-hierarchical.html">Ch.5 Hierarchical Models</a> — Continuous mixture 의 일반론</li>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/02-13-2-em-conditional-marginal-hierarchical.html">Ch.13 § 13.4 — EM Algorithm</a> — ECM 이론적 기반</li>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/03-17-0-robust-inference-overview.html">Ch.17 Robust Inference Overview</a> — <span class="math inline">\(t\)</span> 분포 = scale mixture</li>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/00-4-2-frequency-bayesian-interp.html">Ch.4 § 4.3 — Aliasing</a> — Label ambiguity 의 원형</li>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/01-6-0-model-checking.html">Ch.6 Model Checking</a> — Posterior predictive</li>
</ul>
<p><strong>후속 주제</strong></p>
<ul>
<li><a href="./04-22-2-unspecified-classification-exercises.qmd">Ch.22 § 22.4~22.6 — Unspecified H·Classification·Exercises (예정)</a></li>
<li><a href="./04-23-0-dirichlet-process-overview.qmd">Ch.23 Dirichlet Process Models Overview (예정)</a></li>
</ul>
<p><strong>관련 개념 (cross-category)</strong></p>
<ul>
<li><a href="../../Machine_Learning/em-algorithm.qmd">EM Algorithm and ECM</a></li>
<li><a href="../../Machine_Learning/gaussian-mixture-model.qmd">Gaussian Mixture Models (sklearn)</a></li>
<li><a href="../latent-class-analysis.qmd">Latent Class Analysis</a></li>
<li><a href="../../Machine_Learning/variational-mixture.qmd">Variational Inference for Mixture</a></li>
</ul>
</section>
<section id="참고문헌" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="참고문헌"><span class="header-section-number">9</span> 참고문헌</h2>
<ul>
<li>Gelman, A., Carlin, J. B., Stern, H. S., Dunson, D. B., Vehtari, A., &amp; Rubin, D. B. (2013). <em>Bayesian Data Analysis</em> (3rd ed.), Ch.22 § 22.1~22.3. CRC Press.</li>
<li>Belin, T. R., &amp; Rubin, D. B. (1990). Analysis of a Finite Mixture Model with Variance Components. <em>Proceedings of the Social Statistics Section, ASA</em>. (Schizophrenia 데이터 출처)</li>
<li>Dempster, A. P., Laird, N. M., &amp; Rubin, D. B. (1977). Maximum Likelihood from Incomplete Data via the EM Algorithm. <em>JRSS B</em>, 39(1), 1-38.</li>
<li>Meng, X.-L., &amp; Rubin, D. B. (1993). Maximum Likelihood Estimation via the ECM Algorithm: A General Framework. <em>Biometrika</em>, 80(2), 267-278.</li>
<li>Stephens, M. (2000). Dealing with Label Switching in Mixture Models. <em>JRSS B</em>, 62(4), 795-809. (KL loss postprocessing)</li>
<li>Diebolt, J., &amp; Robert, C. P. (1994). Estimation of Finite Mixture Distributions through Bayesian Sampling. <em>JRSS B</em>, 56(2), 363-375. (Mixture Gibbs 원전)</li>
<li>Celeux, G., Hurn, M., &amp; Robert, C. P. (2000). Computational and Inferential Difficulties with Mixture Posterior Distributions. <em>JASA</em>, 95(451), 957-970.</li>
<li>Jasra, A., Holmes, C. C., &amp; Stephens, D. A. (2005). Markov Chain Monte Carlo Methods and the Label Switching Problem in Bayesian Mixture Modeling. <em>Statistical Science</em>, 20(1), 50-67.</li>
<li>McLachlan, G. J., &amp; Peel, D. (2000). <em>Finite Mixture Models</em>. Wiley.</li>
<li>Fruhwirth-Schnatter, S. (2006). <em>Finite Mixture and Markov Switching Models</em>. Springer.</li>
</ul>


</section>

</main> <!-- /main -->
<script type="text/javascript">

// replace cmd keyboard shortcut w/ control on non-Mac platforms
const kPlatformMac = typeof navigator !== 'undefined' ? /Mac/.test(navigator.platform) : false;
if (!kPlatformMac) {
   var kbds = document.querySelectorAll("kbd")
   kbds.forEach(function(kbd) {
      kbd.innerHTML = kbd.innerHTML.replace(/⌘/g, '⌃');
   });
}

// tweak headings in pymd
document.querySelectorAll(".pymd span.co").forEach(el => {
   if (!el.innerText.startsWith("#|")) {
      el.style.fontWeight = 1000;
   }
});

</script>
<!-- Begin Mailchimp Signup Form -->
<div id="mc_embed_signup" style="padding-bottom: 1em; max-width: 400px;" class="ms-auto me-auto">
  <p style="font-weight: 600; margin-bottom: 0;">Subscribe</p>
  <span style="font-size: 0.9em;">Enjoy this blog? Get notified of new posts by email:</span>
<form action="https://quarto.us14.list-manage.com/subscribe/post?u=c79fb56a311ae347fbe916740&amp;id=ec05dfca03" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate="">
    <div id="mc_embed_signup_scroll">
	
        <div class="input-group mt-1 mb-2">
        <input type="email" class="form-control" placeholder="Email Address" aria-label="Email Address" name="EMAIL" style="font-size: 0.8em; padding: .2em;">
        </div>              

	<div id="mce-responses" class="clear foot">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_c79fb56a311ae347fbe916740_ec05dfca03" tabindex="-1" value=""></div>
        <div class="optionalParent">
            <div class="clear foot" style="display: flex; align-items: center; justify-content: center;">
              
              
                <input type="submit" value="Subscribe" name="subscribe" style="min-width: 150px; font-size: 0.8em;" id="mc-embedded-subscribe" class="button btn btn-light btn-sm ms-auto me-auto">
            </div>
        </div>
    </div>
</form>
</div>

<!--End mc_embed_signup-->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "복사완료!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "복사완료!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="kmink3225/blog" data-repo-id="R_kgDOLCZyDg" data-category="Blog" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script>
<input type="hidden" id="giscus-base-theme" value="light">
<input type="hidden" id="giscus-alt-theme" value="dark">
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Kwangmin Kim</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="../../../../../about.html">
<p>About</p>
</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/kmink3225/blog">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>