<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ko" xml:lang="ko"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.543">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kwangmin Kim">
<meta name="description" content="Gelman BDA Ch.22 의 § 22.4~22.7 을 한 편으로 깊게 다룬다. § 22.4 알려지지 않은 H 의 처리 — truncated upper bound 의 핵심 아이디어, Dirichlet a = n_0/H 가 stick-breaking 으로 sparse weights 유도하는 메커니즘, Gamma representation 으로 본 빈 component 자동 형성, Ishwaran-Zarepour 와 Rousseau-Mengersen 의 이론적 정당화, H_n vs H 의 차이, galaxy 82점·acidity 155점·iris 150점 사례의 cluster 수 추정, Tables 22.2~22.4 결과 해석. § 22.5 mixture 를 분류·회귀로 — Bayesian discriminant analysis 의 Dirichlet 조건부 갱신, class-conditional density 를 mixture of multivariate normals 로, 식 + product kernel 로 categorical/continuous 혼합 predictor 처리, semi-supervised 확장, 식 (22.13) joint density 의 mixture, 식 (22.14)~(22.15) predictor-dependent regression weights 의 “mixture of experts” 해석, joint modeling 의 4 가지 한계. § 22.6 bibliographic note 핵심 정리 + § 22.7 연습문제 8개 (cluster point estimate·overfitted mixture·long-tail·galaxy density·football point spread·kidney cancer·improper prior 위험·Dirichlet sparsity asymptotics) 단계별 풀이. Ch.22 시리즈 4편 (overview·§ 22.1~22.3·§ 22.4~22.7) 의 핵심 수식·발견·체크리스트 결산 + Ch.23 DP 로의 사다리.">

<title>Kwangmin Kim - Ch.22 § 22.4~22.7 심화 — Unspecified H · Classification · Regression · 연습 + Ch.22 결산</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../../../">
<script src="../../../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../../../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../../../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": true,
  "language": {
    "search-no-results-text": "일치 없음",
    "search-matching-documents-text": "일치된 문서",
    "search-copy-link-title": "검색 링크 복사",
    "search-hide-matches-text": "추가 검색 결과 숨기기",
    "search-more-match-text": "추가 검색결과",
    "search-more-matches-text": "추가 검색결과",
    "search-clear-button-title": "제거",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "취소",
    "search-submit-button-title": "검색",
    "search-label": "검색"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-6W0EKFMWBN"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-6W0EKFMWBN', { 'anonymize_ip': true});
</script>
<style>

      .quarto-title-block .quarto-title-banner h1,
      .quarto-title-block .quarto-title-banner h2,
      .quarto-title-block .quarto-title-banner h3,
      .quarto-title-block .quarto-title-banner h4,
      .quarto-title-block .quarto-title-banner h5,
      .quarto-title-block .quarto-title-banner h6
      {
        color: black;
      }

      .quarto-title-block .quarto-title-banner {
        color: black;
background: #EDF3F9;
      }
</style>
<style>
.custom-footer { 
  text-align: center; 
  font-size: 0.8em; 
  color: #666; 
  margin-top: 2rem; 
}
</style>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../../../styles.css">
<meta property="og:title" content="Kwangmin Kim - Ch.22 § 22.4~22.7 심화 — Unspecified H · Classification · Regression · 연습 + Ch.22 결산">
<meta property="og:description" content="Gelman BDA Ch.22 의 § 22.4~22.7 을 한 편으로 깊게 다룬다. § 22.4 알려지지 않은 \(H\) 의 처리 — truncated upper bound 의 핵심 아이디어, Dirichlet \(a = n_0/H\) 가 stick-breaking 으로 sparse weights 유도하는 메커니즘, Gamma representation 으로 본 빈 component 자동 형성, Ishwaran-Zarepour 와 Rousseau-Mengersen 의 이론적 정당화, \(H_n\) vs \(H\) 의 차이, galaxy 82점·acidity 155점·iris 150점 사례의 cluster 수 추정, Tables 22.2~22.4 결과 해석. § 22.5 mixture 를 분류·회귀로 — Bayesian discriminant analysis 의 Dirichlet 조건부 갱신, class-conditional density 를 mixture of multivariate normals 로, 식 + product kernel 로 categorical/continuous 혼합 predictor 처리, semi-supervised 확장, 식 (22.13) joint density 의 mixture, 식 (22.14)~(22.15) predictor-dependent regression weights 의 “mixture of experts” 해석, joint modeling 의 4 가지 한계. § 22.6 bibliographic note 핵심 정리 + § 22.7 연습문제 8개 (cluster point estimate·overfitted mixture·long-tail·galaxy density·football point spread·kidney cancer·improper prior 위험·Dirichlet sparsity asymptotics) 단계별 풀이. Ch.22 시리즈 4편 (overview·§ 22.1~22.3·§ 22.4~22.7) 의 핵심 수식·발견·체크리스트 결산 + Ch.23 DP 로의 사다리.">
<meta property="og:site_name" content="Kwangmin Kim">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../../../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../../../.././images/logo.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../../../../index.html">
    <span class="navbar-title">Kwangmin Kim</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="검색"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="탐색 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../../docs/blog/index.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../../../about.html"> 
<span class="menu-text">Me</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/kmink3225"> <i class="bi bi-github" role="img" aria-label="Github">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/kwangmin-kim-a5241b200/"> <i class="bi bi-linkedin" role="img" aria-label="Linkedin">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../../../../docs/blog/index.xml"> <i class="bi bi-rss" role="img" aria-label="RSS">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="다크 모드 전환"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Ch.22 § 22.4~22.7 심화 — Unspecified H · Classification · Regression · 연습 + Ch.22 결산</h1>
            <p class="subtitle lead">Truncated upper bound + 식 (22.10) sparse Dirichlet <span class="math inline">\(a = n_0/H\)</span> 정당화 (Ishwaran-Zarepour 2002, Rousseau-Mengersen 2011)·galaxy/acidity/iris 사례·Bayesian discriminant analysis·식 (22.13)~(22.15) joint regression mixture·연습문제 8개·Ch.22 시리즈 4편 결산</p>
                  <div>
        <div class="description">
          <p>Gelman BDA Ch.22 의 § 22.4~22.7 을 한 편으로 깊게 다룬다. § 22.4 알려지지 않은 <span class="math inline">\(H\)</span> 의 처리 — truncated upper bound 의 핵심 아이디어, Dirichlet <span class="math inline">\(a = n_0/H\)</span> 가 stick-breaking 으로 sparse weights 유도하는 메커니즘, Gamma representation 으로 본 빈 component 자동 형성, Ishwaran-Zarepour 와 Rousseau-Mengersen 의 이론적 정당화, <span class="math inline">\(H_n\)</span> vs <span class="math inline">\(H\)</span> 의 차이, galaxy 82점·acidity 155점·iris 150점 사례의 cluster 수 추정, Tables 22.2~22.4 결과 해석. § 22.5 mixture 를 분류·회귀로 — Bayesian discriminant analysis 의 Dirichlet 조건부 갱신, class-conditional density 를 mixture of multivariate normals 로, 식 + product kernel 로 categorical/continuous 혼합 predictor 처리, semi-supervised 확장, 식 (22.13) joint density 의 mixture, 식 (22.14)~(22.15) predictor-dependent regression weights 의 “mixture of experts” 해석, joint modeling 의 4 가지 한계. § 22.6 bibliographic note 핵심 정리 + § 22.7 연습문제 8개 (cluster point estimate·overfitted mixture·long-tail·galaxy density·football point spread·kidney cancer·improper prior 위험·Dirichlet sparsity asymptotics) 단계별 풀이. Ch.22 시리즈 4편 (overview·§ 22.1~22.3·§ 22.4~22.7) 의 핵심 수식·발견·체크리스트 결산 + Ch.23 DP 로의 사다리.</p>
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">Statistics</div>
                <div class="quarto-category">Bayesian</div>
                <div class="quarto-category">Mixture-Models</div>
                <div class="quarto-category">Classification</div>
                <div class="quarto-category">Regression</div>
                <div class="quarto-category">Nonparametric-Bayes</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">저자</div>
      <div class="quarto-title-meta-contents">
               <p>Kwangmin Kim </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">공개</div>
      <div class="quarto-title-meta-contents">
        <p class="date">2026년 04월 27일</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">목차</h2>
   
  <ul>
  <li><a href="#들어가며-ch.22-시리즈의-자리" id="toc-들어가며-ch.22-시리즈의-자리" class="nav-link active" data-scroll-target="#들어가며-ch.22-시리즈의-자리"><span class="header-section-number">1</span> 들어가며 — Ch.22 시리즈의 자리</a></li>
  <li><a href="#unspecified-number-of-mixture-components-truncated-upper-bound" id="toc-unspecified-number-of-mixture-components-truncated-upper-bound" class="nav-link" data-scroll-target="#unspecified-number-of-mixture-components-truncated-upper-bound"><span class="header-section-number">2</span> § 22.4 Unspecified Number of Mixture Components — Truncated Upper Bound</a>
  <ul class="collapse">
  <li><a href="#동기-rjmcmc-의-대안" id="toc-동기-rjmcmc-의-대안" class="nav-link" data-scroll-target="#동기-rjmcmc-의-대안"><span class="header-section-number">2.1</span> 동기 — RJMCMC 의 대안</a></li>
  <li><a href="#식-22.10-재방문-a-의-효과" id="toc-식-22.10-재방문-a-의-효과" class="nav-link" data-scroll-target="#식-22.10-재방문-a-의-효과"><span class="header-section-number">2.2</span> 식 (22.10) 재방문 — <span class="math inline">\(a\)</span> 의 효과</a></li>
  <li><a href="#stick-breaking-표현으로-보는-a-n_0h" id="toc-stick-breaking-표현으로-보는-a-n_0h" class="nav-link" data-scroll-target="#stick-breaking-표현으로-보는-a-n_0h"><span class="header-section-number">2.3</span> Stick-Breaking 표현으로 보는 <span class="math inline">\(a = n_0/H\)</span></a></li>
  <li><a href="#이론적-정당화-ishwaran-zarepour-rousseau-mengersen" id="toc-이론적-정당화-ishwaran-zarepour-rousseau-mengersen" class="nav-link" data-scroll-target="#이론적-정당화-ishwaran-zarepour-rousseau-mengersen"><span class="header-section-number">2.4</span> 이론적 정당화 — Ishwaran-Zarepour, Rousseau-Mengersen</a></li>
  <li><a href="#h_n-occupied-components-수" id="toc-h_n-occupied-components-수" class="nav-link" data-scroll-target="#h_n-occupied-components-수"><span class="header-section-number">2.5</span> <span class="math inline">\(H_n\)</span> — Occupied Components 수</a></li>
  <li><a href="#galaxy-acidity-iris-사례" id="toc-galaxy-acidity-iris-사례" class="nav-link" data-scroll-target="#galaxy-acidity-iris-사례"><span class="header-section-number">2.6</span> Galaxy / Acidity / Iris 사례</a></li>
  <li><a href="#default-hyperparameters-실무-권장" id="toc-default-hyperparameters-실무-권장" class="nav-link" data-scroll-target="#default-hyperparameters-실무-권장"><span class="header-section-number">2.7</span> Default Hyperparameters (실무 권장)</a></li>
  </ul></li>
  <li><a href="#mixture-for-classification-and-regression" id="toc-mixture-for-classification-and-regression" class="nav-link" data-scroll-target="#mixture-for-classification-and-regression"><span class="header-section-number">3</span> § 22.5 Mixture for Classification and Regression</a>
  <ul class="collapse">
  <li><a href="#bayesian-discriminant-analysis-dirichlet-갱신" id="toc-bayesian-discriminant-analysis-dirichlet-갱신" class="nav-link" data-scroll-target="#bayesian-discriminant-analysis-dirichlet-갱신"><span class="header-section-number">3.1</span> Bayesian Discriminant Analysis — Dirichlet 갱신</a></li>
  <li><a href="#class-conditional-density-의-mixture" id="toc-class-conditional-density-의-mixture" class="nav-link" data-scroll-target="#class-conditional-density-의-mixture"><span class="header-section-number">3.2</span> Class-Conditional Density 의 Mixture</a></li>
  <li><a href="#gibbs-sampler-discriminant-analysis" id="toc-gibbs-sampler-discriminant-analysis" class="nav-link" data-scroll-target="#gibbs-sampler-discriminant-analysis"><span class="header-section-number">3.3</span> Gibbs Sampler — Discriminant Analysis</a></li>
  <li><a href="#product-kernel-mixed-type-predictors" id="toc-product-kernel-mixed-type-predictors" class="nav-link" data-scroll-target="#product-kernel-mixed-type-predictors"><span class="header-section-number">3.4</span> Product Kernel — Mixed-Type Predictors</a></li>
  <li><a href="#식-22.13-joint-modeling-for-regression" id="toc-식-22.13-joint-modeling-for-regression" class="nav-link" data-scroll-target="#식-22.13-joint-modeling-for-regression"><span class="header-section-number">3.5</span> 식 (22.13) Joint Modeling for Regression</a></li>
  </ul></li>
  <li><a href="#bibliographic-note" id="toc-bibliographic-note" class="nav-link" data-scroll-target="#bibliographic-note"><span class="header-section-number">4</span> § 22.6 Bibliographic Note</a>
  <ul class="collapse">
  <li><a href="#emvbep" id="toc-emvbep" class="nav-link" data-scroll-target="#emvbep"><span class="header-section-number">4.1</span> EM·VB·EP</a></li>
  <li><a href="#mcmc-for-mixtures" id="toc-mcmc-for-mixtures" class="nav-link" data-scroll-target="#mcmc-for-mixtures"><span class="header-section-number">4.2</span> MCMC for Mixtures</a></li>
  <li><a href="#sparse-dirichlet-theory" id="toc-sparse-dirichlet-theory" class="nav-link" data-scroll-target="#sparse-dirichlet-theory"><span class="header-section-number">4.3</span> Sparse Dirichlet Theory</a></li>
  <li><a href="#응용" id="toc-응용" class="nav-link" data-scroll-target="#응용"><span class="header-section-number">4.4</span> 응용</a></li>
  <li><a href="#surveys" id="toc-surveys" class="nav-link" data-scroll-target="#surveys"><span class="header-section-number">4.5</span> Surveys</a></li>
  </ul></li>
  <li><a href="#exercises-8-문제-풀이" id="toc-exercises-8-문제-풀이" class="nav-link" data-scroll-target="#exercises-8-문제-풀이"><span class="header-section-number">5</span> § 22.7 Exercises — 8 문제 풀이</a>
  <ul class="collapse">
  <li><a href="#exercise-1-cluster-point-estimate-mean-vs-median-vs-mode" id="toc-exercise-1-cluster-point-estimate-mean-vs-median-vs-mode" class="nav-link" data-scroll-target="#exercise-1-cluster-point-estimate-mean-vs-median-vs-mode"><span class="header-section-number">5.1</span> Exercise 1 — Cluster Point Estimate (Mean vs Median vs Mode)</a></li>
  <li><a href="#exercise-2-overfitted-mixture-3-234unspecified" id="toc-exercise-2-overfitted-mixture-3-234unspecified" class="nav-link" data-scroll-target="#exercise-2-overfitted-mixture-3-234unspecified"><span class="header-section-number">5.2</span> Exercise 2 — Overfitted Mixture (3 → 2/3/4/unspecified)</a></li>
  <li><a href="#exercise-3-long-tailed-data-with-normal-mixture" id="toc-exercise-3-long-tailed-data-with-normal-mixture" class="nav-link" data-scroll-target="#exercise-3-long-tailed-data-with-normal-mixture"><span class="header-section-number">5.3</span> Exercise 3 — Long-Tailed Data with Normal Mixture</a></li>
  <li><a href="#exercise-4-galaxy-density-estimation" id="toc-exercise-4-galaxy-density-estimation" class="nav-link" data-scroll-target="#exercise-4-galaxy-density-estimation"><span class="header-section-number">5.4</span> Exercise 4 — Galaxy Density Estimation</a></li>
  <li><a href="#exercise-5-football-point-spread-mixture" id="toc-exercise-5-football-point-spread-mixture" class="nav-link" data-scroll-target="#exercise-5-football-point-spread-mixture"><span class="header-section-number">5.5</span> Exercise 5 — Football Point Spread Mixture</a></li>
  <li><a href="#exercise-6-kidney-cancer-mixture-vs-gamma" id="toc-exercise-6-kidney-cancer-mixture-vs-gamma" class="nav-link" data-scroll-target="#exercise-6-kidney-cancer-mixture-vs-gamma"><span class="header-section-number">5.6</span> Exercise 6 — Kidney Cancer Mixture vs Gamma</a></li>
  <li><a href="#exercise-7-improper-prior-위험" id="toc-exercise-7-improper-prior-위험" class="nav-link" data-scroll-target="#exercise-7-improper-prior-위험"><span class="header-section-number">5.7</span> Exercise 7 — Improper Prior 위험</a></li>
  <li><a href="#exercise-8-dirichlet-sparsity-점근" id="toc-exercise-8-dirichlet-sparsity-점근" class="nav-link" data-scroll-target="#exercise-8-dirichlet-sparsity-점근"><span class="header-section-number">5.8</span> Exercise 8 — Dirichlet Sparsity 점근</a></li>
  </ul></li>
  <li><a href="#ch.22-시리즈-결산" id="toc-ch.22-시리즈-결산" class="nav-link" data-scroll-target="#ch.22-시리즈-결산"><span class="header-section-number">6</span> Ch.22 시리즈 결산</a>
  <ul class="collapse">
  <li><a href="#편의-핵심" id="toc-편의-핵심" class="nav-link" data-scroll-target="#편의-핵심"><span class="header-section-number">6.1</span> 4 편의 핵심</a></li>
  <li><a href="#ch.22-의-핵심-수식-통합" id="toc-ch.22-의-핵심-수식-통합" class="nav-link" data-scroll-target="#ch.22-의-핵심-수식-통합"><span class="header-section-number">6.2</span> Ch.22 의 핵심 수식 통합</a></li>
  <li><a href="#ch.22-의-시퀀스-점점-큰-일반화" id="toc-ch.22-의-시퀀스-점점-큰-일반화" class="nav-link" data-scroll-target="#ch.22-의-시퀀스-점점-큰-일반화"><span class="header-section-number">6.3</span> Ch.22 의 시퀀스 — 점점 큰 일반화</a></li>
  <li><a href="#ch.22-의-유산과-한계" id="toc-ch.22-의-유산과-한계" class="nav-link" data-scroll-target="#ch.22-의-유산과-한계"><span class="header-section-number">6.4</span> Ch.22 의 유산과 한계</a></li>
  </ul></li>
  <li><a href="#ch.22-시리즈-통합-체크리스트" id="toc-ch.22-시리즈-통합-체크리스트" class="nav-link" data-scroll-target="#ch.22-시리즈-통합-체크리스트"><span class="header-section-number">7</span> Ch.22 시리즈 통합 체크리스트</a></li>
  <li><a href="#관련-주제" id="toc-관련-주제" class="nav-link" data-scroll-target="#관련-주제"><span class="header-section-number">8</span> 관련 주제</a></li>
  <li><a href="#참고문헌" id="toc-참고문헌" class="nav-link" data-scroll-target="#참고문헌"><span class="header-section-number">9</span> 참고문헌</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="들어가며-ch.22-시리즈의-자리" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="들어가며-ch.22-시리즈의-자리"><span class="header-section-number">1</span> 들어가며 — Ch.22 시리즈의 자리</h2>
<p>Ch.22 의 사다리 마지막 편:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">편</th>
<th style="text-align: left;">주제</th>
<th style="text-align: left;">핵심</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><a href="../../../../../docs/blog/posts/Statistics/bayesian/04-22-0-finite-mixture-overview.html">Overview (04-22-0)</a></td>
<td style="text-align: left;">Ch.22 큰 그림</td>
<td style="text-align: left;">5 절 조망</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="../../../../../docs/blog/posts/Statistics/bayesian/04-22-1-setup-schizophrenia-label-switching.html">§ 22.1~22.3 (04-22-1)</a></td>
<td style="text-align: left;">정의·적합·식별</td>
<td style="text-align: left;">식 (22.1)~(22.7)·Gibbs·식 (22.10)~(22.12)·label switching</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>§ 22.4~22.7 (본 편)</strong></td>
<td style="text-align: left;"><strong>알려지지 않은 H · 응용 · 연습</strong></td>
<td style="text-align: left;">Truncated + sparse Dirichlet·classification·regression·exercises·Ch.22 결산</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
본 편이 답하는 다섯 가지 질문
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><span class="math inline">\(H\)</span> 가 미지일 때 RJMCMC 의 복잡함을 피하면서 “올바른 <span class="math inline">\(H\)</span>” 를 자동 선택하는 단순한 방법은? (§ 22.4)</li>
<li>왜 Dirichlet <span class="math inline">\(a = n_0/H\)</span> 가 <span class="math inline">\(H\)</span> 큰 upper bound 하에서도 작은 <span class="math inline">\(H_n\)</span> 을 favor 하는가? (Ishwaran-Zarepour 정당화)</li>
<li>Mixture 가 분류 (discriminant analysis) 와 회귀 (mixture of experts) 에서 어떻게 비모수 도구로 작동하는가? (§ 22.5)</li>
<li>식 (22.13) joint modeling 과 conditional modeling 의 trade-off 는 무엇인가?</li>
<li>§ 22.7 의 8 연습문제가 점검하는 mixture 의 8 측면은?</li>
</ol>
</div>
</div>
</section>
<section id="unspecified-number-of-mixture-components-truncated-upper-bound" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="unspecified-number-of-mixture-components-truncated-upper-bound"><span class="header-section-number">2</span> § 22.4 Unspecified Number of Mixture Components — Truncated Upper Bound</h2>
<section id="동기-rjmcmc-의-대안" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="동기-rjmcmc-의-대안"><span class="header-section-number">2.1</span> 동기 — RJMCMC 의 대안</h3>
<p>§ 22.1 끝에서 본 <span class="math inline">\(H\)</span> 결정 4 접근 중 가장 단순한 truncated upper bound + sparse Dirichlet 을 본 절에서 깊게.</p>
<p>기존 방법의 문제:</p>
<ul>
<li><strong>여러 <span class="math inline">\(H\)</span> 비교</strong> (WAIC, LOO): <span class="math inline">\(H\)</span> 의 사후 불확실성 무시. 단일 <span class="math inline">\(\widehat H\)</span> 에 conditional 한 inference.</li>
<li><strong>계층적 <span class="math inline">\(H\)</span> + RJMCMC</strong> (Richardson-Green 1997): <span class="math inline">\(H\)</span> 가 변할 때 dimension change 처리 필요. 구현 복잡.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — Truncated upper bound 의 영리함
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>핵심 아이디어</strong>: <span class="math inline">\(H\)</span> 를 충분히 큰 값 (예: <span class="math inline">\(H = 20, 50\)</span>) 으로 고정하고, prior 가 자동으로 <strong>불필요한 component 를 빈 cluster로</strong> 만들도록 한다.</p>
<ul>
<li>“<span class="math inline">\(H\)</span> 가 진짜로 큰가” 질문 회피.</li>
<li>RJMCMC 같은 dimension change 회피.</li>
<li>표준 Gibbs sampler 가 그대로 작동.</li>
</ul>
<p>대신 prior 의 hyperparameter <span class="math inline">\(a\)</span> 를 <strong><span class="math inline">\(H\)</span> 에 따라 조정</strong> 해야 한다 — 그것이 식 <span class="math inline">\(a = n_0/H\)</span>.</p>
</div>
</div>
</section>
<section id="식-22.10-재방문-a-의-효과" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="식-22.10-재방문-a-의-효과"><span class="header-section-number">2.2</span> 식 (22.10) 재방문 — <span class="math inline">\(a\)</span> 의 효과</h3>
<p><span class="math inline">\(\pi = (\pi_1, \ldots, \pi_H) \sim \text{Dirichlet}(a, \ldots, a)\)</span>.</p>
<p><strong><span class="math inline">\(a = 1\)</span></strong> (uniform on simplex):</p>
<ul>
<li>모든 <span class="math inline">\(\pi_h\)</span> 가 비슷한 크기로 추출되는 경향.</li>
<li><span class="math inline">\(H\)</span> 클수록 <span class="math inline">\(\pi_h \approx 1/H\)</span> 평균값.</li>
<li>데이터를 모든 component 에 분산 → <span class="math inline">\(H_n \approx H\)</span> → cluster 수 결정 무용.</li>
</ul>
<p><strong><span class="math inline">\(a = n_0/H\)</span></strong> (sparse, <span class="math inline">\(n_0\)</span> 고정):</p>
<ul>
<li><span class="math inline">\(H\)</span> 클수록 <span class="math inline">\(a\)</span> 작음.</li>
<li>작은 <span class="math inline">\(a\)</span> 의 Dirichlet 은 <strong>simplex 의 corner</strong> 근처에 집중.</li>
<li>결과: 소수 <span class="math inline">\(\pi_h\)</span> 가 큰 값, 나머지 거의 0 → <strong>자동 sparsity</strong>.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — <span class="math inline">\(a\)</span> 가 작을 때 Dirichlet 의 거동
</div>
</div>
<div class="callout-body-container callout-body">
<p>3-차원 simplex 를 시각화하자 (3 component 비율).</p>
<ul>
<li><span class="math inline">\(a = 5\)</span>: 중앙 (1/3, 1/3, 1/3) 에 집중 — uniform component.</li>
<li><span class="math inline">\(a = 1\)</span>: simplex 전체에 평탄.</li>
<li><span class="math inline">\(a = 0.1\)</span>: 세 vertex (1, 0, 0), (0, 1, 0), (0, 0, 1) 근처에 집중 — <strong>거의 단일 component</strong>.</li>
<li><span class="math inline">\(a = 0.01\)</span>: 더 강하게 vertex 집중.</li>
</ul>
<p>따라서 <span class="math inline">\(a\)</span> 가 작을수록 Dirichlet 은 <strong>“확률을 한두 component 에 몰빵”</strong> 을 favor.</p>
</div>
</div>
</section>
<section id="stick-breaking-표현으로-보는-a-n_0h" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="stick-breaking-표현으로-보는-a-n_0h"><span class="header-section-number">2.3</span> Stick-Breaking 표현으로 보는 <span class="math inline">\(a = n_0/H\)</span></h3>
<p>Dirichlet 의 stick-breaking 표현:</p>
<p><span class="math display">\[
\lambda_h \sim \text{Gamma}(a, 1), \qquad \pi_h = \frac{\lambda_h}{\sum_l \lambda_l}
\]</span></p>
<ul>
<li><span class="math inline">\(a\)</span> 작으면 <span class="math inline">\(\text{Gamma}(a, 1)\)</span> 의 사후 mode 가 0 근처 (heavy density at small values).</li>
<li>대부분 <span class="math inline">\(\lambda_h\)</span> 가 0 근처, 소수가 right tail.</li>
<li>정규화 후 → <strong>소수 큰 <span class="math inline">\(\pi\)</span> + 다수 작은 <span class="math inline">\(\pi\)</span></strong> 의 분포.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — <span class="math inline">\(a = n_0/H\)</span> 에서 <span class="math inline">\(H \to \infty\)</span> 한계
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(H\)</span> 가 매우 크면 <span class="math inline">\(a = n_0/H \to 0\)</span>:</p>
<ul>
<li>거의 모든 <span class="math inline">\(\lambda_h\)</span> 가 0 → 거의 모든 <span class="math inline">\(\pi_h\)</span> 가 0.</li>
<li>Right tail 의 소수만 유의미한 weight.</li>
</ul>
<p>이것이 정확히 <strong>Dirichlet Process</strong> 의 stick-breaking (Sethuraman 1994). <span class="math inline">\(H \to \infty\)</span> 한계에서 truncated finite mixture 가 DP 로 수렴 — Ch.23 의 동기.</p>
<p><strong>Ch.22 의 truncated 모델 = Ch.23 DP 의 finite approximation</strong>.</p>
<p>따라서 본 절의 <span class="math inline">\(a = n_0/H\)</span> 가 “마법의 숫자” 가 아니라 DP prior 의 자연스러운 truncation.</p>
</div>
</div>
</section>
<section id="이론적-정당화-ishwaran-zarepour-rousseau-mengersen" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="이론적-정당화-ishwaran-zarepour-rousseau-mengersen"><span class="header-section-number">2.4</span> 이론적 정당화 — Ishwaran-Zarepour, Rousseau-Mengersen</h3>
<p><strong>Ishwaran &amp; Zarepour (2002)</strong>: <span class="math inline">\(a = \alpha/H\)</span> Dirichlet 으로 <span class="math inline">\(H\)</span> 큰 truncation 에 대해 <strong>DP mixture 와 사후가 거의 동일</strong>.</p>
<p><strong>Rousseau &amp; Mengersen (2011)</strong>: Overfitted mixture (true <span class="math inline">\(H_0 &lt; H\)</span>) 에서 redundant component 가 사후적으로 <strong>0 으로 수렴</strong> (<span class="math inline">\(a \leq d/2\)</span>, <span class="math inline">\(d\)</span> = component parameter 차원).</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
자동 sparsity 의 메커니즘
</div>
</div>
<div class="callout-body-container callout-body">
<p>Marginal likelihood:</p>
<p><span class="math display">\[
p(y \mid H) = \int p(y, z, \theta, \pi \mid H) dz d\theta d\pi
\]</span></p>
<p><span class="math inline">\(H\)</span> 가 크면 추가 dimension (component parameter) 의 적분이 marginal 을 줄임 — <strong>complexity penalty</strong>. 자동으로 더 작은 <span class="math inline">\(H_n\)</span> 이 사후적으로 선호.</p>
<p>Bayesian Occam’s razor 의 mixture 버전.</p>
</div>
</div>
</section>
<section id="h_n-occupied-components-수" class="level3" data-number="2.5">
<h3 data-number="2.5" class="anchored" data-anchor-id="h_n-occupied-components-수"><span class="header-section-number">2.5</span> <span class="math inline">\(H_n\)</span> — Occupied Components 수</h3>
<p><span class="math display">\[
H_n = \sum_{h=1}^H 1_{n_h &gt; 0}, \quad n_h = \sum_i z_{ih}
\]</span></p>
<p><span class="math inline">\(H_n\)</span> 은 <strong>MCMC 의 매 iteration 에서 데이터가 실제 사용한 component 수</strong>. <span class="math inline">\(H\)</span> 는 upper bound, <span class="math inline">\(H_n\)</span> 은 effective.</p>
<p>추정 절차:</p>
<ol type="1">
<li><span class="math inline">\(H = 20\)</span> (또는 도메인이 허용하는 큰 값) 으로 Gibbs.</li>
<li>각 iteration 의 <span class="math inline">\(H_n\)</span> 기록.</li>
<li><span class="math inline">\(H_n\)</span> 사후 분포 → mode 또는 평균이 effective cluster 수.</li>
</ol>
<p>이상적으로 <span class="math inline">\(H_n\)</span> 의 사후가 <span class="math inline">\(H\)</span> (upper bound) 에 무관해야 한다 (sufficiently large <span class="math inline">\(H\)</span>). <span class="math inline">\(a = n_0/H\)</span> 가 이 안정성을 보장.</p>
</section>
<section id="galaxy-acidity-iris-사례" class="level3" data-number="2.6">
<h3 data-number="2.6" class="anchored" data-anchor-id="galaxy-acidity-iris-사례"><span class="header-section-number">2.6</span> Galaxy / Acidity / Iris 사례</h3>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">데이터</th>
<th style="text-align: center;"><span class="math inline">\(n\)</span></th>
<th style="text-align: center;">차원</th>
<th style="text-align: center;">upper <span class="math inline">\(H\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\widehat H_n\)</span></th>
<th style="text-align: left;">비고</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Galaxy</td>
<td style="text-align: center;">82</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">~3</td>
<td style="text-align: left;">후퇴 속도, multimodal 의심</td>
</tr>
<tr class="even">
<td style="text-align: left;">Acidity</td>
<td style="text-align: center;">155</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">5</td>
<td style="text-align: center;">2 or 3</td>
<td style="text-align: left;">위스콘신 호수 산성도</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Iris</td>
<td style="text-align: center;">150</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">6</td>
<td style="text-align: center;">~3</td>
<td style="text-align: left;">3 species 와 일치</td>
</tr>
</tbody>
</table>
<section id="galaxy-table-22.2" class="level4" data-number="2.6.1">
<h4 data-number="2.6.1" class="anchored" data-anchor-id="galaxy-table-22.2"><span class="header-section-number">2.6.1</span> Galaxy (Table 22.2)</h4>
<p>5 component 사후 평균:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;"><span class="math inline">\(h\)</span></th>
<th style="text-align: center;">1</th>
<th style="text-align: center;">2</th>
<th style="text-align: center;">3</th>
<th style="text-align: center;">4</th>
<th style="text-align: center;">5</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\pi_h\)</span></td>
<td style="text-align: center;">0.66</td>
<td style="text-align: center;">0.16</td>
<td style="text-align: center;">0.06</td>
<td style="text-align: center;">0.09</td>
<td style="text-align: center;">0.03</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\mu_h\)</span></td>
<td style="text-align: center;">0.10</td>
<td style="text-align: center;">0.20</td>
<td style="text-align: center;">1.89</td>
<td style="text-align: center;">-2.35</td>
<td style="text-align: center;">0.02</td>
</tr>
</tbody>
</table>
<p><span class="math inline">\(\pi_1 = 0.66\)</span> 의 dominant component (origin 근처), 나머지는 outlier 또는 작은 cluster.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — Galaxy 결과의 신뢰성
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(\pi_5 = 0.03\)</span> (3%) 의 component 는 <strong>단 2~3 점만 흡수</strong> — single observation 가까운 cluster 위험.</p>
<p>해석 가이드:</p>
<ul>
<li><span class="math inline">\(\pi_h \cdot n &gt; 5\)</span>: 신뢰 가능한 cluster.</li>
<li><span class="math inline">\(\pi_h \cdot n \in [1, 5]\)</span>: 의심스러운 cluster (overfitting 가능성).</li>
<li><span class="math inline">\(\pi_h \cdot n &lt; 1\)</span>: 거의 무시 가능 (사실상 빈 component).</li>
</ul>
</div>
</div>
</section>
<section id="acidity-table-22.3" class="level4" data-number="2.6.2">
<h4 data-number="2.6.2" class="anchored" data-anchor-id="acidity-table-22.3"><span class="header-section-number">2.6.2</span> Acidity (Table 22.3)</h4>
<p>5 component 결과 → 사실상 <strong>2~3 cluster</strong> (한 cluster 가 skewed 라 정규로는 2 component 로 분리).</p>
</section>
<section id="iris-table-22.4" class="level4" data-number="2.6.3">
<h4 data-number="2.6.3" class="anchored" data-anchor-id="iris-table-22.4"><span class="header-section-number">2.6.3</span> Iris (Table 22.4)</h4>
<p>4 차원, 6 upper bound. 결과: <span class="math inline">\(\pi\)</span> 가 큰 3 component 가 setosa, versicolor, virginica 에 거의 일치. 작은 weight 의 추가 component 는 <strong>species 분포가 정확히 정규가 아닌 부분</strong> 을 보완.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — 통계적 cluster ≠ 생물학적 species
</div>
</div>
<div class="callout-body-container callout-body">
<p>Iris 의 진짜 species 수 = 3, 추정 cluster 수 = 4~5. 왜?</p>
<ul>
<li>Versicolor 와 virginica 는 4 차원 공간에서 약간 겹친다.</li>
<li>정확히 multivariate normal 이 아닌 species 는 mixture 가 추가 component 로 보완.</li>
<li>4 차원 anisotropic distribution 을 spherical normal 로 모델링 → 한 species 가 2 component 로 쪼개짐 가능.</li>
</ul>
<p><strong>경고</strong>: cluster 수를 “ground truth” 로 해석할 때 항상 component family (<span class="math inline">\(f\)</span>) 의 적절성 점검.</p>
</div>
</div>
</section>
</section>
<section id="default-hyperparameters-실무-권장" class="level3" data-number="2.7">
<h3 data-number="2.7" class="anchored" data-anchor-id="default-hyperparameters-실무-권장"><span class="header-section-number">2.7</span> Default Hyperparameters (실무 권장)</h3>
<p>데이터 표준화 후:</p>
<ul>
<li><span class="math inline">\(a = n_0/H = 1/H\)</span> — minimal informative (<span class="math inline">\(n_0 = 1\)</span>).</li>
<li><span class="math inline">\(\mu_0 = 0, \kappa = 1\)</span> — cluster mean prior.</li>
<li><span class="math inline">\(a_\tau = 3, b_\tau = 1\)</span> — variance prior (실 사례에서 좋은 default, BDA recommends).</li>
</ul>
<p><strong>다변량</strong>:</p>
<ul>
<li>$H = $ 최대 그럴듯한 cluster 수 (도메인) + 약간의 여유.</li>
<li><span class="math inline">\(\Sigma_h\)</span> 가정: diagonal (단순) vs full (유연하나 overfitting 위험). 데이터 차원 + <span class="math inline">\(n\)</span> 에 따라.</li>
</ul>
</section>
</section>
<section id="mixture-for-classification-and-regression" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="mixture-for-classification-and-regression"><span class="header-section-number">3</span> § 22.5 Mixture for Classification and Regression</h2>
<section id="bayesian-discriminant-analysis-dirichlet-갱신" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="bayesian-discriminant-analysis-dirichlet-갱신"><span class="header-section-number">3.1</span> Bayesian Discriminant Analysis — Dirichlet 갱신</h3>
<p>분류: <span class="math inline">\(y \in \{1, \ldots, C\}\)</span>, <span class="math inline">\(x \in \mathbb{R}^p\)</span>.</p>
<section id="bayes-룰의-분리" class="level4" data-number="3.1.1">
<h4 data-number="3.1.1" class="anchored" data-anchor-id="bayes-룰의-분리"><span class="header-section-number">3.1.1</span> Bayes 룰의 분리</h4>
<p><span class="math display">\[
\Pr(y_i = c \mid x_i) = \frac{\psi_c f_c(x_i)}{\sum_{c'} \psi_{c'} f_{c'}(x_i)}
\]</span></p>
<ul>
<li><span class="math inline">\(\psi_c = \Pr(y_i = c)\)</span> — class prior.</li>
<li><span class="math inline">\(f_c(x_i) = f(x_i \mid y_i = c)\)</span> — class-conditional density.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — Discriminative vs Generative
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Discriminative</strong> (logistic, GP classification): <span class="math inline">\(\Pr(y \mid x)\)</span> 직접 모델링.</li>
<li><strong>Generative</strong> (Bayesian discriminant): <span class="math inline">\(\Pr(y) \cdot p(x \mid y)\)</span> 분해 후 Bayes 룰.</li>
</ul>
<p>장점 (generative):</p>
<ul>
<li>Missing <span class="math inline">\(y\)</span> (semi-supervised) 자연 처리.</li>
<li>Missing predictor <span class="math inline">\(x\)</span> 자연 처리.</li>
<li>Class imbalance 표현 명시적.</li>
</ul>
<p>단점 (generative):</p>
<ul>
<li><span class="math inline">\(f_c(x)\)</span> 의 정확한 modeling 필요. 잘못되면 분류 성능 저하.</li>
</ul>
</div>
</div>
</section>
<section id="psi-의-conjugate-갱신" class="level4" data-number="3.1.2">
<h4 data-number="3.1.2" class="anchored" data-anchor-id="psi-의-conjugate-갱신"><span class="header-section-number">3.1.2</span> <span class="math inline">\(\psi\)</span> 의 conjugate 갱신</h4>
<p>Prior: <span class="math inline">\(\psi \sim \text{Dirichlet}(a\psi_{01}, \ldots, a\psi_{0C})\)</span>.</p>
<ul>
<li><span class="math inline">\(\psi_0 = E(\psi)\)</span> — prior mean.</li>
<li><span class="math inline">\(a\)</span> = prior sample size.</li>
</ul>
<p>Fully supervised 사후:</p>
<p><span class="math display">\[
\psi \mid y, X \sim \text{Dirichlet}\Bigl(a\psi_{01} + n_1, \ldots, a\psi_{0C} + n_C\Bigr)
\]</span></p>
<p><span class="math inline">\(n_c = \sum_i 1_{y_i = c}\)</span>. <strong>단순 conjugate</strong> — 분석적 closed form.</p>
</section>
</section>
<section id="class-conditional-density-의-mixture" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="class-conditional-density-의-mixture"><span class="header-section-number">3.2</span> Class-Conditional Density 의 Mixture</h3>
<p><span class="math inline">\(f_c(x_i)\)</span> 를 단일 정규로 가정하면 class 가 “단봉 + 정규” 라는 강한 가정. 실제 class 분포는 multimodal 또는 skewed 가능 → mixture 로 표현:</p>
<p><span class="math display">\[
f_c(x_i) = \sum_{h=1}^H \pi_{ch} N_p(x_i \mid \mu_{ch}^*, \Sigma_{ch}^*)
\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — 두 단계 mixture
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>외부</strong>: 각 class <span class="math inline">\(c\)</span> 가 자기만의 mixture distribution.</li>
<li><strong>내부</strong>: 그 mixture 가 <span class="math inline">\(H\)</span> 개 multivariate normal.</li>
</ul>
<p>응용:</p>
<ul>
<li><strong>음성 인식</strong>: 같은 음소 (class) 라도 발화자·억양에 따라 acoustic feature 가 multimodal → mixture.</li>
<li><strong>이미지 객체</strong>: 같은 객체 class (개) 라도 종·각도·조명에 따라 분포가 multimodal.</li>
<li><strong>의료</strong>: 같은 질병 class 라도 환자 subset 에 따라 임상 feature 분포 다름.</li>
</ul>
</div>
</div>
<section id="단순화-공통-weights" class="level4" data-number="3.2.1">
<h4 data-number="3.2.1" class="anchored" data-anchor-id="단순화-공통-weights"><span class="header-section-number">3.2.1</span> 단순화 — 공통 weights</h4>
<p>Computational tractability 를 위해 <span class="math inline">\(\pi_{ch} = \pi_h\)</span> (class-independent weights):</p>
<ul>
<li>모든 class 가 같은 mixture component 집합 사용.</li>
<li>차이는 <span class="math inline">\((\mu_{ch}^*, \Sigma_{ch}^*)\)</span> 의 class-specific values.</li>
<li><span class="math inline">\(\pi \sim \text{Dirichlet}(1/H, \ldots, 1/H)\)</span> — sparse.</li>
<li><span class="math inline">\((\mu_{ch}^*, \Sigma_{ch}^*) \sim\)</span> normal-inverse-Wishart conjugate.</li>
</ul>
</section>
</section>
<section id="gibbs-sampler-discriminant-analysis" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="gibbs-sampler-discriminant-analysis"><span class="header-section-number">3.3</span> Gibbs Sampler — Discriminant Analysis</h3>
<p>매 iteration:</p>
<section id="step-1-z_i-multinomial" class="level4" data-number="3.3.1">
<h4 data-number="3.3.1" class="anchored" data-anchor-id="step-1-z_i-multinomial"><span class="header-section-number">3.3.1</span> Step 1 — <span class="math inline">\(z_i\)</span> multinomial</h4>
<p><span class="math display">\[
\Pr(z_i = h \mid y_i = c, \cdots) = \frac{\pi_h N_p(x_i \mid \mu_{ch}^*, \Sigma_{ch}^*)}{\sum_{h'} \pi_{h'} N_p(x_i \mid \mu_{ch'}^*, \Sigma_{ch'}^*)}
\]</span></p>
</section>
<section id="step-2-psi-dirichlet" class="level4" data-number="3.3.2">
<h4 data-number="3.3.2" class="anchored" data-anchor-id="step-2-psi-dirichlet"><span class="header-section-number">3.3.2</span> Step 2 — <span class="math inline">\(\psi\)</span> Dirichlet</h4>
<p><span class="math inline">\(\psi \mid y \sim \text{Dirichlet}(a\psi_{0c} + n_c)\)</span>.</p>
</section>
<section id="step-3-pi-dirichlet" class="level4" data-number="3.3.3">
<h4 data-number="3.3.3" class="anchored" data-anchor-id="step-3-pi-dirichlet"><span class="header-section-number">3.3.3</span> Step 3 — <span class="math inline">\(\pi\)</span> Dirichlet</h4>
<p><span class="math inline">\(\pi \mid z \sim \text{Dirichlet}(1/H + \sum_{c, i} 1_{y_i = c, z_i = h})\)</span>.</p>
</section>
<section id="step-4-mu_ch-sigma_ch-normal-inverse-wishart" class="level4" data-number="3.3.4">
<h4 data-number="3.3.4" class="anchored" data-anchor-id="step-4-mu_ch-sigma_ch-normal-inverse-wishart"><span class="header-section-number">3.3.4</span> Step 4 — <span class="math inline">\((\mu_{ch}^*, \Sigma_{ch}^*)\)</span> normal-inverse-Wishart</h4>
<p>같은 <span class="math inline">\((c, h)\)</span> 그룹의 데이터로 표준 conjugate 갱신.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Semi-Supervised 확장
</div>
</div>
<div class="callout-body-container callout-body">
<p>Unlabeled <span class="math inline">\(i\)</span> 의 <span class="math inline">\(y_i\)</span> 도 sampling:</p>
<p><span class="math display">\[
\Pr(y_i = c \mid x_i, \cdots) \propto \psi_c f_c(x_i) = \psi_c \sum_h \pi_h N_p(x_i \mid \mu_{ch}^*, \Sigma_{ch}^*)
\]</span></p>
<p>→ 추가 Gibbs step. Unlabeled data 의 cluster 정보가 labeled data 의 추정에 기여 → <strong>분류 성능 향상</strong>.</p>
<p>특히 labeled data 적고 unlabeled 많을 때 (실제 의료 데이터 흔함) 큰 효과.</p>
</div>
</div>
</section>
</section>
<section id="product-kernel-mixed-type-predictors" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="product-kernel-mixed-type-predictors"><span class="header-section-number">3.4</span> Product Kernel — Mixed-Type Predictors</h3>
<p><span class="math inline">\(x_i\)</span> 가 categorical + continuous 혼합일 때:</p>
<p><span class="math display">\[
f(x_i \mid \theta_i) = \prod_{j=1}^p \mathcal{K}_j(x_{ij} \mid \theta_{ij})
\]</span></p>
<ul>
<li><span class="math inline">\(\mathcal{K}_j\)</span> = predictor <span class="math inline">\(j\)</span> 에 적절한 kernel:
<ul>
<li>연속: 정규.</li>
<li>이진: Bernoulli.</li>
<li>count: Poisson.</li>
<li>다범주: multinomial.</li>
</ul></li>
</ul>
<p><strong>문제</strong>: product kernel 은 conditional independence (<span class="math inline">\(\theta_i\)</span> given) 가정. 실제 predictor 간 dependence 는?</p>
<p><strong>해결</strong>: <span class="math inline">\(\theta_i\)</span> 자체를 mixture 로 (<span class="math inline">\(\theta_i \sim \sum_h \pi_h \delta_{\Theta_h}\)</span>). Mixture indicator 를 통해 marginal dependence 유도.</p>
</section>
<section id="식-22.13-joint-modeling-for-regression" class="level3" data-number="3.5">
<h3 data-number="3.5" class="anchored" data-anchor-id="식-22.13-joint-modeling-for-regression"><span class="header-section-number">3.5</span> 식 (22.13) Joint Modeling for Regression</h3>
<p>회귀: <span class="math inline">\(y_i \in \mathbb{R}\)</span>, <span class="math inline">\(x_i \in \mathbb{R}^p\)</span>. <span class="math inline">\(w_i = (y_i, x_i) \in \mathbb{R}^{p+1}\)</span> 의 joint mixture:</p>
<p><span class="math display">\[
f(w_i) = \sum_{h=1}^H \pi_h N_{p+1}(w_i \mid \mu_h, \Sigma_h) \quad (22.13)
\]</span></p>
<section id="식-22.1422.15-conditional-density-유도" class="level4" data-number="3.5.1">
<h4 data-number="3.5.1" class="anchored" data-anchor-id="식-22.1422.15-conditional-density-유도"><span class="header-section-number">3.5.1</span> 식 (22.14)~(22.15) — Conditional Density 유도</h4>
<p>Joint mixture 의 conditional 을 계산하면:</p>
<p><span class="math display">\[
f(y_i \mid x_i) = \sum_{h=1}^H \pi_h(x_i) N(y_i \mid \beta_{0h} + x_i \beta_{1h}, \sigma_h^2) \quad (22.14)
\]</span></p>
<p>predictor-dependent weights:</p>
<p><span class="math display">\[
\pi_h(x_i) = \frac{\pi_h N_p(x_i \mid \mu_h^{(x)}, \Sigma_h^{(x)})}{\sum_{h'} \pi_{h'} N_p(x_i \mid \mu_{h'}^{(x)}, \Sigma_{h'}^{(x)})} \quad (22.15)
\]</span></p>
<ul>
<li><span class="math inline">\(\beta_{0h}, \beta_{1h}\)</span> = <span class="math inline">\(h\)</span>-th component 의 conditional regression 계수.</li>
<li><span class="math inline">\(\sigma_h^2\)</span> = <span class="math inline">\(h\)</span>-th 의 conditional variance.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — Mixture of Experts
</div>
</div>
<div class="callout-body-container callout-body">
<p>식 (22.14) 의 의미:</p>
<blockquote class="blockquote">
<p>“각 <span class="math inline">\(x_i\)</span> 에서 conditional 분포가 <span class="math inline">\(H\)</span> 개 linear regression 의 가중 합. 가중치는 <span class="math inline">\(x_i\)</span> 가 어느 component 의 <span class="math inline">\(x\)</span>-distribution 와 가까운지에 따라.”</p>
</blockquote>
<p>이는 <strong>mixture of experts</strong> (Jacobs et al.&nbsp;1991, Jordan-Jacobs 1994) 와 같은 정신:</p>
<ul>
<li>입력 공간을 “softly partition” — 각 영역에 다른 expert (linear regression).</li>
<li>전체로는 비선형 회귀.</li>
</ul>
<p>차이: mixture of experts 는 gating function 을 명시적 (logistic, neural net) 으로 학습. 식 (22.13)~(22.15) 는 joint <span class="math inline">\(N_{p+1}\)</span> 의 자연스러운 유도.</p>
</div>
</div>
</section>
<section id="joint-modeling-의-4-가지-한계" class="level4" data-number="3.5.2">
<h4 data-number="3.5.2" class="anchored" data-anchor-id="joint-modeling-의-4-가지-한계"><span class="header-section-number">3.5.2</span> Joint Modeling 의 4 가지 한계</h4>
<ol type="1">
<li><strong>Fixed predictor</strong>: <span class="math inline">\(x_i\)</span> 가 design 에 의해 정해진 경우 (실험 설계) → <span class="math inline">\(x\)</span> 에 분포 부여가 부자연스럽다.</li>
<li><strong>Categorical predictor</strong>: <span class="math inline">\(x\)</span> 가 일부 categorical 이면 multivariate normal 부적절 → product kernel 또는 Gaussian copula 필요.</li>
<li><strong>High-dimensional <span class="math inline">\(x\)</span></strong>: <span class="math inline">\(p\)</span> 큼 → marginal <span class="math inline">\(f(x)\)</span> 추정에 막대한 자원, conditional 만 필요한데.</li>
<li><strong>Conditional 단순, joint 복잡</strong>: <span class="math inline">\(y \mid x\)</span> 가 단일 정규로 충분한데 joint 가 multimodal <span class="math inline">\(\Rightarrow\)</span> joint mixture 가 conditional 에 부정확한 노이즈 추가.</li>
</ol>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
실무 권장
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Density estimation 자체가 목적</strong>: joint mixture (식 22.13).</li>
<li><strong>Conditional 만 필요</strong>: conditional mixture 직접 (예: GP regression Ch.21, Bayesian additive regression trees).</li>
<li><strong>Mixed-type <span class="math inline">\(x\)</span></strong>: product kernel + mixture indicator.</li>
<li><strong>High-dim <span class="math inline">\(x\)</span></strong>: feature selection 후 conditional, 또는 sparse joint.</li>
</ul>
</div>
</div>
</section>
</section>
</section>
<section id="bibliographic-note" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="bibliographic-note"><span class="header-section-number">4</span> § 22.6 Bibliographic Note</h2>
<section id="emvbep" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="emvbep"><span class="header-section-number">4.1</span> EM·VB·EP</h3>
<ul>
<li><strong>Dempster, Laird, Rubin (1977)</strong> — EM 의 mixture 응용.</li>
<li><strong>Bishop (2006)</strong> — Variational Bayes for mixtures (chapter 10 of <em>PRML</em>).</li>
<li><strong>Minka (2001)</strong> — Expectation Propagation for mixtures.</li>
</ul>
</section>
<section id="mcmc-for-mixtures" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="mcmc-for-mixtures"><span class="header-section-number">4.2</span> MCMC for Mixtures</h3>
<ul>
<li><strong>Diebolt &amp; Robert (1994)</strong> — Gibbs sampler 원전.</li>
<li><strong>Richardson &amp; Green (1997)</strong> — Reversible Jump for unknown <span class="math inline">\(H\)</span>.</li>
<li><strong>Stephens (2000a, 2000b)</strong> — Unspecified <span class="math inline">\(H\)</span> + label switching postprocessing.</li>
<li><strong>Jasra, Holmes, Stephens (2005)</strong> — Label switching survey.</li>
<li><strong>Papaspiliopoulos &amp; Roberts (2008)</strong> — Label-switching moves within MCMC.</li>
</ul>
</section>
<section id="sparse-dirichlet-theory" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="sparse-dirichlet-theory"><span class="header-section-number">4.3</span> Sparse Dirichlet Theory</h3>
<ul>
<li><strong>Ishwaran &amp; Zarepour (2002)</strong> — <span class="math inline">\(a = \alpha/H\)</span> Dirichlet 의 DP 근사.</li>
<li><strong>Rousseau &amp; Mengersen (2011)</strong> — Overfitted mixture 의 redundant component 의 zero-out 점근.</li>
</ul>
</section>
<section id="응용" class="level3" data-number="4.4">
<h3 data-number="4.4" class="anchored" data-anchor-id="응용"><span class="header-section-number">4.4</span> 응용</h3>
<ul>
<li><strong>Belin &amp; Rubin (1990, 1995a, 1995b)</strong> — Schizophrenia.</li>
<li><strong>Rubin &amp; Wu (1997)</strong> — Schizophrenia 확장.</li>
<li><strong>Gelman &amp; King (1990b)</strong> — Election mixture (informative prior).</li>
<li><strong>Roeder &amp; Wasserman (1997)</strong> — Galaxy density.</li>
<li><strong>Fraley &amp; Raftery (2002)</strong> — Model-based clustering (mclust 패키지).</li>
<li><strong>Dunson (2010a)</strong> — Conditional density mixtures (epidemiology).</li>
<li><strong>Dunson &amp; Bhattacharya (2010)</strong> — Joint product kernel for classification/regression.</li>
</ul>
</section>
<section id="surveys" class="level3" data-number="4.5">
<h3 data-number="4.5" class="anchored" data-anchor-id="surveys"><span class="header-section-number">4.5</span> Surveys</h3>
<ul>
<li><strong>McLachlan &amp; Peel (2000)</strong> — <em>Finite Mixture Models</em> 정전.</li>
<li><strong>Fruhwirth-Schnatter (2006)</strong> — <em>Finite Mixture and Markov Switching Models</em> 베이즈 관점.</li>
<li><strong>Titterington, Smith, Makov (1985)</strong> — 비-베이즈 종합.</li>
<li><strong>West (1992)</strong> — 베이즈 brief review.</li>
</ul>
</section>
</section>
<section id="exercises-8-문제-풀이" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="exercises-8-문제-풀이"><span class="header-section-number">5</span> § 22.7 Exercises — 8 문제 풀이</h2>
<section id="exercise-1-cluster-point-estimate-mean-vs-median-vs-mode" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="exercise-1-cluster-point-estimate-mean-vs-median-vs-mode"><span class="header-section-number">5.1</span> Exercise 1 — Cluster Point Estimate (Mean vs Median vs Mode)</h3>
<p><strong>문제</strong>: 3-component mixture 에서 각 데이터 포인트의 component 식별. Pointwise marginal mean/median/mode 중 어느 것?</p>
<p><strong>풀이</strong>:</p>
<ul>
<li><strong>Mean</strong>: 잠재 indicator <span class="math inline">\(z_i \in \{1, 2, 3\}\)</span> 의 marginal mean = <span class="math inline">\(\sum_h h \cdot \Pr(z_i = h \mid y_i)\)</span>. 정수가 아니라 의미 부적절 (component label 은 categorical).</li>
<li><strong>Median</strong>: 같은 이유로 categorical 변수에서 median 정의 모호.</li>
<li><strong>Mode</strong>: <span class="math inline">\(\arg\max_h \Pr(z_i = h \mid y_i)\)</span> = MAP 분류. <strong>권장</strong>.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — Categorical 변수의 point estimate
</div>
</div>
<div class="callout-body-container callout-body">
<p>연속/순서형 변수: mean, median 의미 있음.</p>
<p>명목형 (categorical) 변수: <strong>mode 만이 의미 있는 point estimate</strong>. 이것이 분류 문제의 0-1 loss 와 연결 — Bayes optimal classifier 가 사후 mode.</p>
</div>
</div>
</section>
<section id="exercise-2-overfitted-mixture-3-234unspecified" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="exercise-2-overfitted-mixture-3-234unspecified"><span class="header-section-number">5.2</span> Exercise 2 — Overfitted Mixture (3 → 2/3/4/unspecified)</h3>
<p><strong>문제</strong>: True <span class="math inline">\(H_0 = 3\)</span> 의 normal mixture (centers <span class="math inline">\(-2, 0, 2\)</span>, scale 1) 에서 500점 추출. Bayesian mixture 를 <span class="math inline">\(H = 2, 3, 4\)</span>, unspecified <span class="math inline">\(H \in [1, 6]\)</span> 으로 적합.</p>
<p><strong>예상 결과</strong>:</p>
<ul>
<li><span class="math inline">\(H = 2\)</span>: 두 cluster 가 합쳐짐 (center 0, scale 더 큼). Underfit.</li>
<li><span class="math inline">\(H = 3\)</span>: 정확한 회복.</li>
<li><span class="math inline">\(H = 4\)</span>: 4 component 가 잡히나 한 component 가 매우 작은 weight (overfit). Sparse Dirichlet 이면 자동 zero-out.</li>
<li>Unspecified: <span class="math inline">\(H_n\)</span> 사후가 3 에 집중.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — Overfitted mixture 의 우아함
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(a = n_0/H\)</span> 와 함께 <span class="math inline">\(H\)</span> 큰 upper bound 를 두면 — <strong>overfit 이 자동 회피</strong>.</p>
<p>Rousseau-Mengersen (2011): Posterior of <span class="math inline">\(\pi_h\)</span> for redundant components → 0. 데이터로부터의 evidence 가 약하면 그 component 는 빈 cluster 로 전락.</p>
</div>
</div>
</section>
<section id="exercise-3-long-tailed-data-with-normal-mixture" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="exercise-3-long-tailed-data-with-normal-mixture"><span class="header-section-number">5.3</span> Exercise 3 — Long-Tailed Data with Normal Mixture</h3>
<p><strong>문제</strong>: 3 개 <span class="math inline">\(t_4\)</span> 분포의 mixture 에서 데이터 추출. Normal mixture 로 적합.</p>
<p><strong>예상 결과</strong>:</p>
<p><span class="math inline">\(t_4\)</span> 의 heavy tail → normal mixture 가 같은 center 의 <strong>여러 component</strong> 로 tail 표현. 즉, 3 개 가 아니라 5~7 component.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — 분포 가족이 다르면 cluster 수 부풀려짐
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(t_4\)</span> = <span class="math inline">\(N\)</span> 의 scale mixture (Inv-<span class="math inline">\(\chi^2\)</span>).</p>
<p><span class="math inline">\(t_4\)</span> 한 분포 ≈ 같은 center 의 두 정규 (작은 분산 + 큰 분산). Normal mixture 가 <span class="math inline">\(t_4\)</span> 를 흉내내려면 <strong>각 진짜 cluster 마다 2 component</strong>.</p>
<p>해결: <span class="math inline">\(t\)</span>-component mixture 사용 (<span class="math inline">\(f\)</span> = <span class="math inline">\(t_\nu\)</span>).</p>
</div>
</div>
</section>
<section id="exercise-4-galaxy-density-estimation" class="level3" data-number="5.4">
<h3 data-number="5.4" class="anchored" data-anchor-id="exercise-4-galaxy-density-estimation"><span class="header-section-number">5.4</span> Exercise 4 — Galaxy Density Estimation</h3>
<p><strong>문제</strong>: 82 점 galaxy 데이터, <span class="math inline">\(\alpha\)</span> Dirichlet + normal-inverse-gamma. <span class="math inline">\(\alpha\)</span> 감소·<span class="math inline">\(k\)</span> 증가·prior variance 증가의 효과.</p>
<p><strong>(a) <span class="math inline">\(\alpha \to 0\)</span></strong>: sparse 강화 → cluster 수 줄어듦. 너무 작으면 single cluster 로 붕괴.</p>
<p><strong>(b) <span class="math inline">\(k\)</span> 증가</strong>: upper bound 증가. <span class="math inline">\(a = \alpha/k\)</span> 라면 <span class="math inline">\(H_n\)</span> 안정. <span class="math inline">\(a\)</span> 고정이면 cluster 수 부풀려짐.</p>
<p><strong>(c) Prior variance <span class="math inline">\(\kappa\)</span> 증가</strong>: cluster mean 의 사전 분포 매우 넓음 → cluster mean 들이 데이터 영역 밖에 위치 가능 → <strong>부적절</strong> (대부분 데이터가 한 cluster 에 몰림).</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — Diffuse <span class="math inline">\(P_0\)</span> 의 함정
</div>
</div>
<div class="callout-body-container callout-body">
<p>Diffuse prior 는 일반적으로 “객관적” 으로 여겨지지만, mixture 에서는 <strong>반대 효과</strong>:</p>
<ul>
<li><span class="math inline">\(\kappa\)</span> 큼 → cluster mean 이 데이터 멀리.</li>
<li>데이터가 그 cluster 에 매핑될 likelihood 작음.</li>
<li>→ 모든 데이터가 한 dominant cluster 에 몰림.</li>
</ul>
<p>따라서 mixture 의 <span class="math inline">\(P_0\)</span> 는 <strong>데이터 영역과 비슷한 scale</strong> 이 권장.</p>
</div>
</div>
</section>
<section id="exercise-5-football-point-spread-mixture" class="level3" data-number="5.5">
<h3 data-number="5.5" class="anchored" data-anchor-id="exercise-5-football-point-spread-mixture"><span class="header-section-number">5.5</span> Exercise 5 — Football Point Spread Mixture</h3>
<p><strong>문제</strong>: § 1.6 의 football data (score differential - point spread) 를 normal 대신 finite mixture of normals 로 적합. <span class="math inline">\(a = 1/k\)</span> Dirichlet 사용.</p>
<p><strong>예상 결과</strong>:</p>
<ul>
<li>단일 정규 적합이 이미 거의 완벽 (Section 1.6) → mixture 가 single dominant component 로 회귀.</li>
<li><span class="math inline">\(H_n \approx 1\)</span>.</li>
<li>따라서 normal 가정 정당화.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — Single component 결과의 의미
</div>
</div>
<div class="callout-body-container callout-body">
<p>“Mixture 모델이 단일 component 를 선택” = “이 데이터에 정규 가정이 충분”.</p>
<p>Mixture 는 <strong>null 가설 (정규) 을 데이터 기반 검증</strong> 도구. Bayes factor 처럼 작동하지만 더 자연스러운 (continuous) prior.</p>
</div>
</div>
</section>
<section id="exercise-6-kidney-cancer-mixture-vs-gamma" class="level3" data-number="5.6">
<h3 data-number="5.6" class="anchored" data-anchor-id="exercise-6-kidney-cancer-mixture-vs-gamma"><span class="header-section-number">5.6</span> Exercise 6 — Kidney Cancer Mixture vs Gamma</h3>
<p><strong>문제</strong>: <span class="math inline">\(y_j \sim \text{Poisson}(10 n_j \theta_j)\)</span>, <span class="math inline">\(\theta_j\)</span> 의 prior 를 (a) 단일 Gamma vs (b) <span class="math inline">\(\sum_h \pi_h \delta_{\theta_h^*}\)</span> + Dirichlet sparse 로.</p>
<p><strong>비교</strong>:</p>
<ul>
<li><strong>(a) 단일 Gamma</strong>: <span class="math inline">\(\theta_j\)</span> 가 연속, smooth 사후.</li>
<li><strong>(b) Mixture of point masses</strong>: <span class="math inline">\(\theta_j\)</span> 가 <span class="math inline">\(H\)</span> 개 점 중 하나. 같은 <span class="math inline">\(\theta^*\)</span> 를 공유하는 county 들이 cluster.</li>
</ul>
<p><strong>결과 차이</strong>:</p>
<ul>
<li><ol type="a">
<li>는 county 별 <span class="math inline">\(\theta_j\)</span> 가 모두 다름 (Bayesian shrinkage).</li>
</ol></li>
<li><ol start="2" type="a">
<li>는 county 들이 그룹화 → 같은 그룹 내 정보 공유 강함 → <strong>shrinkage 더 강함</strong>.</li>
</ol></li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — Discrete vs Continuous mixing distribution
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Continuous: smooth, 모든 <span class="math inline">\(\theta_j\)</span> 다름.</li>
<li>Discrete (DP-like): “타입” 으로 분류, 같은 타입은 동일 <span class="math inline">\(\theta\)</span>.</li>
</ul>
<p>응용:</p>
<ul>
<li>지역 데이터 (kidney cancer county): 비슷한 county 들 그룹화 의미 있음 → discrete.</li>
<li>개별 환자 효과: 각자 다른 → continuous.</li>
</ul>
</div>
</div>
</section>
<section id="exercise-7-improper-prior-위험" class="level3" data-number="5.7">
<h3 data-number="5.7" class="anchored" data-anchor-id="exercise-7-improper-prior-위험"><span class="header-section-number">5.7</span> Exercise 7 — Improper Prior 위험</h3>
<p><strong>문제</strong>: Component-specific parameter 에 noninformative prior → 어떤 문제?</p>
<p><strong>풀이</strong>:</p>
<p>§ 22.1 에서 본 <strong>degenerate mode</strong>:</p>
<ul>
<li>정규 mixture 에서 한 component 가 single observation 에 정확히 맞춰지면서 <span class="math inline">\(\sigma_h^2 \to 0\)</span>.</li>
<li>Likelihood <span class="math inline">\(\to \infty\)</span>.</li>
<li>Improper prior + <span class="math inline">\(\int_0^\epsilon 1/\sigma^2 d\sigma^2\)</span> 가 발산 → improper posterior.</li>
</ul>
<p><strong>해결</strong>:</p>
<ul>
<li>Proper prior on <span class="math inline">\(\sigma_h^2\)</span> (Inverse Gamma).</li>
<li>또는 분산 비율 <span class="math inline">\(\sigma_2/\sigma_1\)</span> 고정 (single 분산 의 improper OK).</li>
<li>또는 정보적 prior + 데이터 표준화.</li>
</ul>
</section>
<section id="exercise-8-dirichlet-sparsity-점근" class="level3" data-number="5.8">
<h3 data-number="5.8" class="anchored" data-anchor-id="exercise-8-dirichlet-sparsity-점근"><span class="header-section-number">5.8</span> Exercise 8 — Dirichlet Sparsity 점근</h3>
<p><strong>문제</strong>: <span class="math inline">\(\pi \sim \text{Dirichlet}(1/k, \ldots, 1/k)\)</span> 에서 1000 표본 추출, <span class="math inline">\(k = 5, 10, 25, 50, 100, 1000\)</span>. 정렬된 order statistic 의 사후 평균.</p>
<p><strong>예상 결과</strong>:</p>
<p><span class="math inline">\(k\)</span> 클수록 정렬된 <span class="math inline">\(\pi\)</span> 의 분포가 <strong>stick-breaking 한계</strong> 에 수렴 (Dirichlet Process 의 stick-breaking representation):</p>
<p><span class="math display">\[
\pi_{(h)} \approx V_{(h)} \prod_{l &lt; h}(1 - V_{(l)}), \qquad V \sim \text{Beta}(1, \alpha)
\]</span></p>
<ul>
<li>첫 element <span class="math inline">\(\pi_{(1)} \approx 0.5\)</span> 정도 (지수적 감소).</li>
<li>매우 빠른 decay — top 5 가 <span class="math inline">\(\sum \approx 0.95\)</span>.</li>
</ul>
<p>비교: <span class="math inline">\(\text{Dirichlet}(1, \ldots, 1)\)</span> 은 모든 element 가 비슷 (<span class="math inline">\(\approx 1/k\)</span>).</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — Stick-breaking 의 시각화
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(k = 100, a = 0.01\)</span> 의 Dirichlet 표본:</p>
<ul>
<li><span class="math inline">\(\pi_{(1)} \approx 0.4\)</span> (가장 큰).</li>
<li><span class="math inline">\(\pi_{(2)} \approx 0.25\)</span>.</li>
<li><span class="math inline">\(\pi_{(3)} \approx 0.15\)</span>.</li>
<li><span class="math inline">\(\pi_{(4)} \approx 0.1\)</span>.</li>
<li><span class="math inline">\(\pi_{(5)} \approx 0.05\)</span>.</li>
<li>나머지 95 개 <span class="math inline">\(\sum \approx 0.05\)</span>.</li>
</ul>
<p>상위 5 개가 95% 의 weight. <strong>자동 sparsity</strong>.</p>
<p>이것이 Ch.23 DP 의 stick-breaking representation 의 직접적 시각화.</p>
</div>
</div>
</section>
</section>
<section id="ch.22-시리즈-결산" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="ch.22-시리즈-결산"><span class="header-section-number">6</span> Ch.22 시리즈 결산</h2>
<section id="편의-핵심" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="편의-핵심"><span class="header-section-number">6.1</span> 4 편의 핵심</h3>
<table class="table">
<colgroup>
<col style="width: 36%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">편</th>
<th style="text-align: left;">한 줄 요약</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Overview (04-22-0)</td>
<td style="text-align: left;">“분포 자체에 사전분포 — finite mixture 의 5 절 조망”</td>
</tr>
<tr class="even">
<td style="text-align: left;">§ 22.1~22.3 (04-22-1)</td>
<td style="text-align: left;">“ECM/Gibbs 식 (22.5)~(22.7), label switching 처리”</td>
</tr>
<tr class="odd">
<td style="text-align: left;">§ 22.4~22.7 (본 편)</td>
<td style="text-align: left;">“<span class="math inline">\(H\)</span> 자동 결정 + 분류·회귀·연습 + 결산”</td>
</tr>
</tbody>
</table>
</section>
<section id="ch.22-의-핵심-수식-통합" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="ch.22-의-핵심-수식-통합"><span class="header-section-number">6.2</span> Ch.22 의 핵심 수식 통합</h3>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">번호</th>
<th style="text-align: left;">수식</th>
<th style="text-align: left;">의미</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">(22.1)</td>
<td style="text-align: left;"><span class="math inline">\(p(y_i) = \sum_h \lambda_h f(y_i \mid \theta_h)\)</span></td>
<td style="text-align: left;">Finite mixture</td>
</tr>
<tr class="even">
<td style="text-align: center;">(22.2)</td>
<td style="text-align: left;"><span class="math inline">\(p(y, z) = \prod_i \prod_h (\lambda_h f(y_i \mid \theta_h))^{z_{ih}}\)</span></td>
<td style="text-align: left;">Joint with indicator</td>
</tr>
<tr class="odd">
<td style="text-align: center;">(22.5)</td>
<td style="text-align: left;">$_{ij} = $ Bayes 룰 ratio</td>
<td style="text-align: left;">E-step</td>
</tr>
<tr class="even">
<td style="text-align: center;">(22.6)</td>
<td style="text-align: left;">$_j^{} = $ conjugate weighted avg</td>
<td style="text-align: left;">M-step random effect</td>
</tr>
<tr class="odd">
<td style="text-align: center;">(22.7)</td>
<td style="text-align: left;"><span class="math inline">\(\mu, \beta\)</span> group mean</td>
<td style="text-align: left;">M-step group</td>
</tr>
<tr class="even">
<td style="text-align: center;">(22.10)</td>
<td style="text-align: left;"><span class="math inline">\(\pi \sim \text{Dir}(a, \ldots, a),\ \theta_h \sim P_0\)</span></td>
<td style="text-align: left;">Exchangeable prior</td>
</tr>
<tr class="odd">
<td style="text-align: center;">(22.11)</td>
<td style="text-align: left;"><span class="math inline">\(y_i \mid z_i \sim N(\mu_{z_i}, \tau_{z_i}^2)\)</span></td>
<td style="text-align: left;">Location-scale</td>
</tr>
<tr class="even">
<td style="text-align: center;">(22.12)</td>
<td style="text-align: left;"><span class="math inline">\(\mu_h, \tau_h^2 \sim N \cdot \text{Inv-Gamma}\)</span></td>
<td style="text-align: left;">Conjugate</td>
</tr>
<tr class="odd">
<td style="text-align: center;">-</td>
<td style="text-align: left;"><span class="math inline">\(a = n_0/H\)</span></td>
<td style="text-align: left;">Sparse Dirichlet</td>
</tr>
<tr class="even">
<td style="text-align: center;">(22.13)</td>
<td style="text-align: left;"><span class="math inline">\(f(w_i) = \sum_h \pi_h N_{p+1}(w_i \mid \mu_h, \Sigma_h)\)</span></td>
<td style="text-align: left;">Joint mixture</td>
</tr>
<tr class="odd">
<td style="text-align: center;">(22.14)</td>
<td style="text-align: left;"><span class="math inline">\(f(y \mid x) = \sum_h \pi_h(x) N(y \mid \beta_{0h} + x\beta_{1h}, \sigma_h^2)\)</span></td>
<td style="text-align: left;">Mixture of experts</td>
</tr>
<tr class="even">
<td style="text-align: center;">(22.15)</td>
<td style="text-align: left;">$_h(x) = $ predictor-dependent weights</td>
<td style="text-align: left;">Gating function</td>
</tr>
</tbody>
</table>
</section>
<section id="ch.22-의-시퀀스-점점-큰-일반화" class="level3" data-number="6.3">
<h3 data-number="6.3" class="anchored" data-anchor-id="ch.22-의-시퀀스-점점-큰-일반화"><span class="header-section-number">6.3</span> Ch.22 의 시퀀스 — 점점 큰 일반화</h3>
<pre><code>Ch.22 § 22.1 Setup
  → 식 (22.1) finite mixture, latent indicator

Ch.22 § 22.2 Schizophrenia
  → ECM/Gibbs 의 closed-form 계산

Ch.22 § 22.3 Label switching
  → Identifiability 와 후처리

Ch.22 § 22.4 Unspecified H
  → Truncated upper bound + sparse Dirichlet
  → DP (Ch.23) 으로의 가교

Ch.22 § 22.5 Classification/Regression
  → Discriminant analysis, mixture of experts
  → 식 (22.14) predictor-dependent

Ch.23 Dirichlet Process
  → H → ∞ 한계
  → 비모수 베이즈 완성</code></pre>
</section>
<section id="ch.22-의-유산과-한계" class="level3" data-number="6.4">
<h3 data-number="6.4" class="anchored" data-anchor-id="ch.22-의-유산과-한계"><span class="header-section-number">6.4</span> Ch.22 의 유산과 한계</h3>
<p><strong>유산</strong>:</p>
<ul>
<li>Latent variable augmentation 의 표준 도구.</li>
<li>Identifiability 처리 (label switching) 의 모범.</li>
<li><span class="math inline">\(H\)</span> 자동 결정 (sparse Dirichlet) — 단순하지만 강력.</li>
<li>Robust 통계학 (<span class="math inline">\(t\)</span> = scale mixture) 의 통일.</li>
<li>Discriminant analysis + mixture of experts 의 베이즈 framework.</li>
</ul>
<p><strong>한계</strong>:</p>
<ul>
<li><span class="math inline">\(H\)</span> 가 truncated — 정말 무한 cluster 면 부족 (Ch.23).</li>
<li>Component 가족 (<span class="math inline">\(f\)</span>) 가정에 cluster 결과가 민감.</li>
<li>다변량 covariance 가정에 cluster 수 민감.</li>
<li>Label switching 의 본질적 어려움 (다변량은 postprocessing 필수).</li>
</ul>
<p><strong>다음 장 (Ch.23)</strong>:</p>
<ul>
<li>DP = Ch.22 의 <span class="math inline">\(H \to \infty\)</span> 한계.</li>
<li>Stick-breaking = <span class="math inline">\(a = n_0/H \to 0\)</span> 의 자연스러운 표현.</li>
<li>Polya urn / Chinese restaurant process = <span class="math inline">\(z_i\)</span> 의 marginal sequential.</li>
<li>HDP = 그룹별 mixture 의 component 공유.</li>
</ul>
</section>
</section>
<section id="ch.22-시리즈-통합-체크리스트" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="ch.22-시리즈-통합-체크리스트"><span class="header-section-number">7</span> Ch.22 시리즈 통합 체크리스트</h2>
<p><strong>모델 결정</strong></p>
<ol type="1">
<li>Mixture 가 정말 필요한가 (conditioning 변수 관측 가능?).</li>
<li>Component 가족 (<span class="math inline">\(f\)</span>): 정규 default, <span class="math inline">\(t\)</span> robust, multivariate <span class="math inline">\(\Sigma\)</span> 결정.</li>
<li><span class="math inline">\(H\)</span> 결정: 도메인 지식 vs WAIC 비교 vs truncated upper bound + sparse.</li>
</ol>
<p><strong>Prior</strong></p>
<ol start="4" type="1">
<li><strong>Proper prior 필수</strong> (improper 는 degenerate posterior).</li>
<li><span class="math inline">\(a = n_0/H\)</span> Dirichlet (with <span class="math inline">\(n_0 = 1\)</span> default) for sparse.</li>
<li><span class="math inline">\(P_0\)</span> 의 scale = 데이터 영역 (표준화 후 <span class="math inline">\(\mu_0 = 0, \kappa = 1\)</span>).</li>
<li>식별성: order constraint 또는 informative component prior.</li>
</ol>
<p><strong>계산</strong></p>
<ol start="8" type="1">
<li>Crude estimate 100 starting points, ECM 100 iter mode finding.</li>
<li>Mode → <span class="math inline">\(t_4\)</span> approximation → importance resampling → Gibbs 시작.</li>
<li>Gibbs 6 단계 (또는 PyMC <code>pm.Mixture</code>) 사용.</li>
<li>NUTS for nonconjugate hyperparameters.</li>
</ol>
<p><strong>검증</strong></p>
<ol start="12" type="1">
<li>PPC test: sufficient statistic 외 quantity (극값, 분위수).</li>
<li>WAIC, LOO-CV 로 <span class="math inline">\(H\)</span> 또는 모델 비교 (DIC 권장 안 함).</li>
<li><span class="math inline">\(\widehat R\)</span> on density 또는 switching-invariant.</li>
<li>Component-specific 추론 시 KL postprocessing.</li>
<li>Cluster size <span class="math inline">\(\pi_h \cdot n &gt; 5\)</span> 만 신뢰.</li>
</ol>
<p><strong>해석</strong></p>
<ol start="17" type="1">
<li>Density estimation: switching 무시.</li>
<li>Cluster ≠ 진짜 부분모집단 — kernel 가정에 민감.</li>
<li>외삽: cluster 가정의 외부 일반성 검토.</li>
<li>Ch.21 GP, Ch.23 DP 와 비교 — 어느 모델이 가장 적절한가.</li>
</ol>
</section>
<section id="관련-주제" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="관련-주제"><span class="header-section-number">8</span> 관련 주제</h2>
<p><strong>Ch.22 시리즈</strong></p>
<ul>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/04-22-0-finite-mixture-overview.html">Ch.22 Overview</a></li>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/04-22-1-setup-schizophrenia-label-switching.html">Ch.22 § 22.1~22.3 — Setup·Schizophrenia·Label Switching</a></li>
</ul>
<p><strong>선행 지식</strong></p>
<ul>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/00-5-0-hierarchical.html">Ch.5 Hierarchical Models</a></li>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/04-21-0-gaussian-process-overview.html">Ch.21 Gaussian Process Models</a></li>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/03-16-0-generalized-linear-models-overview.html">Ch.16 Generalized Linear Models</a></li>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/02-13-2-em-conditional-marginal-hierarchical.html">Ch.13 § 13.4 — EM Algorithm</a></li>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/01-7-0-evaluating-comparing-models.html">Ch.7 Model Comparison (WAIC, LOO)</a></li>
</ul>
<p><strong>후속 주제</strong></p>
<ul>
<li><a href="./04-23-0-dirichlet-process-overview.qmd">Ch.23 Dirichlet Process Models Overview (예정)</a></li>
</ul>
<p><strong>관련 개념 (cross-category)</strong></p>
<ul>
<li><a href="../../Machine_Learning/mixture-of-experts.qmd">Mixture of Experts (Jordan-Jacobs)</a></li>
<li><a href="../../Machine_Learning/bayesian-discriminant.qmd">Bayesian Discriminant Analysis vs Logistic</a></li>
<li><a href="../latent-class-analysis.qmd">Latent Class Analysis</a></li>
<li><a href="../../Machine_Learning/model-based-clustering.qmd">Model-Based Clustering (mclust)</a></li>
<li><a href="../../Machine_Learning/variational-mixture.qmd">Variational Bayes for Mixtures</a></li>
<li><a href="../../Math/dirichlet-process.qmd">Stick-Breaking and Dirichlet Process</a></li>
</ul>
</section>
<section id="참고문헌" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="참고문헌"><span class="header-section-number">9</span> 참고문헌</h2>
<ul>
<li>Gelman, A., Carlin, J. B., Stern, H. S., Dunson, D. B., Vehtari, A., &amp; Rubin, D. B. (2013). <em>Bayesian Data Analysis</em> (3rd ed.), Ch.22 § 22.4~22.7. CRC Press.</li>
<li>Ishwaran, H., &amp; Zarepour, M. (2002). Exact and Approximate Sum-Representations for the Dirichlet Process. <em>Canadian Journal of Statistics</em>, 30(2), 269-283.</li>
<li>Rousseau, J., &amp; Mengersen, K. (2011). Asymptotic Behaviour of the Posterior Distribution in Overfitted Mixture Models. <em>JRSS B</em>, 73(5), 689-710.</li>
<li>Sethuraman, J. (1994). A Constructive Definition of Dirichlet Priors. <em>Statistica Sinica</em>, 4, 639-650. (Stick-breaking 정의)</li>
<li>Richardson, S., &amp; Green, P. J. (1997). On Bayesian Analysis of Mixtures with an Unknown Number of Components. <em>JRSS B</em>, 59(4), 731-792.</li>
<li>Stephens, M. (2000a, 2000b). Bayesian Analysis of Mixture Models with Unknown Number of Components·Dealing with Label Switching. <em>JRSS B</em>, 62(4), 795-809.</li>
<li>Jasra, A., Holmes, C. C., &amp; Stephens, D. A. (2005). Markov Chain Monte Carlo Methods and the Label Switching Problem in Bayesian Mixture Modeling. <em>Statistical Science</em>, 20(1), 50-67.</li>
<li>Jacobs, R. A., Jordan, M. I., Nowlan, S. J., &amp; Hinton, G. E. (1991). Adaptive Mixtures of Local Experts. <em>Neural Computation</em>, 3(1), 79-87.</li>
<li>Jordan, M. I., &amp; Jacobs, R. A. (1994). Hierarchical Mixtures of Experts and the EM Algorithm. <em>Neural Computation</em>, 6(2), 181-214.</li>
<li>Diebolt, J., &amp; Robert, C. P. (1994). Estimation of Finite Mixture Distributions through Bayesian Sampling. <em>JRSS B</em>, 56(2), 363-375.</li>
<li>Roeder, K., &amp; Wasserman, L. (1997). Practical Bayesian Density Estimation Using Mixtures of Normals. <em>JASA</em>, 92(439), 894-902.</li>
<li>Fraley, C., &amp; Raftery, A. E. (2002). Model-Based Clustering, Discriminant Analysis, and Density Estimation. <em>JASA</em>, 97(458), 611-631.</li>
<li>Dunson, D. B. (2010a). Nonparametric Bayes Applications to Biostatistics. In <em>Bayesian Nonparametrics</em> (Hjort et al., eds.), Cambridge.</li>
<li>Dunson, D. B., &amp; Bhattacharya, A. (2010). Nonparametric Bayes Regression and Classification through Mixtures of Product Kernels. In <em>Bayesian Statistics 9</em>, Oxford.</li>
<li>Belin, T. R., &amp; Rubin, D. B. (1995a, 1995b). Inference for Finite Mixture Models. <em>Statistica Sinica</em>.</li>
<li>McLachlan, G. J., &amp; Peel, D. (2000). <em>Finite Mixture Models</em>. Wiley.</li>
<li>Fruhwirth-Schnatter, S. (2006). <em>Finite Mixture and Markov Switching Models</em>. Springer.</li>
<li>Bishop, C. M. (2006). <em>Pattern Recognition and Machine Learning</em>. Springer. (Ch.10 — VB for mixtures)</li>
<li>Minka, T. (2001). Expectation Propagation for Approximate Bayesian Inference. <em>UAI</em>.</li>
</ul>


</section>

</main> <!-- /main -->
<script type="text/javascript">

// replace cmd keyboard shortcut w/ control on non-Mac platforms
const kPlatformMac = typeof navigator !== 'undefined' ? /Mac/.test(navigator.platform) : false;
if (!kPlatformMac) {
   var kbds = document.querySelectorAll("kbd")
   kbds.forEach(function(kbd) {
      kbd.innerHTML = kbd.innerHTML.replace(/⌘/g, '⌃');
   });
}

// tweak headings in pymd
document.querySelectorAll(".pymd span.co").forEach(el => {
   if (!el.innerText.startsWith("#|")) {
      el.style.fontWeight = 1000;
   }
});

</script>
<!-- Begin Mailchimp Signup Form -->
<div id="mc_embed_signup" style="padding-bottom: 1em; max-width: 400px;" class="ms-auto me-auto">
  <p style="font-weight: 600; margin-bottom: 0;">Subscribe</p>
  <span style="font-size: 0.9em;">Enjoy this blog? Get notified of new posts by email:</span>
<form action="https://quarto.us14.list-manage.com/subscribe/post?u=c79fb56a311ae347fbe916740&amp;id=ec05dfca03" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate="">
    <div id="mc_embed_signup_scroll">
	
        <div class="input-group mt-1 mb-2">
        <input type="email" class="form-control" placeholder="Email Address" aria-label="Email Address" name="EMAIL" style="font-size: 0.8em; padding: .2em;">
        </div>              

	<div id="mce-responses" class="clear foot">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_c79fb56a311ae347fbe916740_ec05dfca03" tabindex="-1" value=""></div>
        <div class="optionalParent">
            <div class="clear foot" style="display: flex; align-items: center; justify-content: center;">
              
              
                <input type="submit" value="Subscribe" name="subscribe" style="min-width: 150px; font-size: 0.8em;" id="mc-embedded-subscribe" class="button btn btn-light btn-sm ms-auto me-auto">
            </div>
        </div>
    </div>
</form>
</div>

<!--End mc_embed_signup-->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "복사완료!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "복사완료!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="kmink3225/blog" data-repo-id="R_kgDOLCZyDg" data-category="Blog" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script>
<input type="hidden" id="giscus-base-theme" value="light">
<input type="hidden" id="giscus-alt-theme" value="dark">
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Kwangmin Kim</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="../../../../../about.html">
<p>About</p>
</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/kmink3225/blog">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>