<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ko" xml:lang="ko"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.543">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kwangmin Kim">
<meta name="description" content="Gelman BDA Ch.21 의 § 21.4~21.7 을 한 편으로 깊게 다룬다. § 21.4 함수형 데이터 분석에서 GP 가 어떻게 spline-based FDA 를 자연스럽게 일반화하는지를 separable kernel 구조와 함께 정리하고, 환자 trajectory·학생 성장 곡선 등 실무 응용을 보인다. § 21.5 logistic Gaussian process (LGP) 밀도 추정의 continuous logistic transformation, 정규화 적분의 계산 challenge, 식 (21.4) density regression kernel, 식 (21.5) Kundu-Dunson latent-variable regression 의 분위수 함수 직관, galaxies/lakes 일변량 LGP 결과 해석을 다룬다. § 21.6 핵심 문헌 정리 (Rasmussen-Williams·Neal·Vanhatalo·Hensman·Lindgren). § 21.7 연습문제 9개 (GP prior 표본·NAES04 attitude·multi-predictor·Golf binomial·Birthday 재현·spline→GP 교체·basis 유도 GP·linear→GP 동치) 의 모델 설정·계산 절차·결과 해석을 단계별로 풀이. 마지막으로 Ch.21 시리즈 4편 (overview·§ 21.1~21.3·본 편) 의 핵심 수식·발견·실무 체크리스트를 결산한다.">

<title>Kwangmin Kim - Ch.21 § 21.4~21.7 심화 — FDA · LGP Density · 연습 + Ch.21 결산</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../../../">
<script src="../../../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../../../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../../../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": true,
  "language": {
    "search-no-results-text": "일치 없음",
    "search-matching-documents-text": "일치된 문서",
    "search-copy-link-title": "검색 링크 복사",
    "search-hide-matches-text": "추가 검색 결과 숨기기",
    "search-more-match-text": "추가 검색결과",
    "search-more-matches-text": "추가 검색결과",
    "search-clear-button-title": "제거",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "취소",
    "search-submit-button-title": "검색",
    "search-label": "검색"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-6W0EKFMWBN"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-6W0EKFMWBN', { 'anonymize_ip': true});
</script>
<style>

      .quarto-title-block .quarto-title-banner h1,
      .quarto-title-block .quarto-title-banner h2,
      .quarto-title-block .quarto-title-banner h3,
      .quarto-title-block .quarto-title-banner h4,
      .quarto-title-block .quarto-title-banner h5,
      .quarto-title-block .quarto-title-banner h6
      {
        color: black;
      }

      .quarto-title-block .quarto-title-banner {
        color: black;
background: #EDF3F9;
      }
</style>
<style>
.custom-footer { 
  text-align: center; 
  font-size: 0.8em; 
  color: #666; 
  margin-top: 2rem; 
}
</style>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../../../styles.css">
<meta property="og:title" content="Kwangmin Kim - Ch.21 § 21.4~21.7 심화 — FDA · LGP Density · 연습 + Ch.21 결산">
<meta property="og:description" content="Gelman BDA Ch.21 의 § 21.4~21.7 을 한 편으로 깊게 다룬다. § 21.4 함수형 데이터 분석에서 GP 가 어떻게 spline-based FDA 를 자연스럽게 일반화하는지를 separable kernel 구조와 함께 정리하고, 환자 trajectory·학생 성장 곡선 등 실무 응용을 보인다. § 21.5 logistic Gaussian process (LGP) 밀도 추정의 continuous logistic transformation, 정규화 적분의 계산 challenge, 식 (21.4) density regression kernel, 식 (21.5) Kundu-Dunson latent-variable regression 의 분위수 함수 직관, galaxies/lakes 일변량 LGP 결과 해석을 다룬다. § 21.6 핵심 문헌 정리 (Rasmussen-Williams·Neal·Vanhatalo·Hensman·Lindgren). § 21.7 연습문제 9개 (GP prior 표본·NAES04 attitude·multi-predictor·Golf binomial·Birthday 재현·spline→GP 교체·basis 유도 GP·linear→GP 동치) 의 모델 설정·계산 절차·결과 해석을 단계별로 풀이. 마지막으로 Ch.21 시리즈 4편 (overview·§ 21.1~21.3·본 편) 의 핵심 수식·발견·실무 체크리스트를 결산한다.">
<meta property="og:site_name" content="Kwangmin Kim">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../../../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../../../.././images/logo.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../../../../index.html">
    <span class="navbar-title">Kwangmin Kim</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="검색"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="탐색 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../../docs/blog/index.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../../../about.html"> 
<span class="menu-text">Me</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/kmink3225"> <i class="bi bi-github" role="img" aria-label="Github">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/kwangmin-kim-a5241b200/"> <i class="bi bi-linkedin" role="img" aria-label="Linkedin">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../../../../docs/blog/index.xml"> <i class="bi bi-rss" role="img" aria-label="RSS">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="다크 모드 전환"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Ch.21 § 21.4~21.7 심화 — FDA · LGP Density · 연습 + Ch.21 결산</h1>
            <p class="subtitle lead">함수형 데이터 분석·logistic Gaussian process 식 (21.4) 밀도 회귀·식 (21.5) 잠재변수 회귀·galaxies/lakes 밀도 추정·NAES04 attitude·Golf binomial GP·basis 유도 GP·연습문제 9문제 완전 풀이</p>
                  <div>
        <div class="description">
          <p>Gelman BDA Ch.21 의 § 21.4~21.7 을 한 편으로 깊게 다룬다. § 21.4 함수형 데이터 분석에서 GP 가 어떻게 spline-based FDA 를 자연스럽게 일반화하는지를 separable kernel 구조와 함께 정리하고, 환자 trajectory·학생 성장 곡선 등 실무 응용을 보인다. § 21.5 logistic Gaussian process (LGP) 밀도 추정의 continuous logistic transformation, 정규화 적분의 계산 challenge, 식 (21.4) density regression kernel, 식 (21.5) Kundu-Dunson latent-variable regression 의 분위수 함수 직관, galaxies/lakes 일변량 LGP 결과 해석을 다룬다. § 21.6 핵심 문헌 정리 (Rasmussen-Williams·Neal·Vanhatalo·Hensman·Lindgren). § 21.7 연습문제 9개 (GP prior 표본·NAES04 attitude·multi-predictor·Golf binomial·Birthday 재현·spline→GP 교체·basis 유도 GP·linear→GP 동치) 의 모델 설정·계산 절차·결과 해석을 단계별로 풀이. 마지막으로 Ch.21 시리즈 4편 (overview·§ 21.1~21.3·본 편) 의 핵심 수식·발견·실무 체크리스트를 결산한다.</p>
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">Statistics</div>
                <div class="quarto-category">Bayesian</div>
                <div class="quarto-category">Gaussian-Process</div>
                <div class="quarto-category">Functional-Data-Analysis</div>
                <div class="quarto-category">Density-Estimation</div>
                <div class="quarto-category">Nonparametric-Bayes</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">저자</div>
      <div class="quarto-title-meta-contents">
               <p>Kwangmin Kim </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">공개</div>
      <div class="quarto-title-meta-contents">
        <p class="date">2026년 04월 27일</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">목차</h2>
   
  <ul>
  <li><a href="#들어가며-본-편의-자리" id="toc-들어가며-본-편의-자리" class="nav-link active" data-scroll-target="#들어가며-본-편의-자리"><span class="header-section-number">1</span> 들어가며 — 본 편의 자리</a></li>
  <li><a href="#functional-data-analysis-각-개체가-함수인-데이터" id="toc-functional-data-analysis-각-개체가-함수인-데이터" class="nav-link" data-scroll-target="#functional-data-analysis-각-개체가-함수인-데이터"><span class="header-section-number">2</span> § 21.4 Functional Data Analysis — 각 개체가 함수인 데이터</a>
  <ul class="collapse">
  <li><a href="#동기-데이터-단위가-점이-아니라-곡선" id="toc-동기-데이터-단위가-점이-아니라-곡선" class="nav-link" data-scroll-target="#동기-데이터-단위가-점이-아니라-곡선"><span class="header-section-number">2.1</span> 동기 — 데이터 단위가 점이 아니라 곡선</a></li>
  <li><a href="#전통-fda-와-gp-fda-의-차이" id="toc-전통-fda-와-gp-fda-의-차이" class="nav-link" data-scroll-target="#전통-fda-와-gp-fda-의-차이"><span class="header-section-number">2.2</span> 전통 FDA 와 GP-FDA 의 차이</a></li>
  <li><a href="#separable-kernel-개체-시간" id="toc-separable-kernel-개체-시간" class="nav-link" data-scroll-target="#separable-kernel-개체-시간"><span class="header-section-number">2.3</span> Separable Kernel — 개체 × 시간</a></li>
  <li><a href="#응용-rt-pcr-형광-곡선" id="toc-응용-rt-pcr-형광-곡선" class="nav-link" data-scroll-target="#응용-rt-pcr-형광-곡선"><span class="header-section-number">2.4</span> 응용 — RT-PCR 형광 곡선</a></li>
  </ul></li>
  <li><a href="#density-estimation-and-regression" id="toc-density-estimation-and-regression" class="nav-link" data-scroll-target="#density-estimation-and-regression"><span class="header-section-number">3</span> § 21.5 Density Estimation and Regression</a>
  <ul class="collapse">
  <li><a href="#동기-회귀-함수-너머" id="toc-동기-회귀-함수-너머" class="nav-link" data-scroll-target="#동기-회귀-함수-너머"><span class="header-section-number">3.1</span> 동기 — 회귀 함수 너머</a></li>
  <li><a href="#lgp-일변량-밀도-추정" id="toc-lgp-일변량-밀도-추정" class="nav-link" data-scroll-target="#lgp-일변량-밀도-추정"><span class="header-section-number">3.2</span> LGP — 일변량 밀도 추정</a></li>
  <li><a href="#mean-function-m-의-역할" id="toc-mean-function-m-의-역할" class="nav-link" data-scroll-target="#mean-function-m-의-역할"><span class="header-section-number">3.3</span> Mean Function <span class="math inline">\(m\)</span> 의 역할</a></li>
  <li><a href="#정규화-적분의-계산-challenge" id="toc-정규화-적분의-계산-challenge" class="nav-link" data-scroll-target="#정규화-적분의-계산-challenge"><span class="header-section-number">3.4</span> 정규화 적분의 계산 Challenge</a></li>
  <li><a href="#대안-표현-compactified-gp" id="toc-대안-표현-compactified-gp" class="nav-link" data-scroll-target="#대안-표현-compactified-gp"><span class="header-section-number">3.5</span> 대안 표현 — Compactified GP</a></li>
  <li><a href="#galaxies-and-lakes-예제" id="toc-galaxies-and-lakes-예제" class="nav-link" data-scroll-target="#galaxies-and-lakes-예제"><span class="header-section-number">3.6</span> Galaxies and Lakes 예제</a></li>
  <li><a href="#density-regression-식-21.4" id="toc-density-regression-식-21.4" class="nav-link" data-scroll-target="#density-regression-식-21.4"><span class="header-section-number">3.7</span> Density Regression — 식 (21.4)</a></li>
  <li><a href="#식-21.5-latent-variable-regression-kundu-dunson" id="toc-식-21.5-latent-variable-regression-kundu-dunson" class="nav-link" data-scroll-target="#식-21.5-latent-variable-regression-kundu-dunson"><span class="header-section-number">3.8</span> 식 (21.5) Latent-Variable Regression — Kundu-Dunson</a></li>
  <li><a href="#density-regression-식-21.5-의-일반화" id="toc-density-regression-식-21.5-의-일반화" class="nav-link" data-scroll-target="#density-regression-식-21.5-의-일반화"><span class="header-section-number">3.9</span> Density Regression — 식 (21.5) 의 일반화</a></li>
  </ul></li>
  <li><a href="#bibliographic-note-핵심-문헌-정리" id="toc-bibliographic-note-핵심-문헌-정리" class="nav-link" data-scroll-target="#bibliographic-note-핵심-문헌-정리"><span class="header-section-number">4</span> § 21.6 Bibliographic Note — 핵심 문헌 정리</a>
  <ul class="collapse">
  <li><a href="#gp-이론계산의-4-가지-정전" id="toc-gp-이론계산의-4-가지-정전" class="nav-link" data-scroll-target="#gp-이론계산의-4-가지-정전"><span class="header-section-number">4.1</span> GP 이론·계산의 4 가지 정전</a></li>
  <li><a href="#효율-계산-6-가지-길" id="toc-효율-계산-6-가지-길" class="nav-link" data-scroll-target="#효율-계산-6-가지-길"><span class="header-section-number">4.2</span> 효율 계산 — 6 가지 길</a></li>
  <li><a href="#응용" id="toc-응용" class="nav-link" data-scroll-target="#응용"><span class="header-section-number">4.3</span> 응용</a></li>
  <li><a href="#lgp-문헌" id="toc-lgp-문헌" class="nav-link" data-scroll-target="#lgp-문헌"><span class="header-section-number">4.4</span> LGP 문헌</a></li>
  </ul></li>
  <li><a href="#exercises-9문제-완전-풀이" id="toc-exercises-9문제-완전-풀이" class="nav-link" data-scroll-target="#exercises-9문제-완전-풀이"><span class="header-section-number">5</span> § 21.7 Exercises — 9문제 완전 풀이</a>
  <ul class="collapse">
  <li><a href="#exercise-1-gp-prior-표본-figure-21.1-재현" id="toc-exercise-1-gp-prior-표본-figure-21.1-재현" class="nav-link" data-scroll-target="#exercise-1-gp-prior-표본-figure-21.1-재현"><span class="header-section-number">5.1</span> Exercise 1 — GP Prior 표본 (Figure 21.1 재현)</a></li>
  <li><a href="#exercise-2-naes04-attitude-normal-approx-gp-regression" id="toc-exercise-2-naes04-attitude-normal-approx-gp-regression" class="nav-link" data-scroll-target="#exercise-2-naes04-attitude-normal-approx-gp-regression"><span class="header-section-number">5.2</span> Exercise 2 — NAES04 Attitude (Normal Approx GP Regression)</a></li>
  <li><a href="#exercise-3-naes04-binomial-gp" id="toc-exercise-3-naes04-binomial-gp" class="nav-link" data-scroll-target="#exercise-3-naes04-binomial-gp"><span class="header-section-number">5.3</span> Exercise 3 — NAES04 Binomial GP</a></li>
  <li><a href="#exercise-4-multi-predictor-anisotropic-gp" id="toc-exercise-4-multi-predictor-anisotropic-gp" class="nav-link" data-scroll-target="#exercise-4-multi-predictor-anisotropic-gp"><span class="header-section-number">5.4</span> Exercise 4 — Multi-Predictor Anisotropic GP</a></li>
  <li><a href="#exercise-5-golf-putting-binomial-gp" id="toc-exercise-5-golf-putting-binomial-gp" class="nav-link" data-scroll-target="#exercise-5-golf-putting-binomial-gp"><span class="header-section-number">5.5</span> Exercise 5 — Golf Putting Binomial GP</a></li>
  <li><a href="#exercise-6-birthday-분석-재현" id="toc-exercise-6-birthday-분석-재현" class="nav-link" data-scroll-target="#exercise-6-birthday-분석-재현"><span class="header-section-number">5.6</span> Exercise 6 — Birthday 분석 재현</a></li>
  <li><a href="#exercise-7-pollster-시계열-spline-gp-교체" id="toc-exercise-7-pollster-시계열-spline-gp-교체" class="nav-link" data-scroll-target="#exercise-7-pollster-시계열-spline-gp-교체"><span class="header-section-number">5.7</span> Exercise 7 — Pollster 시계열, Spline → GP 교체</a></li>
  <li><a href="#exercise-8-basis-가-유도하는-gp" id="toc-exercise-8-basis-가-유도하는-gp" class="nav-link" data-scroll-target="#exercise-8-basis-가-유도하는-gp"><span class="header-section-number">5.8</span> Exercise 8 — Basis 가 유도하는 GP</a></li>
  <li><a href="#exercise-9-linear-모형은-gp-인가-비선형-표현-가능한가" id="toc-exercise-9-linear-모형은-gp-인가-비선형-표현-가능한가" class="nav-link" data-scroll-target="#exercise-9-linear-모형은-gp-인가-비선형-표현-가능한가"><span class="header-section-number">5.9</span> Exercise 9 — Linear 모형은 GP 인가, 비선형 표현 가능한가</a></li>
  </ul></li>
  <li><a href="#ch.21-시리즈-결산" id="toc-ch.21-시리즈-결산" class="nav-link" data-scroll-target="#ch.21-시리즈-결산"><span class="header-section-number">6</span> Ch.21 시리즈 결산</a>
  <ul class="collapse">
  <li><a href="#시리즈-4편의-핵심" id="toc-시리즈-4편의-핵심" class="nav-link" data-scroll-target="#시리즈-4편의-핵심"><span class="header-section-number">6.1</span> 시리즈 4편의 핵심</a></li>
  <li><a href="#ch.21-의-핵심-수식-통합" id="toc-ch.21-의-핵심-수식-통합" class="nav-link" data-scroll-target="#ch.21-의-핵심-수식-통합"><span class="header-section-number">6.2</span> Ch.21 의 핵심 수식 통합</a></li>
  <li><a href="#ch.21-의-시퀀스-기하급수적-확장" id="toc-ch.21-의-시퀀스-기하급수적-확장" class="nav-link" data-scroll-target="#ch.21-의-시퀀스-기하급수적-확장"><span class="header-section-number">6.3</span> Ch.21 의 시퀀스 — 기하급수적 확장</a></li>
  <li><a href="#ch.21-의-유산과-한계" id="toc-ch.21-의-유산과-한계" class="nav-link" data-scroll-target="#ch.21-의-유산과-한계"><span class="header-section-number">6.4</span> Ch.21 의 유산과 한계</a></li>
  </ul></li>
  <li><a href="#ch.21-시리즈-통합-체크리스트" id="toc-ch.21-시리즈-통합-체크리스트" class="nav-link" data-scroll-target="#ch.21-시리즈-통합-체크리스트"><span class="header-section-number">7</span> Ch.21 시리즈 통합 체크리스트</a></li>
  <li><a href="#관련-주제" id="toc-관련-주제" class="nav-link" data-scroll-target="#관련-주제"><span class="header-section-number">8</span> 관련 주제</a></li>
  <li><a href="#참고문헌" id="toc-참고문헌" class="nav-link" data-scroll-target="#참고문헌"><span class="header-section-number">9</span> 참고문헌</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="들어가며-본-편의-자리" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="들어가며-본-편의-자리"><span class="header-section-number">1</span> 들어가며 — 본 편의 자리</h2>
<p>Ch.21 의 사다리:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">편</th>
<th style="text-align: left;">주제</th>
<th style="text-align: left;">핵심</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><a href="../../../../../docs/blog/posts/Statistics/bayesian/04-21-0-gaussian-process-overview.html">Overview (04-21-0)</a></td>
<td style="text-align: left;">Ch.21 의 큰 그림</td>
<td style="text-align: left;">GP 정의, kernel 가족, marginal likelihood</td>
</tr>
<tr class="even">
<td style="text-align: left;"><a href="../../../../../docs/blog/posts/Statistics/bayesian/04-21-1-gp-regression-birthdays-latent.html">§ 21.1~21.3 (04-21-1)</a></td>
<td style="text-align: left;">GP regression 의 핵심</td>
<td style="text-align: left;">식 (21.1) 유도·Birthday·Latent GP·Laplace 식 (21.3)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>§ 21.4~21.7 (본 편)</strong></td>
<td style="text-align: left;"><strong>함수·분포까지 확장 + 연습</strong></td>
<td style="text-align: left;">FDA·LGP density·식 (21.4)·식 (21.5)·9문제 풀이</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
본 편이 답하는 다섯 가지 질문
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><strong>개체마다 함수가 다른 데이터</strong> (FDA) 를 GP 가 어떻게 spline 보다 자연스럽게 처리하는가?</li>
<li>회귀 함수가 아닌 <strong>분포 자체</strong> 에 비모수 사전분포를 두려면 어떻게 해야 하는가? (LGP)</li>
<li>식 (21.4) density regression 의 kernel 이 결합 입력 <span class="math inline">\((x, y)\)</span> 에 작용하는 의미는?</li>
<li>식 (21.5) latent-variable regression 이 LGP 의 정규화 적분 부담을 어떻게 우회하는가?</li>
<li>§ 21.7 의 9 연습문제는 GP 의 어떤 측면을 각각 검증하는가?</li>
</ol>
</div>
</div>
</section>
<section id="functional-data-analysis-각-개체가-함수인-데이터" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="functional-data-analysis-각-개체가-함수인-데이터"><span class="header-section-number">2</span> § 21.4 Functional Data Analysis — 각 개체가 함수인 데이터</h2>
<section id="동기-데이터-단위가-점이-아니라-곡선" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="동기-데이터-단위가-점이-아니라-곡선"><span class="header-section-number">2.1</span> 동기 — 데이터 단위가 점이 아니라 곡선</h3>
<p>전통 회귀에서 한 개체 <span class="math inline">\(i\)</span> 의 데이터는 <span class="math inline">\((x_i, y_i)\)</span> — 스칼라 또는 벡터. <strong>함수형 데이터</strong> (functional data) 는 한 개체가 <strong>함수 자체</strong> 다.</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">분야</th>
<th style="text-align: left;">개체</th>
<th style="text-align: left;">함수 <span class="math inline">\(f_i\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">의학</td>
<td style="text-align: left;">환자</td>
<td style="text-align: left;">시간 → 혈압·체중·심박수</td>
</tr>
<tr class="even">
<td style="text-align: left;">교육</td>
<td style="text-align: left;">학생</td>
<td style="text-align: left;">학년 → 시험 점수</td>
</tr>
<tr class="odd">
<td style="text-align: left;">경제</td>
<td style="text-align: left;">국가</td>
<td style="text-align: left;">시점 → GDP·실업률</td>
</tr>
<tr class="even">
<td style="text-align: left;">환경</td>
<td style="text-align: left;">측정소</td>
<td style="text-align: left;">시간 → 미세먼지·온도</td>
</tr>
<tr class="odd">
<td style="text-align: left;">생화학</td>
<td style="text-align: left;">RT-PCR well</td>
<td style="text-align: left;">사이클 → 형광 강도</td>
</tr>
</tbody>
</table>
<p>실무에서는 함수 <span class="math inline">\(f_i\)</span> 를 유한 측정점에서 관측: <span class="math inline">\(y_{ij} = f_i(t_{ij}) + \epsilon_{ij}\)</span>, <span class="math inline">\(t_{ij} \in \mathcal{T}\)</span>.</p>
</section>
<section id="전통-fda-와-gp-fda-의-차이" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="전통-fda-와-gp-fda-의-차이"><span class="header-section-number">2.2</span> 전통 FDA 와 GP-FDA 의 차이</h3>
<p><strong>전통 FDA (Ramsay-Silverman 식 spline)</strong>:</p>
<ol type="1">
<li>각 <span class="math inline">\(f_i\)</span> 를 basis 가중합으로 표현: <span class="math inline">\(f_i(t) = \sum_h c_{ih} b_h(t)\)</span>.</li>
<li>계수 <span class="math inline">\(c_{ih}\)</span> 에 분포 부여.</li>
<li>평균 함수·주성분 (FPCA) 분석.</li>
</ol>
<p><strong>GP-FDA</strong>:</p>
<p><span class="math display">\[
y_{ij} \sim N\bigl(f(x_i, t_{ij}), \sigma^2\bigr), \qquad f \sim \text{GP}(m, k)
\]</span></p>
<p><span class="math inline">\(x_i\)</span> = 개체 특성 (sex, age 등), <span class="math inline">\(t_{ij}\)</span> = 측정 시점. <strong>시간 차원을 입력에 추가</strong> 하여 GP 한 번에 모든 개체와 모든 시점을 동시에 처리.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — 시간 차원을 추가한다는 발상
</div>
</div>
<div class="callout-body-container callout-body">
<p>전통 FDA 가 “함수 공간 위의 분포” 를 직접 다뤘다면, GP-FDA 는 더 단순한 트릭을 쓴다 — <strong>함수 <span class="math inline">\(f(x, t)\)</span> 의 입력에 시간을 끼워 넣는다</strong>.</p>
<p><span class="math inline">\(f\)</span> 는 <span class="math inline">\((x, t)\)</span> 의 <strong>2 차원 또는 그 이상</strong> 의 함수. GP regression 의 기계가 그대로 작동.</p>
<p>장점: 별도 functional machinery 불필요. anisotropic kernel 로 <span class="math inline">\(x\)</span> 차원과 <span class="math inline">\(t\)</span> 차원의 smoothness 를 독립 제어. 측정 시점이 개체마다 달라도 자동 처리 (전통 FDA 는 이 경우 보간 필요).</p>
<p>단점: 개체 수 <span class="math inline">\(n\)</span> + 평균 측정 횟수 <span class="math inline">\(m\)</span> 일 때 총 <span class="math inline">\(nm\)</span> 점이므로 <span class="math inline">\(O((nm)^3)\)</span>. 일반적으로 sparse GP 또는 separable approximation 필요.</p>
</div>
</div>
</section>
<section id="separable-kernel-개체-시간" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="separable-kernel-개체-시간"><span class="header-section-number">2.3</span> Separable Kernel — 개체 × 시간</h3>
<p>GP-FDA 의 일반적 kernel 형태:</p>
<p><span class="math display">\[
k\bigl((x, t), (x', t')\bigr) = \tau^2 \exp\left( -\sum_{j=1}^p \frac{(x_j - x_j')^2}{2\ell_j^2} - \frac{(t - t')^2}{2\ell_{p+1}^2} \right)
\]</span></p>
<p>ARD 가 자동으로 변수 선택까지 해 준다.</p>
<p><strong>Separable</strong> 형태: <span class="math inline">\(k = k_x(x, x') \cdot k_t(t, t')\)</span>. 이 경우 행렬 구조가 Kronecker product:</p>
<p><span class="math display">\[
K = K_x \otimes K_t
\]</span></p>
<p><span class="math inline">\(K_x\)</span> 는 <span class="math inline">\(n \times n\)</span>, <span class="math inline">\(K_t\)</span> 는 <span class="math inline">\(m \times m\)</span>. <strong>Cholesky 가 <span class="math inline">\(O(n^3 + m^3)\)</span></strong> 로 줄어든다 (full <span class="math inline">\(O((nm)^3)\)</span> 대비 큰 이득).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — Separable 의 의미
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(k = k_x \cdot k_t\)</span> 의 의미: 두 데이터 포인트 <span class="math inline">\((x, t)\)</span> 와 <span class="math inline">\((x', t')\)</span> 의 함수 값 닮음은 <strong><span class="math inline">\(x\)</span> 가 닮고 + <span class="math inline">\(t\)</span> 가 닮음</strong> 의 곱.</p>
<p>예: 환자 trajectory 모델에서</p>
<ul>
<li>환자 두 명이 비슷한 특성 (age·sex 비슷) → <span class="math inline">\(k_x\)</span> 큼.</li>
<li>측정 시점이 비슷 → <span class="math inline">\(k_t\)</span> 큼.</li>
<li>둘 다 만족해야 trajectory 값이 비슷.</li>
</ul>
<p>비-separable kernel 은 표현력이 더 크지만 (예: “젊은 환자는 시간 따라 빨리 변한다” 같은 시간 × 특성 상호작용), 계산 비용이 다시 <span class="math inline">\(O((nm)^3)\)</span>.</p>
</div>
</div>
</section>
<section id="응용-rt-pcr-형광-곡선" class="level3" data-number="2.4">
<h3 data-number="2.4" class="anchored" data-anchor-id="응용-rt-pcr-형광-곡선"><span class="header-section-number">2.4</span> 응용 — RT-PCR 형광 곡선</h3>
<p>PCR (polymerase chain reaction) 장비에서 각 well 마다 사이클 (<span class="math inline">\(t = 1, \ldots, 40\)</span>) 별 형광 강도 (<span class="math inline">\(y\)</span>) 측정. 96-well plate 면 96 개 곡선.</p>
<ul>
<li><span class="math inline">\(x_i\)</span> = 시료 농도 (log10 copy 수).</li>
<li><span class="math inline">\(t_{ij}\)</span> = 사이클.</li>
<li><span class="math inline">\(y_{ij}\)</span> = 형광 강도.</li>
</ul>
<p>GP-FDA 모델:</p>
<p><span class="math display">\[
y_{ij} = f(x_i, t_{ij}) + \epsilon_{ij}, \qquad f \sim \text{GP}(0, k_{\text{aniso}})
\]</span></p>
<p>장점:</p>
<ul>
<li>각 well 의 baseline·plateau·midpoint 가 자동 학습.</li>
<li>well 간 정보 공유로 noisy well 의 추정 안정.</li>
<li>외삽 시 “비슷한 농도의 well” 의 패턴 차용.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — GP-FDA 가 hierarchical 모델의 nonparametric 일반화
</div>
</div>
<div class="callout-body-container callout-body">
<p><a href="../../../../../docs/blog/posts/Statistics/bayesian/00-5-0-hierarchical.html">Ch.5 hierarchical models</a> 에서 그룹별 parameter 가 공통 hyperprior 를 통해 정보 공유. GP-FDA 는 <strong>그룹별 함수</strong> 가 공통 GP prior 를 통해 정보 공유.</p>
<p>전자: parameter 차원이 그룹 수. 후자: parameter 차원 무한 (함수).</p>
<p><strong>GP-FDA = nonparametric hierarchical</strong>.</p>
</div>
</div>
</section>
</section>
<section id="density-estimation-and-regression" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="density-estimation-and-regression"><span class="header-section-number">3</span> § 21.5 Density Estimation and Regression</h2>
<section id="동기-회귀-함수-너머" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="동기-회귀-함수-너머"><span class="header-section-number">3.1</span> 동기 — 회귀 함수 너머</h3>
<p>지금까지 GP 는 <span class="math inline">\(E[y \mid x] = \mu(x)\)</span> 의 사전분포. 그런데 데이터의 <strong>전체 조건부 분포</strong> <span class="math inline">\(p(y \mid x)\)</span> 가 비모수일 수도 있다.</p>
<p>예: 측정 노이즈가 정규가 아니라 매우 비대칭 (heavy tail)·다봉 (multi-modal). 이런 분포를 parametric family 로 가정하지 않고 데이터로부터 학습.</p>
<p><strong>두 접근</strong>:</p>
<ol type="1">
<li><strong>Logistic Gaussian Process (LGP)</strong> — § 21.5 의 주제.</li>
<li><strong>Mixture model 기반</strong> (Dirichlet Process mixture, DPM) — Ch.23 의 주제.</li>
</ol>
</section>
<section id="lgp-일변량-밀도-추정" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="lgp-일변량-밀도-추정"><span class="header-section-number">3.2</span> LGP — 일변량 밀도 추정</h3>
<p>Continuous logistic transformation:</p>
<p><span class="math display">\[
p(y \mid f) = \frac{e^{f(y)}}{\int e^{f(y')} dy'}, \qquad f \sim \text{GP}(m, k)
\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — softmax 의 연속화
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><strong>Softmax (이산)</strong>: <span class="math inline">\(p_k = e^{f_k} / \sum_j e^{f_j}\)</span>.</li>
<li><strong>LGP (연속)</strong>: <span class="math inline">\(p(y) = e^{f(y)} / \int e^{f(y')} dy'\)</span>.</li>
</ul>
<p>이산의 합이 연속의 적분으로. 이 변환의 두 보장:</p>
<ol type="1">
<li><span class="math inline">\(e^{f(y)} &gt; 0\)</span> → 음이 아닌 밀도.</li>
<li><span class="math inline">\(\int p(y) dy = 1\)</span> → 정규화 보장.</li>
</ol>
<p>GP 의 임의의 표본 <span class="math inline">\(f\)</span> 가 <strong>자동으로 valid 확률 밀도</strong> 로 변환.</p>
</div>
</div>
</section>
<section id="mean-function-m-의-역할" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="mean-function-m-의-역할"><span class="header-section-number">3.3</span> Mean Function <span class="math inline">\(m\)</span> 의 역할</h3>
<p><span class="math inline">\(m(y)\)</span> 를 <strong>기준 분포의 log density</strong> 로 두면 (예: <span class="math inline">\(m(y) = \log t_4(y \mid \mu_0, \sigma_0)\)</span>), 데이터 부족 영역에서 LGP 가 <span class="math inline">\(t_4\)</span> 분포로 회귀.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — anchored prior
</div>
</div>
<div class="callout-body-container callout-body">
<p>데이터 적을 때: <strong>표준 분포가 default</strong>. 데이터 충분할 때: <strong>데이터 패턴 적극 반영</strong>.</p>
<p>이는 ridge regression 의 sparsity prior 와 같은 정신 — 도메인 지식을 <strong>center</strong> 에 두고 데이터가 허락하는 만큼 이탈.</p>
<p>choices for <span class="math inline">\(m\)</span>:</p>
<ul>
<li><span class="math inline">\(t_4\)</span> — heavy tail 안전.</li>
<li>Empirical Bayes: 데이터의 sample mean·variance 기반 정규.</li>
<li>Mixture: <span class="math inline">\(\log \sum_k \pi_k N(y \mid \mu_k, \sigma_k^2)\)</span> — 다봉 가정 시.</li>
</ul>
</div>
</div>
</section>
<section id="정규화-적분의-계산-challenge" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="정규화-적분의-계산-challenge"><span class="header-section-number">3.4</span> 정규화 적분의 계산 Challenge</h3>
<p><span class="math inline">\(\int e^{f(y')} dy'\)</span> 가 닫힌 형태로 안 나옴 → 근사 필수.</p>
<p><strong>방법</strong>:</p>
<ol type="1">
<li><strong>유한 grid 이산화</strong>: <span class="math inline">\(y\)</span> 의 영역을 <span class="math inline">\(K\)</span> 점 grid 로 → 적분이 합으로 근사.</li>
<li><strong>Finite basis representation</strong>: <span class="math inline">\(f\)</span> 를 spline·Fourier 등 유한 basis 로 표현.</li>
<li><strong>Rejection / importance sampling</strong>: GP 표본 <span class="math inline">\(f\)</span> 마다 정규화 상수를 sampling 으로.</li>
</ol>
<p>전통적으로 1 번이 가장 간단. <span class="math inline">\(K = 100 \sim 200\)</span> grid 면 일변량은 충분.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — LGP 의 unimodality 이점
</div>
</div>
<div class="callout-body-container callout-body">
<p>LGP 의 <span class="math inline">\(f\)</span> 사후는 — hyperparameter 고정 시 — <strong>단봉 (unimodal)</strong>. 이는 mixture model 의 <span class="math inline">\(\theta\)</span> 사후가 multimodal (label switching) 인 것과 큰 차이.</p>
<p>따라서 Laplace 또는 단순 mode finding 으로도 잘 작동. Ch.22 mixture 와 비교 시 계산 안정성에서 명백한 우위.</p>
</div>
</div>
</section>
<section id="대안-표현-compactified-gp" class="level3" data-number="3.5">
<h3 data-number="3.5" class="anchored" data-anchor-id="대안-표현-compactified-gp"><span class="header-section-number">3.5</span> 대안 표현 — Compactified GP</h3>
<p><span class="math inline">\(g_0\)</span> = 기준 parametric density, <span class="math inline">\(G_0\)</span> = 그 CDF. Compactified LGP:</p>
<p><span class="math display">\[
p(y) = g_0(y) \cdot \frac{e^{W(G_0(y))}}{\int e^{W(v)} dv}
\]</span></p>
<ul>
<li><span class="math inline">\(W(t)\)</span> 는 <span class="math inline">\([0, 1]\)</span> 에서 정의된 zero-mean GP.</li>
<li><span class="math inline">\(G_0(y) \in [0, 1]\)</span> 로 변환.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — 왜 [0, 1] 로 압축하는가
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(y \in (-\infty, \infty)\)</span> 에 GP prior 를 직접 두면 <strong>꼬리에서 GP 가 자유롭게 출렁</strong> 인다 → 부적절한 꼬리 추정.</p>
<p>CDF <span class="math inline">\(G_0\)</span> 로 <span class="math inline">\([0, 1]\)</span> 압축하면 꼬리는 <span class="math inline">\(g_0\)</span> 가 결정 (smooth tail), GP 는 중앙부의 deviation 만 표현. <strong>꼬리 안정성 향상</strong>.</p>
</div>
</div>
</section>
<section id="galaxies-and-lakes-예제" class="level3" data-number="3.6">
<h3 data-number="3.6" class="anchored" data-anchor-id="galaxies-and-lakes-예제"><span class="header-section-number">3.6</span> Galaxies and Lakes 예제</h3>
<p><strong>Galaxy 데이터</strong>: 82 개 은하의 후퇴 속도. 다봉 구조 의심.</p>
<p><strong>Acidity 데이터</strong>: 위스콘신 155 호수의 산성도.</p>
<p>저자들은 LGP <span class="math inline">\(\nu = 5/2\)</span> Matern + Gaussian center + 꼬리 단조 감소 제약 (rejection sampling 으로). Figure 21.7 결과:</p>
<ul>
<li>다봉 구조 자연 표현.</li>
<li>histogram 보다 부드러우면서도 mixture 보다 유연.</li>
<li>90% 사후 구간으로 불확실성 정량화.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — LGP vs Mixture 의 trade-off
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>LGP</strong>:</p>
<ul>
<li>장점: 사후 단봉, 계산 안정, 유연성 매우 높음.</li>
<li>단점: 정규화 적분 비용, 다차원 확장 어려움.</li>
</ul>
<p><strong>DP Mixture (Ch.23)</strong>:</p>
<ul>
<li>장점: clustering 해석 가능, 다차원 확장 자연.</li>
<li>단점: 사후 다봉 (label switching), MCMC 까다로움.</li>
</ul>
<p>선택 기준: 일변량·이변량 + clustering 해석 불필요 → LGP. 다차원 + clustering 해석 필요 → DPM.</p>
</div>
</div>
</section>
<section id="density-regression-식-21.4" class="level3" data-number="3.7">
<h3 data-number="3.7" class="anchored" data-anchor-id="density-regression-식-21.4"><span class="header-section-number">3.7</span> Density Regression — 식 (21.4)</h3>
<p>조건부 밀도 <span class="math inline">\(p(y \mid x)\)</span> 도 같은 방식으로 GP prior:</p>
<p><span class="math display">\[
p(y \mid x) = \frac{e^{f(x, y)}}{\int e^{f(x, y')} dy'}, \qquad f \sim \text{GP}(0, k)
\]</span></p>
<p>Squared exponential kernel on joint <span class="math inline">\((x, y)\)</span>:</p>
<p><span class="math display">\[
k\bigl((x, y), (x', y')\bigr) = \tau^2 \exp\left( -\sum_{j=1}^p \frac{(x_j - x_j')^2}{2 \ell_j} - \frac{(y - y')^2}{2 \ell_{p+1}} \right) \quad (21.4)
\]</span></p>
<p>각 <span class="math inline">\(\ell_j\)</span> 의 hyperprior 로 ARD — 불필요한 <span class="math inline">\(x_j\)</span> 자동 탈락.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — Density regression 이 잡는 것
</div>
</div>
<div class="callout-body-container callout-body">
<p>전통 회귀: <span class="math inline">\(E[y \mid x]\)</span> + 등분산 가정.</p>
<p>GLM·heteroscedastic 회귀: <span class="math inline">\(E[y \mid x]\)</span> + <span class="math inline">\(\text{Var}[y \mid x]\)</span>.</p>
<p><strong>Density regression</strong>: <span class="math inline">\(p(y \mid x)\)</span> 의 <strong>모든 모멘트</strong>. 분포 형태가 <span class="math inline">\(x\)</span> 에 따라 변화 (bimodal → unimodal, 좌편향 → 우편향 등) 도 표현.</p>
<p>응용: 의료 (환자 특성에 따라 반응 분포 형태 자체가 다름)·금융 (시장 상황별 수익률 분포).</p>
</div>
</div>
</section>
<section id="식-21.5-latent-variable-regression-kundu-dunson" class="level3" data-number="3.8">
<h3 data-number="3.8" class="anchored" data-anchor-id="식-21.5-latent-variable-regression-kundu-dunson"><span class="header-section-number">3.8</span> 식 (21.5) Latent-Variable Regression — Kundu-Dunson</h3>
<p>LGP 의 정규화 적분 부담을 우회하는 영리한 대안.</p>
<p><span class="math display">\[
y_i \sim N\bigl(\mu(u_i), \sigma^2\bigr), \qquad u_i \sim U(0, 1) \quad (21.5)
\]</span></p>
<p><span class="math inline">\(u_i\)</span> = 잠재 균등 변수. <span class="math inline">\(\mu: [0, 1] \to \mathbb{R}\)</span> 은 GP.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — 분위수 함수 (inverse CDF) 의 GP prior
</div>
</div>
<div class="callout-body-container callout-body">
<p>확률·통계의 기본: 임의의 분포 <span class="math inline">\(f\)</span> 의 sample 은 <span class="math inline">\(y = F^{-1}(u)\)</span>, <span class="math inline">\(u \sim U(0, 1)\)</span> 로 생성 가능 (<span class="math inline">\(F^{-1}\)</span> = quantile function).</p>
<p>식 (21.5) 는 <span class="math inline">\(\mu(u)\)</span> 를 quantile function 의 GP 모델로 본다. 그 위에 noise <span class="math inline">\(\sigma\)</span> 추가.</p>
<p><strong>핵심 이점</strong>: 정규화 적분 없음. GP 의 표준 추론 그대로 적용. 컴팩트 입력 <span class="math inline">\([0, 1]\)</span> 위의 1D GP — 매우 빠름.</p>
</div>
</div>
</section>
<section id="density-regression-식-21.5-의-일반화" class="level3" data-number="3.9">
<h3 data-number="3.9" class="anchored" data-anchor-id="density-regression-식-21.5-의-일반화"><span class="header-section-number">3.9</span> Density Regression — 식 (21.5) 의 일반화</h3>
<p>조건부 밀도로 확장:</p>
<p><span class="math display">\[
y_i \sim N\bigl(\mu(u_i, x_i), \sigma^2\bigr), \qquad u_i \sim U(0, 1)
\]</span></p>
<p><span class="math inline">\(\mu\)</span> 는 <span class="math inline">\((p + 1)\)</span> 차원 GP. ARD 로 변수 선택.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — <span class="math inline">\(u_i\)</span> 의 역할
</div>
</div>
<div class="callout-body-container callout-body">
<p><span class="math inline">\(u_i\)</span> = 개체 <span class="math inline">\(i\)</span> 의 “분위수 위치”. <span class="math inline">\(u_i = 0.5\)</span> 이면 그 분포의 중앙값.</p>
<p>데이터 augmentation 으로 <span class="math inline">\(u_i\)</span> 를 갱신하면, <strong>각 개체가 자기 분포의 어느 분위수에 있는지</strong> 자동 학습.</p>
<p>해석: <span class="math inline">\(u_i\)</span> 의 사후가 한쪽 끝에 몰리면 그 개체는 outlier 후보.</p>
</div>
</div>
</section>
</section>
<section id="bibliographic-note-핵심-문헌-정리" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="bibliographic-note-핵심-문헌-정리"><span class="header-section-number">4</span> § 21.6 Bibliographic Note — 핵심 문헌 정리</h2>
<section id="gp-이론계산의-4-가지-정전" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="gp-이론계산의-4-가지-정전"><span class="header-section-number">4.1</span> GP 이론·계산의 4 가지 정전</h3>
<table class="table">
<colgroup>
<col style="width: 36%">
<col style="width: 63%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">문헌</th>
<th style="text-align: left;">주제</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>O’Hagan (1978)</strong></td>
<td style="text-align: left;">GP regression 의 베이즈 원전 — Bayesian Numerical Analysis 시초</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Neal (1998)</strong></td>
<td style="text-align: left;">GP regression/classification + ARD 도입 + neural network 무한 폭 한계</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Rasmussen &amp; Williams (2006)</strong></td>
<td style="text-align: left;"><em>Gaussian Processes for Machine Learning</em> — GP 의 정전 (free PDF)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Vanhatalo et al.&nbsp;(2013a)</strong></td>
<td style="text-align: left;">GPstuff 패키지 + 종합 리뷰</td>
</tr>
</tbody>
</table>
</section>
<section id="효율-계산-6-가지-길" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="효율-계산-6-가지-길"><span class="header-section-number">4.2</span> 효율 계산 — 6 가지 길</h3>
<table class="table">
<colgroup>
<col style="width: 18%">
<col style="width: 31%">
<col style="width: 22%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">문헌</th>
<th style="text-align: left;">기법</th>
<th style="text-align: left;">비용</th>
<th style="text-align: left;">적용</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Snelson &amp; Ghahramani (2006)</td>
<td style="text-align: left;">FITC inducing</td>
<td style="text-align: left;"><span class="math inline">\(O(nm^2)\)</span></td>
<td style="text-align: left;">일반</td>
</tr>
<tr class="even">
<td style="text-align: left;">Titsias (2009)</td>
<td style="text-align: left;">Variational SGP</td>
<td style="text-align: left;"><span class="math inline">\(O(nm^2)\)</span></td>
<td style="text-align: left;">일반</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hensman, Fusi, Lawrence (2013)</td>
<td style="text-align: left;">Stochastic variational</td>
<td style="text-align: left;"><span class="math inline">\(O(m^3 b)\)</span></td>
<td style="text-align: left;">Big data</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lindgren, Rue, Lindstrom (2011)</td>
<td style="text-align: left;">SPDE → GMRF</td>
<td style="text-align: left;"><span class="math inline">\(O(n^{3/2})\)</span></td>
<td style="text-align: left;">spatial</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sarkka, Solin, Hartikainen (2013)</td>
<td style="text-align: left;">State-space (Bayesian filter)</td>
<td style="text-align: left;"><span class="math inline">\(O(n)\)</span></td>
<td style="text-align: left;">1D 시계열</td>
</tr>
<tr class="even">
<td style="text-align: left;">Wilson &amp; Nickisch (2015)</td>
<td style="text-align: left;">KISS-GP / SKI</td>
<td style="text-align: left;"><span class="math inline">\(O(n)\)</span></td>
<td style="text-align: left;">structured</td>
</tr>
</tbody>
</table>
</section>
<section id="응용" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="응용"><span class="header-section-number">4.3</span> 응용</h3>
<ul>
<li><strong>Riihimaki &amp; Vehtari (2010)</strong> — Monotonic GP regression.</li>
<li><strong>Vanhatalo &amp; Vehtari (2010)</strong> — Binary classification.</li>
<li><strong>Riihimaki, Jylanki, Vehtari (2013)</strong> — Multi-class.</li>
<li><strong>Tolvanen, Jylanki, Vehtari (2014)</strong> — Heteroscedastic.</li>
<li><strong>Jylanki, Vanhatalo, Vehtari (2011)</strong> — Robust regression (Student-<span class="math inline">\(t\)</span>).</li>
<li><strong>Vehtari et al.&nbsp;(2016)</strong> — LOO-CV approximation.</li>
</ul>
</section>
<section id="lgp-문헌" class="level3" data-number="4.4">
<h3 data-number="4.4" class="anchored" data-anchor-id="lgp-문헌"><span class="header-section-number">4.4</span> LGP 문헌</h3>
<ul>
<li><strong>Leonard (1978)</strong> — LGP 도입.</li>
<li><strong>Lenk (1991, 2003)</strong> — 사후 모멘트 기반 추론.</li>
<li><strong>Tokdar (2007)</strong> — MCMC for unconditional LGP.</li>
<li><strong>Tokdar, Zhu, Ghosh (2010)</strong> — MCMC for LGP density regression.</li>
<li><strong>Riihimaki &amp; Vehtari (2014)</strong> — 빠른 Laplace approximation.</li>
<li><strong>Tokdar &amp; Ghosh (2007)</strong>, <strong>Tokdar et al.&nbsp;(2010)</strong> — LGP 일관성 (consistency).</li>
<li><strong>Adams et al.&nbsp;(2009)</strong> — Conditioning + rejection 으로 정규화 회피.</li>
<li><strong>Kundu &amp; Dunson (2014)</strong> — Latent-variable regression (식 21.5).</li>
</ul>
</section>
</section>
<section id="exercises-9문제-완전-풀이" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="exercises-9문제-완전-풀이"><span class="header-section-number">5</span> § 21.7 Exercises — 9문제 완전 풀이</h2>
<section id="exercise-1-gp-prior-표본-figure-21.1-재현" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="exercise-1-gp-prior-표본-figure-21.1-재현"><span class="header-section-number">5.1</span> Exercise 1 — GP Prior 표본 (Figure 21.1 재현)</h3>
<p><strong>문제</strong>: 일변량 <span class="math inline">\(x\)</span> grid 에서 <span class="math inline">\(\tau, \ell\)</span> 다양화하며 GP prior 표본 추출. 데이터 만들고 사후 평균·공분산 계산 후 사후 표본 추출.</p>
<p><strong>모델</strong>: <span class="math inline">\(\mu \sim \text{GP}(0, k)\)</span>, <span class="math inline">\(k(x, x') = \tau^2 \exp(-(x-x')^2 / (2\ell^2))\)</span>.</p>
<p><strong>Prior 표본 절차</strong>:</p>
<ol type="1">
<li>Grid <span class="math inline">\(x_1, \ldots, x_n\)</span> 결정 (예: <span class="math inline">\(n = 100\)</span>, <span class="math inline">\(x_i \in [-3, 3]\)</span>).</li>
<li><span class="math inline">\(K = (k(x_i, x_j))_{ij}\)</span>.</li>
<li><span class="math inline">\(\boldsymbol\mu \sim N(0, K)\)</span> — Cholesky <span class="math inline">\(L L^T = K + \text{jitter} \cdot I\)</span>, <span class="math inline">\(\boldsymbol\mu = L \mathbf{z}\)</span>, <span class="math inline">\(\mathbf{z} \sim N(0, I)\)</span>.</li>
</ol>
<p><strong>사후 절차</strong> (관측 <span class="math inline">\((x_{\text{obs}}, y_{\text{obs}})\)</span>, <span class="math inline">\(y \mid \mu \sim N(\mu, \sigma^2)\)</span>):</p>
<ul>
<li><span class="math inline">\(E(\widetilde\mu) = K(\widetilde x, x) (K(x, x) + \sigma^2 I)^{-1} y\)</span>.</li>
<li><span class="math inline">\(\text{cov}(\widetilde\mu) = K(\widetilde x, \widetilde x) - K(\widetilde x, x)(K(x, x) + \sigma^2 I)^{-1} K(x, \widetilde x)\)</span>.</li>
<li>사후 표본도 <span class="math inline">\(E(\widetilde\mu) + L_{\text{post}} \mathbf{z}\)</span> 로 추출.</li>
</ul>
<p><strong>관찰 포인트</strong>:</p>
<table class="table">
<colgroup>
<col style="width: 26%">
<col style="width: 36%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">(<span class="math inline">\(\tau\)</span>, <span class="math inline">\(\ell\)</span>)</th>
<th style="text-align: left;">Prior 표본 모양</th>
<th style="text-align: left;">Posterior 모양</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(0.5, 2)</td>
<td style="text-align: left;">큰 진폭, 매끄러움</td>
<td style="text-align: left;">데이터 점에서 가까이 통과, 사이 매끄럽게 보간</td>
</tr>
<tr class="even">
<td style="text-align: left;">(0.25, 0.5)</td>
<td style="text-align: left;">작은 진폭, 빠른 변동</td>
<td style="text-align: left;">데이터 통과하나 너무 wiggly</td>
</tr>
<tr class="odd">
<td style="text-align: left;">(0.5, 0.5)</td>
<td style="text-align: left;">중간 진폭, 중간 변동</td>
<td style="text-align: left;">일반적으로 가장 합리적</td>
</tr>
</tbody>
</table>
</section>
<section id="exercise-2-naes04-attitude-normal-approx-gp-regression" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="exercise-2-naes04-attitude-normal-approx-gp-regression"><span class="header-section-number">5.2</span> Exercise 2 — NAES04 Attitude (Normal Approx GP Regression)</h3>
<p><strong>문제</strong>: 2004 National Annenberg Election Survey 의 게이 관련 attitude 데이터. 연령 <span class="math inline">\(x\)</span> 의 함수로 “게이를 알고 있다고 답한 비율” 추정. Normal approximation 사용.</p>
<p><strong>모델</strong>:</p>
<ul>
<li><span class="math inline">\(y_a\)</span> = 연령 <span class="math inline">\(a\)</span> 에서 Yes 비율.</li>
<li><span class="math inline">\(n_a\)</span> = 연령 <span class="math inline">\(a\)</span> 의 응답자 수.</li>
<li><span class="math inline">\(y_a \mid p_a \sim \text{Binomial}(n_a, p_a)\)</span> → 정규 근사 <span class="math inline">\(y_a/n_a \sim N(p_a, p_a(1-p_a)/n_a)\)</span>.</li>
</ul>
<p><strong>GP Prior</strong>: <span class="math inline">\(\text{logit}(p_a) = f(a)\)</span>, <span class="math inline">\(f \sim \text{GP}(0, k_{\text{SE}})\)</span>, <span class="math inline">\(k_{\text{SE}}(a, a') = \tau^2 \exp(-(a-a')^2 / (2\ell^2))\)</span>.</p>
<p><strong>Hyperpriors</strong>: <span class="math inline">\(\tau \sim \text{half-}t_4(0, 1)\)</span>, <span class="math inline">\(\ell \sim \text{half-}t_4(0, 20)\)</span> (연령 단위).</p>
<p><strong>Joint posterior</strong>:</p>
<p><span class="math display">\[
p(f, \tau, \ell \mid y) \propto p(\tau)\, p(\ell)\, N(f \mid 0, K(\tau, \ell)) \prod_a N\bigl(y_a/n_a \mid \text{logit}^{-1}(f(a)),\ p_a(1-p_a)/n_a\bigr)
\]</span></p>
<p><strong>추론</strong>: PyMC, Stan, 또는 Laplace + CCD.</p>
<p><strong>예상 결과</strong>: 청년층 (20s) 매우 높은 비율, 60+ 낮음, 중간 연령에 변곡점. GP 가 자동으로 비선형 곡선 적합.</p>
</section>
<section id="exercise-3-naes04-binomial-gp" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="exercise-3-naes04-binomial-gp"><span class="header-section-number">5.3</span> Exercise 3 — NAES04 Binomial GP</h3>
<p><strong>문제</strong>: Exercise 2 와 동일한 데이터, <strong>정규 근사 대신 binomial 우도</strong>.</p>
<p><strong>모델</strong>:</p>
<p><span class="math display">\[
y_a \sim \text{Binomial}(n_a, p_a), \qquad p_a = \text{logit}^{-1}(f(a)), \qquad f \sim \text{GP}(0, k)
\]</span></p>
<p><strong>추론 차이</strong>: 우도가 비가우시안 → <strong>Laplace 근사 식 (21.3) 적용</strong>. 식 (21.3) 의 <span class="math inline">\(W\)</span>:</p>
<p><span class="math display">\[
W_{aa} = -\frac{\partial^2 \log p(y_a \mid f_a)}{\partial f_a^2} = n_a p_a (1 - p_a)
\]</span></p>
<p>(Logistic regression 의 일반적 second derivative.)</p>
<p><strong>Exercise 2 와의 비교</strong>: 정규 근사가 small <span class="math inline">\(n_a\)</span> 에서 부정확. Binomial 모형이 꼬리에서 더 합리적 (특히 연령별 응답자 수가 적은 양 끝).</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — 왜 두 exercise 를 다 푸는가
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Ex 2 (정규 근사): 우도가 가우시안 → 적분 소거 가능 → 식 (21.1).</li>
<li>Ex 3 (Binomial): 우도가 비가우시안 → Laplace 필요 → 식 (21.3).</li>
</ul>
<p>같은 데이터에 두 방법을 적용하면 (1) 결과가 거의 같음 — 정규 근사가 valid 한 영역, (2) 양 극단에서만 차이 — Binomial 의 꼬리 안정성. <strong>Laplace 의 정확도</strong> 검증.</p>
</div>
</div>
</section>
<section id="exercise-4-multi-predictor-anisotropic-gp" class="level3" data-number="5.4">
<h3 data-number="5.4" class="anchored" data-anchor-id="exercise-4-multi-predictor-anisotropic-gp"><span class="header-section-number">5.4</span> Exercise 4 — Multi-Predictor Anisotropic GP</h3>
<p><strong>문제</strong>: NAES04 데이터, age + sex + race 세 predictor 로 확장.</p>
<p><strong>모델</strong>:</p>
<p><span class="math display">\[
\text{logit}(p) = f(x_1, x_2, x_3), \qquad f \sim \text{GP}(0, k_{\text{ARD}})
\]</span></p>
<p><span class="math display">\[
k_{\text{ARD}}(x, x') = \tau^2 \exp\left( -\sum_{j=1}^3 \frac{(x_j - x_j')^2}{2 \ell_j^2} \right)
\]</span></p>
<p><strong><span class="math inline">\(\ell_j\)</span> Hyperprior</strong>: half-<span class="math inline">\(t_4(0, s_j)\)</span>, <span class="math inline">\(s_j\)</span> = <span class="math inline">\(j\)</span> 번째 변수의 sd.</p>
<p><strong>해석 도구</strong>:</p>
<ul>
<li><span class="math inline">\(\ell_j\)</span> 사후 평균 비교: <span class="math inline">\(\ell_{\text{age}} \approx 15\)</span>, <span class="math inline">\(\ell_{\text{sex}}\)</span> 매우 큼 → sex 효과 미미.</li>
<li>Conditional plot: 각 predictor 별로 다른 변수 고정 후 <span class="math inline">\(f\)</span> 곡선 시각화.</li>
</ul>
<p><strong>예상 발견</strong>: 연령 효과가 가장 강함, race 효과 중간, sex 효과 미미 (또는 race-age 상호작용).</p>
</section>
<section id="exercise-5-golf-putting-binomial-gp" class="level3" data-number="5.5">
<h3 data-number="5.5" class="anchored" data-anchor-id="exercise-5-golf-putting-binomial-gp"><span class="header-section-number">5.5</span> Exercise 5 — Golf Putting Binomial GP</h3>
<p><strong>문제</strong>: 거리별 프로골퍼 putt 성공률. Ch.19 (4PL) 와 Ch.20 (spline) 솔루션과 비교.</p>
<p><strong>모델</strong>:</p>
<p><span class="math display">\[
y_d \sim \text{Binomial}(n_d, p_d), \qquad p_d = \text{logit}^{-1}(f(d)), \qquad f \sim \text{GP}(\text{mean}_0, k)
\]</span></p>
<p><strong>Mean 함수</strong>: 도메인 지식 — 거리 0 이면 100%, 거리 ∞ 이면 0%. 따라서</p>
<p><span class="math display">\[
\text{mean}_0(d) = \text{logit}\bigl(\Phi(\alpha + \beta d)\bigr) \approx -\beta d
\]</span></p>
<p>또는 Berry-Nolan 의 물리 모델을 mean 으로.</p>
<p><strong>Posterior predictive checks</strong>:</p>
<ul>
<li>관측 비율 vs 사후 예측 분위수 — 적합도 확인.</li>
<li>Pointwise 90% intervals: 데이터에서 멀리 떨어진 거리 (very long putts) 에서 불확실성 증가.</li>
</ul>
<p><strong>Ch.19/20 비교</strong>:</p>
<ul>
<li><strong>Ch.19 (4PL)</strong>: 4 parameter, 외삽 안정, 형태 제약.</li>
<li><strong>Ch.20 (spline)</strong>: <span class="math inline">\(H\)</span> 개 basis, 유연하나 외삽 불안정.</li>
<li><strong>Ch.21 (GP)</strong>: 비모수, mean 함수 활용 시 외삽 안정.</li>
</ul>
<p>LOO-CV lppd 비교로 어느 모델이 데이터에 가장 적합한지 정량화.</p>
</section>
<section id="exercise-6-birthday-분석-재현" class="level3" data-number="5.6">
<h3 data-number="5.6" class="anchored" data-anchor-id="exercise-6-birthday-분석-재현"><span class="header-section-number">5.6</span> Exercise 6 — Birthday 분석 재현</h3>
<p><strong>문제</strong>: § 21.2 의 birthday 모델을 component 단계별 추가.</p>
<p><strong>절차</strong>:</p>
<ol type="1">
<li><strong>Stage 1</strong>: <span class="math inline">\(f_1\)</span> + noise. Long-term trend 만 적합.</li>
<li><strong>Stage 2</strong>: + <span class="math inline">\(f_2\)</span> 단기 변동. 잔차 자기상관 감소 확인.</li>
<li><strong>Stage 3</strong>: + <span class="math inline">\(f_3\)</span> 주간. 7일 주기 잔차 사라짐.</li>
<li><strong>Stage 4</strong>: + <span class="math inline">\(f_4\)</span> 계절. 365일 주기 잔차 사라짐.</li>
<li><strong>Stage 5</strong>: + <span class="math inline">\(f_5\)</span> 특별일. Valentine·Halloween 잔차 사라짐.</li>
</ol>
<p>각 단계마다 LOO-CV lppd 측정 → component 추가 효과 정량화.</p>
<p><strong>확장 (Exercise 6b)</strong>: day-of-year 효과가 시간 따라 강해지는 것을 모델에 명시 → quasi-periodic kernel 의 evolution 부분에 추가 length scale.</p>
</section>
<section id="exercise-7-pollster-시계열-spline-gp-교체" class="level3" data-number="5.7">
<h3 data-number="5.7" class="anchored" data-anchor-id="exercise-7-pollster-시계열-spline-gp-교체"><span class="header-section-number">5.7</span> Exercise 7 — Pollster 시계열, Spline → GP 교체</h3>
<p><strong>문제</strong>: Exercise 20.5 (Pollster) 를 spline 대신 GP 로 적합.</p>
<p><strong>Spline 버전 (Ch.20)</strong>: <span class="math inline">\(H\)</span> B-splines + shrinkage prior on <span class="math inline">\(\beta_h\)</span>.</p>
<p><strong>GP 버전</strong>:</p>
<p><span class="math display">\[
\text{poll}_t = f(t) + \text{state effects} + \epsilon_t, \qquad f \sim \text{GP}(0, k_{\text{Matern 5/2}})
\]</span></p>
<p><strong>비교 포인트</strong>:</p>
<ul>
<li>Spline 의 knot 선택 vs GP 의 length scale.</li>
<li>외삽 영역 (선거일 이후) 불확실성.</li>
<li>계산 시간 (<span class="math inline">\(H\)</span> 개 계수 vs <span class="math inline">\(n \times n\)</span> kernel).</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — 같은 결과, 다른 길
</div>
</div>
<div class="callout-body-container callout-body">
<p>Spline 과 GP 는 <strong>같은 함수 공간을 다른 매개변수화</strong> 로 표현한다 (Ch.21 § 21.1 의 basis 동치 관계).</p>
<p>차이는 (1) hyperparameter 가 무엇인지 (knot 위치 vs length scale), (2) 어느 것이 데이터에서 더 자연스럽게 학습되는지에 달려 있다.</p>
<p>일반적으로 <strong>smoothing 문제</strong>: GP 가 더 나음 (knot 결정 불필요). <strong>해석 가능 부분 vs 잔여 부분 분리</strong>: Spline 이 더 나음 (각 basis 가 명시적).</p>
</div>
</div>
</section>
<section id="exercise-8-basis-가-유도하는-gp" class="level3" data-number="5.8">
<h3 data-number="5.8" class="anchored" data-anchor-id="exercise-8-basis-가-유도하는-gp"><span class="header-section-number">5.8</span> Exercise 8 — Basis 가 유도하는 GP</h3>
<p><strong>문제</strong>: <span class="math inline">\(\mu(x) = \sum_{h=1}^k \beta_h b_h(x)\)</span>, <span class="math inline">\(b_h(x) = \exp(\psi(x - \tau_h)^2)\)</span>. <span class="math inline">\((\beta_1, \ldots, \beta_k)\)</span> 의 prior 를 골라 <span class="math inline">\(\mu \sim \text{GP}(m, k)\)</span> 가 되도록.</p>
<p><strong>(a) Prior 선택</strong>: <span class="math inline">\(\beta \sim N(\beta_0, \Sigma_\beta)\)</span> — 다변량 정규.</p>
<p><strong>(b) 유도된 <span class="math inline">\(m, k\)</span></strong>:</p>
<p><span class="math display">\[
m(x) = b(x)^T \beta_0, \qquad k(x, x') = b(x)^T \Sigma_\beta b(x')
\]</span></p>
<p><span class="math inline">\(b(x) = (b_1(x), \ldots, b_k(x))\)</span>.</p>
<p>만약 <span class="math inline">\(\Sigma_\beta = \sigma_\beta^2 I\)</span>, <span class="math inline">\(\beta_0 = 0\)</span>:</p>
<p><span class="math display">\[
m(x) = 0, \qquad k(x, x') = \sigma_\beta^2 \sum_{h=1}^k b_h(x) b_h(x')
\]</span></p>
<p><strong>(c) Squared exp 와의 차이</strong>: <span class="math inline">\(k(x, x') = \exp(-\kappa(x - x')^2)\)</span> 는 모든 <span class="math inline">\(x\)</span> 에 무한 basis. 위의 유도된 <span class="math inline">\(k\)</span> 는 <span class="math inline">\(k\)</span>-개 유한 basis → <strong>rank 가 <span class="math inline">\(k\)</span> 로 제한</strong>.</p>
<p>따라서 유도된 GP 의 표본은 <strong><span class="math inline">\(k\)</span>-차원 함수 공간</strong> 안에 있음. 무한 basis squared exp 보다 표현력 작음.</p>
<p><strong>(d) 차이 최소화</strong>: <span class="math inline">\(\psi\)</span> 와 <span class="math inline">\(\tau_h\)</span> 를 squared exp 의 Mercer 분해 (Hermite polynomial 가중) 와 매칭. <span class="math inline">\(\tau_h\)</span> 를 데이터 영역에 균등 배치.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
이 연습이 가르치는 것
</div>
</div>
<div class="callout-body-container callout-body">
<p>GP (무한 basis) 와 finite basis 모델 (유한 basis) 의 <strong>명시적 변환</strong>. Reduced rank 근사 (KISS-GP, sparse GP) 의 수학적 기반.</p>
<p><span class="math inline">\(k\)</span> 개 inducing point 를 두는 sparse GP 가 사실상 <strong><span class="math inline">\(k\)</span> basis 의 finite expansion</strong> 과 같다.</p>
</div>
</div>
</section>
<section id="exercise-9-linear-모형은-gp-인가-비선형-표현-가능한가" class="level3" data-number="5.9">
<h3 data-number="5.9" class="anchored" data-anchor-id="exercise-9-linear-모형은-gp-인가-비선형-표현-가능한가"><span class="header-section-number">5.9</span> Exercise 9 — Linear 모형은 GP 인가, 비선형 표현 가능한가</h3>
<p><strong>문제</strong>: <span class="math inline">\(\mu(x) = \beta_1 + \beta_2 x\)</span>, <span class="math inline">\(\beta_1, \beta_2\)</span> 에 정규 prior.</p>
<p><strong>(a) GP 인가</strong>: 그렇다.</p>
<p><span class="math display">\[
\mu(x) = (1, x) \begin{pmatrix} \beta_1 \\ \beta_2 \end{pmatrix}
\]</span></p>
<p><span class="math inline">\(\beta \sim N(\beta_0, \Sigma_\beta)\)</span> 면 <span class="math inline">\(\mu(x_1), \ldots, \mu(x_n)\)</span> 의 결합도 정규 (다변량 정규의 affine 변환). 따라서 GP.</p>
<p>Mean·covariance:</p>
<p><span class="math display">\[
m(x) = \beta_{0,1} + \beta_{0,2} x, \qquad k(x, x') = \Sigma_{\beta,11} + (x + x') \Sigma_{\beta,12} + x x' \Sigma_{\beta,22}
\]</span></p>
<p><strong>(b) 비선형 표현 가능한가</strong>: 불가능.</p>
<p>GP 의 표본은 <span class="math inline">\(\mu(x) = \beta_1 + \beta_2 x\)</span> 형태로 제한 — <strong>모든 표본이 선형 함수</strong>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
직관 — “GP 이면 비선형” 은 거짓
</div>
</div>
<div class="callout-body-container callout-body">
<p>GP 가 <strong>자동으로 비선형 표현력</strong> 을 주는 것이 아니다. <strong>kernel 의 rank 와 basis 가 표현력을 결정</strong>.</p>
<ul>
<li><span class="math inline">\(k\)</span> 가 finite rank → 표본 함수가 그 rank 의 함수 공간에 제한.</li>
<li>Squared exp·Matern 같은 universal kernel → 무한 rank → 임의의 연속 함수 근사 가능.</li>
</ul>
<p>선형 kernel (<span class="math inline">\(k(x, x') = c_0 + c_1 x x'\)</span>) 은 <strong>rank 2</strong> — 선형 함수만 표현.</p>
<p>따라서 비선형 표현이 목표라면 squared exp·Matern·polynomial (high degree) 사용.</p>
</div>
</div>
</section>
</section>
<section id="ch.21-시리즈-결산" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="ch.21-시리즈-결산"><span class="header-section-number">6</span> Ch.21 시리즈 결산</h2>
<section id="시리즈-4편의-핵심" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="시리즈-4편의-핵심"><span class="header-section-number">6.1</span> 시리즈 4편의 핵심</h3>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">편</th>
<th style="text-align: left;">핵심 한 줄</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Overview</td>
<td style="text-align: left;">“함수 자체에 사전분포를 두면 무엇이 가능한가”</td>
</tr>
<tr class="even">
<td style="text-align: left;">§ 21.1~21.3</td>
<td style="text-align: left;">“GP regression 의 모든 식과 비가우시안 확장”</td>
</tr>
<tr class="odd">
<td style="text-align: left;">§ 21.4~21.7</td>
<td style="text-align: left;">“FDA·밀도 자체로의 확장 + 9 연습”</td>
</tr>
</tbody>
</table>
</section>
<section id="ch.21-의-핵심-수식-통합" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="ch.21-의-핵심-수식-통합"><span class="header-section-number">6.2</span> Ch.21 의 핵심 수식 통합</h3>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">번호</th>
<th style="text-align: left;">수식</th>
<th style="text-align: left;">의미</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">-</td>
<td style="text-align: left;"><span class="math inline">\(\mu \sim \text{GP}(m, k) \iff (\mu(x_i)) \sim N(\mathbf{m}, \mathbf{K})\)</span></td>
<td style="text-align: left;">GP 정의</td>
</tr>
<tr class="even">
<td style="text-align: center;">-</td>
<td style="text-align: left;"><span class="math inline">\(k(x, x') = \tau^2 \exp(-\|x-x'\|^2 / 2\ell^2)\)</span></td>
<td style="text-align: left;">Squared exp</td>
</tr>
<tr class="odd">
<td style="text-align: center;">-</td>
<td style="text-align: left;"><span class="math inline">\(k(x, x') = \tau^2 \exp(-\sum_j (x_j - x_j')^2 / 2\ell_j^2)\)</span></td>
<td style="text-align: left;">ARD</td>
</tr>
<tr class="even">
<td style="text-align: center;">-</td>
<td style="text-align: left;"><span class="math inline">\(k_{\text{periodic}}(t, t') = \tau^2 \exp(-2\sin^2(\pi(t-t')/p) / \ell^2)\)</span></td>
<td style="text-align: left;">Periodic</td>
</tr>
<tr class="odd">
<td style="text-align: center;">-</td>
<td style="text-align: left;"><span class="math inline">\(E(\widetilde\mu) = K(\widetilde x, x)(K + \sigma^2 I)^{-1} y\)</span></td>
<td style="text-align: left;">사후 평균</td>
</tr>
<tr class="even">
<td style="text-align: center;">(21.1)</td>
<td style="text-align: left;"><span class="math inline">\(\log p(y) = -\frac{n}{2}\log 2\pi - \frac{1}{2}\log|K + \sigma^2 I| - \frac{1}{2} y^T (K + \sigma^2 I)^{-1} y\)</span></td>
<td style="text-align: left;">Marginal lik</td>
</tr>
<tr class="odd">
<td style="text-align: center;">(21.2)</td>
<td style="text-align: left;"><span class="math inline">\(E(\widetilde f_j) = K_j(\widetilde x, x)(K + \sigma^2 I)^{-1} y\)</span></td>
<td style="text-align: left;">Component-wise</td>
</tr>
<tr class="even">
<td style="text-align: center;">(21.3)</td>
<td style="text-align: left;"><span class="math inline">\(\log p(y) \approx \log p(y \mid \widehat f) - \frac{1}{2}\widehat f^T K^{-1} \widehat f - \frac{1}{2}\log|B|\)</span></td>
<td style="text-align: left;">Latent GP Laplace</td>
</tr>
<tr class="odd">
<td style="text-align: center;">-</td>
<td style="text-align: left;"><span class="math inline">\(p(y \mid f) = e^{f(y)} / \int e^{f(y')} dy'\)</span></td>
<td style="text-align: left;">LGP density</td>
</tr>
<tr class="even">
<td style="text-align: center;">(21.4)</td>
<td style="text-align: left;"><span class="math inline">\(k((x,y),(x',y'))\)</span> = SE on joint</td>
<td style="text-align: left;">Density regression</td>
</tr>
<tr class="odd">
<td style="text-align: center;">(21.5)</td>
<td style="text-align: left;"><span class="math inline">\(y_i \sim N(\mu(u_i), \sigma^2),\ u_i \sim U(0,1)\)</span></td>
<td style="text-align: left;">Latent-variable density</td>
</tr>
</tbody>
</table>
</section>
<section id="ch.21-의-시퀀스-기하급수적-확장" class="level3" data-number="6.3">
<h3 data-number="6.3" class="anchored" data-anchor-id="ch.21-의-시퀀스-기하급수적-확장"><span class="header-section-number">6.3</span> Ch.21 의 시퀀스 — 기하급수적 확장</h3>
<pre><code>Ch.20 (basis)
  → 함수 표현이 $\sum \beta_h b_h(x)$

Ch.21 § 21.1 (GP regression)
  → 함수 표현이 GP, basis 무한, 가우시안 우도

Ch.21 § 21.2 (Birthday)
  → GP 들을 더하고 곱해서 큰 모델로 조합

Ch.21 § 21.3 (Latent GP)
  → 우도를 비가우시안으로 (logistic, Poisson, Weibull, log-logistic)
  → Laplace · EP · VI 가 적분 소거 대신

Ch.21 § 21.4 (FDA)
  → 입력에 시간 차원 추가 → 개체별 함수

Ch.21 § 21.5 (LGP)
  → 회귀 함수 → 분포 자체로 확장
  → continuous logistic 또는 latent-variable 로 정규화 회피</code></pre>
</section>
<section id="ch.21-의-유산과-한계" class="level3" data-number="6.4">
<h3 data-number="6.4" class="anchored" data-anchor-id="ch.21-의-유산과-한계"><span class="header-section-number">6.4</span> Ch.21 의 유산과 한계</h3>
<p><strong>유산</strong>:</p>
<ul>
<li>함수 자체에 사전분포 — Bayesian nonparametric 의 첫 번째 자연 도구.</li>
<li>Kernel 합·곱으로 큰 모델 빌딩.</li>
<li>ARD 로 자동 변수 선택.</li>
<li>같은 framework 가 회귀·분류·생존·밀도까지 통일.</li>
</ul>
<p><strong>한계</strong>:</p>
<ul>
<li><span class="math inline">\(O(n^3)\)</span> — 본질적 계산 부담.</li>
<li>외삽 위험 — kernel support 밖에서 mean 함수로 회귀.</li>
<li>Hyperparameter identifiability — 비슷한 적합 결과를 주는 다른 hyperparameter 조합 가능.</li>
<li>Mixture-style clustering 표현 부적합 — 그 영역은 Ch.22~23 의 몫.</li>
</ul>
<p><strong>다음 장 예고</strong>:</p>
<ul>
<li><strong>Ch.22 Mixture Models</strong>: 데이터가 <strong>여러 하위 모집단</strong> 에서 올 때.</li>
<li><strong>Ch.23 Dirichlet Process</strong>: 모집단 수가 미지.</li>
<li>GP 가 함수에 사전분포를 두었듯, DP 는 <strong>분포 자체에 사전분포</strong>.</li>
</ul>
</section>
</section>
<section id="ch.21-시리즈-통합-체크리스트" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="ch.21-시리즈-통합-체크리스트"><span class="header-section-number">7</span> Ch.21 시리즈 통합 체크리스트</h2>
<p><strong>모델 결정</strong></p>
<ol type="1">
<li>데이터가 <span class="math inline">\((x, y)\)</span> 점 → § 21.1 GP regression.</li>
<li>시계열에 추세·주기·특별일 모두 → § 21.2 가법 component.</li>
<li>우도가 비가우시안 (binary, count, 생존) → § 21.3 latent GP.</li>
<li>개체마다 함수 → § 21.4 FDA.</li>
<li>분포 자체가 비모수 → § 21.5 LGP 또는 latent-variable.</li>
</ol>
<p><strong>Kernel 선택</strong></p>
<ol start="6" type="1">
<li>매끄러운 함수 → squared exponential.</li>
<li>약간 거친 함수 → Matern <span class="math inline">\(\nu = 5/2\)</span> (실무 default).</li>
<li>매우 거친 함수 → Matern <span class="math inline">\(\nu = 1/2\)</span> (exponential).</li>
<li>주기 → periodic kernel + smooth 곱 (quasi-periodic).</li>
<li>다변량 → ARD anisotropic.</li>
</ol>
<p><strong>Hyperprior</strong></p>
<ol start="11" type="1">
<li><span class="math inline">\(\tau\)</span> — half-Cauchy / half-Normal, 출력 sd 의 1~2 배.</li>
<li><span class="math inline">\(\ell_j\)</span> — half-<span class="math inline">\(t_4\)</span>, 입력 sd 의 0.1~1 배.</li>
<li><span class="math inline">\(\sigma\)</span> — half-Normal.</li>
<li>Mean function — zero (단순) 또는 linear (외삽 안정).</li>
</ol>
<p><strong>계산</strong></p>
<ol start="15" type="1">
<li><span class="math inline">\(n &lt; 1000\)</span>: 풀 GP + Cholesky + jitter <span class="math inline">\(10^{-6}\)</span>.</li>
<li><span class="math inline">\(1000 \leq n &lt; 10000\)</span>: Sparse GP (inducing points / VFE).</li>
<li>1D 시계열 <span class="math inline">\(n \geq 10^4\)</span>: state-space GP.</li>
<li>Spatial <span class="math inline">\(n \geq 10^4\)</span> + 1-3D: SPDE/MRF (INLA).</li>
<li>비가우시안 우도: Laplace (default) → EP (logistic small <span class="math inline">\(p\)</span>) → MCMC (정확도).</li>
</ol>
<p><strong>검증</strong></p>
<ol start="20" type="1">
<li>LOO-CV lppd 로 모델 비교.</li>
<li>Posterior predictive draws 로 적합도 점검.</li>
<li>ARD length scales 분석 — 큰 <span class="math inline">\(\ell_j\)</span> = 변수 탈락.</li>
<li>사후 사진 평균 + pointwise 90% interval 시각화.</li>
<li>Component-wise prediction 식 (21.2) 으로 가법 모델의 부분 확인.</li>
<li>외삽 영역에서 mean function 으로 회귀 — 신뢰 금지.</li>
</ol>
</section>
<section id="관련-주제" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="관련-주제"><span class="header-section-number">8</span> 관련 주제</h2>
<p><strong>Ch.21 시리즈</strong></p>
<ul>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/04-21-0-gaussian-process-overview.html">Ch.21 Overview</a></li>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/04-21-1-gp-regression-birthdays-latent.html">Ch.21 § 21.1~21.3 — GP Regression·Birthdays·Latent GP</a></li>
</ul>
<p><strong>선행 지식</strong></p>
<ul>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/00-5-0-hierarchical.html">Ch.5 Hierarchical Models</a></li>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/03-16-0-generalized-linear-models-overview.html">Ch.16 Generalized Linear Models</a></li>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/04-20-1-splines-basis-shrinkage.html">Ch.20 § 20.1~20.2 — Splines·Basis Selection·Shrinkage</a></li>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/02-13-3-variational-inference-expectation-propagation.html">Ch.13 § 13.7~13.8 — Variational Inference·EP</a></li>
<li><a href="../../../../../docs/blog/posts/Statistics/bayesian/00-4-1-normal-approx-asymptotics.html">Ch.4 § 4.1 — Normal Approximation (Laplace)</a></li>
</ul>
<p><strong>후속 주제</strong></p>
<ul>
<li><a href="./04-22-0-finite-mixture-overview.qmd">Ch.22 Finite Mixture Models Overview</a> (예정)</li>
<li><a href="./04-23-0-dirichlet-process-overview.qmd">Ch.23 Dirichlet Process Models Overview</a> (예정)</li>
</ul>
<p><strong>관련 개념 (cross-category)</strong></p>
<ul>
<li><a href="../fda/fda-overview.qmd">Functional Data Analysis (Ramsay-Silverman)</a></li>
<li><a href="../../Math/kernel-methods-rkhs.qmd">Kernel Methods and RKHS</a></li>
<li><a href="../../Machine_Learning/bayesian-optimization.qmd">Bayesian Optimization with GP</a></li>
<li><a href="../../Deep_Learning/nngp-ntk.qmd">Neural Network Gaussian Process (NNGP) and NTK</a></li>
<li><a href="../../Math/sde-overview.qmd">Stochastic Differential Equations</a></li>
</ul>
</section>
<section id="참고문헌" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="참고문헌"><span class="header-section-number">9</span> 참고문헌</h2>
<ul>
<li>Gelman, A., Carlin, J. B., Stern, H. S., Dunson, D. B., Vehtari, A., &amp; Rubin, D. B. (2013). <em>Bayesian Data Analysis</em> (3rd ed.), Ch.21 § 21.4~21.7. CRC Press.</li>
<li>Rasmussen, C. E., &amp; Williams, C. K. I. (2006). <em>Gaussian Processes for Machine Learning</em>. MIT Press.</li>
<li>O’Hagan, A. (1978). Curve Fitting and Optimal Design for Prediction. <em>JRSS B</em>, 40, 1-42.</li>
<li>Neal, R. M. (1998). Regression and Classification Using Gaussian Process Priors. <em>Bayesian Statistics</em>, 6, 475-501.</li>
<li>Vanhatalo, J., Riihimaki, J., Hartikainen, J., Jylanki, P., Tolvanen, V., &amp; Vehtari, A. (2013a). GPstuff: Bayesian Modeling with Gaussian Processes. <em>JMLR</em>, 14, 1175-1179.</li>
<li>Vanhatalo, J., Pietilainen, V., &amp; Vehtari, A. (2010). Approximate Inference for Disease Mapping with Sparse Gaussian Processes. <em>Statistics in Medicine</em>, 29(15), 1580-1607.</li>
<li>Snelson, E., &amp; Ghahramani, Z. (2006). Sparse Gaussian Processes Using Pseudo-Inputs (FITC). <em>NeurIPS</em>.</li>
<li>Titsias, M. (2009). Variational Learning of Inducing Variables in Sparse Gaussian Processes (VFE). <em>AISTATS</em>.</li>
<li>Hensman, J., Fusi, N., &amp; Lawrence, N. D. (2013). Gaussian Processes for Big Data. <em>UAI</em>.</li>
<li>Lindgren, F., Rue, H., &amp; Lindstrom, J. (2011). An Explicit Link between Gaussian Fields and Gaussian Markov Random Fields: The SPDE Approach. <em>JRSS B</em>, 73, 423-498.</li>
<li>Sarkka, S., Solin, A., &amp; Hartikainen, J. (2013). Spatiotemporal Learning via Infinite-Dimensional Bayesian Filtering and Smoothing. <em>IEEE Signal Processing Magazine</em>, 30(4), 51-61.</li>
<li>Wilson, A. G., &amp; Nickisch, H. (2015). Kernel Interpolation for Scalable Structured Gaussian Processes (KISS-GP). <em>ICML</em>.</li>
<li>Leonard, T. (1978). Density Estimation, Stochastic Processes, and Prior Information. <em>JRSS B</em>, 40, 113-146. (LGP 도입)</li>
<li>Lenk, P. J. (1991, 2003). The Logistic Normal Distribution for Bayesian, Nonparametric, Predictive Densities. <em>JASA</em>.</li>
<li>Tokdar, S. T. (2007). Towards a Faster Implementation of Density Estimation with Logistic Gaussian Process Priors. <em>JCGS</em>, 16(3), 633-655.</li>
<li>Tokdar, S. T., Zhu, Y., &amp; Ghosh, J. K. (2010). Bayesian Density Regression with Logistic Gaussian Process and Subspace Projection. <em>Bayesian Analysis</em>, 5(2), 319-344.</li>
<li>Riihimaki, J., &amp; Vehtari, A. (2014). Laplace Approximation for Logistic Gaussian Process Density Estimation and Regression. <em>Bayesian Analysis</em>, 9(2), 425-448.</li>
<li>Adams, R. P., Murray, I., &amp; MacKay, D. J. C. (2009). The Gaussian Process Density Sampler. <em>NeurIPS</em>.</li>
<li>Kundu, S., &amp; Dunson, D. B. (2014). Latent Factor Models for Density Estimation. <em>Biometrika</em>, 101, 641-654.</li>
<li>Vehtari, A., Mononen, T., Tolvanen, V., Sivula, T., &amp; Winther, O. (2016). Bayesian Leave-One-Out Cross-Validation Approximations for Gaussian Latent Variable Models. <em>JMLR</em>, 17, 1-38.</li>
<li>Henderson, R., Shimakura, S., &amp; Gorst, D. (2002). Modeling Spatial Variation in Leukemia Survival Data. <em>JASA</em>, 97, 965-972.</li>
</ul>


</section>

</main> <!-- /main -->
<script type="text/javascript">

// replace cmd keyboard shortcut w/ control on non-Mac platforms
const kPlatformMac = typeof navigator !== 'undefined' ? /Mac/.test(navigator.platform) : false;
if (!kPlatformMac) {
   var kbds = document.querySelectorAll("kbd")
   kbds.forEach(function(kbd) {
      kbd.innerHTML = kbd.innerHTML.replace(/⌘/g, '⌃');
   });
}

// tweak headings in pymd
document.querySelectorAll(".pymd span.co").forEach(el => {
   if (!el.innerText.startsWith("#|")) {
      el.style.fontWeight = 1000;
   }
});

</script>
<!-- Begin Mailchimp Signup Form -->
<div id="mc_embed_signup" style="padding-bottom: 1em; max-width: 400px;" class="ms-auto me-auto">
  <p style="font-weight: 600; margin-bottom: 0;">Subscribe</p>
  <span style="font-size: 0.9em;">Enjoy this blog? Get notified of new posts by email:</span>
<form action="https://quarto.us14.list-manage.com/subscribe/post?u=c79fb56a311ae347fbe916740&amp;id=ec05dfca03" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate="">
    <div id="mc_embed_signup_scroll">
	
        <div class="input-group mt-1 mb-2">
        <input type="email" class="form-control" placeholder="Email Address" aria-label="Email Address" name="EMAIL" style="font-size: 0.8em; padding: .2em;">
        </div>              

	<div id="mce-responses" class="clear foot">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_c79fb56a311ae347fbe916740_ec05dfca03" tabindex="-1" value=""></div>
        <div class="optionalParent">
            <div class="clear foot" style="display: flex; align-items: center; justify-content: center;">
              
              
                <input type="submit" value="Subscribe" name="subscribe" style="min-width: 150px; font-size: 0.8em;" id="mc-embedded-subscribe" class="button btn btn-light btn-sm ms-auto me-auto">
            </div>
        </div>
    </div>
</form>
</div>

<!--End mc_embed_signup-->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "복사완료!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "복사완료!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="kmink3225/blog" data-repo-id="R_kgDOLCZyDg" data-category="Blog" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script>
<input type="hidden" id="giscus-base-theme" value="light">
<input type="hidden" id="giscus-alt-theme" value="dark">
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Kwangmin Kim</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="../../../../../about.html">
<p>About</p>
</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/kmink3225/blog">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>