---
title: "정규표현식 기본 규칙"
subtitle: NLP에서 활용하는 정규표현식 기초
description: |
  자연어 처리에서 텍스트 전처리와 패턴 매칭에 필수적인 정규표현식의 기본 규칙을 알아본다.
categories:
  - NLP
author: Kwangmin Kim
date: 01/01/2025
format: 
  html:
    page-layout: full
    code-fold: true
    toc: true
    number-sections: true
comments: 
  utterances: 
    repo: ./docs/comments
draft: False
---

# 자연어 처리의 개요

* 자연어란
   * 자연어: 인간이 일상 생활에서 사용하는 언어
   * 예시: 한국어, 영어, 중국어, 일본어 등
* 자연어 처리란
   * 자연어 처리: 컴퓨터가 자연어를 이해하고 처리하는 기술
   * 예시: 음성 인식, 요약, 번역, 감성 분석, 텍스트 분류, 질의 응답 시스템, 챗봇 등
* 딥러닝을 이용한 자연어 처리의 성능이 괄목할만한 성과를 얻으면서 폭발적으로 성장이면서 기회가 많은 분야
* 텍스트 분석이라고도 불리는 분야지만 자연어처리 라고 하면 인공 지능을 이용한 분야라는 의미가 포함되는 편

# 자연어 처리의 기회

* 회사 도메인을 가리지 않고 수요가 있음
* 현재 실무에서 여전히 PLM (Pre-trained Language Model) 을 이용한 자연어 처리를 할 수 있는 중급 이상의 인력이 많지 않아 기회가 많다.
* 성능 좋은 오픈 소스가 지속적으로 공개되고 있어 자연어 처리를 할 줄 안다면 손쉽게 높은 성능의 모델을 사용할 수 있다.

# 자연어 처리 학습 순서

* 자연어 처리의 개념
통계적인 방식의 자연어 처리
초기의 딥러닝 자연어 처리 (from 2010~)
현재의 딥러닝 자연어 처리 - PLM (현재))

# PyTorch

FAIR에서 만든 딥러닝 프레임워크
연구용 프로토타입부터 상용제품까지 빠르게 만들 수 있는 오픈 소스 머신러닝 프레임 워크
가장 보편적인 프레임워크

# Transformer

* 자연어 처리 스타일의 허깅페이스가 개발한 다양한 트랜스포머 계열의 모델들과 고나련 모듈들을 제공하는 Data Science Hub 플랫폼
* 대부분의 PLM을 사용할때는 Transformer 라이브러리를 사용하는 경우가 많음

# 한국의 자연어 처리 난이도는 영어보다 어렵다

* 한국어는 교착어
* 영어는 모음 구조가 단순해서 영어 문장을 처리하는 것이 쉬움
* 한국어는 모음 구조가 복잡해서 한국어 문장을 처리하는 것이 어려움
* 한국어는 영어보다 자연어 처리 난이도가 높음
* 한국어는 띄어쓰기가 그렇게 잘 지켜지지 않는다
* 한국어는 어순이 그렇게 중요하지 않다.
* 한자어라는 특성상 하나의 음절조차도 다른 의미를 가질 수 있다
* 주어가 손쉽게 생략된다
* 데이터와 언어에 특화된 모델이 영어에 비해 부족하다.
* 한국어는 띄어쓰기가 잘 지켜지지 않는다.
한국어는 띄어쓰기가 어렵고 지키지 않더라도 쉽게 읽을 숭 ㅣㅆ다.
 
 대부분의 데이터에서 띄어쓰기가 잘 지켜지지 않는 경향이 있다.
 반면 영어는 띄어씌기를 하지 않으면 읽기 어려운 언어의 특성으로 띄어쓰기가 매우 엄격하게 지켜지는 편이다.
# 한국의 자연어 처리 난이도는 영어보다 어렵다


