---
title: "References"
subtitle: "articles, papers, textbooks, or images"
description: |
  As the number of blog topics has increased, organizing the content has become more challenging. To enhance content accessibility and facilitate an understanding of the blog's relevance, we have provided links to a list of contents categorized by topic.
categories:
author: Kwangmin Kim
date: 01/01/1000
format: 
  html:
    page-layout: full
    code-fold: true
---

:::{.callout-note}
* Scalars are denoted with a lower-case letter (ex a ) or a non-bolded lower-case Greek letter (ex $\alpha$ ).
* Vectors are denoted using a bold-faced lower-case letter (ex $\mathbf a$).
* Matrices are denoted using a bold-faced upper-case letter (ex $\mathbf A$, $\mathbf \phi$) or a bold-faced upper-case Greek letter (ex $\mathbf \Phi$).
* Tensors are denoted using a bold-faced upper-case letter with multiple subscripts or superscripts, indicating the number of indices and the dimensions of the tensor along each axis. 
  * A second-order tensor (also known as a matrix) $\mathbf A$ with dimensions $n \times m$ can be represented as: 
  $\mathbf A_{ij}$ where $i = 1,\dots,m$ and $j = 1,\dots,n$, which are the indices that run over the rows and columns of the matrix, respectively. 
  * A third-order tensor $T$ with dimensions $n \times m \times p$ can be represented as:
   $\mathbf A_{ijk}$ where $i = 1,\dots,m$, $j = 1,\dots,n$, which are $i$, and $k = 1,\dots,p$ $j$, and $k$, which are the indices that run over the three dimensions of the tensor.

:::

# Contents

* [Engineering](../posts/Engineering/guide_map/index.qmd)
* [Surveilance](../posts/Surveilance/guide_map/index.qmd)

# Reference

* Bioinformatics
    *  [incoedu](https://edu.insilicogen.com/kobic/course/map)
        * NGS 데이터 분석 기초편	김상수 / 숭실대학교	
        * CCNGS 데이터 변이 분석 기초편	김상우 / 연세대학교	
        * 전사체 데이터 분석	이상혁 / 이화여자대학교	
        * WES 기초편	최무림 / 서울대학교	
        * 단일세포 분석	김규태 / 아주대학교 의과대학 생리학교실
        * 김준일 / 숭실대학교 의생명시스템학부
        * 박지환 / 광주과학기술원 생명과학부
        * 황대희 / 서울대학교 생명과학부	
        * 예제 데이터를 활용한 전사체 데이터 분석	김종환 / KOBIC	
        * 예제 데이터를 활용한 단일세포 전사체 데이터 분석	김종환 / KOBIC	
        * 후성 유전체 데이터 분석	노태영 / 포항공과대학교	
        * 암 유전체 분석	주영석 / KAIST	
        * ChIP-seq	정인경 / KAIST	
        * 단백체 분석	황대희 / 서울대학교	
        * 기계학습 및 딥러닝 기초 이론과 암 유전체 데이터 딥러닝 적용 실습	김권일 / 경희대학교	
        * 롱리드 시퀀싱 데이터 분석	김준 / 서울대학교	
        * 생명정보학 시작하기	안준용 / 고려대학교	
        * 인공지능을 활용한 데이터 분석 및 신약개발 활용	김은영 / 삼진제약	
        * eQTL 분석	최무림 / 서울대학교	
        * Microbiome	이선재 / GIST
        * 이병욱 / KOBIC
* Statistics 
    * George Casella & Rogeer L. Berger - Statistcal Inference, 2nd Edition
    * Dobson and Barnett (2008) An Introduction to Generalized Linear Model. 3rd Ed. Chapman & Hall.
    * Fitzmaurice, Laird and Ware (2011) Applied Longitudinal Analysis. 2nd Ed. Wiley.
    * Hosmer, Lemeshow and May (2008) Applied Survival Analysis. 2nd Ed. Wiley.
    * 슬기로운 통계생활 - https://www.youtube.com/@statisticsplaybook
    * 슬기로운 통계생활 - https://github.com/statisticsplaybook
    * Fast Campus, Coursera, Inflearn
    * 그 외 다수의 Youtube, and Documents from Googling
* Mathematics
    * James Stewart - Calculus Early Transcedentals, 7th Eidition & any James Stewart series
    * GILBERT STRANG - Introduction to Linear Algebra, 4th Edition. 
    * 임장환 - 머신러닝, 인공지능, 컴퓨터 비전 전공자를 위한 최적화 이론
    * Fast Campus, Coursera, Inflearn
    * [8일간의 선형대수학 기초(이상준 경희대 교수)](https://www.youtube.com/playlist?list=PLaqQvlCBe8vIkIEb4GX2ZZ1A4tFYeXR5W)
    * [Linear Algebra(Prof. Gilbert Strang, MIT Open Courseware)](https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/)
    * [Computational Linear Algebra for Coders](https://github.com/fastai/numerical-linear-algebra/blob/master/README.md)
    * [Immersive linear Algebra](http://immersivemath.com/ila/)
    * [3blue1brown](https://www.3blue1brown.com/topics/linear-algebra)
    * 그 외 다수의 Youtube, and Documents from Googling
* Machine Learning
    * Gareth M. James, Daniela Witten, Trevor Hastie, Robert Tibshirani - An Introduction to Statistical Learning: With Applications in R 2nd Edition
    * Trevor Hastie, Robert Tibshirani, Jerome H. Friedman - The Elements of Statistical Learning 2nd Edition
    * Fast Campus, Coursera, Inflearn
    * 그 외 다수의 Youtube, and Documents from Googling
* Deep Learning
    * Saito Koki - Deep Learning from Scratch 1,2,3 (밑바닥부터 시작하는 딥러닝 1,2,3)
    * 조준우 - 머신러닝·딥러닝에 필요한 기초 수학 with 파이썬
    * 조준우 - https://github.com/metamath1/noviceml
    * 동빈나 - https://www.youtube.com/c/dongbinna 
    * 혁펜하임 - https://www.youtube.com/channel/UCcbPAIfCa4q0x7x8yFXmBag
    * Fast Campus, Coursera, Inflearn
    * 다수의 Youtube, and Documents from Googling
* Engineering
    * Fast Campus, Coursera, Inflearn
    * 그 외 다수의 Youtube, and Documents from Googling