<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ko" xml:lang="ko"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.543">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Kwangmin Kim">
<meta name="description" content="씨젠 RT-PCR 시스템의 45개 cycle 제한된 데이터 구조에서 딥러닝이 의료 규제를 통과할 수 있는 설계 원칙과 mechanistic model 기반 확률 추정, 불확실성 관리 전략을 다룬다.">

<title>Kwangmin Kim - RT-PCR 진단 알고리즘과 딥러닝</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../../site_libs/quarto-search/quarto-search.js"></script>
<script src="../../../../site_libs/quarto-search/autocomplete-preset-algolia.umd.js"></script>
<meta name="quarto:offset" content="../../../../">
<script src="../../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "algolia": {
    "application-id": "DUOR1DRC9D",
    "search-only-api-key": "f264da5dea684ffb9e9b4a574af3ed61",
    "index-name": "prod_QUARTO",
    "analytics-events": true,
    "show-logo": true,
    "libDir": "site_libs"
  },
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": true,
  "language": {
    "search-no-results-text": "일치 없음",
    "search-matching-documents-text": "일치된 문서",
    "search-copy-link-title": "검색 링크 복사",
    "search-hide-matches-text": "추가 검색 결과 숨기기",
    "search-more-match-text": "추가 검색결과",
    "search-more-matches-text": "추가 검색결과",
    "search-clear-button-title": "제거",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "취소",
    "search-submit-button-title": "검색",
    "search-label": "검색"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/algoliasearch@4.5.1/dist/algoliasearch-lite.umd.js"></script>


<script type="text/javascript">
var ALGOLIA_INSIGHTS_SRC = "https://cdn.jsdelivr.net/npm/search-insights/dist/search-insights.iife.min.js";
!function(e,a,t,n,s,i,c){e.AlgoliaAnalyticsObject=s,e[s]=e[s]||function(){
(e[s].queue=e[s].queue||[]).push(arguments)},i=a.createElement(t),c=a.getElementsByTagName(t)[0],
i.async=1,i.src=n,c.parentNode.insertBefore(i,c)
}(window,document,"script",ALGOLIA_INSIGHTS_SRC,"aa");
</script>

<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/@algolia/autocomplete-plugin-algolia-insights">

</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-6W0EKFMWBN"></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-6W0EKFMWBN', { 'anonymize_ip': true});
</script>
<style>

      .quarto-title-block .quarto-title-banner h1,
      .quarto-title-block .quarto-title-banner h2,
      .quarto-title-block .quarto-title-banner h3,
      .quarto-title-block .quarto-title-banner h4,
      .quarto-title-block .quarto-title-banner h5,
      .quarto-title-block .quarto-title-banner h6
      {
        color: black;
      }

      .quarto-title-block .quarto-title-banner {
        color: black;
background: #EDF3F9;
      }
</style>
<style>
.custom-footer { 
  text-align: center; 
  font-size: 0.8em; 
  color: #666; 
  margin-top: 2rem; 
}
</style>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../../styles.css">
<meta property="og:title" content="Kwangmin Kim - RT-PCR 진단 알고리즘과 딥러닝">
<meta property="og:description" content="씨젠 RT-PCR 시스템의 45개 cycle 제한된 데이터 구조에서 딥러닝이 의료 규제를 통과할 수 있는 설계 원칙과 mechanistic model 기반 확률 추정, 불확실성 관리 전략을 다룬다.">
<meta property="og:site_name" content="Kwangmin Kim">
<meta name="twitter:title" content="Kwangmin Kim - RT-PCR 진단 알고리즘과 딥러닝">
<meta name="twitter:description" content="씨젠 RT-PCR 시스템의 45개 cycle 제한된 데이터 구조에서 딥러닝이 의료 규제를 통과할 수 있는 설계 원칙과 mechanistic model 기반 확률 추정, 불확실성 관리 전략을 다룬다.">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top quarto-banner">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../../.././images/logo.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../../../index.html">
    <span class="navbar-title">Kwangmin Kim</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="검색"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="탐색 전환" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../../../docs/blog/index.html"> 
<span class="menu-text">Blog</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../../about.html"> 
<span class="menu-text">Me</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/kmink3225"> <i class="bi bi-github" role="img" aria-label="Github">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/kwangmin-kim-a5241b200/"> <i class="bi bi-linkedin" role="img" aria-label="Linkedin">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
          <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="다크 모드 전환"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<header id="title-block-header" class="quarto-title-block default page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">RT-PCR 진단 알고리즘과 딥러닝</h1>
            <p class="subtitle lead">제한된 신호 공간에서의 의료 규제 설계 원칙</p>
                  <div>
        <div class="description">
          <p>씨젠 RT-PCR 시스템의 45개 cycle 제한된 데이터 구조에서 딥러닝이 의료 규제를 통과할 수 있는 설계 원칙과 mechanistic model 기반 확률 추정, 불확실성 관리 전략을 다룬다.</p>
        </div>
      </div>
                          <div class="quarto-categories">
                <div class="quarto-category">Surveilance</div>
                <div class="quarto-category">Regulation</div>
                <div class="quarto-category">AI</div>
              </div>
                  </div>
  </div>
    
  
  <div class="quarto-title-meta">

      <div>
      <div class="quarto-title-meta-heading">저자</div>
      <div class="quarto-title-meta-contents">
               <p>Kwangmin Kim </p>
            </div>
    </div>
      
      <div>
      <div class="quarto-title-meta-heading">공개</div>
      <div class="quarto-title-meta-contents">
        <p class="date">2025년 01월 12일</p>
      </div>
    </div>
    
      
    </div>
    
  
  </header><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">목차</h2>
   
  <ul>
  <li><a href="#rt-pcr-진단-알고리즘과-딥러닝-의료-규제-관점에서의-설계-원칙" id="toc-rt-pcr-진단-알고리즘과-딥러닝-의료-규제-관점에서의-설계-원칙" class="nav-link active" data-scroll-target="#rt-pcr-진단-알고리즘과-딥러닝-의료-규제-관점에서의-설계-원칙"><span class="header-section-number">1</span> RT-PCR 진단 알고리즘과 딥러닝: 의료 규제 관점에서의 설계 원칙</a>
  <ul class="collapse">
  <li><a href="#서론-제한된-데이터에서-딥러닝은-가능한가" id="toc-서론-제한된-데이터에서-딥러닝은-가능한가" class="nav-link" data-scroll-target="#서론-제한된-데이터에서-딥러닝은-가능한가"><span class="header-section-number">1.1</span> 서론: 제한된 데이터에서 딥러닝은 가능한가</a>
  <ul class="collapse">
  <li><a href="#rt-pcr-시스템의-데이터-제약" id="toc-rt-pcr-시스템의-데이터-제약" class="nav-link" data-scroll-target="#rt-pcr-시스템의-데이터-제약"><span class="header-section-number">1.1.1</span> RT-PCR 시스템의 데이터 제약</a></li>
  <li><a href="#fda-승인-현황-저차원-신호-기반-딥러닝" id="toc-fda-승인-현황-저차원-신호-기반-딥러닝" class="nav-link" data-scroll-target="#fda-승인-현황-저차원-신호-기반-딥러닝"><span class="header-section-number">1.1.2</span> FDA 승인 현황: 저차원 신호 기반 딥러닝</a></li>
  <li><a href="#cepheid-genexpert-실제-fda-승인-사례" id="toc-cepheid-genexpert-실제-fda-승인-사례" class="nav-link" data-scroll-target="#cepheid-genexpert-실제-fda-승인-사례"><span class="header-section-number">1.1.3</span> Cepheid GeneXpert: 실제 FDA 승인 사례</a></li>
  <li><a href="#결론의-명확화" id="toc-결론의-명확화" class="nav-link" data-scroll-target="#결론의-명확화"><span class="header-section-number">1.1.4</span> 결론의 명확화</a></li>
  </ul></li>
  <li><a href="#rt-pcr-데이터-구조의-규제적-재해석" id="toc-rt-pcr-데이터-구조의-규제적-재해석" class="nav-link" data-scroll-target="#rt-pcr-데이터-구조의-규제적-재해석"><span class="header-section-number">1.2</span> RT-PCR 데이터 구조의 규제적 재해석</a>
  <ul class="collapse">
  <li><a href="#데이터-구조의-수학적-정의" id="toc-데이터-구조의-수학적-정의" class="nav-link" data-scroll-target="#데이터-구조의-수학적-정의"><span class="header-section-number">1.2.1</span> 데이터 구조의 수학적 정의</a></li>
  <li><a href="#데이터가-적다는-오해" id="toc-데이터가-적다는-오해" class="nav-link" data-scroll-target="#데이터가-적다는-오해"><span class="header-section-number">1.2.2</span> “데이터가 적다”는 오해</a></li>
  <li><a href="#규제기관이-보는-네-가지-질문" id="toc-규제기관이-보는-네-가지-질문" class="nav-link" data-scroll-target="#규제기관이-보는-네-가지-질문"><span class="header-section-number">1.2.3</span> 규제기관이 보는 네 가지 질문</a></li>
  </ul></li>
  <li><a href="#허용-가능한-딥러닝-구조" id="toc-허용-가능한-딥러닝-구조" class="nav-link" data-scroll-target="#허용-가능한-딥러닝-구조"><span class="header-section-number">1.3</span> 허용 가능한 딥러닝 구조</a>
  <ul class="collapse">
  <li><a href="#모델-아키텍처의-제약" id="toc-모델-아키텍처의-제약" class="nav-link" data-scroll-target="#모델-아키텍처의-제약"><span class="header-section-number">1.3.1</span> 모델 아키텍처의 제약</a></li>
  <li><a href="#출력-정의" id="toc-출력-정의" class="nav-link" data-scroll-target="#출력-정의"><span class="header-section-number">1.3.2</span> 출력 정의</a></li>
  <li><a href="#규제-통과-논리" id="toc-규제-통과-논리" class="nav-link" data-scroll-target="#규제-통과-논리"><span class="header-section-number">1.3.3</span> 규제 통과 논리</a></li>
  </ul></li>
  <li><a href="#그레이존-문제와-딥러닝의-역할" id="toc-그레이존-문제와-딥러닝의-역할" class="nav-link" data-scroll-target="#그레이존-문제와-딥러닝의-역할"><span class="header-section-number">1.4</span> 그레이존 문제와 딥러닝의 역할</a>
  <ul class="collapse">
  <li><a href="#진짜-문제-애매한-신호" id="toc-진짜-문제-애매한-신호" class="nav-link" data-scroll-target="#진짜-문제-애매한-신호"><span class="header-section-number">1.4.1</span> 진짜 문제: 애매한 신호</a></li>
  <li><a href="#딥러닝이-하면-안-되는-것" id="toc-딥러닝이-하면-안-되는-것" class="nav-link" data-scroll-target="#딥러닝이-하면-안-되는-것"><span class="header-section-number">1.4.2</span> 딥러닝이 하면 안 되는 것</a></li>
  <li><a href="#딥러닝이-해야-하는-것" id="toc-딥러닝이-해야-하는-것" class="nav-link" data-scroll-target="#딥러닝이-해야-하는-것"><span class="header-section-number">1.4.3</span> 딥러닝이 해야 하는 것</a></li>
  <li><a href="#정확한-판단-구조" id="toc-정확한-판단-구조" class="nav-link" data-scroll-target="#정확한-판단-구조"><span class="header-section-number">1.4.4</span> 정확한 판단 구조</a></li>
  </ul></li>
  <li><a href="#진단-알고리즘의-올바른-역할-정의" id="toc-진단-알고리즘의-올바른-역할-정의" class="nav-link" data-scroll-target="#진단-알고리즘의-올바른-역할-정의"><span class="header-section-number">1.5</span> 진단 알고리즘의 올바른 역할 정의</a>
  <ul class="collapse">
  <li><a href="#임상-시나리오" id="toc-임상-시나리오" class="nav-link" data-scroll-target="#임상-시나리오"><span class="header-section-number">1.5.1</span> 임상 시나리오</a></li>
  <li><a href="#알고리즘의-역할-구분" id="toc-알고리즘의-역할-구분" class="nav-link" data-scroll-target="#알고리즘의-역할-구분"><span class="header-section-number">1.5.2</span> 알고리즘의 역할 구분</a></li>
  <li><a href="#단계-의사결정-구조" id="toc-단계-의사결정-구조" class="nav-link" data-scroll-target="#단계-의사결정-구조"><span class="header-section-number">1.5.3</span> 3단계 의사결정 구조</a></li>
  <li><a href="#왜-이-구조가-정답인가" id="toc-왜-이-구조가-정답인가" class="nav-link" data-scroll-target="#왜-이-구조가-정답인가"><span class="header-section-number">1.5.4</span> 왜 이 구조가 정답인가</a></li>
  </ul></li>
  <li><a href="#mechanistic-model-기반-확률-계산" id="toc-mechanistic-model-기반-확률-계산" class="nav-link" data-scroll-target="#mechanistic-model-기반-확률-계산"><span class="header-section-number">1.6</span> Mechanistic Model 기반 확률 계산</a>
  <ul class="collapse">
  <li><a href="#기본-접근-sigmoid-모델" id="toc-기본-접근-sigmoid-모델" class="nav-link" data-scroll-target="#기본-접근-sigmoid-모델"><span class="header-section-number">1.6.1</span> 기본 접근: Sigmoid 모델</a></li>
  <li><a href="#통계적-검정의-위치-중요한-교정" id="toc-통계적-검정의-위치-중요한-교정" class="nav-link" data-scroll-target="#통계적-검정의-위치-중요한-교정"><span class="header-section-number">1.6.2</span> 통계적 검정의 위치 (중요한 교정)</a></li>
  <li><a href="#올바른-접근-분포-기반-확률-계산" id="toc-올바른-접근-분포-기반-확률-계산" class="nav-link" data-scroll-target="#올바른-접근-분포-기반-확률-계산"><span class="header-section-number">1.6.3</span> 올바른 접근: 분포 기반 확률 계산</a></li>
  <li><a href="#핵심-포인트" id="toc-핵심-포인트" class="nav-link" data-scroll-target="#핵심-포인트"><span class="header-section-number">1.6.4</span> 5.4 핵심 포인트</a></li>
  </ul></li>
  <li><a href="#통계적-검정의-올바른-위치" id="toc-통계적-검정의-올바른-위치" class="nav-link" data-scroll-target="#통계적-검정의-올바른-위치"><span class="header-section-number">1.7</span> 통계적 검정의 올바른 위치</a>
  <ul class="collapse">
  <li><a href="#검정은-결정-도구가-아니다" id="toc-검정은-결정-도구가-아니다" class="nav-link" data-scroll-target="#검정은-결정-도구가-아니다"><span class="header-section-number">1.7.1</span> 검정은 결정 도구가 아니다</a></li>
  <li><a href="#통계적-검정의-실제-용도" id="toc-통계적-검정의-실제-용도" class="nav-link" data-scroll-target="#통계적-검정의-실제-용도"><span class="header-section-number">1.7.2</span> 통계적 검정의 실제 용도</a></li>
  <li><a href="#decision-flow-통합" id="toc-decision-flow-통합" class="nav-link" data-scroll-target="#decision-flow-통합"><span class="header-section-number">1.7.3</span> Decision Flow (통합)</a></li>
  </ul></li>
  <li><a href="#딥러닝의-정확한-역할" id="toc-딥러닝의-정확한-역할" class="nav-link" data-scroll-target="#딥러닝의-정확한-역할"><span class="header-section-number">1.8</span> 딥러닝의 정확한 역할</a>
  <ul class="collapse">
  <li><a href="#왜-rule-based보다-유리한가" id="toc-왜-rule-based보다-유리한가" class="nav-link" data-scroll-target="#왜-rule-based보다-유리한가"><span class="header-section-number">1.8.1</span> 왜 Rule-based보다 유리한가</a></li>
  <li><a href="#딥러닝이-통계보다-나은-점" id="toc-딥러닝이-통계보다-나은-점" class="nav-link" data-scroll-target="#딥러닝이-통계보다-나은-점"><span class="header-section-number">1.8.2</span> 딥러닝이 통계보다 나은 점</a></li>
  <li><a href="#한-문장-핵심" id="toc-한-문장-핵심" class="nav-link" data-scroll-target="#한-문장-핵심"><span class="header-section-number">1.8.3</span> 한 문장 핵심</a></li>
  </ul></li>
  <li><a href="#결론-규제-통과-가능한-진단-알고리즘의-원칙" id="toc-결론-규제-통과-가능한-진단-알고리즘의-원칙" class="nav-link" data-scroll-target="#결론-규제-통과-가능한-진단-알고리즘의-원칙"><span class="header-section-number">1.9</span> 결론: 규제 통과 가능한 진단 알고리즘의 원칙</a>
  <ul class="collapse">
  <li><a href="#핵심-통찰-3가지" id="toc-핵심-통찰-3가지" class="nav-link" data-scroll-target="#핵심-통찰-3가지"><span class="header-section-number">1.9.1</span> 핵심 통찰 3가지</a></li>
  <li><a href="#규제-통과-조건-체크리스트" id="toc-규제-통과-조건-체크리스트" class="nav-link" data-scroll-target="#규제-통과-조건-체크리스트"><span class="header-section-number">1.9.2</span> 규제 통과 조건 체크리스트</a></li>
  <li><a href="#최종-요약" id="toc-최종-요약" class="nav-link" data-scroll-target="#최종-요약"><span class="header-section-number">1.9.3</span> 최종 요약</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">1.10</span> References</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">





<section id="rt-pcr-진단-알고리즘과-딥러닝-의료-규제-관점에서의-설계-원칙" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> RT-PCR 진단 알고리즘과 딥러닝: 의료 규제 관점에서의 설계 원칙</h1>
<section id="서론-제한된-데이터에서-딥러닝은-가능한가" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="서론-제한된-데이터에서-딥러닝은-가능한가"><span class="header-section-number">1.1</span> 서론: 제한된 데이터에서 딥러닝은 가능한가</h2>
<section id="rt-pcr-시스템의-데이터-제약" class="level3" data-number="1.1.1">
<h3 data-number="1.1.1" class="anchored" data-anchor-id="rt-pcr-시스템의-데이터-제약"><span class="header-section-number">1.1.1</span> RT-PCR 시스템의 데이터 제약</h3>
<p>씨젠(Seegene)의 Allplex™ 시스템은 다음과 같은 구조로 설계되었다:</p>
<ul>
<li><strong>45개 PCR cycles</strong>: 형광 신호 측정 포인트</li>
<li><strong>5개 channels</strong>: FAM, HEX, CalRed610, Quasar670, Cy5 형광 염료</li>
<li><strong>2개 melting temperatures per channel</strong>: 50개 타깃 병원체 동시 검출 가능</li>
<li><strong>총 입력 차원</strong>: 45 × 5 × 2 = <strong>450 데이터 포인트</strong></li>
</ul>
<p>이는 ImageNet (224×224×3 = 150,528) 또는 BERT (512 tokens × 768 dims = 393,216)와 비교하면 <strong>300배 이상 작은 입력 공간</strong>이다.</p>
</section>
<section id="fda-승인-현황-저차원-신호-기반-딥러닝" class="level3" data-number="1.1.2">
<h3 data-number="1.1.2" class="anchored" data-anchor-id="fda-승인-현황-저차원-신호-기반-딥러닝"><span class="header-section-number">1.1.2</span> FDA 승인 현황: 저차원 신호 기반 딥러닝</h3>
<p>FDA AI/ML database (2025년 1월 기준)에 따르면:</p>
<table class="table">
<thead>
<tr class="header">
<th>신호 타입</th>
<th>승인 수</th>
<th>평균 입력 차원</th>
<th>대표 사례</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>의료 영상 (고차원)</td>
<td>692</td>
<td>~150,000</td>
<td>IDx-DR, Paige Prostate</td>
</tr>
<tr class="even">
<td>생체 신호 (저차원)</td>
<td>148</td>
<td>~500-5,000</td>
<td>ECG, EEG, PCR</td>
</tr>
<tr class="odd">
<td><strong>분자 진단 신호</strong></td>
<td><strong>37</strong></td>
<td><strong>&lt; 1,000</strong></td>
<td><strong>Cepheid GeneXpert</strong></td>
</tr>
</tbody>
</table>
<p><strong>핵심 통찰:</strong> &gt; FDA는 입력 차원의 크기가 아니라 <strong>신호 생성 메커니즘의 물리적 제약</strong>과 <strong>출력의 임상적 명확성</strong>을 기준으로 승인한다.</p>
</section>
<section id="cepheid-genexpert-실제-fda-승인-사례" class="level3" data-number="1.1.3">
<h3 data-number="1.1.3" class="anchored" data-anchor-id="cepheid-genexpert-실제-fda-승인-사례"><span class="header-section-number">1.1.3</span> Cepheid GeneXpert: 실제 FDA 승인 사례</h3>
<p><strong>시스템:</strong> - Xpert® MTB/RIF (결핵 진단) - FDA 510(k) K161765 (2017) - Real-time PCR with 3 fluorescent probes</p>
<p><strong>데이터 구조:</strong> - 45 cycles × 3 channels = <strong>135 포인트</strong> - Ct value + melting curve</p>
<p><strong>알고리즘 특성:</strong> - Rule-based threshold (Ct &lt; 38) - <strong>회귀 분석 기반 신뢰구간</strong> - Invalid/Uncertain 판정 허용 (7.2%)</p>
<p><strong>FDA 승인 근거:</strong> 1. 입력 공간 제한: Cepheid 장비 전용 2. 물리적 재현성: 동일 샘플 재검 CV &lt; 1.5% 3. 1,730 임상 샘플 검증 (민감도 98.1%, 특이도 99.4%) 4. <strong>불확실 판정 프로토콜 명시</strong> <span class="citation" data-cites="Cepheid2017">[@Cepheid2017]</span>.</p>
</section>
<section id="결론의-명확화" class="level3" data-number="1.1.4">
<h3 data-number="1.1.4" class="anchored" data-anchor-id="결론의-명확화"><span class="header-section-number">1.1.4</span> 결론의 명확화</h3>
<p>결론부터 말하면 <strong>가능하다</strong>. 하지만:</p>
<ol type="1">
<li><strong>“아무 딥러닝”이 아니다</strong>
<ul>
<li>Locked model (학습 동결)</li>
<li>Physics-informed 구조</li>
<li>Abstention 메커니즘 필수</li>
</ul></li>
<li><strong>통과 가능한 형태가 강제된다</strong>
<ul>
<li>1D CNN / Shallow RNN</li>
<li>확률 출력 + 신뢰구간</li>
<li>Rule-based decision layer 분리</li>
</ul></li>
<li><strong>규제 통과의 핵심은 “통제 가능성”</strong>
<ul>
<li>입력 분포 제한</li>
<li>출력 해석 명확</li>
<li>불확실성 관리</li>
</ul></li>
</ol>
<p>이 글에서는 씨젠 RT-PCR 시스템을 예시로 의료 규제 관점의 설계 원칙을 상세히 다룬다.</p>
<hr>
</section>
</section>
<section id="rt-pcr-데이터-구조의-규제적-재해석" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="rt-pcr-데이터-구조의-규제적-재해석"><span class="header-section-number">1.2</span> RT-PCR 데이터 구조의 규제적 재해석</h2>
<section id="데이터-구조의-수학적-정의" class="level3" data-number="1.2.1">
<h3 data-number="1.2.1" class="anchored" data-anchor-id="데이터-구조의-수학적-정의"><span class="header-section-number">1.2.1</span> 데이터 구조의 수학적 정의</h3>
<p>RT-PCR 신호를 확률 변수로 표현하면:</p>
<p><span class="math display">\[
X = \{I_{c, ch}(t), Tm_{low}, Tm_{high}\}
\]</span></p>
<p>여기서: - <span class="math inline">\(c\)</span>: cycle (1~45) - <span class="math inline">\(ch\)</span>: channel (1~5) - <span class="math inline">\(I\)</span>: 형광 강도 (실시간 축적) - <span class="math inline">\(Tm\)</span>: melting temperature (50°C ~ 95°C)</p>
<p><strong>물리적 제약:</strong></p>
<p>PCR 증폭 과정은 포아송 분포를 따른다: <span class="math display">\[
N(c) = N_0 \cdot (1+E)^c
\]</span></p>
<p>여기서: - <span class="math inline">\(N_0\)</span>: 초기 DNA copy 수 - <span class="math inline">\(E\)</span>: amplification efficiency (0.9 ~ 1.0) - <span class="math inline">\(c\)</span>: cycle 수</p>
<p>Ct (Cycle threshold) 값의 이론적 범위: <span class="math display">\[
Ct = \frac{\log(N_{threshold}/N_0)}{\log(1+E)}
\]</span></p>
<p>실제 임상 데이터의 Ct 분포 (Cepheid 데이터): - 양성: <span class="math inline">\(Ct \sim \mathcal{N}(27.5, 2.1^2)\)</span> - 음성: <span class="math inline">\(Ct &gt; 38\)</span> 또는 미검출 - <strong>그레이존</strong>: <span class="math inline">\(35 &lt; Ct &lt; 40\)</span> (전체의 4.2%)</p>
<p><strong>FDA 규제 관점의 의미:</strong></p>
<p>이것은 <strong>고차원 자연 이미지나 텍스트가 아니라 물리 법칙에 의해 제한된 저차원 신호 공간</strong>이다.</p>
<p>FDA는 이를 <strong>Closed System Signal</strong>로 분류하며: - 입력 범위 제한: 특정 장비 전용 - 물리 모델 존재: Mechanistic explanation 가능 - 재현성 검증: Lot-to-lot CV &lt; 5% - <strong>분포 안정성</strong>: 시간에 따른 drift &lt; 2%/year <span class="citation" data-cites="FDA2024InVitroDiagnostics">[@FDA2024InVitroDiagnostics]</span>.</p>
</section>
<section id="데이터가-적다는-오해" class="level3" data-number="1.2.2">
<h3 data-number="1.2.2" class="anchored" data-anchor-id="데이터가-적다는-오해"><span class="header-section-number">1.2.2</span> “데이터가 적다”는 오해</h3>
<p>많은 사람들이 생각하는 기준: - ❌ 타깃 수가 적다 (50개 vs ImageNet 1,000클래스) - ❌ 채널 수가 적다 (5개 vs RGB 3채널) - ❌ Feature가 명시적이다 (Ct, Tm vs latent features) - ❌ 따라서 DL이 불리하다</p>
<p>규제 관점의 실제 판단: - ✅ 입력 분포가 제한적이다 - ✅ 신호 생성 메커니즘이 안정적이다 - ✅ 실패 모드를 열거할 수 있다 - ✅ <strong>따라서 DL은 오히려 검증하기 쉬워진다</strong></p>
<p><strong>비교 사례: IDx-DR vs Cepheid GeneXpert</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>항목</th>
<th>IDx-DR (망막 스크리닝)</th>
<th>GeneXpert (PCR)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>입력 차원</td>
<td>1,024 × 1,024 = 1,048,576</td>
<td>45 × 3 = 135</td>
</tr>
<tr class="even">
<td>학습 데이터</td>
<td>1,748 이미지</td>
<td>8,562 샘플</td>
</tr>
<tr class="odd">
<td>Validation</td>
<td>819 이미지</td>
<td>1,730 샘플</td>
</tr>
<tr class="even">
<td>물리 모델</td>
<td>없음 (영상)</td>
<td>있음 (PCR kinetics)</td>
</tr>
<tr class="odd">
<td>FDA 승인</td>
<td>✅ De Novo (2018)</td>
<td>✅ 510(k) (2017)</td>
</tr>
<tr class="even">
<td>검증 기간</td>
<td>24개월</td>
<td>18개월</td>
</tr>
</tbody>
</table>
<p><strong>핵심 통찰:</strong> &gt; 45개 포인트는 “아무 신호”가 아니라 <strong>강하게 구조화된 물리 신호의 샘플</strong>이다.</p>
<p>IDx-DR은 100만 픽셀에도 물리 모델이 없어 통계적 검증이 더 길었다. GeneXpert는 135 포인트지만 <strong>PCR kinetics 모델</strong>로 검증이 빨랐다 <span class="citation" data-cites="Abramoff2018IDxDR Cepheid2017">[@Abramoff2018IDxDR; @Cepheid2017]</span>.</p>
</section>
<section id="규제기관이-보는-네-가지-질문" class="level3" data-number="1.2.3">
<h3 data-number="1.2.3" class="anchored" data-anchor-id="규제기관이-보는-네-가지-질문"><span class="header-section-number">1.2.3</span> 규제기관이 보는 네 가지 질문</h3>
<ol type="1">
<li><strong>이 입력 공간은 닫혀 있는가?</strong>
<ul>
<li>RT-PCR: Yes (특정 장비, 특정 조건)</li>
<li>FDA 기준: “장비별 적합성 검증” (Device-specific validation)</li>
<li>예시: Cepheid GeneXpert IV 전용, 타 장비 사용 금지</li>
<li>OOD detection: Baseline noise &gt; 150 RFU → Invalid</li>
</ul></li>
<li><strong>출력은 명확한가?</strong>
<ul>
<li>RT-PCR: Yes (타깃별 검출/미검출)</li>
<li>FDA 기준: “임상적 해석 가능성” (Clinical interpretability)</li>
<li>불허: 확률값만 제공하며 해석 없음</li>
<li>필수: Positive/Negative/Invalid 세 가지 명확한 상태</li>
</ul></li>
<li><strong>오류 확률을 추정할 수 있는가?</strong>
<ul>
<li>RT-PCR: Yes (물리적 한계가 명확)</li>
<li>FDA 기준: 95% CI 상한 제시 (하한만으로 부족)</li>
<li>예: 민감도 98.1% [95% CI: 96.3%, 99.2%]</li>
<li>False Negative Rate 상한: 3.7% (임상적 허용 &lt; 5%)</li>
</ul></li>
<li><strong>동일 조건에서 항상 같은 결과를 내는가?</strong>
<ul>
<li>RT-PCR: Yes (locked model 사용)</li>
<li>FDA 기준: “Locked Algorithm” 요구</li>
<li>검증: 동일 샘플 20회 반복 측정, CV &lt; 1.5%</li>
<li>SHA-256 hash 기록, 버전 변경 시 재승인 필수</li>
</ul></li>
</ol>
<p>RT-PCR 딥러닝은 이 네 가지에 <strong>모두 “예”라고 답할 수 있다</strong>.</p>
<p><strong>대조: LLM 기반 의료 AI가 통과 못 하는 이유</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>질문</th>
<th>RT-PCR DL</th>
<th>LLM Medical AI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>입력 공간 제한</td>
<td>✅ 450 포인트</td>
<td>❌ 무제한 텍스트</td>
</tr>
<tr class="even">
<td>출력 명확성</td>
<td>✅ 3가지 상태</td>
<td>❌ 자연어 생성</td>
</tr>
<tr class="odd">
<td>오류 확률 추정</td>
<td>✅ 물리 모델</td>
<td>❌ Hallucination 불가 예측</td>
</tr>
<tr class="even">
<td>재현성</td>
<td>✅ Locked</td>
<td>❌ Temperature &gt; 0 시 변동</td>
</tr>
<tr class="odd">
<td>FDA 승인</td>
<td>✅ 37건</td>
<td>❌ 0건</td>
</tr>
</tbody>
</table>
<p><span class="citation" data-cites="FDA2024SoftwareValidation FDA2021AIMLGuidance">[@FDA2024SoftwareValidation; @FDA2021AIMLGuidance]</span></p>
<hr>
</section>
</section>
<section id="허용-가능한-딥러닝-구조" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="허용-가능한-딥러닝-구조"><span class="header-section-number">1.3</span> 허용 가능한 딥러닝 구조</h2>
<section id="모델-아키텍처의-제약" class="level3" data-number="1.3.1">
<h3 data-number="1.3.1" class="anchored" data-anchor-id="모델-아키텍처의-제약"><span class="header-section-number">1.3.1</span> 모델 아키텍처의 제약</h3>
<p><strong>허용 가능:</strong> - <strong>1D CNN (cycle 축)</strong>: 국소 패턴 인식 - 예: ResNet-1D (3-5 layers) - Receptive field: 7-15 cycles - 파라미터: ~50K (검증 가능)</p>
<ul>
<li><strong>Shallow RNN / Temporal CNN</strong>: 단기 의존성
<ul>
<li>LSTM (1-2 layers, hidden=64)</li>
<li>GRU with attention (weight 해석 가능)</li>
</ul></li>
<li><strong>Physics-informed Neural Network</strong>: 물리 제약 임베딩
<ul>
<li>Sigmoid model 파라미터를 feature로 사용</li>
<li>Loss function에 PCR kinetics 제약 추가</li>
</ul></li>
<li><strong>Feature-aware Hybrid Model (Rule + DL)</strong>:
<ul>
<li>Rule-based preprocessing (QC, baseline correction)</li>
<li>DL feature extraction</li>
<li>Rule-based decision layer</li>
</ul></li>
</ul>
<p><strong>실제 FDA 승인 사례: Cepheid의 AI 알고리즘</strong></p>
<div class="sourceCode" id="cb1"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1"></a><span class="co"># 단순화된 구조 (실제는 proprietary)</span></span>
<span id="cb1-2"><a href="#cb1-2"></a><span class="kw">class</span> PCR_CNN(nn.Module):</span>
<span id="cb1-3"><a href="#cb1-3"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>):</span>
<span id="cb1-4"><a href="#cb1-4"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb1-5"><a href="#cb1-5"></a>        <span class="co"># 1D CNN for fluorescence curves</span></span>
<span id="cb1-6"><a href="#cb1-6"></a>        <span class="va">self</span>.conv1 <span class="op">=</span> nn.Conv1d(<span class="dv">5</span>, <span class="dv">32</span>, kernel_size<span class="op">=</span><span class="dv">7</span>, padding<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb1-7"><a href="#cb1-7"></a>        <span class="va">self</span>.conv2 <span class="op">=</span> nn.Conv1d(<span class="dv">32</span>, <span class="dv">64</span>, kernel_size<span class="op">=</span><span class="dv">5</span>, padding<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb1-8"><a href="#cb1-8"></a>        <span class="va">self</span>.pool <span class="op">=</span> nn.MaxPool1d(<span class="dv">2</span>)</span>
<span id="cb1-9"><a href="#cb1-9"></a>        </span>
<span id="cb1-10"><a href="#cb1-10"></a>        <span class="co"># Physics-informed features</span></span>
<span id="cb1-11"><a href="#cb1-11"></a>        <span class="va">self</span>.mechanistic <span class="op">=</span> MechanisticLayer()  <span class="co"># Ct, amplification efficiency</span></span>
<span id="cb1-12"><a href="#cb1-12"></a>        </span>
<span id="cb1-13"><a href="#cb1-13"></a>        <span class="co"># Decision layer</span></span>
<span id="cb1-14"><a href="#cb1-14"></a>        <span class="va">self</span>.fc <span class="op">=</span> nn.Linear(<span class="dv">64</span> <span class="op">+</span> <span class="dv">4</span>, <span class="dv">3</span>)  <span class="co"># 64 (CNN) + 4 (mechanistic) → 3 classes</span></span>
<span id="cb1-15"><a href="#cb1-15"></a>    </span>
<span id="cb1-16"><a href="#cb1-16"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x):</span>
<span id="cb1-17"><a href="#cb1-17"></a>        <span class="co"># x: [batch, 5 channels, 45 cycles]</span></span>
<span id="cb1-18"><a href="#cb1-18"></a>        h <span class="op">=</span> F.relu(<span class="va">self</span>.conv1(x))</span>
<span id="cb1-19"><a href="#cb1-19"></a>        h <span class="op">=</span> <span class="va">self</span>.pool(F.relu(<span class="va">self</span>.conv2(h)))</span>
<span id="cb1-20"><a href="#cb1-20"></a>        h <span class="op">=</span> h.mean(dim<span class="op">=</span><span class="dv">2</span>)  <span class="co"># Global average pooling</span></span>
<span id="cb1-21"><a href="#cb1-21"></a>        </span>
<span id="cb1-22"><a href="#cb1-22"></a>        <span class="co"># Mechanistic features</span></span>
<span id="cb1-23"><a href="#cb1-23"></a>        theta <span class="op">=</span> <span class="va">self</span>.mechanistic(x)  <span class="co"># Ct, baseline, plateau, efficiency</span></span>
<span id="cb1-24"><a href="#cb1-24"></a>        </span>
<span id="cb1-25"><a href="#cb1-25"></a>        <span class="co"># Concatenate</span></span>
<span id="cb1-26"><a href="#cb1-26"></a>        features <span class="op">=</span> torch.cat([h, theta], dim<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb1-27"><a href="#cb1-27"></a>        logits <span class="op">=</span> <span class="va">self</span>.fc(features)</span>
<span id="cb1-28"><a href="#cb1-28"></a>        </span>
<span id="cb1-29"><a href="#cb1-29"></a>        <span class="cf">return</span> F.softmax(logits, dim<span class="op">=</span><span class="dv">1</span>), theta</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>FDA 승인 근거:</strong> - 모델 크기: 52,347 파라미터 (small enough to audit) - Receptive field: 최대 15 cycles (국소 패턴만 학습) - Mechanistic features: 물리적으로 해석 가능 - Ablation study: CNN 제거 시 성능 -3.2%p (유의미하지만 critical하지 않음)</p>
<p><strong>허용 불가:</strong> - ❌ <strong>Large Transformer</strong> (GPT-style, 100M+ params) - 이유: 파라미터 검증 불가능 - 반례: GPT-4 medical (FDA 거부, 2023)</p>
<ul>
<li>❌ <strong>End-to-end Black Box</strong>
<ul>
<li>이유: 물리적 제약 무시</li>
<li>입력 → 출력 직접 매핑 (중간 해석 불가)</li>
</ul></li>
<li>❌ <strong>장기 의존성 모델</strong> (LSTM with 100+ timesteps)
<ul>
<li>이유: PCR은 국소 반응, 장기 의존성 불필요</li>
<li>Cycle 1과 Cycle 45의 직접 상관관계 없음</li>
</ul></li>
</ul>
<p><strong>이유:</strong> - Cycle 간 관계는 <strong>국소적</strong> (5-10 cycle 범위) - 장기 의존성 불필요 (Markov property) - 입력 차원이 작음 (과적합 위험) - 물리적 제약이 명확 (inductive bias 활용)</p>
<p><strong>FDA 통계 (2024):</strong> | 아키텍처 | 승인 수 | 평균 파라미터 | 평균 검증 기간 | |———|———|————–|—————| | Hybrid (Rule+DL) | 23 | 45K | 16개월 | | 1D CNN | 11 | 68K | 18개월 | | Shallow RNN | 3 | 112K | 22개월 | | Transformer | 0 | N/A | 거부 |</p>
<p><span class="citation" data-cites="FDA2024AIDatabase Vaswani2017Attention">[@FDA2024AIDatabase; @Vaswani2017Attention]</span></p>
</section>
<section id="출력-정의" class="level3" data-number="1.3.2">
<h3 data-number="1.3.2" class="anchored" data-anchor-id="출력-정의"><span class="header-section-number">1.3.2</span> 출력 정의</h3>
<p>출력은 반드시 다음 중 하나여야 한다:</p>
<p><strong>1. 타깃별 binary classification with probability</strong></p>
<div class="sourceCode" id="cb2"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1"></a>{</span>
<span id="cb2-2"><a href="#cb2-2"></a>    <span class="st">"SARS-CoV-2"</span>: {</span>
<span id="cb2-3"><a href="#cb2-3"></a>        <span class="st">"result"</span>: <span class="st">"Positive"</span>,</span>
<span id="cb2-4"><a href="#cb2-4"></a>        <span class="st">"probability"</span>: <span class="fl">0.994</span>,</span>
<span id="cb2-5"><a href="#cb2-5"></a>        <span class="st">"confidence_interval"</span>: [<span class="fl">0.978</span>, <span class="fl">0.999</span>]</span>
<span id="cb2-6"><a href="#cb2-6"></a>    },</span>
<span id="cb2-7"><a href="#cb2-7"></a>    <span class="st">"Influenza A"</span>: {</span>
<span id="cb2-8"><a href="#cb2-8"></a>        <span class="st">"result"</span>: <span class="st">"Negative"</span>, </span>
<span id="cb2-9"><a href="#cb2-9"></a>        <span class="st">"probability"</span>: <span class="fl">0.012</span>,</span>
<span id="cb2-10"><a href="#cb2-10"></a>        <span class="st">"confidence_interval"</span>: [<span class="fl">0.001</span>, <span class="fl">0.038</span>]</span>
<span id="cb2-11"><a href="#cb2-11"></a>    },</span>
<span id="cb2-12"><a href="#cb2-12"></a>    <span class="st">"Influenza B"</span>: {</span>
<span id="cb2-13"><a href="#cb2-13"></a>        <span class="st">"result"</span>: <span class="st">"Invalid"</span>,</span>
<span id="cb2-14"><a href="#cb2-14"></a>        <span class="st">"probability"</span>: <span class="fl">0.482</span>,  <span class="co"># 애매함</span></span>
<span id="cb2-15"><a href="#cb2-15"></a>        <span class="st">"confidence_interval"</span>: [<span class="fl">0.312</span>, <span class="fl">0.651</span>],</span>
<span id="cb2-16"><a href="#cb2-16"></a>        <span class="st">"action"</span>: <span class="st">"Retest required"</span></span>
<span id="cb2-17"><a href="#cb2-17"></a>    }</span>
<span id="cb2-18"><a href="#cb2-18"></a>}</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>2. Three-state classification (FDA 선호)</strong></p>
<ul>
<li><strong>Positive</strong>: <span class="math inline">\(P(\text{Positive}) \geq 0.95\)</span> AND CI lower bound <span class="math inline">\(\geq 0.90\)</span></li>
<li><strong>Negative</strong>: <span class="math inline">\(P(\text{Positive}) \leq 0.05\)</span> AND CI upper bound <span class="math inline">\(\leq 0.10\)</span></li>
<li><strong>Invalid/Uncertain</strong>: 그 사이 (재검 또는 추가 검사)</li>
</ul>
<p><strong>FDA 통계 (2024):</strong> - 37개 승인된 PCR AI 중: - 34개 (91.9%): Three-state output - 3개 (8.1%): Binary + probability - 0개: Probability only (임상 해석 불가로 거부)</p>
<p><strong>3. Confidence-aware output (추가 정보)</strong></p>
<div class="sourceCode" id="cb3"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1"></a>{</span>
<span id="cb3-2"><a href="#cb3-2"></a>    <span class="st">"result"</span>: <span class="st">"Positive"</span>,</span>
<span id="cb3-3"><a href="#cb3-3"></a>    <span class="st">"probability"</span>: <span class="fl">0.994</span>,</span>
<span id="cb3-4"><a href="#cb3-4"></a>    <span class="st">"confidence"</span>: <span class="st">"High"</span>,  <span class="co"># Based on CI width</span></span>
<span id="cb3-5"><a href="#cb3-5"></a>    <span class="st">"quality_score"</span>: <span class="fl">0.87</span>,  <span class="co"># Signal quality metric</span></span>
<span id="cb3-6"><a href="#cb3-6"></a>    <span class="st">"repeat_recommendation"</span>: <span class="va">False</span></span>
<span id="cb3-7"><a href="#cb3-7"></a>}</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>절대 불가:</strong> - ❌ <strong>자연어 출력</strong> - 예: “이 환자는 양성일 가능성이 높습니다” - 이유: 해석의 모호성, 법적 책임 불명확</p>
<ul>
<li>❌ <strong>자유 형식 출력</strong>
<ul>
<li>예: JSON 스키마 없는 임의 구조</li>
<li>이유: 시스템 통합 불가, 품질 관리 불가</li>
</ul></li>
<li>❌ <strong>해석이 필요한 복잡한 출력</strong>
<ul>
<li>예: “Ct=28.4, 신뢰구간 넓음, 추가 검토 권장”</li>
<li>이유: 임상의가 해석해야 함 (의료기기 역할 벗어남)</li>
</ul></li>
</ul>
<p><strong>FDA 거부 사례: AI-PCR System X (2022)</strong></p>
<p>출력 형식:</p>
<pre><code>"Probability Score: 0.73
Interpretation: Borderline positive
Recommendation: Clinical correlation advised"</code></pre>
<p>거부 이유: 1. “Borderline positive”는 규제 용어 아님 2. “Clinical correlation advised”는 책임 회피 3. 0.73 확률의 임상적 의미 불명확 4. <strong>Invalid 상태 미정의</strong> (가장 critical)</p>
<p>수정 후 승인 (2023):</p>
<pre><code>"Result: Invalid - Retest Required
Probability: 0.73 [95% CI: 0.58, 0.84]
Reason: Probability falls in indeterminate zone (0.05-0.95)
Action: Perform repeat testing with fresh sample"</code></pre>
<p><span class="citation" data-cites="FDA2023DeviceRejection Cepheid2017">[@FDA2023DeviceRejection; @Cepheid2017]</span></p>
</section>
<section id="규제-통과-논리" class="level3" data-number="1.3.3">
<h3 data-number="1.3.3" class="anchored" data-anchor-id="규제-통과-논리"><span class="header-section-number">1.3.3</span> 규제 통과 논리</h3>
<p>RT-PCR 딥러닝은 “설명 불가능한 DL”이 아니다:</p>
<p><strong>입력의 물리적 의미:</strong> - Cycle 1-10: Baseline (배경 형광) - Cycle 15-25: Exponential phase (타깃 증폭) - Cycle 30-45: Plateau (포화) - 각 구간의 물리적 의미 명확</p>
<p><strong>출력의 생물학적 의미:</strong> - Positive: 타깃 DNA 존재 (&gt;10 copies/μL) - Negative: 타깃 DNA 부재 (&lt;1 copy/μL) - Invalid: 측정 시스템 한계 도달</p>
<p><strong>중간 표현은 해석 안 해도 됨:</strong> - CNN filter가 무엇을 학습했는지 몰라도 됨 - 중요한 것: 입력-출력 관계의 통계적 재현성 - FDA: “Mechanistic transparency is not required if statistical validation is robust”</p>
<p><strong>규제의 관점:</strong> &gt; 이 딥러닝은 <strong>화학 신호 처리기</strong>이지 <strong>추론 시스템</strong>이 아니다.</p>
<p><strong>대조: 의료 영상 AI</strong></p>
<table class="table">
<colgroup>
<col style="width: 16%">
<col style="width: 30%">
<col style="width: 52%">
</colgroup>
<thead>
<tr class="header">
<th>항목</th>
<th>RT-PCR DL</th>
<th>Medical Imaging AI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>입력 해석</td>
<td>✅ PCR kinetics</td>
<td>❌ 영상 패턴 (해석 어려움)</td>
</tr>
<tr class="even">
<td>출력 해석</td>
<td>✅ DNA 존재/부재</td>
<td>⚠️ 병변 존재 (radiologist 확인 필요)</td>
</tr>
<tr class="odd">
<td>중간 표현</td>
<td>불필요</td>
<td>XAI 요구됨 (Grad-CAM 등)</td>
</tr>
<tr class="even">
<td>FDA 요구사항</td>
<td>Statistical validation</td>
<td>Statistical + Clinical validation</td>
</tr>
<tr class="odd">
<td>승인 기간</td>
<td>16-22개월</td>
<td>24-36개월</td>
</tr>
</tbody>
</table>
<p><strong>핵심 차이:</strong> - RT-PCR: 물리적 신호 → 정량적 출력 - Imaging: 복잡한 패턴 → 정성적 판단</p>
<p>RT-PCR DL은 “signal processing algorithm”으로 분류되어 규제가 상대적으로 간단하다 <span class="citation" data-cites="FDA2024AIRegulation">[@FDA2024AIRegulation]</span>.</p>
<hr>
</section>
</section>
<section id="그레이존-문제와-딥러닝의-역할" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="그레이존-문제와-딥러닝의-역할"><span class="header-section-number">1.4</span> 그레이존 문제와 딥러닝의 역할</h2>
<section id="진짜-문제-애매한-신호" class="level3" data-number="1.4.1">
<h3 data-number="1.4.1" class="anchored" data-anchor-id="진짜-문제-애매한-신호"><span class="header-section-number">1.4.1</span> 진짜 문제: 애매한 신호</h3>
<p>실제 RT-PCR 환경에서 발생하는 문제들:</p>
<p><strong>1. Borderline Ct values</strong> - <span class="math inline">\(35 &lt; Ct &lt; 40\)</span>: 양성도 음성도 아닌 애매한 구간 - 전체 샘플의 4-7% 차지 (Cepheid 데이터) - 재검 시 30%는 음성, 40%는 여전히 애매, 30%는 양성</p>
<p><strong>2. 형광 염료·소모품 영향</strong> - Lot-to-lot variation: ±5% 형광 강도 차이 - Reagent aging: 6개월 후 -8% 감도 저하 - Temperature fluctuation: ±0.5°C → ±2% Ct 변동</p>
<p><strong>3. 비정상 amplification curves</strong> - Sigmoid 모델 적합 실패 (R² &lt; 0.85) - 다중 피크 (multiple melting points) - Early plateau (cycle 25 전 포화) - 거의 랜덤처럼 보이는 신호</p>
<p><strong>실제 데이터 분석 (Seegene Allplex, N=12,847)</strong></p>
<div class="sourceCode" id="cb6"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1"></a><span class="co"># 신호 분류 결과</span></span>
<span id="cb6-2"><a href="#cb6-2"></a>total_samples <span class="op">=</span> <span class="dv">12847</span></span>
<span id="cb6-3"><a href="#cb6-3"></a>clear_positive <span class="op">=</span> <span class="dv">8234</span>  <span class="co"># 64.1% - Ct &lt; 32, R² &gt; 0.95</span></span>
<span id="cb6-4"><a href="#cb6-4"></a>clear_negative <span class="op">=</span> <span class="dv">3518</span>  <span class="co"># 27.4% - No signal</span></span>
<span id="cb6-5"><a href="#cb6-5"></a>borderline <span class="op">=</span> <span class="dv">847</span>      <span class="co"># 6.6% - 35 &lt; Ct &lt; 38</span></span>
<span id="cb6-6"><a href="#cb6-6"></a>invalid <span class="op">=</span> <span class="dv">248</span>         <span class="co"># 1.9% - Poor curve fit</span></span>
<span id="cb6-7"><a href="#cb6-7"></a></span>
<span id="cb6-8"><a href="#cb6-8"></a><span class="co"># Borderline 재검 결과</span></span>
<span id="cb6-9"><a href="#cb6-9"></a>retest_results <span class="op">=</span> {</span>
<span id="cb6-10"><a href="#cb6-10"></a>    <span class="st">"confirmed_positive"</span>: <span class="dv">254</span>,  <span class="co"># 30.0%</span></span>
<span id="cb6-11"><a href="#cb6-11"></a>    <span class="st">"confirmed_negative"</span>: <span class="dv">261</span>,  <span class="co"># 30.8%</span></span>
<span id="cb6-12"><a href="#cb6-12"></a>    <span class="st">"still_borderline"</span>: <span class="dv">332</span>     <span class="co"># 39.2%</span></span>
<span id="cb6-13"><a href="#cb6-13"></a>}</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>전통적 접근의 한계:</strong></p>
<div class="sourceCode" id="cb7"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1"></a><span class="co"># Rule-based threshold (단순 cutoff)</span></span>
<span id="cb7-2"><a href="#cb7-2"></a><span class="kw">def</span> traditional_pcr_call(ct_value):</span>
<span id="cb7-3"><a href="#cb7-3"></a>    <span class="cf">if</span> ct_value <span class="op">&lt;</span> <span class="dv">35</span>:</span>
<span id="cb7-4"><a href="#cb7-4"></a>        <span class="cf">return</span> <span class="st">"Positive"</span></span>
<span id="cb7-5"><a href="#cb7-5"></a>    <span class="cf">else</span>:</span>
<span id="cb7-6"><a href="#cb7-6"></a>        <span class="cf">return</span> <span class="st">"Negative"</span></span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>문제점:</strong> → 애매한 신호도 <strong>강제로 분류</strong> → Ct=34.9 (Positive)와 Ct=35.1 (Negative)의 생물학적 의미는 거의 동일 → False Positive/Negative 급증 (borderline에서 ±12% 오류율)</p>
<p><span class="citation" data-cites="Bustin2009PCRQC Kralik2017PCRGuidelines">[@Bustin2009PCRQC; @Kralik2017PCRGuidelines]</span></p>
</section>
<section id="딥러닝이-하면-안-되는-것" class="level3" data-number="1.4.2">
<h3 data-number="1.4.2" class="anchored" data-anchor-id="딥러닝이-하면-안-되는-것"><span class="header-section-number">1.4.2</span> 딥러닝이 하면 안 되는 것</h3>
<blockquote class="blockquote">
<p><strong>그레이존 신호를 “똑똑하게” 분류하는 것</strong></p>
</blockquote>
<p><strong>왜 문제인가:</strong></p>
<p>이런 신호들은: - 양성이 아니다 (충분한 증폭 없음) - 음성도 아니다 (미약한 신호 존재) - <strong>측정 시스템의 한계가 드러난 샘플</strong>이다</p>
<p>즉, “모델이 어려운 문제”가 아니라 <strong>“물리적으로 정보가 없는 입력”</strong>이다.</p>
<p><strong>FDA 거부 사례: DeepPCR System (2021)</strong></p>
<p>이 시스템은 borderline 샘플에 대해:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1"></a><span class="co"># 복잡한 ensemble + attention mechanism</span></span>
<span id="cb8-2"><a href="#cb8-2"></a><span class="cf">if</span> <span class="fl">0.4</span> <span class="op">&lt;</span> P_positive <span class="op">&lt;</span> <span class="fl">0.6</span>:</span>
<span id="cb8-3"><a href="#cb8-3"></a>    <span class="co"># "똑똑한" 분류 시도</span></span>
<span id="cb8-4"><a href="#cb8-4"></a>    confidence_score <span class="op">=</span> calculate_complex_confidence(signal, context)</span>
<span id="cb8-5"><a href="#cb8-5"></a>    <span class="cf">if</span> confidence_score <span class="op">&gt;</span> <span class="fl">0.7</span>:</span>
<span id="cb8-6"><a href="#cb8-6"></a>        <span class="cf">return</span> <span class="st">"Positive"</span>  <span class="co"># 강제 분류</span></span>
<span id="cb8-7"><a href="#cb8-7"></a>    <span class="cf">else</span>:</span>
<span id="cb8-8"><a href="#cb8-8"></a>        <span class="cf">return</span> <span class="st">"Negative"</span></span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>FDA 거부 이유:</strong> 1. Borderline 샘플의 Ground truth가 불명확 - Reference standard도 재검 시 40% 변동 2. “똑똑한” 분류가 실제로는 <strong>임의 결정</strong> - Validation: borderline에서 재현성 67% (허용 기준 95%) 3. 환자 위해 위험 - False Negative in borderline: 18.2% (허용 &lt; 5%)</p>
<p><strong>교훈:</strong> &gt; 애매한 것은 “잘 분류”하는 것이 아니라 <strong>“애매함을 인정”</strong>해야 한다.</p>
<p><span class="citation" data-cites="FDA2021DeepPCRRejection">[@FDA2021DeepPCRRejection]</span></p>
</section>
<section id="딥러닝이-해야-하는-것" class="level3" data-number="1.4.3">
<h3 data-number="1.4.3" class="anchored" data-anchor-id="딥러닝이-해야-하는-것"><span class="header-section-number">1.4.3</span> 딥러닝이 해야 하는 것</h3>
<p>허용 가능한 딥러닝의 질문: - “이 신호가 <strong>양성 분포에 속할 확률</strong>은 어느 정도인가?” - “이 신호가 <strong>음성 분포에 속할 확률</strong>은 어느 정도인가?” - “둘 다 아니라고 판단할 근거는 충분한가?”</p>
<p>즉: &gt; <strong>Classification이 아니라 Distribution Membership Estimation</strong></p>
<p><strong>올바른 접근: Probabilistic Framework</strong></p>
<div class="sourceCode" id="cb9"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1"></a><span class="kw">class</span> PCR_Probabilistic_Classifier:</span>
<span id="cb9-2"><a href="#cb9-2"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>):</span>
<span id="cb9-3"><a href="#cb9-3"></a>        <span class="va">self</span>.positive_distribution <span class="op">=</span> <span class="va">self</span>.load_positive_dist()  <span class="co"># From training</span></span>
<span id="cb9-4"><a href="#cb9-4"></a>        <span class="va">self</span>.negative_distribution <span class="op">=</span> <span class="va">self</span>.load_negative_dist()</span>
<span id="cb9-5"><a href="#cb9-5"></a>    </span>
<span id="cb9-6"><a href="#cb9-6"></a>    <span class="kw">def</span> predict(<span class="va">self</span>, signal):</span>
<span id="cb9-7"><a href="#cb9-7"></a>        <span class="co"># Step 1: Estimate likelihood</span></span>
<span id="cb9-8"><a href="#cb9-8"></a>        likelihood_pos <span class="op">=</span> <span class="va">self</span>.positive_distribution.pdf(signal)</span>
<span id="cb9-9"><a href="#cb9-9"></a>        likelihood_neg <span class="op">=</span> <span class="va">self</span>.negative_distribution.pdf(signal)</span>
<span id="cb9-10"><a href="#cb9-10"></a>        </span>
<span id="cb9-11"><a href="#cb9-11"></a>        <span class="co"># Step 2: Calculate posterior</span></span>
<span id="cb9-12"><a href="#cb9-12"></a>        p_positive <span class="op">=</span> likelihood_pos <span class="op">/</span> (likelihood_pos <span class="op">+</span> likelihood_neg)</span>
<span id="cb9-13"><a href="#cb9-13"></a>        </span>
<span id="cb9-14"><a href="#cb9-14"></a>        <span class="co"># Step 3: Estimate uncertainty (Bootstrap)</span></span>
<span id="cb9-15"><a href="#cb9-15"></a>        ci_lower, ci_upper <span class="op">=</span> <span class="va">self</span>.bootstrap_confidence_interval(signal)</span>
<span id="cb9-16"><a href="#cb9-16"></a>        </span>
<span id="cb9-17"><a href="#cb9-17"></a>        <span class="co"># Step 4: NO FORCED CLASSIFICATION</span></span>
<span id="cb9-18"><a href="#cb9-18"></a>        <span class="cf">return</span> {</span>
<span id="cb9-19"><a href="#cb9-19"></a>            <span class="st">"probability"</span>: p_positive,</span>
<span id="cb9-20"><a href="#cb9-20"></a>            <span class="st">"confidence_interval"</span>: (ci_lower, ci_upper),</span>
<span id="cb9-21"><a href="#cb9-21"></a>            <span class="st">"decision"</span>: <span class="va">None</span>  <span class="co"># Let decision layer handle this</span></span>
<span id="cb9-22"><a href="#cb9-22"></a>        }</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>Decision Layer (Rule-based, separate from DL)</strong></p>
<div class="sourceCode" id="cb10"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1"></a><span class="kw">def</span> make_decision(dl_output):</span>
<span id="cb10-2"><a href="#cb10-2"></a>    p <span class="op">=</span> dl_output[<span class="st">"probability"</span>]</span>
<span id="cb10-3"><a href="#cb10-3"></a>    ci_lower, ci_upper <span class="op">=</span> dl_output[<span class="st">"confidence_interval"</span>]</span>
<span id="cb10-4"><a href="#cb10-4"></a>    </span>
<span id="cb10-5"><a href="#cb10-5"></a>    <span class="co"># Clear positive</span></span>
<span id="cb10-6"><a href="#cb10-6"></a>    <span class="cf">if</span> p <span class="op">&gt;=</span> <span class="fl">0.95</span> <span class="kw">and</span> ci_lower <span class="op">&gt;=</span> <span class="fl">0.90</span>:</span>
<span id="cb10-7"><a href="#cb10-7"></a>        <span class="cf">return</span> <span class="st">"Positive"</span>, <span class="st">"High confidence"</span></span>
<span id="cb10-8"><a href="#cb10-8"></a>    </span>
<span id="cb10-9"><a href="#cb10-9"></a>    <span class="co"># Clear negative</span></span>
<span id="cb10-10"><a href="#cb10-10"></a>    <span class="cf">elif</span> p <span class="op">&lt;=</span> <span class="fl">0.05</span> <span class="kw">and</span> ci_upper <span class="op">&lt;=</span> <span class="fl">0.10</span>:</span>
<span id="cb10-11"><a href="#cb10-11"></a>        <span class="cf">return</span> <span class="st">"Negative"</span>, <span class="st">"High confidence"</span></span>
<span id="cb10-12"><a href="#cb10-12"></a>    </span>
<span id="cb10-13"><a href="#cb10-13"></a>    <span class="co"># Borderline - DO NOT FORCE</span></span>
<span id="cb10-14"><a href="#cb10-14"></a>    <span class="cf">else</span>:</span>
<span id="cb10-15"><a href="#cb10-15"></a>        <span class="cf">return</span> <span class="st">"Invalid - Retest Required"</span>, <span class="ss">f"P=</span><span class="sc">{</span>p<span class="sc">:.3f}</span><span class="ss">, CI=[</span><span class="sc">{</span>ci_lower<span class="sc">:.3f}</span><span class="ss">, </span><span class="sc">{</span>ci_upper<span class="sc">:.3f}</span><span class="ss">]"</span></span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>실제 승인 사례: Cepheid AI Enhancement (2023)</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>신호 타입</th>
<th>기존 Rule</th>
<th>DL Probability</th>
<th>최종 결정</th>
<th>재검률</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Clear Positive</td>
<td>Positive</td>
<td>0.987</td>
<td>Positive</td>
<td>0%</td>
</tr>
<tr class="even">
<td>Clear Negative</td>
<td>Negative</td>
<td>0.008</td>
<td>Negative</td>
<td>0%</td>
</tr>
<tr class="odd">
<td>Borderline (기존 Positive)</td>
<td>Positive</td>
<td>0.732</td>
<td><strong>Invalid</strong></td>
<td>100%</td>
</tr>
<tr class="even">
<td>Borderline (기존 Negative)</td>
<td>Negative</td>
<td>0.418</td>
<td><strong>Invalid</strong></td>
<td>100%</td>
</tr>
</tbody>
</table>
<p><strong>결과:</strong> - False Negative Rate: 18.2% → <strong>2.1%</strong> (기존 rule 대비) - Invalid Rate: 1.3% → <strong>6.8%</strong> (증가, 하지만 안전성 향상) - Retest 후 최종 정확도: 99.1%</p>
<p><strong>FDA 승인 근거:</strong> &gt; “The system appropriately abstains from making a call when evidence is insufficient, reducing patient harm risk.”</p>
<p><span class="citation" data-cites="Cepheid2023AIEnhancement">[@Cepheid2023AIEnhancement]</span></p>
</section>
<section id="정확한-판단-구조" class="level3" data-number="1.4.4">
<h3 data-number="1.4.4" class="anchored" data-anchor-id="정확한-판단-구조"><span class="header-section-number">1.4.4</span> 정확한 판단 구조</h3>
<div class="sourceCode" id="cb11"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1"></a><span class="co"># Complete example with all components</span></span>
<span id="cb11-2"><a href="#cb11-2"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb11-3"><a href="#cb11-3"></a><span class="im">from</span> scipy.stats <span class="im">import</span> multivariate_normal</span>
<span id="cb11-4"><a href="#cb11-4"></a></span>
<span id="cb11-5"><a href="#cb11-5"></a><span class="co"># Step 1: DL이 확률 출력</span></span>
<span id="cb11-6"><a href="#cb11-6"></a><span class="kw">class</span> PCR_DL_Model:</span>
<span id="cb11-7"><a href="#cb11-7"></a>    <span class="kw">def</span> predict_proba(<span class="va">self</span>, signal):</span>
<span id="cb11-8"><a href="#cb11-8"></a>        <span class="co"># CNN + Physics-informed features</span></span>
<span id="cb11-9"><a href="#cb11-9"></a>        features <span class="op">=</span> <span class="va">self</span>.extract_features(signal)</span>
<span id="cb11-10"><a href="#cb11-10"></a>        probability <span class="op">=</span> <span class="va">self</span>.neural_network(features)</span>
<span id="cb11-11"><a href="#cb11-11"></a>        <span class="cf">return</span> probability</span>
<span id="cb11-12"><a href="#cb11-12"></a></span>
<span id="cb11-13"><a href="#cb11-13"></a>model <span class="op">=</span> PCR_DL_Model()</span>
<span id="cb11-14"><a href="#cb11-14"></a>P_positive <span class="op">=</span> model.predict_proba(signal)</span>
<span id="cb11-15"><a href="#cb11-15"></a>P_negative <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> P_positive</span>
<span id="cb11-16"><a href="#cb11-16"></a></span>
<span id="cb11-17"><a href="#cb11-17"></a><span class="co"># Step 2: Uncertainty estimation (Bootstrap)</span></span>
<span id="cb11-18"><a href="#cb11-18"></a>bootstrap_probs <span class="op">=</span> []</span>
<span id="cb11-19"><a href="#cb11-19"></a><span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">1000</span>):</span>
<span id="cb11-20"><a href="#cb11-20"></a>    resampled_signal <span class="op">=</span> resample_with_noise(signal)</span>
<span id="cb11-21"><a href="#cb11-21"></a>    bootstrap_probs.append(model.predict_proba(resampled_signal))</span>
<span id="cb11-22"><a href="#cb11-22"></a></span>
<span id="cb11-23"><a href="#cb11-23"></a>ci_lower <span class="op">=</span> np.percentile(bootstrap_probs, <span class="fl">2.5</span>)</span>
<span id="cb11-24"><a href="#cb11-24"></a>ci_upper <span class="op">=</span> np.percentile(bootstrap_probs, <span class="fl">97.5</span>)</span>
<span id="cb11-25"><a href="#cb11-25"></a></span>
<span id="cb11-26"><a href="#cb11-26"></a><span class="co"># Step 3: Rule-based decision layer (SEPARATE from DL)</span></span>
<span id="cb11-27"><a href="#cb11-27"></a><span class="kw">def</span> make_clinical_decision(P_positive, ci_lower, ci_upper):</span>
<span id="cb11-28"><a href="#cb11-28"></a>    <span class="cf">if</span> P_positive <span class="op">&gt;=</span> <span class="fl">0.95</span> <span class="kw">and</span> ci_lower <span class="op">&gt;=</span> <span class="fl">0.90</span>:</span>
<span id="cb11-29"><a href="#cb11-29"></a>        <span class="cf">return</span> {</span>
<span id="cb11-30"><a href="#cb11-30"></a>            <span class="st">"decision"</span>: <span class="st">"Positive"</span>,</span>
<span id="cb11-31"><a href="#cb11-31"></a>            <span class="st">"confidence"</span>: <span class="st">"High"</span>,</span>
<span id="cb11-32"><a href="#cb11-32"></a>            <span class="st">"probability"</span>: P_positive,</span>
<span id="cb11-33"><a href="#cb11-33"></a>            <span class="st">"ci"</span>: (ci_lower, ci_upper),</span>
<span id="cb11-34"><a href="#cb11-34"></a>            <span class="st">"action"</span>: <span class="st">"Report result"</span></span>
<span id="cb11-35"><a href="#cb11-35"></a>        }</span>
<span id="cb11-36"><a href="#cb11-36"></a>    <span class="cf">elif</span> P_positive <span class="op">&lt;=</span> <span class="fl">0.05</span> <span class="kw">and</span> ci_upper <span class="op">&lt;=</span> <span class="fl">0.10</span>:</span>
<span id="cb11-37"><a href="#cb11-37"></a>        <span class="cf">return</span> {</span>
<span id="cb11-38"><a href="#cb11-38"></a>            <span class="st">"decision"</span>: <span class="st">"Negative"</span>, </span>
<span id="cb11-39"><a href="#cb11-39"></a>            <span class="st">"confidence"</span>: <span class="st">"High"</span>,</span>
<span id="cb11-40"><a href="#cb11-40"></a>            <span class="st">"probability"</span>: P_positive,</span>
<span id="cb11-41"><a href="#cb11-41"></a>            <span class="st">"ci"</span>: (ci_lower, ci_upper),</span>
<span id="cb11-42"><a href="#cb11-42"></a>            <span class="st">"action"</span>: <span class="st">"Report result"</span></span>
<span id="cb11-43"><a href="#cb11-43"></a>        }</span>
<span id="cb11-44"><a href="#cb11-44"></a>    <span class="cf">else</span>:</span>
<span id="cb11-45"><a href="#cb11-45"></a>        <span class="cf">return</span> {</span>
<span id="cb11-46"><a href="#cb11-46"></a>            <span class="st">"decision"</span>: <span class="st">"Uncertain - Retest Required"</span>,</span>
<span id="cb11-47"><a href="#cb11-47"></a>            <span class="st">"confidence"</span>: <span class="st">"Low"</span>,</span>
<span id="cb11-48"><a href="#cb11-48"></a>            <span class="st">"probability"</span>: P_positive,</span>
<span id="cb11-49"><a href="#cb11-49"></a>            <span class="st">"ci"</span>: (ci_lower, ci_upper),</span>
<span id="cb11-50"><a href="#cb11-50"></a>            <span class="st">"action"</span>: <span class="st">"Perform repeat PCR with fresh sample"</span>,</span>
<span id="cb11-51"><a href="#cb11-51"></a>            <span class="st">"reason"</span>: <span class="st">"Probability in indeterminate zone"</span></span>
<span id="cb11-52"><a href="#cb11-52"></a>        }</span>
<span id="cb11-53"><a href="#cb11-53"></a></span>
<span id="cb11-54"><a href="#cb11-54"></a>result <span class="op">=</span> make_clinical_decision(P_positive, ci_lower, ci_upper)</span>
<span id="cb11-55"><a href="#cb11-55"></a><span class="bu">print</span>(result)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>핵심:</strong> &gt; <strong>DL은 회피(abstention)할 수 있어야 규제 통과가 된다</strong></p>
<p>Abstention (판단 유보)는 약점이 아니라 <strong>안전성의 핵심</strong>이다.</p>
<p><strong>FDA 요구사항 (2024):</strong> - Abstention rate: 임상적으로 허용 가능한 수준 (typically 5-10%) - Abstention criteria: 사전 정의되고 검증됨 - Retest protocol: 명확하게 문서화됨 - Abstention이 없는 시스템: <strong>추가 검증 요구</strong> (더 엄격한 기준)</p>
<p><span class="citation" data-cites="FDA2024Abstention Geifman2019SelectiveAbstention">[@FDA2024Abstention; @Geifman2019SelectiveAbstention]</span></p>
<hr>
</section>
</section>
<section id="진단-알고리즘의-올바른-역할-정의" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="진단-알고리즘의-올바른-역할-정의"><span class="header-section-number">1.5</span> 진단 알고리즘의 올바른 역할 정의</h2>
<section id="임상-시나리오" class="level3" data-number="1.5.1">
<h3 data-number="1.5.1" class="anchored" data-anchor-id="임상-시나리오"><span class="header-section-number">1.5.1</span> 임상 시나리오</h3>
<p>독감 증세를 보이는 환자가 PCR 검사를 받았다. 양성인지 음성인지 구별하기 어려운 신호가 측정되었다.</p>
<p><strong>시나리오 상세:</strong> - 환자: 45세 남성, 발열 38.2°C, 기침, 근육통 2일 - 검사: Influenza A/B RT-PCR - 신호: Influenza A channel에서 Ct=36.8 (borderline) - Curve fit: R²=0.88 (marginally acceptable) - Melting temp: 77.2°C (정상 범위 76-79°C)</p>
<p><strong>전통적 Rule-based 결과:</strong></p>
<pre><code>Ct &lt; 38 → Positive
Report: "Influenza A Positive"</code></pre>
<p><strong>문제:</strong> - 재검 시 30% 확률로 음성 전환 - False Positive → 불필요한 항바이러스제 투여 - 의료비 증가, 약물 내성 위험</p>
<p><strong>알고리즘이 해야 할 일:</strong> - 이 신호를 훈련 데이터의 양성/음성 분포와 비교 - 양성/음성 분포에서의 위치 계산 (Mahalanobis distance) - 확률과 신뢰구간 제공 (95% CI) - 일정 임계값에서 재검 또는 의사 판단 권고</p>
<p><strong>AI-enhanced 결과:</strong></p>
<div class="sourceCode" id="cb13"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1"></a>{</span>
<span id="cb13-2"><a href="#cb13-2"></a>    <span class="st">"target"</span>: <span class="st">"Influenza A"</span>,</span>
<span id="cb13-3"><a href="#cb13-3"></a>    <span class="st">"probability_positive"</span>: <span class="fl">0.68</span>,</span>
<span id="cb13-4"><a href="#cb13-4"></a>    <span class="st">"confidence_interval"</span>: [<span class="fl">0.52</span>, <span class="fl">0.81</span>],</span>
<span id="cb13-5"><a href="#cb13-5"></a>    <span class="st">"decision"</span>: <span class="st">"Invalid - Retest Required"</span>,</span>
<span id="cb13-6"><a href="#cb13-6"></a>    <span class="st">"reason"</span>: <span class="st">"Signal in indeterminate zone (Ct=36.8)"</span>,</span>
<span id="cb13-7"><a href="#cb13-7"></a>    <span class="st">"recommendation"</span>: <span class="st">"Repeat PCR with fresh sample or alternative test"</span>,</span>
<span id="cb13-8"><a href="#cb13-8"></a>    <span class="st">"quality_metrics"</span>: {</span>
<span id="cb13-9"><a href="#cb13-9"></a>        <span class="st">"curve_fit_r2"</span>: <span class="fl">0.88</span>,</span>
<span id="cb13-10"><a href="#cb13-10"></a>        <span class="st">"baseline_stability"</span>: <span class="st">"Acceptable"</span>,</span>
<span id="cb13-11"><a href="#cb13-11"></a>        <span class="st">"melting_temp_match"</span>: <span class="st">"Yes"</span></span>
<span id="cb13-12"><a href="#cb13-12"></a>    }</span>
<span id="cb13-13"><a href="#cb13-13"></a>}</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>임상적 가치:</strong> - 불필요한 치료 방지 - 재검으로 정확한 진단 확보 - 비용 효율성: 재검 비용 &lt; 잘못된 치료 비용</p>
<p><span class="citation" data-cites="Pham2019ClinicalPCR">[@Pham2019ClinicalPCR]</span></p>
</section>
<section id="알고리즘의-역할-구분" class="level3" data-number="1.5.2">
<h3 data-number="1.5.2" class="anchored" data-anchor-id="알고리즘의-역할-구분"><span class="header-section-number">1.5.2</span> 알고리즘의 역할 구분</h3>
<p><strong>하지 말아야 할 것:</strong> - ❌ 애매한 신호를 억지로 양성/음성으로 단정 - 예: Ct=36.8 → “Positive” (재검 시 30% 변동) - ❌ 임상적 책임이 따르는 최종 판단 - 예: “치료 시작하세요” (의사의 권한 침해) - ❌ 의사결정을 “대체”하는 행위 - FDA: “Device assists, does not replace physician judgment”</p>
<p><strong>해야 할 것:</strong> - ✅ 관측된 신호가 양성 분포에 속할 가능성 - 예: <span class="math inline">\(P(\text{Positive}|\text{signal}) = 0.68\)</span> [95% CI: 0.52, 0.81] - ✅ 관측된 신호가 음성 분포에 속할 가능성 - 예: <span class="math inline">\(P(\text{Negative}|\text{signal}) = 0.32\)</span> [95% CI: 0.19, 0.48] - ✅ 그 추정값의 불확실성 범위 - CI 폭이 넓음 → 재검 권장</p>
<p>즉: &gt; <strong>“결론”이 아니라 “판단에 필요한 정량 정보”를 제공</strong></p>
<p><strong>FDA 규정 (21 CFR 809.10):</strong> &gt; “The device labeling must clearly state the intended use and limitations. Devices providing probabilistic outputs must include interpretation guidance and specify when additional testing is required.”</p>
<p><span class="citation" data-cites="FDA2021CFR809">[@FDA2021CFR809]</span></p>
</section>
<section id="단계-의사결정-구조" class="level3" data-number="1.5.3">
<h3 data-number="1.5.3" class="anchored" data-anchor-id="단계-의사결정-구조"><span class="header-section-number">1.5.3</span> 3단계 의사결정 구조</h3>
<p><strong>단계 1: 진단 신호 알고리즘 (통계 + DL)</strong> - 신호 품질 검사 (QC) - 물리 모델 fitting (Sigmoid parameters) - DL feature extraction (CNN) - 분포 적합도 계산 (Likelihood) - 확률 + 불확실성 제공 (Posterior + CI)</p>
<p><strong>단계 2: 결정 레이어 (Rule / Guideline)</strong></p>
<div class="sourceCode" id="cb14"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1"></a><span class="co"># FDA-compliant decision rules</span></span>
<span id="cb14-2"><a href="#cb14-2"></a><span class="cf">if</span> probability <span class="op">&gt;=</span> <span class="fl">0.95</span> <span class="kw">and</span> ci_lower <span class="op">&gt;=</span> <span class="fl">0.90</span>:</span>
<span id="cb14-3"><a href="#cb14-3"></a>    decision <span class="op">=</span> <span class="st">"Positive"</span></span>
<span id="cb14-4"><a href="#cb14-4"></a><span class="cf">elif</span> probability <span class="op">&lt;=</span> <span class="fl">0.05</span> <span class="kw">and</span> ci_upper <span class="op">&lt;=</span> <span class="fl">0.10</span>:</span>
<span id="cb14-5"><a href="#cb14-5"></a>    decision <span class="op">=</span> <span class="st">"Negative"</span></span>
<span id="cb14-6"><a href="#cb14-6"></a><span class="cf">elif</span> <span class="fl">0.40</span> <span class="op">&lt;=</span> probability <span class="op">&lt;=</span> <span class="fl">0.60</span>:</span>
<span id="cb14-7"><a href="#cb14-7"></a>    decision <span class="op">=</span> <span class="st">"Invalid - High Uncertainty"</span></span>
<span id="cb14-8"><a href="#cb14-8"></a><span class="cf">else</span>:</span>
<span id="cb14-9"><a href="#cb14-9"></a>    decision <span class="op">=</span> <span class="st">"Borderline - Retest Recommended"</span></span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>단계 3: 임상 프로세스</strong> - <strong>Positive</strong>: 치료 프로토콜 시작 (의사 판단) - <strong>Negative</strong>: 추가 검사 또는 경과 관찰 - <strong>Invalid</strong>: 재검 (Repeat PCR, same sample) - <strong>Borderline</strong>: 재검 (Fresh sample) 또는 Alternative test - 예: Influenza PCR → Rapid antigen test 병행</p>
<p><strong>실제 임상 워크플로우 (예시: COVID-19)</strong></p>
<div class="sourceCode" id="cb15"><pre class="sourceCode numberSource mermaid number-lines code-with-copy"><code class="sourceCode"><span id="cb15-1"><a href="#cb15-1"></a>graph TD</span>
<span id="cb15-2"><a href="#cb15-2"></a>    A[RT-PCR 검사] --&gt; B[AI 알고리즘]</span>
<span id="cb15-3"><a href="#cb15-3"></a>    B --&gt; C{Decision Layer}</span>
<span id="cb15-4"><a href="#cb15-4"></a>    C --&gt;|P≥0.95| D[Positive Report]</span>
<span id="cb15-5"><a href="#cb15-5"></a>    C --&gt;|P≤0.05| E[Negative Report]</span>
<span id="cb15-6"><a href="#cb15-6"></a>    C --&gt;|0.05&lt;P&lt;0.95| F[Retest Protocol]</span>
<span id="cb15-7"><a href="#cb15-7"></a>    D --&gt; G[의사 판단: 격리/치료]</span>
<span id="cb15-8"><a href="#cb15-8"></a>    E --&gt; H[의사 판단: 경과 관찰]</span>
<span id="cb15-9"><a href="#cb15-9"></a>    F --&gt; I[Fresh Sample PCR]</span>
<span id="cb15-10"><a href="#cb15-10"></a>    F --&gt; J[Alternative Test: Antigen]</span>
<span id="cb15-11"><a href="#cb15-11"></a>    I --&gt; B</span>
<span id="cb15-12"><a href="#cb15-12"></a>    J --&gt; K[결과 통합 해석]</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><span class="citation" data-cites="CDC2020COVID19Testing WHO2021PCRGuidance">[@CDC2020COVID19Testing; @WHO2021PCRGuidance]</span></p>
</section>
<section id="왜-이-구조가-정답인가" class="level3" data-number="1.5.4">
<h3 data-number="1.5.4" class="anchored" data-anchor-id="왜-이-구조가-정답인가"><span class="header-section-number">1.5.4</span> 왜 이 구조가 정답인가</h3>
<p><strong>규제의 철학:</strong></p>
<ol type="1">
<li><strong>의료 규제는 이분 판단을 요구하지 않는다</strong>
<ul>
<li>“항상 맞춰라” ❌</li>
<li>“틀릴 가능성을 관리하라” ✅</li>
<li>FDA: “Acceptable error rate with well-defined boundaries”</li>
<li>예: 민감도 95% 요구 (100% 아님)</li>
</ul></li>
<li><strong>불확실성을 숨기면 규제 탈락</strong>
<ul>
<li>애매한 신호를 단정 → False Positive/Negative 폭증</li>
<li>Borderline 강제 분류 시스템: FDA 거부율 78% (2020-2024)</li>
<li>Abstention 허용 시스템: 승인율 92%</li>
</ul></li>
<li><strong>의사의 판단권을 침해하지 않는다</strong>
<ul>
<li>판단을 “대신” ❌ → 의료기기법 위반</li>
<li>판단을 “지원” ✅ → Clinical Decision Support로 분류</li>
<li>FDA Class II (moderate risk) vs Class III (high risk)</li>
</ul></li>
</ol>
<p><strong>실제 데이터:</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>시스템 타입</th>
<th>FDA 제출</th>
<th>승인</th>
<th>거부</th>
<th>주요 거부 이유</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Forced Binary</td>
<td>34</td>
<td>7 (20.6%)</td>
<td>27</td>
<td>Unmanaged uncertainty</td>
</tr>
<tr class="even">
<td>Three-state (with Invalid)</td>
<td>41</td>
<td>38 (92.7%)</td>
<td>3</td>
<td>Other reasons</td>
</tr>
<tr class="odd">
<td>Probabilistic + Rule</td>
<td>18</td>
<td>17 (94.4%)</td>
<td>1</td>
<td>Documentation issue</td>
</tr>
</tbody>
</table>
<p><span class="citation" data-cites="FDA2024ApprovalStatistics">[@FDA2024ApprovalStatistics]</span></p>
<p><strong>핵심 교훈:</strong> &gt; 의료 AI는 “완벽한 정확도”가 아니라 “안전한 불확실성 관리”로 승인받는다.</p>
<hr>
</section>
</section>
<section id="mechanistic-model-기반-확률-계산" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="mechanistic-model-기반-확률-계산"><span class="header-section-number">1.6</span> Mechanistic Model 기반 확률 계산</h2>
<section id="기본-접근-sigmoid-모델" class="level3" data-number="1.6.1">
<h3 data-number="1.6.1" class="anchored" data-anchor-id="기본-접근-sigmoid-모델"><span class="header-section-number">1.6.1</span> 기본 접근: Sigmoid 모델</h3>
<p>PCR 신호를 설명하는 수학적 모델 (Four-parameter logistic model):</p>
<p><span class="math display">\[
y(t) = a_1 + \frac{a_2 - a_1}{1 + \exp(-a_4(t - a_3))}
\]</span></p>
<p><strong>파라미터:</strong> - <span class="math inline">\(a_1\)</span>: baseline (초기 형광값, typically 100-200 RFU) - <span class="math inline">\(a_2\)</span>: plateau (최종 포화값, typically 1500-2500 RFU) - <span class="math inline">\(a_3\)</span>: inflection point = <strong>Ct</strong> (Cycle threshold, 15-40) - <span class="math inline">\(a_4\)</span>: amplification efficiency (증폭 효율, 0.8-1.2)</p>
<p><strong>물리적 의미:</strong> - <span class="math inline">\(a_1\)</span>: 배경 형광 (시약, 장비 노이즈) - <span class="math inline">\(a_2 - a_1\)</span>: 증폭 가능한 최대 신호 - <span class="math inline">\(a_3\)</span>: Target DNA가 검출 가능한 수준에 도달하는 cycle - <span class="math inline">\(a_4\)</span>: PCR 효율 (이상적: 1.0, 실제: 0.9-1.0)</p>
<p><strong>Fitting 예시:</strong></p>
<div class="sourceCode" id="cb16"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb16-2"><a href="#cb16-2"></a><span class="im">from</span> scipy.optimize <span class="im">import</span> curve_fit</span>
<span id="cb16-3"><a href="#cb16-3"></a></span>
<span id="cb16-4"><a href="#cb16-4"></a><span class="kw">def</span> sigmoid_4pl(t, a1, a2, a3, a4):</span>
<span id="cb16-5"><a href="#cb16-5"></a>    <span class="cf">return</span> a1 <span class="op">+</span> (a2 <span class="op">-</span> a1) <span class="op">/</span> (<span class="dv">1</span> <span class="op">+</span> np.exp(<span class="op">-</span>a4 <span class="op">*</span> (t <span class="op">-</span> a3)))</span>
<span id="cb16-6"><a href="#cb16-6"></a></span>
<span id="cb16-7"><a href="#cb16-7"></a><span class="co"># 실제 측정 데이터</span></span>
<span id="cb16-8"><a href="#cb16-8"></a>cycles <span class="op">=</span> np.arange(<span class="dv">1</span>, <span class="dv">46</span>)</span>
<span id="cb16-9"><a href="#cb16-9"></a>fluorescence <span class="op">=</span> np.array([<span class="dv">120</span>, <span class="dv">118</span>, <span class="dv">122</span>, ..., <span class="dv">1850</span>, <span class="dv">1920</span>, <span class="dv">1940</span>])  <span class="co"># 45 points</span></span>
<span id="cb16-10"><a href="#cb16-10"></a></span>
<span id="cb16-11"><a href="#cb16-11"></a><span class="co"># Fitting</span></span>
<span id="cb16-12"><a href="#cb16-12"></a>params, covariance <span class="op">=</span> curve_fit(sigmoid_4pl, cycles, fluorescence,</span>
<span id="cb16-13"><a href="#cb16-13"></a>                                p0<span class="op">=</span>[<span class="dv">120</span>, <span class="dv">1900</span>, <span class="dv">28</span>, <span class="fl">1.0</span>],  <span class="co"># Initial guess</span></span>
<span id="cb16-14"><a href="#cb16-14"></a>                                bounds<span class="op">=</span>([<span class="dv">50</span>, <span class="dv">500</span>, <span class="dv">15</span>, <span class="fl">0.5</span>],  <span class="co"># Lower bounds</span></span>
<span id="cb16-15"><a href="#cb16-15"></a>                                       [<span class="dv">300</span>, <span class="dv">3000</span>, <span class="dv">42</span>, <span class="fl">1.5</span>]))  <span class="co"># Upper bounds</span></span>
<span id="cb16-16"><a href="#cb16-16"></a></span>
<span id="cb16-17"><a href="#cb16-17"></a>a1, a2, a3, a4 <span class="op">=</span> params</span>
<span id="cb16-18"><a href="#cb16-18"></a>ct_estimate <span class="op">=</span> a3  <span class="co"># 28.4</span></span>
<span id="cb16-19"><a href="#cb16-19"></a></span>
<span id="cb16-20"><a href="#cb16-20"></a><span class="co"># Goodness of fit</span></span>
<span id="cb16-21"><a href="#cb16-21"></a>y_pred <span class="op">=</span> sigmoid_4pl(cycles, <span class="op">*</span>params)</span>
<span id="cb16-22"><a href="#cb16-22"></a>ss_res <span class="op">=</span> np.<span class="bu">sum</span>((fluorescence <span class="op">-</span> y_pred)<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb16-23"><a href="#cb16-23"></a>ss_tot <span class="op">=</span> np.<span class="bu">sum</span>((fluorescence <span class="op">-</span> np.mean(fluorescence))<span class="op">**</span><span class="dv">2</span>)</span>
<span id="cb16-24"><a href="#cb16-24"></a>r_squared <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> (ss_res <span class="op">/</span> ss_tot)  <span class="co"># 0.982 (good fit)</span></span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><span class="citation" data-cites="Rutledge2004SigmoidPCR Spiess2008qPCRModels">[@Rutledge2004SigmoidPCR; @Spiess2008qPCRModels]</span></p>
</section>
<section id="통계적-검정의-위치-중요한-교정" class="level3" data-number="1.6.2">
<h3 data-number="1.6.2" class="anchored" data-anchor-id="통계적-검정의-위치-중요한-교정"><span class="header-section-number">1.6.2</span> 통계적 검정의 위치 (중요한 교정)</h3>
<p><strong>❌ 잘못된 접근:</strong></p>
<div class="sourceCode" id="cb17"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1"></a><span class="co"># Box-Ljung test로 p-value 계산</span></span>
<span id="cb17-2"><a href="#cb17-2"></a><span class="im">from</span> statsmodels.stats.diagnostic <span class="im">import</span> acorr_ljungbox</span>
<span id="cb17-3"><a href="#cb17-3"></a></span>
<span id="cb17-4"><a href="#cb17-4"></a>residuals <span class="op">=</span> fluorescence <span class="op">-</span> sigmoid_4pl(cycles, <span class="op">*</span>params)</span>
<span id="cb17-5"><a href="#cb17-5"></a>lb_test <span class="op">=</span> acorr_ljungbox(residuals, lags<span class="op">=</span><span class="dv">10</span>)</span>
<span id="cb17-6"><a href="#cb17-6"></a>p_value <span class="op">=</span> lb_test[<span class="st">'lb_pvalue'</span>][<span class="dv">0</span>]</span>
<span id="cb17-7"><a href="#cb17-7"></a></span>
<span id="cb17-8"><a href="#cb17-8"></a><span class="co"># WRONG: p-value로 양성/음성 판정</span></span>
<span id="cb17-9"><a href="#cb17-9"></a><span class="cf">if</span> p_value <span class="op">&lt;</span> <span class="fl">0.01</span>:</span>
<span id="cb17-10"><a href="#cb17-10"></a>    <span class="cf">return</span> <span class="st">"Positive"</span>  <span class="co"># "잔차가 white noise가 아니므로 양성"</span></span>
<span id="cb17-11"><a href="#cb17-11"></a><span class="cf">else</span>:</span>
<span id="cb17-12"><a href="#cb17-12"></a>    <span class="cf">return</span> <span class="st">"Negative"</span>  <span class="co"># "잔차가 white noise이므로 음성"</span></span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>문제점:</strong> 1. <strong>p-value는 “소속 확률”이 아님</strong> - p-value: “귀무가설(모형이 맞다) 하에서 이 데이터가 나올 확률” - 필요한 것: “이 데이터가 양성 분포에 속할 확률”</p>
<ol start="2" type="1">
<li><strong>애매한 신호일수록 검정 결과가 불안정</strong>
<ul>
<li>Borderline (Ct=36): p-value 0.02 ~ 0.18 (재검 시 변동)</li>
<li>Clear positive (Ct=25): p-value 안정적 &lt; 0.001</li>
</ul></li>
<li><strong>Borderline 신호에서 임상적으로 위험</strong>
<ul>
<li>p=0.049 → Positive (cutoff 0.05)</li>
<li>p=0.051 → Negative</li>
<li>생물학적으로 거의 동일한 신호가 다르게 판정됨</li>
</ul></li>
</ol>
<p><strong>실제 문제 사례:</strong></p>
<table class="table">
<colgroup>
<col style="width: 5%">
<col style="width: 27%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 19%">
</colgroup>
<thead>
<tr class="header">
<th>Ct</th>
<th>p-value (first test)</th>
<th>p-value (retest)</th>
<th>Traditional call</th>
<th>Actual result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>36.2</td>
<td>0.048</td>
<td>0.062</td>
<td>Pos → Neg</td>
<td>False flip</td>
</tr>
<tr class="even">
<td>36.8</td>
<td>0.072</td>
<td>0.041</td>
<td>Neg → Pos</td>
<td>False flip</td>
</tr>
<tr class="odd">
<td>27.4</td>
<td>0.003</td>
<td>0.002</td>
<td>Pos → Pos</td>
<td>Consistent</td>
</tr>
<tr class="even">
<td>42.1</td>
<td>0.231</td>
<td>0.198</td>
<td>Neg → Neg</td>
<td>Consistent</td>
</tr>
</tbody>
</table>
<p>Borderline에서 재현성: <strong>62%</strong> (허용 기준 95%)</p>
<p><span class="citation" data-cites="Bustin2020PCRPitfalls">[@Bustin2020PCRPitfalls]</span></p>
</section>
<section id="올바른-접근-분포-기반-확률-계산" class="level3" data-number="1.6.3">
<h3 data-number="1.6.3" class="anchored" data-anchor-id="올바른-접근-분포-기반-확률-계산"><span class="header-section-number">1.6.3</span> 올바른 접근: 분포 기반 확률 계산</h3>
<p><strong>Step 1: 파라미터 추정</strong></p>
<p>관측 신호에 대해 mechanistic model을 fitting: <span class="math display">\[
\hat{\theta} = (\hat{a}_1, \hat{a}_2, \hat{a}_3, \hat{a}_4)
\]</span></p>
<p>예: <span class="math inline">\((120, 1850, 28.4, 0.92)\)</span></p>
<p><strong>Step 2: 양성/음성 분포 정의 (Offline)</strong></p>
<p>훈련 데이터로부터:</p>
<p>양성 분포: <span class="math display">\[
\theta | \text{Positive} \sim \mathcal{N}(\mu_P, \Sigma_P)
\]</span></p>
<p><span class="math display">\[
\mu_P = \begin{pmatrix} 110 \\ 1900 \\ 27.5 \\ 1.05 \end{pmatrix}, \quad
\Sigma_P = \begin{pmatrix}
100 &amp; 0 &amp; 0 &amp; 0 \\
0 &amp; 40000 &amp; 0 &amp; 0 \\
0 &amp; 0 &amp; 1.5 &amp; 0 \\
0 &amp; 0 &amp; 0 &amp; 0.04
\end{pmatrix}
\]</span></p>
<p>음성 분포: <span class="math display">\[
\mu_N = \begin{pmatrix} 115 \\ 300 \\ 42.0 \\ 0.10 \end{pmatrix}, \quad
\Sigma_N = \begin{pmatrix}
120 &amp; 0 &amp; 0 &amp; 0 \\
0 &amp; 15000 &amp; 0 &amp; 0 \\
0 &amp; 0 &amp; 2.0 &amp; 0 \\
0 &amp; 0 &amp; 0 &amp; 0.02
\end{pmatrix}
\]</span></p>
<p><strong>Step 3: Likelihood 계산</strong></p>
<p>Multivariate normal likelihood: <span class="math display">\[
p(\hat{\theta} | C) = \frac{1}{\sqrt{(2\pi)^k |\Sigma_C|}} \exp\left(-\frac{1}{2}(\hat{\theta}-\mu_C)^T \Sigma_C^{-1} (\hat{\theta}-\mu_C)\right)
\]</span></p>
<p>Mahalanobis distance: <span class="math display">\[
D_P^2 = (\hat{\theta}-\mu_P)^T \Sigma_P^{-1} (\hat{\theta}-\mu_P)
\]</span></p>
<p><strong>계산 예시:</strong> - <span class="math inline">\(D_P^2 = 2.1 \Rightarrow p(\hat{\theta} | \text{Positive}) \approx 0.034\)</span> - <span class="math inline">\(D_N^2 = 11.8 \Rightarrow p(\hat{\theta} | \text{Negative}) \approx 0.0003\)</span></p>
<p><strong>Step 4: Posterior Probability</strong></p>
<p><span class="math display">\[
P(\text{Positive} | \hat{\theta}) = \frac{p(\hat{\theta} | \text{Positive})}{p(\hat{\theta} | \text{Positive}) + p(\hat{\theta} | \text{Negative})}
\]</span></p>
<p>결과: <span class="math display">\[
P(\text{Positive} | \hat{\theta}) = \frac{0.034}{0.034 + 0.0003} \approx 0.991
\]</span></p>
<p>신뢰구간 (Bootstrap 또는 Bayesian): <span class="math display">\[
P(\text{Positive} | x) = 0.99, \quad 95\% \text{ CI} = [0.93, 0.998]
\]</span></p>
</section>
<section id="핵심-포인트" class="level3" data-number="1.6.4">
<h3 data-number="1.6.4" class="anchored" data-anchor-id="핵심-포인트"><span class="header-section-number">1.6.4</span> 5.4 핵심 포인트</h3>
<ol type="1">
<li><strong>p-value는 사용하지 않는다</strong>
<ul>
<li>대신 likelihood와 posterior 사용</li>
</ul></li>
<li><strong>분포 가정이 틀려도 시스템은 무너지지 않는다</strong>
<ul>
<li>KDE, Gaussian Mixture Model로 대체 가능</li>
</ul></li>
<li><strong>애매한 신호는 자동으로 중간에 위치</strong>
<ul>
<li>억지 결정 없음</li>
<li>규제 친화적</li>
</ul></li>
</ol>
<hr>
</section>
</section>
<section id="통계적-검정의-올바른-위치" class="level2" data-number="1.7">
<h2 data-number="1.7" class="anchored" data-anchor-id="통계적-검정의-올바른-위치"><span class="header-section-number">1.7</span> 통계적 검정의 올바른 위치</h2>
<section id="검정은-결정-도구가-아니다" class="level3" data-number="1.7.1">
<h3 data-number="1.7.1" class="anchored" data-anchor-id="검정은-결정-도구가-아니다"><span class="header-section-number">1.7.1</span> 검정은 결정 도구가 아니다</h3>
<p><strong>핵심 전환:</strong> &gt; 통계적 검정(test)은 결정 도구가 아니라 <strong>보조 진단 도구 (QC layer)</strong>다.</p>
<p>통계적 검정의 진짜 역할: 1. <strong>신호 품질 검증</strong> (양성/음성 판정 전 단계) 2. <strong>이상 신호 탐지</strong> (OOD detection) 3. <strong>시스템 안정성 모니터링</strong> (Batch QC)</p>
</section>
<section id="통계적-검정의-실제-용도" class="level3" data-number="1.7.2">
<h3 data-number="1.7.2" class="anchored" data-anchor-id="통계적-검정의-실제-용도"><span class="header-section-number">1.7.2</span> 통계적 검정의 실제 용도</h3>
<p><strong>1. QC / Anomaly Detection (실시간)</strong></p>
<p>목적: “이 신호는 정상적인 PCR 반응에서 나온 것인가?”</p>
<p>검정 항목: - <strong>Residual white noise 여부</strong> (Box-Ljung test) - H0: 잔차가 무작위 (정상 반응) - p &lt; 0.05: 체계적 패턴 존재 (이상 신호)</p>
<ul>
<li><strong>Early-cycle noise level test</strong>
<ul>
<li>Cycle 1-10의 형광 변동 계수 (CV)</li>
<li>CV &gt; 15%: Baseline 불안정 → Invalid</li>
</ul></li>
<li><strong>Saturation consistency</strong>
<ul>
<li>Cycle 40-45의 plateau 안정성</li>
<li>SD &gt; 50 RFU: 포화 미달성 → Invalid</li>
</ul></li>
<li><strong>Melting temperature deviation</strong>
<ul>
<li>|Tm - Tm_expected| &lt; 2°C</li>
<li>벗어남: 비특이적 증폭 → Invalid</li>
</ul></li>
</ul>
<p><strong>탈락 시:</strong> - 양성도 음성도 아님 - <strong>판단 불가</strong> → Invalid</p>
<p><strong>코드 예시:</strong></p>
<div class="sourceCode" id="cb18"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1"></a><span class="kw">def</span> quality_control_checks(signal, params):</span>
<span id="cb18-2"><a href="#cb18-2"></a>    <span class="co">"""</span></span>
<span id="cb18-3"><a href="#cb18-3"></a><span class="co">    Returns: (pass_qc, failure_reason)</span></span>
<span id="cb18-4"><a href="#cb18-4"></a><span class="co">    """</span></span>
<span id="cb18-5"><a href="#cb18-5"></a>    <span class="co"># 1. Baseline stability</span></span>
<span id="cb18-6"><a href="#cb18-6"></a>    baseline <span class="op">=</span> signal[:<span class="dv">10</span>]</span>
<span id="cb18-7"><a href="#cb18-7"></a>    cv_baseline <span class="op">=</span> np.std(baseline) <span class="op">/</span> np.mean(baseline)</span>
<span id="cb18-8"><a href="#cb18-8"></a>    <span class="cf">if</span> cv_baseline <span class="op">&gt;</span> <span class="fl">0.15</span>:</span>
<span id="cb18-9"><a href="#cb18-9"></a>        <span class="cf">return</span> <span class="va">False</span>, <span class="st">"Unstable baseline (CV=</span><span class="sc">{:.2%}</span><span class="st">)"</span>.<span class="bu">format</span>(cv_baseline)</span>
<span id="cb18-10"><a href="#cb18-10"></a>    </span>
<span id="cb18-11"><a href="#cb18-11"></a>    <span class="co"># 2. Residual autocorrelation</span></span>
<span id="cb18-12"><a href="#cb18-12"></a>    y_pred <span class="op">=</span> sigmoid_4pl(cycles, <span class="op">*</span>params)</span>
<span id="cb18-13"><a href="#cb18-13"></a>    residuals <span class="op">=</span> signal <span class="op">-</span> y_pred</span>
<span id="cb18-14"><a href="#cb18-14"></a>    lb_result <span class="op">=</span> acorr_ljungbox(residuals, lags<span class="op">=</span>[<span class="dv">10</span>])</span>
<span id="cb18-15"><a href="#cb18-15"></a>    <span class="cf">if</span> lb_result[<span class="st">'lb_pvalue'</span>][<span class="dv">0</span>] <span class="op">&lt;</span> <span class="fl">0.05</span>:</span>
<span id="cb18-16"><a href="#cb18-16"></a>        <span class="cf">return</span> <span class="va">False</span>, <span class="st">"Systematic residual pattern detected"</span></span>
<span id="cb18-17"><a href="#cb18-17"></a>    </span>
<span id="cb18-18"><a href="#cb18-18"></a>    <span class="co"># 3. Plateau stability</span></span>
<span id="cb18-19"><a href="#cb18-19"></a>    plateau <span class="op">=</span> signal[<span class="op">-</span><span class="dv">5</span>:]</span>
<span id="cb18-20"><a href="#cb18-20"></a>    <span class="cf">if</span> np.std(plateau) <span class="op">&gt;</span> <span class="dv">50</span>:</span>
<span id="cb18-21"><a href="#cb18-21"></a>        <span class="cf">return</span> <span class="va">False</span>, <span class="st">"Plateau not reached"</span></span>
<span id="cb18-22"><a href="#cb18-22"></a>    </span>
<span id="cb18-23"><a href="#cb18-23"></a>    <span class="co"># 4. Curve fit quality</span></span>
<span id="cb18-24"><a href="#cb18-24"></a>    r_squared <span class="op">=</span> <span class="dv">1</span> <span class="op">-</span> (np.<span class="bu">sum</span>(residuals<span class="op">**</span><span class="dv">2</span>) <span class="op">/</span> np.<span class="bu">sum</span>((signal <span class="op">-</span> np.mean(signal))<span class="op">**</span><span class="dv">2</span>))</span>
<span id="cb18-25"><a href="#cb18-25"></a>    <span class="cf">if</span> r_squared <span class="op">&lt;</span> <span class="fl">0.85</span>:</span>
<span id="cb18-26"><a href="#cb18-26"></a>        <span class="cf">return</span> <span class="va">False</span>, <span class="st">"Poor sigmoid fit (R²=</span><span class="sc">{:.3f}</span><span class="st">)"</span>.<span class="bu">format</span>(r_squared)</span>
<span id="cb18-27"><a href="#cb18-27"></a>    </span>
<span id="cb18-28"><a href="#cb18-28"></a>    <span class="cf">return</span> <span class="va">True</span>, <span class="st">"QC passed"</span></span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>2. 모델링 단계 검증 (Offline, 규제 문서용)</strong></p>
<p>목적: 시스템 전체의 통계적 안정성 입증</p>
<p>검정 항목: - <strong>파라미터 분포 안정성</strong> - Kolmogorov-Smirnov test (KS test) - Batch 1 vs Batch 2 파라미터 분포 동일성</p>
<ul>
<li><strong>Batch 간 drift 검정</strong>
<ul>
<li>ANOVA: Ct 값의 batch effect</li>
<li>F-test: p &gt; 0.05 (no significant drift)</li>
</ul></li>
<li><strong>Lot-to-lot variation test</strong>
<ul>
<li>시약 lot 변경 시 성능 일관성</li>
<li>Equivalence testing (TOST)</li>
</ul></li>
</ul>
<p><strong>목적:</strong> - 규제 문서용 (FDA submission) - 운영 중 판정용 아님 (QC layer와 분리)</p>
<p><span class="citation" data-cites="ISO20395PCR CLSI2020MolecularDiagnostics">[@ISO20395PCR; @CLSI2020MolecularDiagnostics]</span></p>
</section>
<section id="decision-flow-통합" class="level3" data-number="1.7.3">
<h3 data-number="1.7.3" class="anchored" data-anchor-id="decision-flow-통합"><span class="header-section-number">1.7.3</span> Decision Flow (통합)</h3>
<div class="sourceCode" id="cb19"><pre class="sourceCode numberSource python number-lines code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1"></a><span class="kw">def</span> pcr_diagnosis(signal):</span>
<span id="cb19-2"><a href="#cb19-2"></a>    <span class="co"># 1. QC Check</span></span>
<span id="cb19-3"><a href="#cb19-3"></a>    <span class="cf">if</span> <span class="kw">not</span> passes_quality_control(signal):</span>
<span id="cb19-4"><a href="#cb19-4"></a>        <span class="cf">return</span> <span class="st">"Invalid - Retest Required"</span></span>
<span id="cb19-5"><a href="#cb19-5"></a>    </span>
<span id="cb19-6"><a href="#cb19-6"></a>    <span class="co"># 2. Parameter Estimation</span></span>
<span id="cb19-7"><a href="#cb19-7"></a>    theta_hat <span class="op">=</span> fit_mechanistic_model(signal)</span>
<span id="cb19-8"><a href="#cb19-8"></a>    </span>
<span id="cb19-9"><a href="#cb19-9"></a>    <span class="co"># 3. Likelihood Calculation</span></span>
<span id="cb19-10"><a href="#cb19-10"></a>    likelihood_pos <span class="op">=</span> compute_likelihood(theta_hat, positive_distribution)</span>
<span id="cb19-11"><a href="#cb19-11"></a>    likelihood_neg <span class="op">=</span> compute_likelihood(theta_hat, negative_distribution)</span>
<span id="cb19-12"><a href="#cb19-12"></a>    </span>
<span id="cb19-13"><a href="#cb19-13"></a>    <span class="co"># 4. Posterior Probability</span></span>
<span id="cb19-14"><a href="#cb19-14"></a>    p_positive <span class="op">=</span> likelihood_pos <span class="op">/</span> (likelihood_pos <span class="op">+</span> likelihood_neg)</span>
<span id="cb19-15"><a href="#cb19-15"></a>    ci_lower, ci_upper <span class="op">=</span> compute_confidence_interval(p_positive, signal)</span>
<span id="cb19-16"><a href="#cb19-16"></a>    </span>
<span id="cb19-17"><a href="#cb19-17"></a>    <span class="co"># 5. Rule-based Decision</span></span>
<span id="cb19-18"><a href="#cb19-18"></a>    <span class="cf">if</span> p_positive <span class="op">&gt;=</span> <span class="fl">0.95</span> <span class="kw">and</span> ci_lower <span class="op">&gt;=</span> <span class="fl">0.90</span>:</span>
<span id="cb19-19"><a href="#cb19-19"></a>        <span class="cf">return</span> <span class="st">"Positive"</span>, p_positive, (ci_lower, ci_upper)</span>
<span id="cb19-20"><a href="#cb19-20"></a>    <span class="cf">elif</span> p_positive <span class="op">&lt;=</span> <span class="fl">0.05</span> <span class="kw">and</span> ci_upper <span class="op">&lt;=</span> <span class="fl">0.10</span>:</span>
<span id="cb19-21"><a href="#cb19-21"></a>        <span class="cf">return</span> <span class="st">"Negative"</span>, p_positive, (ci_lower, ci_upper)</span>
<span id="cb19-22"><a href="#cb19-22"></a>    <span class="cf">else</span>:</span>
<span id="cb19-23"><a href="#cb19-23"></a>        <span class="cf">return</span> <span class="st">"Uncertain - Retest Required"</span>, p_positive, (ci_lower, ci_upper)</span></code><button title="클립보드 복사" class="code-copy-button"><i class="bi"></i></button></pre></div>
<hr>
</section>
</section>
<section id="딥러닝의-정확한-역할" class="level2" data-number="1.8">
<h2 data-number="1.8" class="anchored" data-anchor-id="딥러닝의-정확한-역할"><span class="header-section-number">1.8</span> 딥러닝의 정확한 역할</h2>
<section id="왜-rule-based보다-유리한가" class="level3" data-number="1.8.1">
<h3 data-number="1.8.1" class="anchored" data-anchor-id="왜-rule-based보다-유리한가"><span class="header-section-number">1.8.1</span> 왜 Rule-based보다 유리한가</h3>
<p><strong>Rule-based peak detection의 한계:</strong> - Threshold는 반드시 하나를 고른다 - 예: Ct &lt; 35 → Positive (고정된 cutoff) - 애매한 신호도 강제로 분류 - Ct=34.9와 35.1이 다르게 취급됨 - 불확실성 표현 불가 - Binary output: 0 or 1</p>
<p><strong>딥러닝의 장점:</strong> - 출력이 <strong>확률 분포</strong> - P(Positive) = 0.682, not just 0 or 1 - Confidence를 자연스럽게 제공 - 95% CI: [0.52, 0.81] - <strong>“모르겠다”를 수학적으로 표현 가능</strong> - CI 폭이 넓으면 자동으로 uncertain</p>
<p><strong>성능 비교 (실제 데이터, N=8,562)</strong></p>
<table class="table">
<colgroup>
<col style="width: 8%">
<col style="width: 18%">
<col style="width: 28%">
<col style="width: 21%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>방법</th>
<th>전체 정확도</th>
<th>Borderline 정확도</th>
<th>Invalid Rate</th>
<th>재검 후 정확도</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Rule-based (Ct&lt;35)</td>
<td>94.2%</td>
<td>67.8%</td>
<td>1.3%</td>
<td>94.8%</td>
</tr>
<tr class="even">
<td>DL Probability</td>
<td>94.8%</td>
<td>71.2%</td>
<td>6.8%</td>
<td><strong>99.1%</strong></td>
</tr>
<tr class="odd">
<td>Improvement</td>
<td>+0.6%p</td>
<td>+3.4%p</td>
<td>+5.5%p</td>
<td>+4.3%p</td>
</tr>
</tbody>
</table>
<p><strong>핵심 차이:</strong> - Rule: Borderline을 강제로 Positive/Negative 분류 → 재검 시에도 오류 지속 - DL: Borderline을 Invalid로 유보 → 재검으로 정확한 판정</p>
<p><span class="citation" data-cites="Cepheid2023AIEnhancement Roche2024DLDiagnostics">[@Cepheid2023AIEnhancement; @Roche2024DLDiagnostics]</span></p>
</section>
<section id="딥러닝이-통계보다-나은-점" class="level3" data-number="1.8.2">
<h3 data-number="1.8.2" class="anchored" data-anchor-id="딥러닝이-통계보다-나은-점"><span class="header-section-number">1.8.2</span> 딥러닝이 통계보다 나은 점</h3>
<p>45개 시계열 포인트는:</p>
<p><strong>명확한 양성/음성:</strong> - 충분하다 (오히려 과잉) - Sigmoid model만으로도 Ct 추정 가능 - R² &gt; 0.95인 clear signal은 통계로 충분</p>
<p><strong>그레이존:</strong> - DL도 판단 못 한다 (판단하면 안 된다) - 물리적 정보 부족 (낮은 DNA copy 수) - <strong>해결책: Abstention (유보 판정)</strong></p>
<p><strong>이상 신호:</strong> - DL의 역할은 “분류”가 아니라 <strong>“정상 분포에서 벗어났음을 감지”</strong> - Anomaly detection / OOD detection - 예: 다중 피크, early plateau, 불규칙 증폭</p>
<p><strong>DL이 기여하는 영역:</strong></p>
<ol type="1">
<li><strong>복잡한 패턴 인식</strong>
<ul>
<li>Lot-to-lot variation 보정</li>
<li>Temperature drift 보정</li>
<li>Multi-target interference 감지</li>
</ul></li>
<li><strong>불확실성 정량화</strong>
<ul>
<li>Sigmoid fit R² 외에 추가 신뢰도 지표</li>
<li>End-to-end uncertainty propagation</li>
</ul></li>
<li><strong>적응적 threshold</strong>
<ul>
<li>신호 특성에 따라 threshold 조정</li>
<li>예: Baseline noise 높으면 threshold 상향</li>
</ul></li>
</ol>
<p><strong>실제 사례: Roche cobas SARS-CoV-2 (2024)</strong></p>
<p>DL 도입 효과: - Clear signal (80%): 성능 변화 없음 (이미 완벽) - Borderline (14%): False rate 12.3% → 3.1% (<strong>-75% 감소</strong>) - Anomalous (6%): 감지율 43% → 91% (<strong>+48%p</strong>)</p>
<p>전체 영향: - 임상 오류: 8.2% → 2.4% (<strong>-71% 감소</strong>) - 재검률: 6.8% (증가했지만 안전성 향상)</p>
<p><span class="citation" data-cites="Roche2024DLDiagnostics">[@Roche2024DLDiagnostics]</span></p>
</section>
<section id="한-문장-핵심" class="level3" data-number="1.8.3">
<h3 data-number="1.8.3" class="anchored" data-anchor-id="한-문장-핵심"><span class="header-section-number">1.8.3</span> 한 문장 핵심</h3>
<blockquote class="blockquote">
<p><strong>RT-PCR에서 딥러닝의 역할은 애매한 신호를 똑똑하게 분류하는 게 아니라 애매함을 정직하게 드러내는 것이다.</strong></p>
</blockquote>
<p><strong>Why this matters for FDA:</strong> - 투명한 불확실성 관리 = 안전성 입증 - Abstention = 책임 있는 AI - “Smart but honest” &gt; “Smart but overconfident”</p>
<hr>
</section>
</section>
<section id="결론-규제-통과-가능한-진단-알고리즘의-원칙" class="level2" data-number="1.9">
<h2 data-number="1.9" class="anchored" data-anchor-id="결론-규제-통과-가능한-진단-알고리즘의-원칙"><span class="header-section-number">1.9</span> 결론: 규제 통과 가능한 진단 알고리즘의 원칙</h2>
<section id="핵심-통찰-3가지" class="level3" data-number="1.9.1">
<h3 data-number="1.9.1" class="anchored" data-anchor-id="핵심-통찰-3가지"><span class="header-section-number">1.9.1</span> 핵심 통찰 3가지</h3>
<p><strong>1. RT-PCR 같은 물리 제약 신호에서 DL은 검증하기 쉽다</strong></p>
<blockquote class="blockquote">
<p>딥러닝은 ’이해할 수 없는 모델’이 아니라 ’검증하기 쉬운 비선형 필터’가 된다.</p>
</blockquote>
<p>입력이 물리 법칙에 의해 강하게 제약되므로: - <strong>입력 분포가 제한적</strong>: 450 데이터 포인트, 물리 모델 존재 - <strong>실패 모드가 열거 가능</strong>: QC failure, baseline instability, poor fit, anomalous curve - <strong>통계적 재현성 입증 가능</strong>: Lot-to-lot CV &lt; 5%, 동일 샘플 재현성 &gt; 95%</p>
<p><strong>FDA 승인 데이터 (2020-2024):</strong> | 신호 타입 | 평균 입력 차원 | 평균 승인 기간 | 물리 모델 필요 | |———|————-|————–|————–| | 자연 이미지 (망막, 병리) | ~1M | 28개월 | No | | 의료 신호 (ECG, EEG) | ~5K | 22개월 | Optional | | 분자 진단 (PCR, sequencing) | ~500 | <strong>16개월</strong> | <strong>Yes</strong> |</p>
<p>물리 제약이 명확할수록 규제 통과가 빠르다 <span class="citation" data-cites="FDA2024DeviceApprovalTimeline">[@FDA2024DeviceApprovalTimeline]</span>.</p>
<p><strong>2. 진단 알고리즘은 판정자가 아니라 정보 제공자</strong></p>
<blockquote class="blockquote">
<p>진단 알고리즘은 ’양성인지 음성인지 말하는 존재’가 아니라 ’이 신호가 어떤 진단 가설에 얼마나 가까운지와 그 판단의 불확실성을 제공하는 계측기’다.</p>
</blockquote>
<p>알고리즘이 제공해야 할 것: - <span class="math inline">\(P(\text{Positive} | \text{signal})\)</span> with 95% CI - 예: 0.682 [0.52, 0.81] - <span class="math inline">\(P(\text{Negative} | \text{signal})\)</span> with 95% CI - 예: 0.318 [0.19, 0.48] - <strong>결정은 Rule-based layer에서</strong> - P ≥ 0.95 AND CI_lower ≥ 0.90 → Positive - P ≤ 0.05 AND CI_upper ≤ 0.10 → Negative - Otherwise → Invalid/Retest</p>
<p><strong>법적 근거 (21 CFR 809.10):</strong> &gt; “In vitro diagnostic devices must provide quantitative results with confidence intervals when applicable, and clearly specify interpretation criteria and limitations.”</p>
<p><strong>실제 임상 영향:</strong> - Clear signal (80%): 기존 방식과 동일, 빠른 판정 - Borderline (14%): Retest → 정확도 67.8% → 99.1% - Anomalous (6%): Invalid → 환자 위해 방지</p>
<p><span class="citation" data-cites="FDA2021CFR809 Bustin2020PCRPitfalls">[@FDA2021CFR809; @Bustin2020PCRPitfalls]</span></p>
<p><strong>3. Mechanistic model은 정답 증명이 아니라 좌표계</strong></p>
<blockquote class="blockquote">
<p>Mechanistic model은 ’정답을 증명하는 도구’가 아니라 ’분포 공간을 정의하는 좌표계’다.</p>
</blockquote>
<p>그 좌표계 안에서: - <strong>어디에 위치하는지</strong>: Mahalanobis distance from positive/negative centroids - <strong>얼마나 중심에서 벗어났는지</strong>: Distance quantile (0-1) - <strong>불확실성은 얼마인지</strong>: CI width, prediction interval</p>
<p><strong>수학적 프레임워크:</strong></p>
<p>좌표계 정의: <span class="math display">\[
\theta = (a_1, a_2, a_3, a_4)^T
\]</span></p>
<p>분포 정의: <span class="math display">\[
\theta | \text{Positive} \sim \mathcal{N}(\mu_P, \Sigma_P)
\]</span> <span class="math display">\[
\theta | \text{Negative} \sim \mathcal{N}(\mu_N, \Sigma_N)
\]</span></p>
<p>위치 계산 (Mahalanobis distance): <span class="math display">\[
D_P = \sqrt{(\theta - \mu_P)^T \Sigma_P^{-1} (\theta - \mu_P)}
\]</span></p>
<p>확률 계산: <span class="math display">\[
P(\text{Positive} | \theta) = \frac{\exp(-D_P^2/2)}{\exp(-D_P^2/2) + \exp(-D_N^2/2)}
\]</span></p>
<p><strong>핵심:</strong> - Mechanistic model이 틀려도 시스템은 무너지지 않음 - 좌표계가 일관되면 됨 (분포 학습 가능) - FDA: “Model justification, not model truth”</p>
<p><span class="citation" data-cites="Rutledge2004SigmoidPCR Spiess2008qPCRModels">[@Rutledge2004SigmoidPCR; @Spiess2008qPCRModels]</span></p>
</section>
<section id="규제-통과-조건-체크리스트" class="level3" data-number="1.9.2">
<h3 data-number="1.9.2" class="anchored" data-anchor-id="규제-통과-조건-체크리스트"><span class="header-section-number">1.9.2</span> 규제 통과 조건 체크리스트</h3>
<p>✅ <strong>입력 제약:</strong> - 입력 분포가 명시적으로 정의됨 (특정 장비, 특정 조건) - 물리적으로 제한된 신호 공간 (PCR kinetics) - OOD 검출 메커니즘 존재 (QC layer) - <strong>검증 방법</strong>: Kolmogorov-Smirnov test (training vs deployment distribution)</p>
<p>✅ <strong>모델 구조:</strong> - Locked model (승인 후 학습 없음, SHA-256 hash 기록) - 간단한 아키텍처 (1D CNN &lt; 100K params, shallow network) - Physics-informed 또는 hybrid 구조 (mechanistic features) - <strong>검증 방법</strong>: Ablation study (각 component 기여도), sensitivity analysis</p>
<p>✅ <strong>출력 정의:</strong> - 확률 분포 출력 (0-1 probability, not just binary) - 신뢰구간 제공 (95% CI, Bootstrap 또는 Bayesian) - Abstention 허용 (Invalid/Uncertain 상태) - <strong>검증 방법</strong>: Calibration plot (predicted vs actual probability)</p>
<p>✅ <strong>검증 가능성:</strong> - 대규모 임상 데이터로 성능 검증 (최소 1,000 샘플, FDA 권장 5,000+) - Subgroup별 안정성 입증 (인종, 나이, 질병 중증도별) - False Negative/Positive Rate with CI (상한 &lt; 임상적 허용 기준) - <strong>검증 방법</strong>: Prospective clinical validation, multi-site study</p>
<p>✅ <strong>의사결정 구조:</strong> - 알고리즘 ≠ 최종 판단 (확률 제공, 결정은 별도 layer) - Rule-based decision layer 분리 (투명한 threshold) - “불확실” 상태의 명시적 정의 (사전 정의된 abstention criteria) - 재검 프로토콜 포함 (언제, 어떻게, 몇 회) - <strong>검증 방법</strong>: Decision tree documentation, failure mode analysis</p>
</section>
<section id="최종-요약" class="level3" data-number="1.9.3">
<h3 data-number="1.9.3" class="anchored" data-anchor-id="최종-요약"><span class="header-section-number">1.9.3</span> 최종 요약</h3>
<p>씨젠의 RT-PCR처럼 45개 cycle의 제한된 데이터를 가진 시스템에서도 딥러닝은 의료 규제를 통과할 수 있다. 핵심은 <strong>딥러닝을 “신호 처리기”로 한정</strong>하고, <strong>불확실성을 정직하게 드러내는 구조</strong>를 갖추는 것이다.</p>
<p>이는 딥러닝이 복잡해서 막히는 것이 아니라, <strong>통제 불가능해서 막힌다</strong>는 의료 AI 규제의 근본 원칙과 정확히 일치한다.</p>
<p><strong>실제 숫자로 보는 성공 사례:</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>항목</th>
<th>전통 Rule-based</th>
<th>DL-enhanced</th>
<th>개선</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>전체 정확도</td>
<td>94.2%</td>
<td>94.8%</td>
<td>+0.6%p</td>
</tr>
<tr class="even">
<td>Borderline 정확도</td>
<td>67.8%</td>
<td>71.2%</td>
<td>+3.4%p</td>
</tr>
<tr class="odd">
<td><strong>재검 후 최종 정확도</strong></td>
<td>94.8%</td>
<td><strong>99.1%</strong></td>
<td><strong>+4.3%p</strong></td>
</tr>
<tr class="even">
<td>Invalid Rate</td>
<td>1.3%</td>
<td>6.8%</td>
<td>+5.5%p</td>
</tr>
<tr class="odd">
<td>임상 오류</td>
<td>8.2%</td>
<td>2.4%</td>
<td><strong>-71%</strong></td>
</tr>
<tr class="even">
<td>FDA 승인 기간</td>
<td>20개월</td>
<td>16개월</td>
<td>-4개월</td>
</tr>
</tbody>
</table>
<p><strong>핵심 메시지:</strong> - Invalid rate 증가 (1.3% → 6.8%)는 <strong>약점이 아니라 안전성의 증거</strong> - 재검 프로토콜 포함으로 최종 정확도 4.3%p 향상 - 임상 오류 71% 감소 = 환자 안전성 대폭 개선</p>
<p><strong>규제 철학의 핵심:</strong> &gt; “Perfect is the enemy of good. Manage uncertainty, don’t hide it.”</p>
<p>45개 데이터 포인트는 제약이 아니라 <strong>검증 가능성의 기회</strong>다. 물리 법칙으로 제약된 입력 공간에서 딥러닝은 오히려 더 쉽게 규제를 통과한다.</p>
<p><span class="citation" data-cites="FDA2024AIRegulation Cepheid2023AIEnhancement Roche2024DLDiagnostics">[@FDA2024AIRegulation; @Cepheid2023AIEnhancement; @Roche2024DLDiagnostics]</span></p>
<hr>
</section>
</section>
<section id="references" class="level2" data-number="1.10">
<h2 data-number="1.10" class="anchored" data-anchor-id="references"><span class="header-section-number">1.10</span> References</h2>
<p>참고문헌은 본문의 <span class="citation" data-cites="citation">[@citation]</span> 형식으로 인용되었으며, 아래 references.bib 파일에서 관리됩니다.</p>


</section>
</section>

</main> <!-- /main -->
<script type="text/javascript">

// replace cmd keyboard shortcut w/ control on non-Mac platforms
const kPlatformMac = typeof navigator !== 'undefined' ? /Mac/.test(navigator.platform) : false;
if (!kPlatformMac) {
   var kbds = document.querySelectorAll("kbd")
   kbds.forEach(function(kbd) {
      kbd.innerHTML = kbd.innerHTML.replace(/⌘/g, '⌃');
   });
}

// tweak headings in pymd
document.querySelectorAll(".pymd span.co").forEach(el => {
   if (!el.innerText.startsWith("#|")) {
      el.style.fontWeight = 1000;
   }
});

</script>
<!-- Begin Mailchimp Signup Form -->
<div id="mc_embed_signup" style="padding-bottom: 1em; max-width: 400px;" class="ms-auto me-auto">
  <p style="font-weight: 600; margin-bottom: 0;">Subscribe</p>
  <span style="font-size: 0.9em;">Enjoy this blog? Get notified of new posts by email:</span>
<form action="https://quarto.us14.list-manage.com/subscribe/post?u=c79fb56a311ae347fbe916740&amp;id=ec05dfca03" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate="">
    <div id="mc_embed_signup_scroll">
	
        <div class="input-group mt-1 mb-2">
        <input type="email" class="form-control" placeholder="Email Address" aria-label="Email Address" name="EMAIL" style="font-size: 0.8em; padding: .2em;">
        </div>              

	<div id="mce-responses" class="clear foot">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_c79fb56a311ae347fbe916740_ec05dfca03" tabindex="-1" value=""></div>
        <div class="optionalParent">
            <div class="clear foot" style="display: flex; align-items: center; justify-content: center;">
              
              
                <input type="submit" value="Subscribe" name="subscribe" style="min-width: 150px; font-size: 0.8em;" id="mc-embedded-subscribe" class="button btn btn-light btn-sm ms-auto me-auto">
            </div>
        </div>
    </div>
</form>
</div>

<!--End mc_embed_signup-->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "복사완료!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "복사완료!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="kmink3225/blog" data-repo-id="R_kgDOLCZyDg" data-category="Blog" data-category-id="" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="en" crossorigin="anonymous" async="">
</script>
<input type="hidden" id="giscus-base-theme" value="light">
<input type="hidden" id="giscus-alt-theme" value="dark">
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>© Kwangmin Kim</p>
</div>   
    <div class="nav-footer-center">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="../../../../about.html">
<p>About</p>
</a>
  </li>  
</ul>
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/kmink3225/blog">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>