---
title: "Introduction to Data Modeling"
subtitle: "Motivation, Database, Data Modeling Steps" 
description: |
  template
categories:
  - Engineering
author: Kwangmin Kim
date: 07/01/2023
format: 
  html:
    page-layout: full
    code-fold: true
    toc: true
    number-sections: true
comments: 
  utterances: 
    repo: ./docs/comments
draft: False
---

<ul class="nav nav-pills" id="language-tab" role="tablist">
  <li class="nav-item" role="presentation">
    <button class="nav-link active" id="Korean-tab" data-bs-toggle="tab" data-bs-target="#Korean" type="button" role="tab" aria-controls="Korean" aria-selected="true">Korean</button>
  </li>
  <li class="nav-item" role="presentation">
    <button class="nav-link" id="English-tab" data-bs-toggle="tab" data-bs-target="#English" type="button" role="tab" aria-controls="knitr" aria-selected="false">English</button>
  </li>

<div class="tab-content" id="language-tabcontent">

<div class="tab-pane fade  show active" id="Korean" role="tabpanel" aria-labelledby="Korean-tab">

::: {#Korean .tab-pane .fade .show .active role="tabpanel" aria-labelledby="Korean-tab"}

# Motivation

데이터 플랫폼은 data를 기반으로 플랫폼 생태계를 관리를 가능하게 하며 유저들의 needs관리와 경향 분석을 자동화할 수 있다. 
구체적으로, 기업에겐 데이터를 수집, 저장, 처리, 분석 및 배포하여 
비즈니스 의사결정 지원, 운영 효율성 향상, 고객 경험 개선, 비용 절감 및 혁신을 촉진하는 통합 시스템으로서 중요한 전략적 자산이 될 수 있다. 

데이터 모델링은 이러한 플랫폼의 성공적인 구현과 운영에 필수적이며, 데이터를 효율적으로 구조화하고 관리하여 데이터의 무결성, 일관성 및 성능을 보장한다. 
따라서 데이터 모델링과 데이터 플랫폼은 상호 보완적으로 작용하여 데이터 중심의 비즈니스 환경을 구축하고 기업의 경쟁력을 강화할 수 있다.

많은 한국의 기업은 미국의 기업보다 data platform의 이해와 도입이 한 박자 늦지만 data platform구축에 많은 노력을 기울이고 있다. 지금 다니고 있는 회사도 한창 data governance와 통계 플랫폼 구축에 힘을 쏟고 있지만 부서와의 의사소통, 체계, 문서 및 지식 부족으로 인해 상당한 난항을 겪고 있다. 이 블로깅을 통해 지식을 체계화하여 실무적 도움과 의사 소통에 도움이 되었으면 좋겠다.

# Data Modeling

* **데이터 모델링(data modeling)**은 데이터를 구조화하고 체계적으로 조직화하는 과정이다.
  * 즉, 데이터베이스 시스템 (Database System)에서 데이터를 어떻게 저장하고, 접근하며, 사용할지를 정의하는 데 중점을 둔다.
* 나는 데이터 모델링이 데이터베이스 설계를 포함하는 상위 개념으로 이해하고 있다. 
* 데이터 모델링이 데이터의 구조와 관계를 정의하는 전체 과정을 포괄한다면
* 데이터 모델링에서 얻은 정보를 바탕으로 데이터베이스 설계를 하여 데이터베이스 시스템의 논리적 및 물리적 구현에 중점을 둔다.
* Data modeling과 DB design은 엄밀히 말하면 다르다곤 하지만 실무자들이나 많은 사람들은 혼용하고 있는 것 같아 보인다.

# Data Modeling의 단계

## 요구사항 수집 및 분석

  * 사용자의 요구사항을 수집하고 분석하여 어떤 데이터가 필요한지, 어떤 데이터 관계가 있는지를 이해한다.  

## 개념적 데이터 모델링 (Conceptual Data Modeling)  

  * 데이터베이스에 저장될 데이터의 개념적 구조를 정의한다. 
  * 개념적 모델은 보통 ERD(Entity-Relationship Diagram)와 같은 도구를 사용하여 엔티티(entity), 속성(attribute), 관계(relationship)를 시각적으로 표현한다.

## 논리적 데이터 모델링 (Logical Data Modeling)
  
  * 개념적 모델을 기반으로 데이터베이스의 논리적 구조를 정의한다. 
  * 이 단계에서는 데이터 타입, 관계, 키(key) 등을 포함한 데이터베이스 스키마를 설계한다.

## 물리적 데이터 모델링 (Physical Data Modeling)

  * 논리적 모델을 실제 데이터베이스 관리 시스템(DBMS)에서 구현 가능한 물리적 구조로 변환한다.
  * 테이블, 인덱스, 파티션 등 데이터베이스의 물리적 요소를 설계한다.

## 데이터베이스 구현 및 관리

  * 물리적 모델을 실제 데이터베이스로 구현하고, 이를 유지 보수하며, 성능을 최적화한다.

앞으로, Data Modeling의 단계를 구체적으로 이해하여 실무에 적용할 수 있는 염감을 얻도록 해보자.


:::
</div>

<div class="tab-pane fade" id="English" role="tabpanel" aria-labelledby="English-tab">

::: {#English .tab-pane .fade role="tabpanel" aria-labelledby="English-tab"}

:::


</div>


# Go to Blog Content List

[Blog Content List](../../content_list.qmd)  
[Engineering Content List](../../Engineering/guide_map/index.qmd)