---
title: Content List, Data Governance 
subtitle: Data Governance 
description: | 
  Data Governance Contents List
categories:
  - Data Governance
author: Kwangmin Kim
date: 01/01/2200
draft: false
format: 
  html:
    toc: true
    number-sections: True
    code-fold: true
    page-layout: full
execute: 
  warning: false
  message: false
---

## Data Governance


* 2024-08-01, [Data Governance Basic Concepts, 거버넌스 기본 개념](../1.basis.qmd)

## Process

* 2024-08-02, [Task Process, 업무 절차](../2.task_process.qmd)

## Data Architecture

* 2024-08-03, [Data Architecture, 구조관리](../3.architetucre.qmd)
* 0000-00-00, [Data Pipeline Design, 파이프라인 설계]
* 0000-00-00, [Data Storage, 저장소 관리]

### Data Governance Frameworks

* 0000-00-00, [Data Management Policy, 데이터 관리 정책]
* 0000-00-00, [Data Stewardship Model, 데이터 관리 모델]

### Data Model

* 2024-08-04, [Data Model Basic Concept](../4-0.data_model.qmd)
* 2024-08-05, [Data Model ()](../4-.architetucre.qmd)
* 2024-08-06, [Data Model ()](../4-.architetucre.qmd)
* 2024-08-07, [Data Model ()](../4-.architetucre.qmd)
* 2024-08-08, [Data Model ()](../4-.architetucre.qmd)
* 2024-08-09, [Data Model ()](../4-.architetucre.qmd)
* 2024-08-10, [Data Model ()](../4-.architetucre.qmd)
* 2024-08-11, [Data Model ()](../4-.architetucre.qmd)

### Data Standardization

* 0000-00-00, [Data Standardization]

### Data Quality

* 0000-00-00, [Data Quality Control Process, 데이터 품질 절차]
* 0000-00-00, [Data Quality Measurement, 데이터 품질 측정]
* 0000-00-00, [Data Validation, 데이터 품질 검증]

### etc.

* 0000-00-00, [Data Governance Solutions, 데이터 관리 솔루션]
* 0000-00-00, [Metadata Management, 메타데이터 관리]
* 0000-00-00, [Data Integration, 데이터 통합]
* 0000-00-00, [Data Security, 데이터 보안]



## Development Environment Setting

### WSL2

* 2023-05-01, [Introduction & Installation](../WSL/01.wsl-install.qmd)
* 2023-05-01, [Frequently Used Linux Command](../Linux/01.linux_comands.qmd)
* 2024-01-25, [Linux_Error_Fix_rm_cannot_remove_files_busy](../Linux/rm_cannot_remove_files.qmd)

### Docker

* 2023-05-01, [Introduction & Installation](../Docker/01.docker_install.qmd)

### VS code

* 2023-05-01, [Introduction & Installation](../VScode/01.vscode_install.qmd)

### Conda

* 2023-05-01, [Introduction & Installation](../Conda/01.conda_install.qmd)

### Git

* 2023-05-01, [Introduction & Installation](../Git/01.git_install.qmd)

## Documentation

### Dynamic Documentation

* 2023-01-19, [Quarto](https://quarto.org/docs/get-started/)
* 2023-01-19, [xaringan[R]](https://github.com/yihui/xaringan)
* 2023-01-19, [Bookdown[R]](https://bookdown.org/yihui/bookdown/get-started.html)
* 2023-01-19, [DISTL](https://decile-team-distil.readthedocs.io/en/latest/index.html)
* 2023-01-26, [Sphinx[Python]](https://www.sphinx-doc.org/en/master/)

### Diagrams

* 2023-05-01, [Quarto & Diagrams](https://quarto.org/docs/authoring/diagrams.html)
* 2023-05-01, [Graphiz Gallery](https://graphviz.org/gallery/)
* 2023-05-01, [Mermaid Gallery](https://mermaid.js.org/#/)

## AWS Cloud

Coursera Course: AWS Fundamentals

* 2023-03-09, [Computing and Networking](../2023-03-02_aws/computing_networking.qmd)
* 2023-03-12, [Storage and Database](../2023-03-02_aws/storage_database.qmd)
* 2023-03-26, [Monitoring and SharedResponsibility](../2023-03-02_aws/monitoring_sharedresponsibility.qmd)
* 2023-04-05, [Infrastructure Security](../2023-03-02_aws/infra_security.qmd)

## Azure Cloud

## GCP

## python

* 2023-06-01, [Package Management: requirements.txt](../Python/package_management.qmd)
* 2023-07-01, [Pathlib Library: File System Path Management](../Python/pathlib.qmd)

## Web

* 2023-05-01, [HTTP Methods](../web/http_method.qmd)

## Apache Airflow

* 2023-05-01, [Introduction](../airflow/01.intro.qmd)
* 2023-05-01, [Airflow Environment Setting](../airflow/02.env_setting.qmd)
* 2023-05-01, [Operator Basics](../airflow/03.operator_basic.qmd)
* 2023-05-01, [Python Operators](../airflow/04.python_operator.qmd)
* 2023-05-01, [Template Variable](../airflow/05.template_variable.qmd)
* 2023-05-01, [Data Share](../airflow/06.data_share.qmd)
* 2023-05-01, [Task Handling - Advanced](../airflow/07.task_handling.qmd)
* 2023-05-01, [More Operators](../airflow/08.more_operators.qmd)
* 2023-05-10, [Connection & Hook](../airflow/09.connection_hook.qmd)
* 2023-05-10, [Sensor](../airflow/10.sensor.qmd)
* 2023-05-10, [More Airflow Functions](../airflow/11.airflow_functions.qmd)
* 2023-05-10, [Operate WebApp Using Rshiny](../airflow/11.airflow_functions.qmd)

## Apache Spark

## Data Modeling



## Front End

## Back End

## Public data

* 2024-01-01, [Public Data Centers](../public_data/index.qmd)