---
title: "Deep Learning Content List"
subtitle: Deep Learning Content List
description: |
  
categories:
  - Deep Learning
author: Kwangmin Kim
date: 05/01/2023
format: 
  html:
    page-layout: full
    code-fold: true
    toc: true
    number-sections: true
draft: False
---

## RAG

### Intro
1.  [intro rag](./00-Intro/1.intro_rag.qmd)
1.  [settings](./00-Intro/2-0.settings.qmd)
1.  [settings api issue](./00-Intro/2-1.settings_api_issue.qmd)
1.  [settings LangSmith](./00-Intro/2-2.settings_LangSmith.qmd)
1.  [settings VScode JASON](./00-Intro/2-3.settings_VScode_JASON.qmd)
1.  [LangChain intro](./00-Intro/3-0.LangChain_intro.qmd)

### Basic
1.  [01-OpenAI-APIKey](./01-Basic/01-OpenAI-APIKey.ipynb)
1.  [02-OpenAI-LLM](./01-Basic/02-OpenAI-LLM.ipynb)
1.  [03-LCEL](./01-Basic/03-LCEL.Ipynb)
1.  [04-LCEL-Advanced](./01-Basic/04-LCEL-Advanced.ipynb)
1.  [05-Runnable](./01-Basic/05-Runnable.ipynb)

### Prompt
1.  [01-PromptTemplate](./02-Prompt/01-PromptTemplate.ipynb)
1.  [02-FewShotTemplates](./02-Prompt/02-FewShotTemplates.ipynb)
1.  [03-LangChain-Hub](./02-Prompt/03-LangChain-Hub.ipynb)
1.  [04-Personal-Prompts](./02-Prompt/04-Personal-Prompts.ipynb)
1.  [05-ChatPromptTemplate](./02-Prompt/05-ChatPromptTemplate.ipynb)

### Output Parser
1.  [01-PydanticOuputParser](./03-OutputParser/01-PydanticOuputParser.ipynb)
1.  [02-CommaSeparatedListOutputParser](./03-OutputParser/02-CommaSeparatedListOutputParser.ipynb)
1.  [03-StructuredOutputParser](./03-OutputParser/03-StructuredOutputParser.ipynb)
1.  [04-JsonOutputParser](./03-OutputParser/04-JsonOutputParser.ipynb)
1.  [05-PandasDataFrameOutputParser](./03-OutputParser/05-PandasDataFrameOutputParser.ipynb)
1.  [06-DatetimeOutputParser](./03-OutputParser/06-DatetimeOutputParser.ipynb)
1.  [07-EnumOutputParser](./03-OutputParser/07-EnumOutputParser.ipynb)
1.  [08-OutputFixingParser](./03-OutputParser/08-OutputFixingParser.ipynb)

### Model
1.  [01-Chat-Models](./04-Model/01-Chat-Models.ipynb)
1.  [02-Cache](./04-Model/02-Cache.ipynb)
1.  [03-ModelSerialization](./04-Model/03-ModelSerialization.ipynb)
1.  [04-TokenUsage](./04-Model/04-TokenUsage.ipynb)
1.  [05-Google-Generative-AI](./04-Model/05-Google-Generative-AI.ipynb)
1.  [06-HuggingFace-Endpoint](./04-Model/06-HuggingFace-Endpoint.ipynb)
1.  [07-HuggingFace-Local](./04-Model/07-HuggingFace-Local.ipynb)
1.  [08-Huggingface-Pipelines](./04-Model/08-Huggingface-Pipelines.ipynb)
1.  [09-Ollama](./04-Model/09-Ollama.ipynb)
1.  [10-GPT4ALL](./04-Model/10-GPT4ALL.ipynb)
1.  [11-Gemini-Video](./04-Model/11-Gemini-Video.ipynb)

### Memory
1.  [01-ConversationBufferMemory](./05-Memory/01-ConversationBufferMemory.ipynb)
1.  [02-ConversationBufferWindowMemory](./05-Memory/02-ConversationBufferWindowMemory.ipynb)
1.  [03-ConversationTokenBufferMemory](./05-Memory/03-ConversationTokenBufferMemory.ipynb)
1.  [04-ConversationEntityMemory](./05-Memory/04-ConversationEntityMemory.ipynb)
1.  [05-ConversationKnowledgeGraph](./05-Memory/05-ConversationKnowledgeGraph.ipynb)
1.  [06-ConversationSummary](./05-Memory/06-ConversationSummary.ipynb)
1.  [07-VectorStoreRetrieverMemory](./05-Memory/07-VectorStoreRetrieverMemory.ipynb)
1.  [08-LCEL-add-memory](./05-Memory/08-LCEL-add-memory.ipynb)
1.  [09-Memory-using-SQLite](./05-Memory/09-Memory-using-SQLite.ipynb)
1.  [10-Conversation-With-History](./05-Memory/10-Conversation-With-History.ipynb)

### Document Loader
1.  [00-Document-Loader](./06-DocumentLoader/00-Document-Loader.ipynb)
1.  [01-PDF-Loader](./06-DocumentLoader/01-PDF-Loader.ipynb)
1.  [02-HWP-Loader](./06-DocumentLoader/02-HWP-Loader.ipynb)
1.  [03-CSV-Loader](./06-DocumentLoader/03-CSV-Loader.ipynb)
1.  [04-Excel-Loader](./06-DocumentLoader/04-Excel-Loader.ipynb)
1.  [05-Word-Loader](./06-DocumentLoader/05-Word-Loader.ipynb)
1.  [06-PowerPoint-Loader](./06-DocumentLoader/06-PowerPoint-Loader.ipynb)
1.  [07-WebBase-Loader](./06-DocumentLoader/07-WebBase-Loader.ipynb)
1.  [08-TXT-Loader](./06-DocumentLoader/08-TXT-Loader.ipynb)
1.  [09-JSON-Loader](./06-DocumentLoader/09-JSON-Loader.ipynb)
1.  [10-Arxiv-Loader](./06-DocumentLoader/10-Arxiv-Loader.ipynb)
1.  [11-Directory-Loader](./06-DocumentLoader/11-Directory-Loader.ipynb)
1.  [12-UpstageLayoutAnalysisLoader](./06-DocumentLoader/12-UpstageLayoutAnalysisLoader.ipynb)
1.  [13-Llamaparser](./06-DocumentLoader/13-Llamaparser.ipynb)

### Text Splitter
1.  [01-CharacterTextSplitter](./07-TextSplitter/01-CharacterTextSplitter.ipynb)
1.  [02-RecursiveCharacterTextSplitter](./07-TextSplitter/02-RecursiveCharacterTextSplitter.ipynb)
1.  [03-TokenTextSplitter](./07-TextSplitter/03-TokenTextSplitter.ipynb)
1.  [04-SemanticChunker](./07-TextSplitter/04-SemanticChunker.ipynb)
1.  [05-CodeSplitter](./07-TextSplitter/05-CodeSplitter.ipynb)
1.  [06-MarkdownHeaderTextSplitter](./07-TextSplitter/06-MarkdownHeaderTextSplitter.ipynb)
1.  [07-HTMLHeaderTextSplitter](./07-TextSplitter/07-HTMLHeaderTextSplitter.ipynb)
1.  [08-RecursiveJsonSplitter](./07-TextSplitter/08-RecursiveJsonSplitter.ipynb)

### Embeddings
1.  [01-OpenAIEmbeddings](./08-Embeddings/01-OpenAIEmbeddings.ipynb)
1.  [02-CacheBackedEmbeddings](./08-Embeddings/02-CacheBackedEmbeddings.ipynb)
1.  [03-HuggingFaceEmbeddings](./08-Embeddings/03-HuggingFaceEmbeddings.ipynb)
1.  [04-UpstageEmbeddings](./08-Embeddings/04-UpstageEmbeddings.ipynb)
1.  [05-OllamaEmbeddings](./08-Embeddings/05-OllamaEmbeddings.ipynb)
1.  [06-llamacpp](./08-Embeddings/06-llamacpp.ipynb)
1.  [07-GPT4ALL](./08-Embeddings/07-GPT4ALL.ipynb)

### Vector Store
1.  [01-Chroma](./09-VectorStore/01-Chroma.ipynb)
1.  [02-FAISS](./09-VectorStore/02-FAISS.ipynb)
1.  [03-Pinecone](./09-VectorStore/03-Pinecone.ipynb)

### Retriever
1.  [00-Retriever](./10-Retriever/00-Retriever.ipynb)
1.  [01-VectorStoreRetriever](./10-Retriever/01-VectorStoreRetriever.ipynb)
1.  [02-MultiQueryRetriever](./10-Retriever/02-MultiQueryRetriever.ipynb)
1.  [03-ContextualCompressionRetriever](./10-Retriever/03-ContextualCompressionRetriever.ipynb)
1.  [04-EnsembleRetriever](./10-Retriever/04-EnsembleRetriever.ipynb)
1.  [05-SelfQueryRetriever](./10-Retriever/05-SelfQueryRetriever.ipynb)
1.  [06-WebResearchRetriever](./10-Retriever/06-WebResearchRetriever.ipynb)
1.  [07-ParentDocumentRetriever](./10-Retriever/07-ParentDocumentRetriever.ipynb)
1.  [08-HYDE](./10-Retriever/08-HYDE.ipynb)
1.  [09-Flare](./10-Retriever/09-Flare.ipynb)
1.  [10-TimeWeightedVectorStoreRetriever](./10-Retriever/10-TimeWeightedVectorStoreRetriever.ipynb)
1.  [11-DocumentCompressor](./10-Retriever/11-DocumentCompressor.ipynb)

### Reranker
1.  [01-Cross-Encoder-Reranker](./11-Reranker/01-Cross-Encoder-Reranker.ipynb)
1.  [02-Cohere-Reranker](./11-Reranker/02-Cohere-Reranker.ipynb)
1.  [03-Jina-Reranker](./11-Reranker/03-Jina-Reranker.ipynb)
1.  [04-FlashRank-Reranker](./11-Reranker/04-FlashRank-Reranker.ipynb)

### RAG
1.  [01-Naive-RAG](./12-RAG/01-Naive-RAG.ipynb)
1.  [02-Stuff-RAG](./12-RAG/02-Stuff-RAG.ipynb)
1.  [03-MapReduce-RAG](./12-RAG/03-MapReduce-RAG.ipynb)
1.  [04-Refine-RAG](./12-RAG/04-Refine-RAG.ipynb)
1.  [05-MapRerank-RAG](./12-RAG/05-MapRerank-RAG.ipynb)
1.  [06-Agent-RAG](./12-RAG/06-Agent-RAG.ipynb)
1.  [07-SelfRAG](./12-RAG/07-SelfRAG.ipynb)
1.  [08-CorrectiveRAG](./12-RAG/08-CorrectiveRAG.ipynb)