---
title: "Data Governance Study - Data Domain Standardization"
subtitle: "데이터 표준 관리: 도메인 표준화"
description: "이 블로그 포스트에서는 데이터 표준 도메인의 개념, 목적, 구성 요소를 상세히 설명한다. 도메인 그룹, 도메인, 인포타입, DBMS별 데이터 타입 등 주요 구성 요소를 소개하고, 날짜, 명칭, 내용, 수량, 율, 금액, 번호, 코드, 분류 등 다양한 도메인 그룹과 그 특성을 설명한다. 데이터 품질 향상과 일관성 있는 데이터 구조 설계를 위한 필수 지식을 담고 있어, 데이터 모델러, 데이터베이스 관리자, 그리고 데이터 거버넌스 담당자에게 유용한 정보를 제공한다."
author: Kwangmin Kim
categories:
  - Data Governance
date: 2024-08-13
format: 
  html:
    toc: true  
    code-fold: true
    code-copy: true
    code-overflow: wrap
    number-sections: true
    number-depth: 4
    grid:
      sidebar-width: 200px
      body-width: 1150px
      margin-width: 300px
---

# Data Standard Governance > Data Standard Domain

## 데이터 표준 도메인이란?

* 비즈니스적으로 의미 있고 데이터의 성격을 분류한 것으로 동일한 형식을 가진 집합을 도메인이라 하며, 하나의 용어는 하나의 도메인만 지정한다.
* 동일한 형식을 가진 데이터에 대해서 같은 도메인을 적용함으로써 속성의 의미 및 데이터의 범위를 명확히 할 수 있고 컬럼에 대한 일관적인 관리가 가능하다
    * 데이터의 형식, 길이, 허용 가능한 값의 범위 등을 명시
* 표준 단어 조합의 마지막에 위치하는 분류단어(도메인성) 단어가 도메인의 후보가 된다.
* 예시
    * 표준 단어 (주제어): 장기
    * 표준 단어 (수식어): 대여
    * 표준 단어 (분류단어): **금액**
    * 표준 용어 : 장기대여금액
    * 데이터 모델 (속성명): 장기대여금액 with datatype = NUMBER(10)
    * **도메인**: **금액**N10

### 목적

* 동일한 형식을 가진 데이터에 대해서 같은 도메인을 적용함으로써 속성의 의미 및 유효한 데이터범위를 명확히 할 수 있고, 칼럼에 대한 일관적인 관리가 가능하다
* 동일한 도메인을 사용하는 칼럼의 속성 성격을 변경하고자 할 때 도메인만을 변경함으로써 데이터 타입 및 길이를 동시에 부여하여 변경할 수 있다


### 표준 도메인 관리 체계

```{dot}
graph ER {
    rankdir=LR;
    fontname="Helvetica,Arial,sans-serif"
    node [shape=box, fontname="Helvetica,Arial,sans-serif"]
    edge [fontname="Helvetica,Arial,sans-serif"]

    a0 [shape=box, label="Domain Group"];
    a1 [shape=box, label="Domain"];
    a2 [shape=box, label="Info Type"];
    
    a0 -- a1 [label="1:N", headlabel="N", taillabel="1", dir=both, arrowhead=dot, arrowtail=none];
    a1 -- a2 [label="1:N", headlabel="N", taillabel="1", dir=both, arrowhead=dot, arrowtail=none];
}
```

* 도메인그룹 (Domain Group) : 도메인 그룹은 성격이 유사한 도메인들을 그룹화 해서 관리하는 관리 단위이며, 예를 들면 금액, 날짜, 내용, 율 등의 도메인 그룹이 존재하며, 금액 도메인 그룹의 하위에는 금액, 외화금액,세액 등의 도메인이 존재 한다
* 도메인 (Domain): 도메인은 데이터 값의 범위를 컬럼(속성)의 특성에 따라 분류한 것이므로 업무적으로 또는 비지니스적으로 의미가 있는 도메인명을 부여해야 하며, 표준단어를 사용하여 명명한다.
* 인포타입 (Info Type): 인포타입은 Information Type의 약어로, 해당 도메인에서 사용할 수 있는 데이터 타입과 길이가 결합된 형태로 속성이 가질 수 있는 데이터 타입과 길이를 나타낸다
* DBMS별 데이터 타입 (Data Type): 표준 인포타입을 정의한 뒤에는 각 DBMS의 특성에 적합한 데이터 타입을 정의한다. DBMS는 다양한 제약 사항이 존재하기 때문에 데이터베이스를 설계할 DBMS의 특성도 반영해야 한다. 따라서 DBMS별 인포타입을 정의하고 이는 전사 표준 인포타입과 매핑 정보를 유지한다.

### 도메인 그룹

* 예를 들어, 회사의 전사 도메인 그룹은 9개 도메인 그룹으로 관리한다고 하면 도메인은 다음과 같이 관리 될 수 있다.
* [도메인 그룹 – 도메인 – 인포타입 – DBMS별 데이터 타입] 예시 

| 도메인그룹 | 도메인 | 인포타입 | DBMS별 데이터 타입 ||  예시 |
|-----|----|-----|---------|---|---------|
| | | | **데이터 타입** | **길이** | |
| 날짜 | 일자 | 일자VC8 | VARCHAR2 | 8 | 대손처리 <u style="color:red;">일자</u> |
| 날짜 | 일시 | 일시VC16 | VARCHAR2 | 16 | 대여시작 <u style="color:red;">일시</u> |
| 명 | 명 | 명VC30 | VARCHAR2 | 30 | 송금정비업체 <u style="color:red;">명</u> |
| 명 | 성명 | 성명VC10 | VARCHAR2 | 10 | 담당자 <u style="color:red;">성명</u> |
| 내용 | 내용 | 내용VC200 | VARCHAR2 | 200 | 수리요청 <u style="color:red;">내용</u> |
| 수 | 수 | 수N9 | NUMBER | 4 | 에어백보유 <u style="color:red;">수</u> |
| 수 | 건수 | 건수N4 | NUMBER | 4 | 신청 <u style="color:red;">건수</u> |
| 수 | 수량 | 수량N4 | NUMBER | 4 | 신품출고 <u style="color:red;">수량</u> |
| 율 | 이율 | 이율N5,3 | NUMBER | 5,3 | 연체 <u style="color:red;">이율</u> |
| 율 | 금리 | 금리N5,2 | NUMBER | 5,2 | 적용 <u style="color:red;">금리</u> |
| 금액 | 금액 | 금액N10 | NUMBER | 10 | 정산승인 <u style="color:red;">금액</u> |
| 금액 | 잔액 | 잔액N10 | NUMBER | 10 | 매출 <u style="color:red;">잔액</u> |
| 번호 | 고객번호 | 법인고객번호 | VARCHAR2 | 9 | 법인고객<u style="color:red;">번호</u> |
| 번호 | 법인등록번호 | 법인등록번호 | VARCHAR2 | 13 | 협력업체 법인등록<u style="color:red;">번호</u> |
| 코드 | 구분코드 | 가족관계유형코드 | VARCHAR2 | 5 | 지점 시도구분<u style="color:red;">코드</u> |
| 분류 | 여부 | 여부VC1 | VARCHAR2 | 1 | 신규사업MT <u style="color:red;">여부</u> |

* NUMBER(5,3)은 다음을 의미
    * 총 5자리의 숫자를 저장
    * 그 중 3자리는 소수점 이하 숫자
    * 결과적으로 소수점 앞에는 2자리의 숫자만 올 수 있다.
    * 예시,
        * 12.345 (유효)
        * 1.234 (유효)
        * 0.123 (유효)
        * 123.45 (무효 - 소수점 이상 자릿수 초과)
        * 1.2345 (무효 - 소수점 이하 자릿수 초과)

### 표준 도메인 유형

* 표준 도메인 구성 요소 
    * 범위형 도메인: 속성(컬럼)에 허용되는 데이터 값을 데이터의 유형과 길이로 범위를 제한    
    * 열거형 도메인: 속성(컬럼)에 허용되는 데이터 값을 정의된 범위 내에서 구체적으로 열거 또는 목록화하여 범위를 제한
    * 예시

    | 도메인 유형 | 도메인그룹 | 정의 | 도메인 예시 |
    |-----|-----|-------------|-------------|
    | 범위형 도메인 | 날짜 | • 특정 사건이 일어난 시점 또는 시점과 시점간의 정해진 기간을 표현하기 위한 도메인 | 일자, 일시, 년도, 년월, 월, 일, 시각, 시분, 분기, 반기 등 |
    | 범위형 도메인 | 명칭 | • 문자 형식으로 객체에 대한 식별을 표현하기 위한 도메인 | 명, 성명, 영문성명, 주소, 우편번호주소, 상세주소, 이메일주소 등 |
    | 범위형 도메인 | 내용 | • 서술 형식의 상세 내용을 자유 형식의 텍스트로 표현하기 위한 도메인 | 내용 |
    | 범위형 도메인 | 수량 | • 객체의 개수나 양을 수로써 표현하기 위한 도메인<br>• 일반적인 측량 단위도 포함됨 | 수, 일수, 개월수, 매수, 좌수, 건수, 량, 평점, 연령, 면적, 평형 등 |
    | 범위형 도메인 | 율 | • 비율을 수로 표현하기 위한 도메인 | 율, 이율, 이자율, 지분율, 할인율 등 |
    | 범위형 도메인 | 금액 | • 화폐의 가치를 수로 표현하기 위한 도메인 | 금액, 잔액, 차액, 보증금, 수수료, 할인료, 보험료 등 |
    | 범위형 도메인 | 번호 | • 각 자리 별 특정 의미를 가지거나 체계를 가지고 관리되어야 하는 속성을 정의하기 위한 도메인<br>• 용어 별 고유의 번호 도메인을 부여 | 전사고객번호, 계좌번호, 직원번호, 단말번호, 거래번호, 법인등록번호, 일련번호 등 |
    | 열거형 도메인 | 코드 | • 코드화 하여 관리되는 속성을 정의하기 위한 도메인 | 그룹내기관코드, 거래상태코드 등 |
    | 열거형 도메인 | 분류 | • 상반된 상태의 값을 갖는 속성을 정의하기 위한 도메인 | 여부, 유무 |

### 표준 도메인 사전 원칙

#### 일관성과 표준화

* 데이터 표준 도메인은 비즈니스적으로 의미 있고 동일한 형식을 가진 데이터 집합을 체계적으로 관리하기 위한 기준이다.
* 동일한 속성 유형에는 일관된 도메인을 적용하여 데이터 품질과 재사용성을 높이고, 중복을 방지한다.

#### 정합성과 무결성

* 하나의 용어는 하나의 도메인만 지정하여 중복을 방지하고, 속성의 형식과 길이, 유효값 범위를 명확히 정의함으로써 데이터 품질을 보장한다.
* 도메인은 업무적·기술적 요구사항을 동시에 충족해야 하며, 데이터 형식, 길이, 허용값 등을 명확히 규정해야 한다.
* 허용된 값의 범위를 명확히 정의하여 데이터 무결성을 보장하고, 변경 시 정합성을 유지해야 한다.

#### 유연성과 확장성

* 도메인은 도메인 그룹, 도메인, 인포타입, DBMS별 데이터 타입의 계층 구조로 체계화되어 효율적인 변경 관리가 가능하다.
* 새로운 데이터 요구사항에 유연하게 대응할 수 있도록 설계하며, 시스템 변경에도 쉽게 확장될 수 있어야 한다.

#### 관리와 유지보수

* 도메인은 지속적으로 관리·개선되며, 명명 규칙과 데이터 타입을 전사적으로 표준화해야 한다.
* 변경 이력을 추적하여 체계적인 데이터 품질 관리와 유지보수를 보장한다.

### 표준 도메인 세부 사항

#### 날짜 도메인 그룹

* [날짜] 도메인그룹은 특정 사건이 일어난 시점 또는 시점과 시점간의 정해진 기간을 표현하기 위한 도메인들을 그룹화하여 관리한다.

| 도메인 | 설명 | 데이터타입 | 길이 | 유효값 범위 | 예시 |
|-----|----------|-----|---|-------------|--------|
| 일 | DD형태의 데이터 값을 갖는 도메인 | VARCHAR2 | 2 | 01~31 | 계약시작 일 |
| 시각 | HHMISS 형태의 시각을 나타내는 도메인 | VARCHAR2 | 6 | 000000~235959 | 차량사용시작 시각 |
| 일자 | YYYYMMDD형태의 데이터 값을 갖는 도메인 | VARCHAR2 | 8 | 00010101 ~ 99991231 | 계약해지 일자 |
| 생년월일 | YYMMDD형태의 데이터 값을 갖는 도메인 | VARCHAR2 | 6 | 000101 ~ 991231 | 회원 생년월일 |
| 일시 | YYYYMMDDHH24MISS형태의 데이터 값을 갖는 도메인 | VARCHAR2 | 16 | | 가격정책등록 일시 |
| 타임스템프 | YYYYMMDDHH24MISSFF3형태의 데이터 값을 갖는 도메인 | TIMESTAMP | 20 | | |
| 년도 | YYYY형태의 데이터 값을 갖는 도메인 | VARCHAR2 | 4 | 0001 ~ 9999 | 기준 년도 |
| 년월 | YYYYMM형태의 데이터 값을 갖는 도메인 | VARCHAR2 | 6 | | 지불 년월 |
| 월 | MM형태의 데이터 값을 갖는 도메인 | VARCHAR2 | 2 | | 청구 월 |

* 년월일 형식은 ‘YYYYMMDD’ 로 통일하며, 도메인명은 ‘일자’ 로 정의하여 사용한다
    * (예시) 계약해지 일자 : 20160420
* ‘YYYY’ 형식의 도메인명은 ‘년도’ 로 정의하여 사용한다
    * (예시) 출생 년도 : 1966, 기준 년도 : 2016
* ‘YYYYMM’ 형식의 도메인명은 ‘년월’ 로 정의하여 사용한다
    * (예시) 포인트적립 년월 : 201604
* ‘MM’ 형식의 도메인명은 ‘월’ 로 정의하여 사용한다
    * (예시) 결산 월 : 04
* ‘MMDD’ 형식의 도메인명은 ‘월일’ 로 정의하여 사용한다
    * (예시)  기혼기념 월일 : 1010
* ‘DD’ 형식의 도메인명은 ‘일’ 로 정의하여 사용한다
    * (예시) 자동이체지정 일 : 25
* 년월일+시분초 형식의 도메인명은 ‘일시’ 로 정의하여 사용한다. ‘일시’ 도메인의 DataType은 Date 와 Variable Character의 두 가지를 지원한다
* 시스템 로그일시(YYYYMMDDTTMMSSFF3)를 표시하기 위해서는 타임스탬프 도메인을 사용한다. DataType은 Timestamp 형태이다

#### 명(이름) 도메인 그룹

* [명] 도메인그룹은 객체에 대한 식별을 표현하기 위한 도메인들을 그룹화하여 관리한다.
* 사람을 제외한 포함한 모든 명칭은 ‘명’ 을 도메인으로 정의하여 사용하며, 사람은 ‘성명’을 사용한다. 
* '명' 도메인을 속성(컬럼)에 사용할 경우 도메인 앞에 ‘한글’,’영문’,‘한자’,‘약어’ 등과 같은 수식어가 생략된 경우는 ‘한글’+’명을 ‘명’으로 갈음한다
    * (예시) 종목 명(한글), 종목 영문 명(영문)
* 사람이 살고 있는 곳이나 기관, 회사 따위가 자리 잡고 있는 곳을 행정 구역으로 나타낸 이름은 ‘주소’ 를 도메인으로 정의하여 사용한다
* ‘명’은 단독으로 사용하지 않고 사전을 참조하여 복합어로 생성한다
* 예시

| 도메인 | 설명 | 예시 | 비고 |
|---|----------|----|------|
| 명 | 상품, 사물 등을 식별하기 위한 명칭에는 '명' 도메인을 사용한다 | 상품 명 | |
| 성명 | 사람의 성명을 관리할 경우 '성명'이라는 도메인을 사용한다 | 고객 영문성명 | |
| 주소 | 사람이 살고 있는 곳이나 기관, 회사 따위가 자리 잡고 있는 곳을 행정 구역으로 나타낸 이름은 '주소' 도메인을 사용한다 | 직장 주소 | |
| 이메일주소 | 전자우편주소 | 수신자 이메일주소 | |
| ID | 시스템 오브젝트 등을 식별하기 위해 사용되는 도메인으로서 체계 없이 순차적으로 체번하여 사용하는 일련번호와는 구별하여 사용한다 | 스마트빌 ID | |

#### 내용 도메인 그룹

* “내용” 단일 도메인으로 정의 한다.
* “명세”, “설명”, ”비고”, “적요”, “내역”, “의견”, “사유”, “사항”  등 유사 도메인은 별도로 정의하지 않고 “내용”  도메인으로 통합관리 한다.
    * (예시) 평가자 의견 (X) → 평가자 의견 내용 (O)
* ‘값’은 단일단어로 허용하지 않고, 사전을 참조하여 복합어로 생성한다.
* 예시

| 도메인 | 설명 | 예시 | 비고 |
|---|---------------|------|------|
| 내용 | 사실이나 사물에 대해 전하고자 하는 정보를 형식 없이 서술형으로 저장하는 경우 사용된다. | 사고 내용 | |
| 값 | 평가값, 항목값 등 값을 의미하는 용어에 대해 값 도메인을 사용한다. | 항목 값, 입력 값 | |

#### 수 도메인 그룹

* [수] 도메인그룹은 객체의 개수나 양을 수로써 표현하기 위한 도메인들을 그룹화하여 관리한다.
* [수 도메인그룹] 도메인 상세

| 도메인 | 설명 | 예시 | 비고 |
|---|-----------|----|---|
| 수 | 셀 수 있는 사물의 크기를 나타내는 값(복합어로 생성) | 종업원 수 | |
| 일수 | 일을 기준으로 헤아리는 수. | 연체 일수 | |
| 개월수 | 월을 기준으로 헤아리는 수 | 견적 개월수 | |
| 년수 | 년을 기준으로 헤아리는 수 | 근무 년수 | |
| 매수 | 종이나 유리 따위의 장으로 셀 수 있는 물건의 수효 | 기본 매수 | |
| 개수 | 한 개씩 낱으로 셀 수 있는 물건의 수효 | 보유 개수 | |
| 건수 | 사물이나 사건의 가짓수 | 조회 건수 | |
| 횟수 | 돌아오는 차례의 수효 | 기존인출 횟수 | |
| 점수 | 성적을 나타내는 숫자 | 평가대상 점수 | |
| 연령 | 나이, 사람이 세상에 나서 현재 또는 기준이 되는 때까지 살아 온 햇수 | 보험 연령 | |
| 수량 | 수와 량이 혼재된 수량을 자연수로 표현한 수 | 수량 | |

* 금액을 제외한 정보의 수치 및 합계 등을 정의하는 경우에 사용한다
    * (예시) 고객 수, 연체 일수, 거래 량
* 되풀이되는 일이나 차례의 수효를 나타내는 경우는 ‘횟수’를 도메인으로 정의하여 사용한다.
    * (예시) 지로자동이체 횟수
* 나이와 관련된 용어는 ‘연령’ 을 도메인으로 정의하여 사용한다
    * (예시) 보험 연령
* 기간을 나타내는 용어의 경우 ‘기간’을 사용하지 않고, ‘년수’, ‘개월수’, ‘일수’ 등으로 구체 적으로 정의한다
    * (예시) 대출 년수, 연장 개월수, 연체 일수

#### 율 도메인 그룹

* [율] 도메인그룹은 둘 이상의 수를 비교하여 그 중 하나의 수를 기준으로 하여 나타낸 다른 수의 비교 값을 표현하기 위한 도메인들을 그룹화하여 관리한다.
* ‘율’ 또는 ‘률＇은 단일단어로 사용하지 않고 사전을 참조하여 복합어로 생성한다 
* 확률, 비율 등 ‘%’ 로 관리되는 속성에 대해 ‘율/비율’ 을 도메인으로 정의하여 사용한다
    * (예시) 연체 율, 담보 비율, 적용 비율
* [율 도메인그룹] 도메인 상세

| 도메인 | 설명 | 예시 | 비고 |
|--------|------|------|------|
| 율 | 비율의 뜻을 나타내는 말 "~율"은 모음으로 끝나거나 'ㄴ' 받침을 가진 일부 명사 뒤에 붙임(복합어로 생성) | 할인 율 | |
| 이율 | 원금에 대한 이자의 비율, 즉 이자 산출에 기초가 되는 비율 | 연체 이율 | |
| 세율 | 과세 표준에 의하여 세금을 계산하여 매기는 법정률 | | |
| 요율 | 요금의 정도나 비율 | 보증 요율 | |
| 금리 | 자금의 사용료로 대외적으로 공시되는 기준의 의미로 사용 | 대출 금리 | |
| 환율 | 외국환 시세 | 기준 환율 | |
| 비율 | 둘 이상의 수를 비교하여 나타낼 때 그 중 한 개의 수를 기준으로 하여 나타낸 다른 수의 비교 값 | 사고MT 비율 | |

#### 금액 도메인 그룹

* [금액] 도메인그룹은 돈의 액수나 화폐 가치를 표현하기 위한 도메인들을 그룹화하여 관리한다
* 금액을 의미하는 도메인은 중복해서 사용하는 것을 피한다
    * (예시) 물품 + 원가(도메인) + 금액(도메인) →  물품 + 원가(도메인)
* 기본적으로 '금액' 도메인으로 표현될 수 있는 속성에 대해서는 '금액' 도메인의 사용을 권장한다. 하지만 관용적으로 '금' 도메인이 사용되는 표현에는 별도의 도메인으로 분류하여 사용한다
* 합산금액을 의미하는 총계, 합계, 누계 등의 수식어는 반드시 금액 앞에 붙인다
    * (예시) 감가상각누계금액, 자산총계금액
* 부득이하게 ‘금＇을 사용해야 하는 경우 복합어 생성한다
* [금액 도메인그룹] 도메인 상세

| 도메인 | 세부 도메인 | 설명 | 예시 | 비고 |
|--------|-------------|------|------|------|
| 요금 | 료 | 대여료, 렌탈료, 리스료 등을 나타내는 금액 단위(복합어로 생성) | 수수 료, 과태 료 | |
| 금액 | 금액 | 돈의 액수 | 고객청구 금액 | |
| 금액 | 잔액 | 남은 금액 | 연체이자 잔액 | |
| 세 | 세 | 조세의 액수(복합어로 생성) | 부가 세 | |
| 가격 | 단가 | 물건 한 단위(單位)의 가격 | 계약 단가 | |
| 가격 | 원가 | 상품의 제조 판매 배급 따위에 든 재화와 용역을 단위에 따라 계산한 가격 | 물품 원가 | |

#### 번호 도메인 그룹

* [번호] 도메인그룹은 일정한 체계를 가지거나 특정 자리에 존재하는 의미를 표현하기 위한 도메인들을 그룹화하여 관리한다. 
* 번호도메인의 공통 도메인은 생성하지 않는다. 
* '번호' 도메인은 일정한 체계를 가지거나 특정 자리의 의미가 존재하는 속성을 정의할 때 사용하는 것을 원칙으로 한다.
* 번호 자체에 특별한 의미를 가진 경우 해당 번호를 번호도메인으로 정의하여 사용한다
    * (예시) 주민등록번호, 사업자등록번호, 전화번호, 법인등록번호 등
* 순차적으로 채번되는 번호는 ‘일련번호’ 도메인으로 정의하여 사용한다.
* 번호도메인의 공통인 도메인은 생성하지 않는다. 
    * (예시) 번호N10 (Number(10))과 같이 분류어가 번호인 용어의 도메인이 공통적으로 쓰는 도메인 생성 금지.
* [번호 도메인그룹] 도메인 상세

| 도메인 | 설명 | 예시 | 비고 |
|--------|------|------|------|
| 전화번호 | 가입된 전화마다 매겨져 있는 일정한 번호 | 계약담당 전화번호 | |
| 우편번호 | 우편물을 쉽게 분류하기 위하여 정보 통신부에서 각 지역마다 매긴 번호 | 계약자 우편번호 | |
| 주민등록번호 | 주민등록을 할 때에, 국가에서 국민에게 부여하는 고유 번호 | 계약자 주민등록번호 | |
| 사업자등록번호 | 세무에서, 신규로 개업하는 사업자에게 부여하는 사업체의 고유번호이다 | 공급자 사업자등록번호 | |
| 법인등록번호 | 사무소의 소재지에서 설립등기(設立登記)를 함으로써 성립하는데 이때 부여된 일련번호이다 | ~ 법인등록번호 | |
| 계좌번호 | 금융 기관에 예금하려고 설정한 개인명이나 법인명의 계좌에 부여된 번호 | 입금 계좌번호 | |
| 휴대전화번호 | 지니고 다니면서 걸고 받을 수 있는 소형 무선 전화기 번호 | | |
| 비밀번호 | 본인임을 확인하기 위해 설정한 암호 | | |
| 신용카드번호 | 신용카드식별번호 | ~ 신용카드번호 | |
| 직원번호 | 회사 직원 식별번호 | ~ 사원번호 | |
| 여권번호 | 외국을 여행하는 사람의 신분이나 국적을 증명하고 상대국에 그 보호를 의뢰하는 문서번호. | 고객 여권번호 | |
| 외국인등록번호 | 외국인등록번호 | 외국인등록번호 | |
| 일련번호 | 일률적으로 연속되어 있는 번호 | 구성품 일련번호 | |

#### 코드 도메인 그룹

* 코드는 다른 도메인들과 달리 특정 도메인 값(즉, 코드값)과 이 값에 대한 의미(즉, 코드값명)를 표현하기 위해 코드도메인을 그룹화하여 표준코드로 분류하여 별도로 관리한다
* 코드값을 가지는 속성은 반드시 ‘코드’ 를 도메인으로 정의하여 사용한다
* 속성명은 해당 속성이 사용하는 코드도메인명과 일치시키는 것을 원칙으로 하나, 속성명에 수식어를 붙여서 사용할 수 있다
    * (예시) 코드도메인 ‘거래코드’  :  속성명  → 거래코드(O), 수신거래코드(O)
* 코드의 의미가 ‘여부’ 또는 ‘유무’ 인 경우 ‘코드’를 도메인으로 사용할 수 없고, ‘여부/유무’ 를 도메인으로 정의하여 사용한다
* 코드도메인은 ‘수식어 + 코드유형수식어 + 코드’ 로 명명한다
* [코드 도메인그룹] 도메인 상세

| 도메인 | 설명 | 비고 |
|--------|------|------|
| 가상계좌은행코드 | [가상계좌은행코드] 코드는 회사 전사에서 사용하는 가상계좌 은행코드 | |
| 제품카테고리코드 | [제품카테고리코드] 코드는 제품의 카테코리에 대하여 조회할 수 있도록 구분하는 코드 | |
| 주차장코드 | [주차장구분코드] 코드는 자산 제고의 위치를 구분하는 코드 | |
| 수리항목코드 | [수리항목코드] 수리항목 목록을 구분하는 코드 | |

#### 분류 도메인 그룹

* “여부” 도메인의  인스턴스는 반드시 ‘Y’ 또는 ‘N’ 만 허용되며, NULL, N/A, SAPCE 등의 값은 허용하지 않는다.
* “유무” 도메인의  인스턴스는 반드시 ‘Y’ 또는 ‘N’ 만 허용되며, NULL, N/A, SAPCE 등의 값은 허용하지 않는다.
* “여부/유무” 도메인명은 ‘Y/N’ 이외의 값을 허용하지 않으므로, 기타 값을 사용해야 하는 경우는 코드도메인으로 분류하여 사용하고, 특히 미 정의된 값은 속성의 인스턴스로 사용할 수 없으며, ‘미정의’ 값을 표현하기 위해서는 ‘*’ (미정의)와 같이 반드시 대체값을 정의하여 인스턴스로 사용한다. (Not Null)
* 단, 대외 인터페이스 테이블의 경우 업무 특성에 따라 Null을 에외로 허용할 수 있다
* [분류 도메인그룹] 도메인 상세

| 도메인 | 설명 | 예시 | 비고 |
|--------|------|------|------|
| 여부 | 특정 사실이나 행위의 '그러함/그러하지 아니함'을 의미 | 반출 여부 | |
| 유무 | 존재나 소유의 '있음/없음'을 의미 | 보증금 유무 | |

* 이 두 도메인을 명확히 구분하여 사용하면 데이터의 의미를 더 정확하게 전달할 수 있다. 
    * 예를 들어, '계약 여부'는 계약이 체결되었는지 아닌지를 나타내는 반면, '계약서 유무'는 물리적인 계약서 문서가 존재하는지 않는지를 나타낼 수 있다.

### 표준도메인 등록 기준

* 도메인 등록 기준

| 순번 | 원칙 | 예시 |
|----|--------------|------|
| 1 | • 속성 데이터가 규칙을 가지는 경우 도메인 명으로 지정한다.<br>• 속성값의 자릿수가 항상 일정해야 하는 경우<br>• 특정 자릿수의 데이터가 의미를 가지는 경우<br>• 속성값 데이터 내의 규칙이 존재하는 경우 | • 고객번호는 20자리<br>• 사업자등록번호, 여권번호, 법인등록번호 |
| 2 | 속성 데이터 값의 유효값이나 유효 범위의 제한이 있는 경우 도메인으로 지정한다. | • 분기 – 1,2,3,4 만 유효함<br>• 일(Day) – 1~31만 유효함 |
| 3 | 속성값의 성격을 식별하고자 하는 경우 도메인 명으로 지정한다 | 지점구분코드 |
| 4 | 속성명 명명 시에 합성어 등이 관용적으로 사용되어 분리하여 사용하기 힘든 경우 도메인 명으로 지정한다. | 잔액, 특소세 |
| 5 | 코드값 체계를 가지는 모든 코드는 도메인 명으로 지정한다 | 은행코드, 부품코드 |

### 데이터 표준 도메인 예시


| 도메인 그룹 | 도메인 | 인포타입 | 데이터 타입 | 길이 | 설명 | 예시 |
|-------------|--------|----------|-------------|------|------|------|
| 날짜 | 일자 | 일자VC8 | VARCHAR2 | 8 | YYYYMMDD 형식의 날짜 | 20230501 |
| 날짜 | 일시 | 일시VC14 | VARCHAR2 | 14 | YYYYMMDDHHMMSS 형식의 날짜와 시간 | 20230501143000 |
| 명칭 | 성명 | 성명VC50 | VARCHAR2 | 50 | 개인의 이름 | 홍길동 |
| 명칭 | 상품명 | 명VC100 | VARCHAR2 | 100 | 상품의 이름 | 스마트폰 갤럭시 S23 |
| 내용 | 내용 | 내용VC4000 | VARCHAR2 | 4000 | 자유 형식의 텍스트 | 이 제품은 최신 기술을 적용한... |
| 수량 | 수량 | 수량N10 | NUMBER | 10 | 물품의 개수 | 1000 |
| 율 | 이율 | 이율N5_2 | NUMBER | 5,2 | 비율을 나타내는 수치 (소수점 2자리) | 3.75 |
| 금액 | 금액 | 금액N15 | NUMBER | 15 | 화폐 금액 | 10000000 |
| 번호 | 전화번호 | 전화번호VC20 | VARCHAR2 | 20 | 전화번호 형식 | 010-1234-5678 |
| 코드 | 상품코드 | 코드VC10 | VARCHAR2 | 10 | 상품을 구분하는 고유 코드 | PRD0001234 |
| 분류 | 여부 | 여부VC1 | VARCHAR2 | 1 | Y/N으로 표현되는 여부 | Y |
