---
title: "Data Governance Study - the contents agreement"
subtitle: "데이터 표준 관리: 데이터 표준 코드 등록 절차"
description: "이 글에서는 애플리케이션 개발 시 발생하는 표준 코드의 신규 및 변경 요청과 승인 절차를 설명한다. 개발자가 신규 코드 요건을 도출하고 표준 코드 사전에서 검색한 후, 표준 담당자가 이를 검토 및 등록하는 과정을 단계별로 안내한다."
author: Kwangmin Kim
categories:
  - Data Governance
date: 2024-08-18
format: 
  html:
    toc: true  
    code-fold: true
    code-copy: true
    code-overflow: wrap
    number-sections: true
    number-depth: 4
    grid:
      sidebar-width: 200px
      body-width: 1150px
      margin-width: 300px
---


## Data Standard Governance > Contents Agreement



### 데이터 Contents Agreement

| 번호 | 도메인 | 질의내용 | 확정 |
|---|---|-------------|-------------|
| 1 | 수 | 1,2,3,4, … , 01, 02, 03 등 숫자형 금칙어 등록<br>- 숫자는 문자와 함께 씀<br>- 운전자1 (Driver1) | 숫자 단일 사용은 금지 |
| 2 | 수 | 갯수 -> 개수 | 개수로 사용 |
| 3 | 금액 | 금, 비, 액, 가격, 가액(공금가액, 증가액, 차량가액) -> 금액으로 통일<br>- 금액으로 사용하지 못하는 단어일 경우 복합어 사용 | fee : 요금<br>price : 가격<br>cost : 비용<br>amount : 금액 |
| 4 | 금액 | 금액을 나타내는 '료' 단어 단일어 인정 여부<br>- 렌탈료->렌탈요금, 휴차료, 담보료 | 요금으로 사용하며, 관용단어 -> 료 복합어 생성 |
| 5 | 명 | '명'을 단일어로 사용 여부(성명, 명 모두 명으로 사용) | 사물 : 명<br>사람 : 성명 |
| 6 | 일자 | 일 -> 일자로 사용(취득일, 종료일, 승인일, 발행일 -> 취득일자, 종료일자) 하고 DD의 형태는 '일'로 사용 | '일자'로 사용 |
| 7 | - | 차대 -> 차대번호 고유단어로 등록<br>- CARBODYNO(차대번호), CAR_BODY_NO로 사용 중 | 차대번호 복합어 생성 |
| 8 | - | 상품(상품코드, 주문상품) -> 제품<br>- 별도로 사용하면 상품 영문명(Goods), 제품(Product)<br>- 상품은 Good과 Product를 사용중<br>- 제품은 Item을 사용중<br>- 상품을 Commondity로 등록 | 상품 : Product<br>자산 : Asset<br>제품 : Goods<br>부품 : Components<br>소모품 : Consumption Goods |
| 9 | - | 회사(실사용자회사명, 사용회사, 소속회사) -> 업체<br>- 회사 영문명(Corporation) 업체(Company) | 회사 : 사용<br>업체 : 사용하지 않고 '비즈니스파트너'로 대체 |
| 10 | 일자 | 월 -> 월단가, 월렌탈료, 월리스료 등으로 단어 생성<br>- 월(Month)은 1월~12월을 표현하는 용도로만 사용 | 필요시 복합어 생성<br>ex) 월별렌탈금액 단어 생성 |
| 11 | 수 | 수 -> 단일어 허용할지 여부(고객수, 직원수, 회전수) | 단일어 사용하지 않고 복합어 생성 |
| 12 | 수 | 건수(Count/CNT, 처리건수, 발생건수)와 개수(Count/CO, 반품갯수, 쿠폰갯수)로 분리해서 사용 | 건수는 CNT약어로 생성 |
| 13 | 명 | 이름(금칙어 등록), 성명 -> 명으로 사용 | 사물 : 명<br>사람 : 성명 |
| 14 | 내용 | 사항(특기사항, 특약사항, 참고사항) -> 내용으로 사용 | 내용으로 사용하며 명시적으로 사항을 사용하는 경우 복합어 생성 |
| 15 | 번호 | 사업자번호(인증서 사업자번호) -> 사업자등록번호 : 사업자번호가 사업자등록번호와 다른 의미이면 단어 생성 | 사업자등록번호로 사용 |
| 16 | 번호 | 연락처 -> 전화번호로 사용 (ASIS 컬럼은 대부분 TEL로 전화번호 내용임)<br>- 연락을 취할수 있는 모든 내용의 의미로 사용예정이면 등록 | 연락처 단어 생성(연락처 Pool에서 사용)<br>ASIS에서 연락처는 전화번호의 의미이므로 ASIS의 연락처 용어는 전화번호로 대체 |
| 17 | 번호 | 핸드폰번호(가장많음), 휴대전화번호, 휴대폰 -> 휴대전화번호(표준어)로 통일 | 휴대전화번호로 사용 |
| 18 | - | 대여 (대여종료일자, 대여지점, 월간대여료)-> 랜탈 | 렌탈로 사용하며 대여는 금칙어 |
| 19 | - | 제작사(MAKERCODE, CONFIRMDATE)와 제조사(Maker) 차이 | 제작사 : 사용<br>제조사 : 금칙어 |
| 20 | 율 | 백분율을 나타내는 '율' 단어 단일어 인정 여부<br>- 감가율, 공채율, 대비율 | 복합어 생성(사전 참조)<br>단일어 불허 |
| 21 | 세 | 세금을 나타내는 '세' 단어 단일어 인정 여부<br>- 과세, 교육세 | 복합어 생성(사전 참조)<br>단일어 불허 |
| 22 | - | 구입(구입가격, 차량구입비, 구입일자) -> 구매<br>- 구입가격, 구입일 | 구매<br>구입 : 금칙어 |
| 23 | 명 | 이름을 나타내는 '명' 단어 단일어 인정 여부<br>- 파일명, 차량명 | 사물 : 명<br>사람 : 성명 |
| 24 | - | 구입(구입가격, 차량구입비, 구입일자) -> 구매<br>- 구입가격, 구입일 | 구매<br>구입 : 금칙어 |
| 25 | - | 제원(specification) (제원), 스팩(SPEC) (제품스팩, 제품스팩아이디) -> 스펙 | 스펙<br>제원 : 금칙어 |
| 26 | - | 제휴협력사 vs 협력사 vs 파트너 | 비즈니스파트너 |
| 27 | - | 제휴사 -> ex) 대한항공 | - |
| 28 | - | 협력사 -> 정비업체 | - |
| 29 | - | 이해당사자 vs 이해관계자 | 이해관계자 |
| 30 | 량 | 양을 나타내는 의미로 '량' 단어 단일어 인정 여부<br>- 월평균소요량, 연료량 등 | '량'으로 복합어 생성(사전 참조)<br>단일어 불허 |
| 31 | 값 | 값을 나타내는 의미로 '값' 단어 단일어 인정 여부<br>- 변경값, 관리키값, 상태값 등 | 복합어 생성(사전 참조)<br>단일어 불허 |
| 32 | 번호 | 번호 그룹 도메인에 속하는 용어들의 데이터 타입 및 길이가 상이하므로, 용어별 도메인 별도 생성 | 번호용어 별 도메인 생성 |
| 33 | - | 매각제품 별 단가, 회차 별 산출금액에서 '별' 단어 허용 여부 | 별, 및 : 금칙어<br>필요시 복합어 생성 |
| 34 | 명 | '처' (유지보수 처, 송금 처) 단어 허용 여부<br>- 처의 의미 | 처 : 금칙어<br>-> 대상 등으로 사용 |
| 35 | 번호 | 순번과 일련번호 중 일련번호 사용 (순번 -> 금칙어)<br>- 일련번호를 Serial Number로 사용하고 순번을 단순한 순차적인 번호(Sequence)로 사용할지 에 대한 의사결정 필요 | 순번 : 금칙어<br>일련번호 : 순차적인 번호 (KEY)<br>고유번호(시리얼번호) : 제품고유번호 |